import type { SeedDay } from "./types";

export const DAY_01: SeedDay = {
  dayNumber: 1,
  date: "2026-09-18",
  scriptureBonus: {
    displayText: "The Lord is my shepherd; I shall not want.",
    book: "Psalms",
    chapter: 23,
    verseStart: 1,
    referenceDisplay: "Psalm 23:1",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Psalm 23 uses the image of a shepherd to express trust in God's guidance and care.",
    acceptedBookAliases: ["psalm", "psalms"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name someone who spoke directly with God in the Bible.",
      instructions: "You get one guess.",
      whatCounts:
        "Any named person for whom the biblical text explicitly describes direct speech from God, including the many prophets to whom \"the word of the LORD came\" and who record God speaking to them in the first person (not visions or dreams — see the separate dream/vision question for those). Use the product's defined 66-book canon.",
      answers: [
        {
          canonical: "Moses",
          aliases: ["moshe"],
          score: 10,
          tier: "outer-court",
          references: [
            { book: "Exodus", chapterStart: 3, verseStart: 4, verseEnd: 6, display: "Exodus 3:4-6" },
            { book: "Exodus", chapterStart: 33, verseStart: 11, display: "Exodus 33:11" },
          ],
          explanation:
            "God calls Moses from the burning bush and speaks with him repeatedly during Israel's wilderness journey.",
        },
        {
          canonical: "Abraham",
          aliases: ["abram"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 12, verseStart: 1, display: "Genesis 12:1" }],
          explanation:
            "Direct divine speech appears throughout Genesis in God's covenant dealings with Abraham.",
        },
        {
          canonical: "Jesus",
          aliases: ["jesus christ", "christ", "yeshua"],
          score: 10,
          tier: "outer-court",
          references: [
            { book: "Matthew", chapterStart: 3, verseStart: 17, display: "Matthew 3:17" },
            { book: "Matthew", chapterStart: 26, verseStart: 39, display: "Matthew 26:39" },
          ],
          explanation:
            "The Father's voice addresses Jesus directly at his baptism, and Jesus prays directly to the Father in Gethsemane.",
          inclusionNotes:
            "Included for the Gospels' accounts of two-way address between Jesus and the Father — not a claim about the nature of the Trinity, which this game doesn't adjudicate.",
        },
        {
          canonical: "Jacob",
          aliases: ["israel"],
          score: 20,
          tier: "bronze-altar",
          references: [
            { book: "Genesis", chapterStart: 28, verseStart: 13, display: "Genesis 28:13" },
            { book: "Genesis", chapterStart: 46, verseStart: 2, display: "Genesis 46:2" },
          ],
          explanation: "God speaks to Jacob at Bethel and again in a night vision on the way to Egypt.",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 3, verseStart: 5, display: "1 Kings 3:5" }],
          explanation: "The LORD appears to Solomon in a dream at Gibeon and speaks with him directly.",
        },
        {
          canonical: "Samuel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 3, verseStart: 1, display: "1 Samuel 3" }],
          explanation: "God calls the boy Samuel by name in the night in 1 Samuel 3.",
        },
        {
          canonical: "Elijah",
          aliases: ["elias"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 9, verseEnd: 18, display: "1 Kings 19:9-18" }],
          explanation:
            "On Mount Horeb, after the wind, earthquake, and fire, God speaks to Elijah in a still, small voice.",
        },
        {
          canonical: "Isaiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Isaiah", chapterStart: 6, verseStart: 1, verseEnd: 8, display: "Isaiah 6:1-8" }],
          explanation:
            "In his temple vision, Isaiah hears the Lord ask, \"Whom shall I send?\" and answers directly.",
        },
        {
          canonical: "Job",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Job", chapterStart: 38, verseStart: 1, display: "Job 38:1" }],
          explanation: "God answers Job out of the whirlwind after Job's long complaint.",
        },
        {
          canonical: "Hagar",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [
            { book: "Genesis", chapterStart: 16, verseStart: 7, verseEnd: 13, display: "Genesis 16:7-13" },
            { book: "Genesis", chapterStart: 21, verseStart: 17, verseEnd: 19, display: "Genesis 21:17-19" },
          ],
          explanation:
            "God meets Hagar in the wilderness, gives her a promise concerning Ishmael, and later hears her son's cry.",
        },
        {
          canonical: "Balaam",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 22, verseStart: 9, verseEnd: 12, display: "Numbers 22:9-12" }],
          explanation:
            "God speaks directly to Balaam, a non-Israelite prophet-for-hire, warning him about Balak's request.",
        },
        {
          canonical: "Huldah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 22, display: "2 Kings 22" }],
          explanation: "The prophet Huldah is consulted and delivers the Lord's word in 2 Kings 22.",
        },
        {
          canonical: "Cain",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 4, verseStart: 6, verseEnd: 15, display: "Genesis 4:6-15" }],
          explanation: "After Cain becomes angry, God questions, warns, judges, and marks him for protection.",
        },
        {
          canonical: "Adam",
          aliases: ["the first man"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 16, verseEnd: 17, display: "Genesis 2:16-17" }],
          explanation: "God speaks directly to Adam, commanding him not to eat from the tree of the knowledge of good and evil.",
        },
        {
          canonical: "Noah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 6, verseStart: 13, display: "Genesis 6:13" }],
          explanation: "God speaks directly to Noah, instructing him to build the ark ahead of the flood.",
        },
        {
          canonical: "David",
          aliases: ["king david"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 23, verseStart: 2, display: "1 Samuel 23:2" }],
          explanation: "David inquires of the LORD and the LORD answers him directly, telling him to attack the Philistines at Keilah.",
        },
        {
          canonical: "Joshua",
          aliases: ["son of nun"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 1, verseStart: 1, verseEnd: 9, display: "Joshua 1:1-9" }],
          explanation: "After Moses' death the LORD speaks directly to Joshua, commissioning him to lead Israel into the land.",
        },
        {
          canonical: "Isaac",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 26, verseStart: 2, verseEnd: 5, display: "Genesis 26:2-5" }],
          explanation: "The LORD appears to Isaac and speaks to him directly, renewing the covenant promise given to Abraham.",
        },
        {
          canonical: "Jeremiah",
          aliases: ["the weeping prophet"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 1, verseStart: 4, verseEnd: 9, display: "Jeremiah 1:4-9" }],
          explanation: "The word of the LORD comes to Jeremiah directly, calling and commissioning him as a prophet from the womb.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a judge of Israel.",
      instructions: "You get one guess.",
      whatCounts:
        "Any of the judges named in the book of Judges (or 1 Samuel for Samuel's predecessors' successors). Use the product's defined 66-book canon.",
      answers: [
        {
          canonical: "Othniel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Judges", chapterStart: 3, verseStart: 9, verseEnd: 11, display: "Judges 3:9-11" }],
          explanation: "Othniel is the first judge the LORD raises up to deliver Israel.",
        },
        {
          canonical: "Gideon",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Judges", chapterStart: 6, display: "Judges 6-8" }],
          explanation: "Gideon tests God with the fleece and leads Israel against Midian with 300 men.",
        },
        {
          canonical: "Samson",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Judges", chapterStart: 13, display: "Judges 13-16" }],
          explanation: "Samson, famed for his strength and his fall to Delilah, judges Israel for twenty years.",
        },
        {
          canonical: "Deborah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 4, display: "Judges 4-5" }],
          explanation: "Deborah, a prophetess, is the only woman named among Israel's judges.",
        },
        {
          canonical: "Ehud",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 3, verseStart: 15, verseEnd: 30, display: "Judges 3:15-30" }],
          explanation: "The left-handed judge Ehud delivers Israel from King Eglon of Moab.",
        },
        {
          canonical: "Jephthah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 11, display: "Judges 11" }],
          explanation: "Jephthah defeats the Ammonites after a rash vow that costs him his daughter.",
        },
        {
          canonical: "Shamgar",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 3, verseStart: 31, display: "Judges 3:31" }],
          explanation: "Shamgar gets a single verse, striking down 600 Philistines with an ox goad.",
        },
        {
          canonical: "Tola",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Judges", chapterStart: 10, verseStart: 1, verseEnd: 2, display: "Judges 10:1-2" }],
          explanation: "Tola judged Israel for twenty-three years, one of the minor judges given only a couple of verses.",
        },
        {
          canonical: "Ibzan",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Judges", chapterStart: 12, verseStart: 8, verseEnd: 10, display: "Judges 12:8-10" }],
          explanation: "Ibzan judged Israel seven years and is noted for his thirty sons and thirty daughters.",
        },
        {
          canonical: "Elon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Judges", chapterStart: 12, verseStart: 11, verseEnd: 12, display: "Judges 12:11-12" }],
          explanation: "Elon the Zebulunite judged Israel for ten years.",
        },
        {
          canonical: "Abdon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Judges", chapterStart: 12, verseStart: 13, verseEnd: 15, display: "Judges 12:13-15" }],
          explanation: "Abdon judged Israel eight years; the text notes his forty sons and thirty grandsons rode seventy donkeys.",
        },
        {
          canonical: "Jair",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Judges", chapterStart: 10, verseStart: 3, verseEnd: 5, display: "Judges 10:3-5" }],
          explanation:
            "Jair judged Israel 22 years; his thirty sons rode thirty donkeys and held thirty towns.",
        },
        {
          canonical: "Samuel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 7, verseStart: 15, verseEnd: 17, display: "1 Samuel 7:15-17" }],
          explanation: "The text says Samuel judges Israel all the days of his life, making his yearly circuit from Ramah.",
        },
        {
          canonical: "Eli",
          aliases: ["eli the priest"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Samuel", chapterStart: 4, verseStart: 18, display: "1 Samuel 4:18" }],
          explanation: "The text states Eli had judged Israel for forty years before his death.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a woman named in the Gospels.",
      instructions: "You get one guess.",
      whatCounts: "Any woman named by the biblical text in Matthew, Mark, Luke, or John.",
      answers: [
        {
          canonical: "Mary",
          aliases: ["mary mother of jesus", "virgin mary"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 26, verseEnd: 38, display: "Luke 1:26-38" }],
          explanation: "Mary, the mother of Jesus, receives the angel Gabriel's announcement.",
        },
        {
          canonical: "Mary Magdalene",
          aliases: ["magdalene"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 20, verseStart: 1, verseEnd: 18, display: "John 20:1-18" }],
          explanation: "Mary Magdalene is the first witness of the risen Jesus.",
        },
        {
          canonical: "Martha",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 10, verseStart: 38, verseEnd: 42, display: "Luke 10:38-42" }],
          explanation: "Martha serves Jesus in her home while her sister Mary listens at his feet.",
        },
        {
          canonical: "Mary of Bethany",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 11, verseStart: 1, verseEnd: 2, display: "John 11:1-2" }],
          explanation: "Mary of Bethany, Martha and Lazarus's sister, anoints Jesus' feet with expensive perfume.",
        },
        {
          canonical: "Elizabeth",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 5, verseEnd: 25, display: "Luke 1:5-25" }],
          explanation: "Elizabeth, John the Baptist's mother, greets the pregnant Mary as blessed.",
        },
        {
          canonical: "Anna",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 36, verseEnd: 38, display: "Luke 2:36-38" }],
          explanation: "The prophetess Anna recognizes the infant Jesus in the temple.",
        },
        {
          canonical: "Joanna",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 8, verseStart: 3, display: "Luke 8:3" }],
          explanation: "Joanna is named among the women who supported Jesus' ministry out of their means.",
        },
        {
          canonical: "Salome",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 15, verseStart: 40, display: "Mark 15:40" }],
          explanation: "Salome is named among the women who watch Jesus' crucifixion from a distance.",
          inclusionNotes: "Distinct from Herodias's unnamed dancing daughter, whom later tradition (not the biblical text) calls Salome.",
        },
        {
          canonical: "Mary Mother of James",
          aliases: ["mary the mother of james and joses"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 15, verseStart: 40, display: "Mark 15:40" }],
          explanation: "Mary the mother of James and Joses is named among the women at the crucifixion.",
        },
        {
          canonical: "Susanna",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 8, verseStart: 3, display: "Luke 8:3" }],
          explanation: "Susanna is named only once, alongside Joanna, as a supporter of Jesus' ministry.",
        },
        {
          canonical: "Herodias",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 3, verseEnd: 11, display: "Matthew 14:3-11" }],
          explanation:
            "Herodias, Herod's wife, orchestrates John the Baptist's execution through her daughter's dance.",
        },
        {
          canonical: "Tamar",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 3, display: "Matthew 1:3" }],
          explanation: "Matthew's genealogy of Jesus explicitly names Tamar as the mother of Perez and Zerah by Judah.",
        },
        {
          canonical: "Rahab",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Matthew's genealogy of Jesus names Rahab as the mother of Boaz.",
        },
        {
          canonical: "Ruth",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Matthew's genealogy of Jesus names Ruth as the mother of Obed.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a city Paul visited in the book of Acts.",
      instructions: "You get one guess.",
      whatCounts: "Any city the book of Acts explicitly describes Paul visiting.",
      answers: [
        {
          canonical: "Antioch",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 1, display: "Acts 13:1" }],
          explanation: "Antioch in Syria sends Paul out on his missionary journeys.",
        },
        {
          canonical: "Damascus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 3, display: "Acts 9:3" }],
          explanation: "Paul encounters the risen Jesus on the road to Damascus and is converted there.",
        },
        {
          canonical: "Rome",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 16, display: "Acts 28:16" }],
          explanation: "Paul finally reaches Rome, where Acts ends with him under house arrest.",
        },
        {
          canonical: "Ephesus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 19, display: "Acts 19" }],
          explanation: "Paul spends over two years teaching in Ephesus.",
        },
        {
          canonical: "Corinth",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 1, display: "Acts 18:1" }],
          explanation: "Paul settles in Corinth for a year and a half, working alongside Aquila and Priscilla.",
        },
        {
          canonical: "Philippi",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 12, display: "Acts 16:12" }],
          explanation: "Paul and Silas are imprisoned and miraculously freed in Philippi.",
        },
        {
          canonical: "Iconium",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 1, display: "Acts 14:1" }],
          explanation: "Paul and Barnabas preach in the synagogue at Iconium.",
        },
        {
          canonical: "Thessalonica",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 1, display: "Acts 17:1" }],
          explanation: "Paul reasons in the synagogue at Thessalonica for three Sabbaths.",
        },
        {
          canonical: "Athens",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 16, display: "Acts 17:16" }],
          explanation: "Paul addresses the Areopagus in Athens about the \"unknown god.\"",
        },
        {
          canonical: "Berea",
          aliases: ["beroea"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 10, display: "Acts 17:10" }],
          explanation: "The Bereans are commended for examining the Scriptures daily to test Paul's teaching.",
        },
        {
          canonical: "Caesarea",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 23, verseStart: 33, display: "Acts 23:33" }],
          explanation: "Paul is held in custody at Caesarea for two years before appealing to Caesar.",
        },
        {
          canonical: "Derbe",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 20, display: "Acts 14:20" }],
          explanation: "Paul and Barnabas preach in Derbe after fleeing Lystra.",
        },
        {
          canonical: "Lystra",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 8, display: "Acts 14:8" }],
          explanation: "Paul heals a lame man in Lystra and is later stoned there.",
        },
        {
          canonical: "Troas",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 9, display: "Acts 20:9" }],
          explanation:
            "In Troas, young Eutychus falls asleep during Paul's long sermon, falls from a window, and is raised back to life.",
        },
        {
          canonical: "Jerusalem",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 17, display: "Acts 21:17" }],
          explanation: "Paul arrives in Jerusalem and is warmly received by the brothers, one of several visits Acts records.",
        },
        {
          canonical: "Tarsus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 30, display: "Acts 9:30" }],
          explanation: "The brothers send Paul away to Tarsus, his hometown, for safety after the plot against his life.",
        },
        {
          canonical: "Miletus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 15, verseEnd: 17, display: "Acts 20:15-17" }],
          explanation: "Paul stops at Miletus and summons the Ephesian elders there to deliver his farewell address.",
        },
        {
          canonical: "Tyre",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 3, verseEnd: 4, display: "Acts 21:3-4" }],
          explanation: "Paul's ship lands at Tyre, where he seeks out the disciples and stays with them seven days.",
        },
        {
          canonical: "Ptolemais",
          aliases: ["ptolemais"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 7, display: "Acts 21:7" }],
          explanation: "Paul greets the believers during a brief stop at Ptolemais on his way to Jerusalem.",
        },
        {
          canonical: "Sidon",
          aliases: ["sidon"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 3, display: "Acts 27:3" }],
          explanation: "Paul's ship docks at Sidon, where Julius lets him visit friends.",
        },
        {
          canonical: "Myra",
          aliases: ["myra"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 5, display: "Acts 27:5" }],
          explanation: "Paul changes ships at Myra in Lycia while under guard for Rome.",
        },
        {
          canonical: "Syracuse",
          aliases: ["syracuse"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 12, display: "Acts 28:12" }],
          explanation: "Paul's ship stays three days at Syracuse in Sicily en route to Rome.",
        },
        {
          canonical: "Rhegium",
          aliases: ["rhegium"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 13, display: "Acts 28:13" }],
          explanation: "Paul's ship stops briefly at Rhegium before reaching Puteoli.",
        },
        {
          canonical: "Puteoli",
          aliases: ["puteoli"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 13, verseEnd: 14, display: "Acts 28:13-14" }],
          explanation: "Paul finds believers and stays a week at Puteoli near Naples.",
        },
        {
          canonical: "Seleucia",
          aliases: ["seleucia"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 4, display: "Acts 13:4" }],
          explanation: "Paul and Barnabas sail from Seleucia to launch the first missionary journey.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name an object in or associated with the tabernacle.",
      instructions: "You get one guess.",
      whatCounts:
        "Any furnishing or object the text explicitly places in or associated with the wilderness tabernacle.",
      answers: [
        {
          canonical: "Ark of the Covenant",
          aliases: ["ark"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 10, verseEnd: 22, display: "Exodus 25:10-22" }],
          explanation: "The Ark of the Covenant holds the tablets of the law within the Holy of Holies.",
        },
        {
          canonical: "Altar of Burnt Offering",
          aliases: ["bronze altar", "brazen altar"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 27, verseStart: 1, verseEnd: 8, display: "Exodus 27:1-8" }],
          explanation: "The bronze altar for burnt offerings stands in the tabernacle's outer court.",
        },
        {
          canonical: "Menorah",
          aliases: ["lampstand", "golden lampstand"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 31, verseEnd: 40, display: "Exodus 25:31-40" }],
          explanation: "The golden lampstand lights the Holy Place.",
        },
        {
          canonical: "Table of Showbread",
          aliases: ["table of the bread of the presence", "showbread"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 23, verseEnd: 30, display: "Exodus 25:23-30" }],
          explanation: "Twelve loaves of bread rest continually on this table in the Holy Place.",
        },
        {
          canonical: "Veil",
          aliases: ["curtain"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 26, verseStart: 31, verseEnd: 33, display: "Exodus 26:31-33" }],
          explanation: "The veil separates the Holy Place from the Holy of Holies.",
        },
        {
          canonical: "Laver",
          aliases: ["bronze basin", "bronze laver"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 17, verseEnd: 21, display: "Exodus 30:17-21" }],
          explanation: "Priests wash their hands and feet at the bronze laver before serving.",
        },
        {
          canonical: "Ephod",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 6, verseEnd: 14, display: "Exodus 28:6-14" }],
          explanation: "The high priest's ephod carries two onyx stones engraved with Israel's tribes.",
        },
        {
          canonical: "Mercy Seat",
          aliases: ["atonement cover"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 17, verseEnd: 22, display: "Exodus 25:17-22" }],
          explanation:
            "The golden mercy seat atop the Ark is where God promises to meet Moses and speak with him.",
        },
        {
          canonical: "Altar of Incense",
          aliases: ["golden altar","incense altar"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 1, verseEnd: 10, display: "Exodus 30:1-10" }],
          explanation: "A gold-covered acacia altar stands before the veil, where incense is burned morning and evening.",
        },
        {
          canonical: "Tablets of the Covenant",
          aliases: ["ten commandments","stone tablets","tablets of the law","tablets of testimony"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 16, display: "Exodus 25:16" }],
          explanation: "The stone tablets of the testimony are placed inside the ark within the tabernacle.",
        },
        {
          canonical: "Jar of Manna",
          aliases: ["pot of manna","golden urn of manna","manna jar"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 16, verseStart: 33, verseEnd: 34, display: "Exodus 16:33-34" }],
          explanation: "At the LORD's command a jar of manna is set before the testimony to be kept for later generations.",
        },
        {
          canonical: "Aaron's Staff",
          aliases: ["aaron's rod","budding staff","rod that budded"],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 17, verseStart: 10, display: "Numbers 17:10" }],
          explanation: "God commands that Aaron's staff, which had budded, be kept before the testimony as a sign to rebels.",
        },
        {
          canonical: "Urim and Thummim",
          aliases: ["urim","thummim"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 30, display: "Exodus 28:30" }],
          explanation: "The Urim and Thummim are placed in the priestly breastpiece for divine guidance in tabernacle service.",
        },
        {
          canonical: "Anointing Oil",
          aliases: ["holy anointing oil","anointing oil","sacred oil"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 22, verseEnd: 33, display: "Exodus 30:22-33" }],
          explanation: "The anointing oil is specially compounded to consecrate the tabernacle, its furnishings, and the priests.",
        },
        {
          canonical: "Incense",
          aliases: ["holy incense","sweet incense","incense"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 34, verseEnd: 38, display: "Exodus 30:34-38" }],
          explanation: "A specially formulated incense is burned before the Lord on the altar of incense.",
        },
        {
          canonical: "Bread of the Presence",
          aliases: ["twelve loaves","presence bread","shewbread loaves"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 30, verseEnd: 30, display: "Exodus 25:30" }],
          explanation: "Twelve loaves of bread are set continually before the Lord on the table, distinct from the table itself.",
        },
        {
          canonical: "Breastpiece",
          aliases: ["breastplate","high priest's breastpiece","breastpiece of judgment"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 15, verseEnd: 30, display: "Exodus 28:15-30" }],
          explanation: "The high priest wears a jeweled breastpiece bearing the names of the twelve tribes over his heart.",
        },
        {
          canonical: "Robe",
          aliases: ["blue robe","robe of the ephod","bells and pomegranates"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 31, verseEnd: 35, display: "Exodus 28:31-35" }],
          explanation: "The high priest's blue robe is hemmed with alternating bells and pomegranates so its sound is heard when he ministers.",
        },
        {
          canonical: "Turban",
          aliases: ["turban","gold plate","holy to the lord plate"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 36, verseEnd: 39, display: "Exodus 28:36-39" }],
          explanation: "The high priest's turban bears a gold plate engraved 'Holy to the Lord'.",
        },
      ],
    },
  ],
};
