import type { SeedDay } from "./types";

export const DAY_07: SeedDay = {
  dayNumber: 7,
  date: "2026-10-07",
  scriptureBonus: {
    displayText:
      "Don't you be afraid, for I am with you. Don't be dismayed, for I am your God. I will strengthen you.",
    book: "Isaiah",
    chapter: 41,
    verseStart: 10,
    referenceDisplay: "Isaiah 41:10",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "God reassures his people of his presence and strength in the face of fear.",
    acceptedBookAliases: ["isa"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a giant or notably large figure in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any giant or notably large figure the biblical text explicitly describes.",
      answers: [
        {
          canonical: "Goliath",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 17, verseStart: 4, display: "1 Samuel 17:4" }],
          explanation: "Goliath, a Philistine champion over nine feet tall, challenges Israel before David defeats him.",
        },
        {
          canonical: "Og",
          aliases: ["king of bashan"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Deuteronomy", chapterStart: 3, verseStart: 11, display: "Deuteronomy 3:11" }],
          explanation: "Og, king of Bashan, is remembered for his enormous iron bed, nine cubits long.",
        },
        {
          canonical: "The Anakim",
          aliases: ["sons of anak", "anakites"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 33, display: "Numbers 13:33" }],
          explanation: "The spies report seeing the Anakim, a people of great size, in Canaan.",
        },
        {
          canonical: "Ish-bi-benob",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 21, verseStart: 16, display: "2 Samuel 21:16" }],
          explanation: "Ish-bi-benob, a descendant of the giants, nearly kills David in battle.",
        },
        {
          canonical: "Saph",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 21, verseStart: 18, display: "2 Samuel 21:18" }],
          explanation: "Saph, another descendant of the giants, is killed in a battle with the Philistines.",
        },
        {
          canonical: "The Giant with Six Fingers and Six Toes",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 21, verseStart: 20, display: "2 Samuel 21:20" }],
          explanation: "An unnamed giant of great size with six fingers on each hand and six toes on each foot is described in battle.",
        },
        {
          canonical: "Lahmi",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Chronicles", chapterStart: 20, verseStart: 5, display: "1 Chronicles 20:5" }],
          explanation: "Lahmi, Goliath's brother, is killed by Elhanan in a lesser-known battle.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a queen mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any woman the biblical text explicitly identifies as a queen (or queen mother).",
      answers: [
        {
          canonical: "Esther",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 17, display: "Esther 2:17" }],
          explanation: "Esther becomes queen of Persia after finding favor with King Ahasuerus.",
        },
        {
          canonical: "Queen of Sheba",
          aliases: ["sheba"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 10, verseStart: 1, verseEnd: 10, display: "1 Kings 10:1-10" }],
          explanation: "The Queen of Sheba visits Solomon, testing him with hard questions.",
        },
        {
          canonical: "Jezebel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 16, verseStart: 31, display: "1 Kings 16:31" }],
          explanation: "Jezebel, wife of King Ahab, promotes the worship of Baal in Israel.",
        },
        {
          canonical: "Vashti",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Esther", chapterStart: 1, verseStart: 9, verseEnd: 12, display: "Esther 1:9-12" }],
          explanation: "Queen Vashti is deposed for refusing King Ahasuerus's summons, opening the way for Esther.",
        },
        {
          canonical: "Athaliah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 11, verseStart: 1, verseEnd: 3, display: "2 Kings 11:1-3" }],
          explanation: "Athaliah seizes the throne of Judah, the only woman to reign there in her own right.",
        },
        {
          canonical: "Candace",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 27, display: "Acts 8:27" }],
          explanation: "Candace, queen of the Ethiopians, is mentioned in connection with her treasurer's conversion.",
        },
        {
          canonical: "Maacah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 15, verseStart: 13, display: "1 Kings 15:13" }],
          explanation: "Maacah, a queen mother, is removed from her position by King Asa for making an idol.",
        },
        {
          canonical: "Nehushta",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 8, display: "2 Kings 24:8" }],
          explanation: "Nehushta is named as the queen mother of King Jehoiachin.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a tree or plant mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any tree or plant explicitly named in the biblical text.",
      answers: [
        {
          canonical: "Fig Tree",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 11, verseStart: 13, display: "Mark 11:13" }],
          explanation: "Jesus approaches a fig tree looking for fruit.",
        },
        {
          canonical: "Olive Tree",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 8, verseStart: 11, display: "Genesis 8:11" }],
          explanation: "Noah's dove returns carrying a freshly plucked olive leaf.",
        },
        {
          canonical: "Cedar",
          aliases: ["cedar of lebanon"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 5, verseStart: 6, display: "1 Kings 5:6" }],
          explanation: "Solomon requests cedar from Lebanon to build the temple.",
        },
        {
          canonical: "Vine",
          aliases: ["grapevine"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 15, verseStart: 5, display: "John 15:5" }],
          explanation: "Jesus describes himself as the vine and his followers as the branches.",
        },
        {
          canonical: "Sycamore Tree",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 19, verseStart: 4, display: "Luke 19:4" }],
          explanation: "Zacchaeus climbs a sycamore tree to see Jesus over the crowd.",
        },
        {
          canonical: "Mustard Plant",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 31, verseEnd: 32, display: "Matthew 13:31-32" }],
          explanation: "Jesus compares the kingdom of heaven to a mustard plant growing from a tiny seed.",
        },
        {
          canonical: "Terebinth",
          aliases: ["oak"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 35, verseStart: 4, display: "Genesis 35:4" }],
          explanation: "Jacob buries his household's foreign idols under the terebinth (or oak) near Shechem.",
        },
        {
          canonical: "Broom Tree",
          aliases: ["juniper", "juniper tree"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 4, verseEnd: 5, display: "1 Kings 19:4-5" }],
          explanation: "Exhausted and fleeing Jezebel, Elijah rests and sleeps beneath a broom tree.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a high priest mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly identifies as a high priest.",
      answers: [
        {
          canonical: "Aaron",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 1, display: "Exodus 28:1" }],
          explanation: "Aaron, Moses' brother, is consecrated as Israel's first high priest.",
        },
        {
          canonical: "Caiaphas",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 57, display: "Matthew 26:57" }],
          explanation: "Caiaphas is high priest at the time of Jesus' trial.",
        },
        {
          canonical: "Annas",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 18, verseStart: 13, display: "John 18:13" }],
          explanation: "Annas, a former high priest and Caiaphas's father-in-law, questions Jesus first.",
        },
        {
          canonical: "Eli",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 9, display: "1 Samuel 1:9" }],
          explanation: "Eli serves as priest at Shiloh and raises the boy Samuel.",
        },
        {
          canonical: "Eleazar",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 20, verseStart: 25, verseEnd: 28, display: "Numbers 20:25-28" }],
          explanation: "Eleazar succeeds his father Aaron as high priest.",
        },
        {
          canonical: "Jehoiada",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 11, verseStart: 4, verseEnd: 12, display: "2 Kings 11:4-12" }],
          explanation: "The priest Jehoiada protects and crowns the young King Joash.",
        },
        {
          canonical: "Hilkiah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 22, verseStart: 8, display: "2 Kings 22:8" }],
          explanation: "The high priest Hilkiah finds the Book of the Law during Josiah's temple repairs.",
        },
        {
          canonical: "Ithamar",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 38, verseStart: 21, display: "Exodus 38:21" }],
          explanation: "Ithamar, Aaron's youngest son, oversees the record of materials used in the tabernacle.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name one of the seven churches of Revelation.",
      instructions: "You get one guess.",
      whatCounts: "Any of the seven churches addressed in Revelation chapters 2-3.",
      answers: [
        {
          canonical: "Ephesus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 1, display: "Revelation 2:1" }],
          explanation: "Ephesus is the first of the seven churches addressed.",
        },
        {
          canonical: "Laodicea",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 3, verseStart: 14, display: "Revelation 3:14" }],
          explanation: "Laodicea, the last of the seven churches addressed, is rebuked for being lukewarm.",
        },
        {
          canonical: "Smyrna",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 8, display: "Revelation 2:8" }],
          explanation: "Smyrna is the second of the seven churches addressed.",
        },
        {
          canonical: "Pergamum",
          aliases: ["pergamos"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 12, display: "Revelation 2:12" }],
          explanation: "Pergamum is addressed as the church where \"Satan's throne\" is.",
        },
        {
          canonical: "Thyatira",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 18, display: "Revelation 2:18" }],
          explanation: "Thyatira is addressed regarding a false prophetess called Jezebel.",
        },
        {
          canonical: "Sardis",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 3, verseStart: 1, display: "Revelation 3:1" }],
          explanation: "Sardis is told it has a reputation for being alive but is actually dead.",
        },
        {
          canonical: "Philadelphia",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 3, verseStart: 7, display: "Revelation 3:7" }],
          explanation: "Philadelphia is commended and given an open door that no one can shut.",
        },
      ],
    },
  ],
};
