import type { SeedDay } from "./types";

export const DAY_08: SeedDay = {
  dayNumber: 8,
  date: "2026-09-25",
  scriptureBonus: {
    displayText: "Seek first God's Kingdom, and his righteousness; and all these things will be given to you as well.",
    book: "Matthew",
    chapter: 6,
    verseStart: 33,
    referenceDisplay: "Matthew 6:33",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Part of the Sermon on the Mount, encouraging trust in God's provision over anxious striving.",
    acceptedBookAliases: ["matt"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person imprisoned for their faith.",
      instructions: "You get one guess.",
      whatCounts:
        "Any person the biblical text describes as imprisoned or exiled because of their faithfulness to God.",
      answers: [
        {
          canonical: "Paul",
          aliases: ["saul"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 23, verseEnd: 24, display: "Acts 16:23-24" }],
          explanation: "Paul and Silas are beaten and imprisoned in Philippi for their preaching.",
        },
        {
          canonical: "Peter",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 3, verseEnd: 5, display: "Acts 12:3-5" }],
          explanation: "Herod imprisons Peter, who is later freed by an angel.",
        },
        {
          canonical: "John the Baptist",
          aliases: ["the baptist", "baptist"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 3, display: "Matthew 14:3" }],
          explanation: "Herod Antipas imprisons John the Baptist for condemning his marriage.",
        },
        {
          canonical: "Silas",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 23, verseEnd: 24, display: "Acts 16:23-24" }],
          explanation: "Silas is imprisoned alongside Paul in Philippi.",
        },
        {
          canonical: "Jeremiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 37, verseStart: 15, display: "Jeremiah 37:15" }],
          explanation: "Jeremiah is beaten and imprisoned for his unwelcome prophecies.",
        },
        {
          canonical: "Micaiah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 26, verseEnd: 27, display: "1 Kings 22:26-27" }],
          explanation: "King Ahab imprisons the prophet Micaiah for a true but unwelcome prophecy.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 39, verseStart: 20, display: "Genesis 39:20" }],
          explanation:
            "Joseph is imprisoned on a false accusation after refusing to betray his integrity with Potiphar's wife.",
          inclusionNotes:
            "Included for his imprisonment resulting from faithful refusal to sin, though the text frames the charge itself as false.",
        },
        {
          canonical: "John",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 1, verseStart: 9, display: "Revelation 1:9" }],
          explanation:
            "John is on the island of Patmos \"for the word of God and the testimony of Jesus\" when he receives his vision.",
        },
        {
          canonical: "Hanani the Seer",
          aliases: ["Hanani","Hanani the prophet"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Chronicles", chapterStart: 16, verseStart: 10, display: "2 Chronicles 16:10" }],
          explanation: "King Asa, enraged at Hanani the seer for rebuking his reliance on Syria instead of the LORD, puts him in prison.",
        },
        {
          canonical: "Aristarchus",
          aliases: ["Aristarchus my fellow prisoner"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Colossians", chapterStart: 4, verseStart: 10, display: "Colossians 4:10" }],
          explanation: "Paul calls Aristarchus his fellow prisoner while writing to the Colossians.",
        },
        {
          canonical: "Epaphras",
          aliases: ["Epaphras my fellow prisoner"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Philemon", chapterStart: 1, verseStart: 23, display: "Philemon 1:23" }],
          explanation: "Paul names Epaphras his fellow prisoner in Christ Jesus in his letter to Philemon.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a king of Israel (the northern kingdom).",
      instructions: "You get one guess.",
      whatCounts: "Any king who ruled over the northern kingdom of Israel after the division from Judah.",
      answers: [
        {
          canonical: "Jeroboam I",
          aliases: ["jeroboam the first", "jeroboam 1"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 12, verseStart: 20, display: "1 Kings 12:20" }],
          explanation: "Jeroboam becomes the first king of the northern kingdom of Israel.",
        },
        {
          canonical: "Ahab",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 16, verseStart: 29, display: "1 Kings 16:29" }],
          explanation: "Ahab, married to Jezebel, is opposed by the prophet Elijah.",
        },
        {
          canonical: "Omri",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 16, verseStart: 23, display: "1 Kings 16:23" }],
          explanation: "Omri, Ahab's father, builds the city of Samaria as Israel's capital.",
        },
        {
          canonical: "Jehu",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 9, verseStart: 1, verseEnd: 13, display: "2 Kings 9:1-13" }],
          explanation: "Jehu is anointed to destroy the house of Ahab.",
        },
        {
          canonical: "Jeroboam II",
          aliases: ["jeroboam the second", "jeroboam 2"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 14, verseStart: 23, display: "2 Kings 14:23" }],
          explanation: "Jeroboam II presides over a period of military and economic expansion in Israel.",
        },
        {
          canonical: "Baasha",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 15, verseStart: 33, display: "1 Kings 15:33" }],
          explanation: "Baasha reigns over Israel after seizing the throne from Jeroboam's line.",
        },
        {
          canonical: "Pekah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 27, display: "2 Kings 15:27" }],
          explanation: "Pekah reigns over Israel during a period of Assyrian pressure.",
        },
        {
          canonical: "Hoshea",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 17, verseStart: 1, display: "2 Kings 17:1" }],
          explanation: "Hoshea is the last king of Israel before the Assyrian conquest ends the northern kingdom.",
        },
        {
          canonical: "Nadab",
          aliases: ["Nadab son of Jeroboam"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 15, verseStart: 25, verseEnd: 31, display: "1 Kings 15:25-31" }],
          explanation: "Nadab son of Jeroboam I reigns two years over Israel before Baasha assassinates him and wipes out his house.",
        },
        {
          canonical: "Elah",
          aliases: ["Elah son of Baasha"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 16, verseStart: 6, verseEnd: 14, display: "1 Kings 16:6-14" }],
          explanation: "Elah son of Baasha reigns two years over Israel until his servant Zimri strikes him down while he is drunk.",
        },
        {
          canonical: "Zimri",
          aliases: ["Zimri king of Israel","seven-day king"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 16, verseStart: 15, verseEnd: 20, display: "1 Kings 16:15-20" }],
          explanation: "Zimri reigns just seven days in Tirzah before burning the palace down over himself as Omri's forces close in.",
        },
        {
          canonical: "Tibni",
          aliases: ["Tibni son of Ginath"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 16, verseStart: 21, verseEnd: 22, display: "1 Kings 16:21-22" }],
          explanation: "Half of Israel follows Tibni as rival king against Omri until Omri's supporters prevail and Tibni dies.",
        },
        {
          canonical: "Ahaziah of Israel",
          aliases: ["Ahaziah son of Ahab","King Ahaziah (Israel)"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 1, verseStart: 1, verseEnd: 18, display: "2 Kings 1:1-18" }],
          explanation: "Ahaziah son of Ahab reigns over Israel and later, injured in a fall, sends messengers to inquire of Baal-zebub instead of the LORD.",
        },
        {
          canonical: "Jehoram of Israel",
          aliases: ["Joram of Israel","Jehoram son of Ahab"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 9, verseStart: 24, verseEnd: 26, display: "2 Kings 9:24-26" }],
          explanation: "Jehoram son of Ahab reigns over Israel until Jehu kills him and throws his body into Naboth's field.",
        },
        {
          canonical: "Jehoahaz of Israel",
          aliases: ["Jehoahaz son of Jehu"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 13, verseStart: 1, verseEnd: 9, display: "2 Kings 13:1-9" }],
          explanation: "Jehoahaz son of Jehu reigns over Israel and Israel is oppressed by Hazael of Syria throughout his days.",
        },
        {
          canonical: "Jehoash of Israel",
          aliases: ["Joash of Israel","Jehoash son of Jehoahaz"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 13, verseStart: 10, verseEnd: 25, display: "2 Kings 13:10-25" }],
          explanation: "Jehoash son of Jehoahaz reigns over Israel, weeps over the dying Elisha, and later defeats Amaziah of Judah.",
        },
        {
          canonical: "Zechariah of Israel",
          aliases: ["Zechariah son of Jeroboam"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 8, verseEnd: 12, display: "2 Kings 15:8-12" }],
          explanation: "Zechariah son of Jeroboam II reigns just six months before Shallum assassinates him, fulfilling the LORD's word to Jehu.",
        },
        {
          canonical: "Shallum",
          aliases: ["Shallum son of Jabesh"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 13, verseEnd: 15, display: "2 Kings 15:13-15" }],
          explanation: "Shallum assassinates Zechariah and reigns over Israel for only one month before Menahem kills him in turn.",
        },
        {
          canonical: "Menahem",
          aliases: ["Menahem son of Gadi"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 14, verseEnd: 22, display: "2 Kings 15:14-22" }],
          explanation: "Menahem seizes the throne of Israel and later pays tribute silver to Pul, king of Assyria, to secure his hold on power.",
        },
        {
          canonical: "Pekahiah",
          aliases: ["Pekahiah son of Menahem"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 23, verseEnd: 26, display: "2 Kings 15:23-26" }],
          explanation: "Pekahiah son of Menahem reigns two years over Israel before his officer Pekah conspires and kills him.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name an item of the high priest's garments.",
      instructions: "You get one guess.",
      whatCounts: "Any item of the high priest's garments described in Exodus 28.",
      answers: [
        {
          canonical: "Ephod",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 6, display: "Exodus 28:6" }],
          explanation: "The ephod is a decorated vest worn by the high priest over his robe.",
        },
        {
          canonical: "Breastplate",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 15, display: "Exodus 28:15" }],
          explanation: "The breastplate of judgment holds twelve stones representing Israel's tribes.",
        },
        {
          canonical: "Turban",
          aliases: ["mitre"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 36, verseEnd: 38, display: "Exodus 28:36-38" }],
          explanation: "The high priest wears a turban with a gold plate fastened to the front.",
        },
        {
          canonical: "Robe",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 31, verseEnd: 34, display: "Exodus 28:31-34" }],
          explanation: "The blue robe of the ephod is hemmed with bells and pomegranates.",
        },
        {
          canonical: "Sash",
          aliases: ["girdle"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 39, display: "Exodus 28:39" }],
          explanation: "A finely woven sash is part of the priestly garments.",
        },
        {
          canonical: "Tunic",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 39, display: "Exodus 28:39" }],
          explanation: "A fine linen tunic is woven for the high priest.",
        },
        {
          canonical: "Golden Bells",
          aliases: ["bells"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 33, verseEnd: 34, display: "Exodus 28:33-34" }],
          explanation: "Golden bells alternate with pomegranates around the hem of the priestly robe.",
        },
        {
          canonical: "Gold Plate on the Turban",
          aliases: ["gold plate", "turban plate"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 36, display: "Exodus 28:36" }],
          explanation: "A gold plate engraved with a holy inscription is fastened to the front of the turban.",
        },
        {
          canonical: "Pomegranates on the Robe",
          aliases: ["pomegranates","hem pomegranates","robe pomegranates"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 33, verseEnd: 34, display: "Exodus 28:33-34" }],
          explanation: "Blue, purple, and scarlet pomegranates are made around the hem of the robe, alternating with the golden bells.",
        },
        {
          canonical: "Urim and Thummim",
          aliases: ["Urim","Thummim"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 30, display: "Exodus 28:30" }],
          explanation: "Moses is told to put the Urim and Thummim inside the breastplate for Aaron to carry before the LORD.",
        },
        {
          canonical: "Onyx Shoulder Stones",
          aliases: ["onyx stones","shoulder stones","shoulder onyx"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 9, verseEnd: 12, display: "Exodus 28:9-12" }],
          explanation: "Two onyx stones engraved with the names of Israel's tribes are set on the ephod's shoulder pieces as memorial stones.",
        },
        {
          canonical: "Linen Undergarments",
          aliases: ["linen breeches","linen undergarment","priestly undergarments"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 42, display: "Exodus 28:42" }],
          explanation: "Linen undergarments are made to cover the priests' bodies from the waist to the thigh.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a fisherman among Jesus' disciples.",
      instructions: "You get one guess.",
      whatCounts: "Any of the disciples the Gospels explicitly describe as fishermen before following Jesus.",
      answers: [
        {
          canonical: "Peter",
          aliases: ["simon peter"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 18, display: "Matthew 4:18" }],
          explanation: "Peter is fishing on the Sea of Galilee when Jesus calls him.",
        },
        {
          canonical: "Andrew",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 18, display: "Matthew 4:18" }],
          explanation: "Andrew, Peter's brother, is casting a net into the sea when called.",
        },
        {
          canonical: "James",
          aliases: ["james son of zebedee"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 21, display: "Matthew 4:21" }],
          explanation: "James is in a boat mending nets with his father Zebedee when Jesus calls him.",
        },
        {
          canonical: "John",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 21, display: "Matthew 4:21" }],
          explanation: "John is in the boat with his brother James and their father Zebedee.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a spy sent into Canaan.",
      instructions: "You get one guess.",
      whatCounts: "Any of the twelve spies Moses sent to scout the land of Canaan, named in Numbers 13.",
      answers: [
        {
          canonical: "Caleb",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 6, display: "Numbers 13:6" }],
          explanation: "Caleb, representing Judah, is one of only two spies who urge Israel to enter the land.",
        },
        {
          canonical: "Joshua",
          aliases: ["hoshea"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 8, display: "Numbers 13:8" }],
          explanation: "Joshua, called Hoshea before Moses renamed him, represents Ephraim among the spies.",
        },
        {
          canonical: "Shammua",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 4, display: "Numbers 13:4" }],
          explanation: "Shammua represents the tribe of Reuben among the twelve spies.",
        },
        {
          canonical: "Shaphat",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 5, display: "Numbers 13:5" }],
          explanation: "Shaphat represents the tribe of Simeon among the twelve spies.",
        },
        {
          canonical: "Igal",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 7, display: "Numbers 13:7" }],
          explanation: "Igal represents the tribe of Issachar among the twelve spies.",
        },
        {
          canonical: "Palti",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 9, display: "Numbers 13:9" }],
          explanation: "Palti represents the tribe of Benjamin among the twelve spies.",
        },
        {
          canonical: "Gaddiel",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 10, display: "Numbers 13:10" }],
          explanation: "Gaddiel represents the tribe of Zebulun among the twelve spies.",
        },
        {
          canonical: "Gaddi",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 11, display: "Numbers 13:11" }],
          explanation: "Gaddi represents the tribe of Manasseh among the twelve spies.",
        },
        {
          canonical: "Ammiel",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 12, display: "Numbers 13:12" }],
          explanation: "Ammiel represents the tribe of Dan among the twelve spies.",
        },
        {
          canonical: "Sethur",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 13, display: "Numbers 13:13" }],
          explanation: "Sethur represents the tribe of Asher among the twelve spies.",
        },
        {
          canonical: "Nahbi",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 14, display: "Numbers 13:14" }],
          explanation: "Nahbi represents the tribe of Naphtali among the twelve spies.",
        },
        {
          canonical: "Geuel",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Numbers", chapterStart: 13, verseStart: 15, display: "Numbers 13:15" }],
          explanation: "Geuel, representing Gad, is the last of the twelve spies named in the list.",
        },
      ],
    },
  ],
};
