import type { SeedDay } from "./types";

export const DAY_03: SeedDay = {
  dayNumber: 3,
  date: "2026-09-20",
  scriptureBonus: {
    displayText: "I can do all things through Christ, who strengthens me.",
    book: "Philippians",
    chapter: 4,
    verseStart: 13,
    referenceDisplay: "Philippians 4:13",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote:
      "Paul writes this from prison, describing the contentment he has learned in every circumstance through Christ's strength.",
    acceptedBookAliases: ["phil"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person who spoke with an angel.",
      instructions: "You get one guess.",
      whatCounts:
        "Any named person the biblical text explicitly describes speaking with an angel (including \"the angel of the LORD\"). A few answers from the wider Catholic canon are also accepted — see the results screen for those.",
      answers: [
        {
          canonical: "Mary",
          aliases: ["mary mother of jesus", "virgin mary"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 26, verseEnd: 38, display: "Luke 1:26-38" }],
          explanation: "The angel Gabriel announces to Mary that she will bear Jesus.",
        },
        {
          canonical: "Mary Magdalene",
          aliases: ["magdalene"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 20, verseStart: 11, verseEnd: 13, display: "John 20:11-13" }],
          explanation: "Two angels ask Mary Magdalene, weeping at the empty tomb, why she is crying.",
        },
        {
          canonical: "Zechariah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 11, verseEnd: 20, display: "Luke 1:11-20" }],
          explanation:
            "Gabriel appears to Zechariah in the temple, announcing the birth of John the Baptist.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 20, verseEnd: 21, display: "Matthew 1:20-21" }],
          explanation: "An angel speaks to Joseph in a dream, telling him to take Mary as his wife.",
        },
        {
          canonical: "Hagar",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 16, verseStart: 7, verseEnd: 13, display: "Genesis 16:7-13" }],
          explanation: "The angel of the LORD speaks with Hagar in the wilderness.",
        },
        {
          canonical: "Gideon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 11, verseEnd: 24, display: "Judges 6:11-24" }],
          explanation: "The angel of the LORD appears to Gideon and commissions him to deliver Israel.",
        },
        {
          canonical: "Manoah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 13, verseStart: 3, verseEnd: 20, display: "Judges 13:3-20" }],
          explanation:
            "The angel of the LORD appears to Manoah and his wife, announcing the birth of Samson.",
        },
        {
          canonical: "Tobit",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Tobit", chapterStart: 5, chapterEnd: 12, display: "Tobit 5-12" }],
          explanation:
            "The angel Raphael, disguised as a traveling companion for Tobit's son, later reveals himself as one of God's seven holy angels.",
          catholicOnly: true,
        },
        {
          canonical: "Daniel",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 9, verseStart: 21, verseEnd: 22, display: "Daniel 9:21-22" }],
          explanation: "The angel Gabriel speaks with Daniel to give him understanding of a vision.",
        },
        {
          canonical: "Philip",
          aliases: ["philip the evangelist"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 26, display: "Acts 8:26" }],
          explanation:
            "An angel of the Lord speaks to Philip, sending him south to meet the Ethiopian official.",
        },
        {
          canonical: "Abraham",
          aliases: ["Father Abraham"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 22, verseStart: 11, verseEnd: 12, display: "Genesis 22:11-12" }],
          explanation: "The angel of the LORD calls to Abraham from heaven and stops him from sacrificing Isaac.",
        },
        {
          canonical: "Lot",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 1, verseEnd: 22, display: "Genesis 19:1-22" }],
          explanation: "Two angels come to Sodom, warn Lot of its destruction, and speak with him as they lead his family to safety.",
        },
        {
          canonical: "Balaam",
          aliases: ["Balaam's donkey"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 22, verseStart: 22, verseEnd: 35, display: "Numbers 22:22-35" }],
          explanation: "The angel of the LORD stands in Balaam's path with a drawn sword and speaks to him directly.",
        },
        {
          canonical: "Elijah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 5, verseEnd: 7, display: "1 Kings 19:5-7" }],
          explanation: "An angel touches the exhausted Elijah under the broom tree and tells him to get up and eat.",
        },
        {
          canonical: "Peter",
          aliases: ["Simon Peter"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 7, verseEnd: 10, display: "Acts 12:7-10" }],
          explanation: "An angel wakes Peter in prison, tells him to get up quickly, and leads him past the guards to freedom.",
        },
        {
          canonical: "Cornelius",
          aliases: ["Cornelius the Centurion"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 3, verseEnd: 6, display: "Acts 10:3-6" }],
          explanation: "An angel appears to Cornelius in a vision and tells him to send for Peter in Joppa.",
        },
        {
          canonical: "Paul",
          aliases: ["Apostle Paul","Saul"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 23, verseEnd: 24, display: "Acts 27:23-24" }],
          explanation: "During the storm before his shipwreck, an angel stands beside Paul and tells him not to be afraid.",
        },
        {
          canonical: "John",
          aliases: ["John the Apostle","John of Patmos"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 22, verseStart: 8, verseEnd: 9, display: "Revelation 22:8-9" }],
          explanation: "John falls down to worship the angel showing him the visions, and the angel speaks, telling him not to do so.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a ruler of Judah.",
      instructions: "You get one guess.",
      whatCounts:
        "Any king or ruler over Judah, including David and Solomon of the united kingdom, the later kings of the southern kingdom after the division of Israel, and Athaliah, who seized the throne and ruled in her own right.",
      answers: [
        {
          canonical: "David",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 3, verseEnd: 5, display: "2 Samuel 5:3-5" }],
          explanation: "David is anointed king over all Israel and Judah.",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 1, verseStart: 39, display: "1 Kings 1:39" }],
          explanation: "Solomon is anointed king, succeeding his father David.",
        },
        {
          canonical: "Hezekiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 18, verseStart: 1, verseEnd: 3, display: "2 Kings 18:1-3" }],
          explanation: "Hezekiah reigns in Judah and is remembered for doing right in the LORD's eyes.",
        },
        {
          canonical: "Josiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 22, verseStart: 1, verseEnd: 2, display: "2 Kings 22:1-2" }],
          explanation:
            "Josiah becomes king at age eight and leads a major religious reform after the Law is rediscovered.",
        },
        {
          canonical: "Rehoboam",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 12, verseStart: 1, verseEnd: 17, display: "1 Kings 12:1-17" }],
          explanation: "Solomon's son Rehoboam's harsh response to Israel leads to the kingdom's division.",
        },
        {
          canonical: "Manasseh",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 21, verseStart: 1, verseEnd: 9, display: "2 Kings 21:1-9" }],
          explanation: "Manasseh reigns fifty-five years in Judah and leads it into idolatry.",
        },
        {
          canonical: "Amon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 21, verseStart: 19, verseEnd: 22, display: "2 Kings 21:19-22" }],
          explanation: "Amon, Manasseh's son, reigns briefly in Judah and follows his father's idolatry.",
        },
        {
          canonical: "Jotham",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 32, verseEnd: 35, display: "2 Kings 15:32-35" }],
          explanation: "Jotham, son of Uzziah, reigns over Judah and does what is right in the LORD's eyes.",
        },
        {
          canonical: "Asa",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 15, verseStart: 9, verseEnd: 24, display: "1 Kings 15:9-24" }],
          explanation: "Asa reigns in Judah, removes idols from the land, and is commended for a mostly faithful rule.",
        },
        {
          canonical: "Jehoshaphat",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 41, verseEnd: 50, display: "1 Kings 22:41-50" }],
          explanation: "Jehoshaphat rules Judah, allies with Israel's king Ahab, and is commended for seeking the LORD.",
        },
        {
          canonical: "Uzziah",
          aliases: ["Azariah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 1, verseEnd: 7, display: "2 Kings 15:1-7" }],
          explanation: "Uzziah rules Judah for 52 years but is struck with leprosy after burning incense in the temple.",
        },
        {
          canonical: "Joash",
          aliases: ["Jehoash"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 11, verseStart: 1, verseEnd: 21, display: "2 Kings 11:1-12:21" }],
          explanation: "Joash is hidden in the temple as a child to escape Athaliah's purge, then crowned king of Judah at age seven.",
        },
        {
          canonical: "Ahaz",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 16, verseStart: 1, verseEnd: 20, display: "2 Kings 16:1-20" }],
          explanation: "Ahaz rules Judah, turns to foreign gods, and receives Isaiah's Immanuel prophecy during an invasion.",
        },
        {
          canonical: "Zedekiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 17, verseEnd: 25, display: "2 Kings 24:17-25:7" }],
          explanation: "Zedekiah is Judah's last king before Jerusalem falls to Babylon, and he is captured and blinded.",
        },
        {
          canonical: "Athaliah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 11, verseStart: 1, verseEnd: 3, display: "2 Kings 11:1-3" }],
          explanation: "Athaliah seizes the throne after her son's death, becoming the only queen to rule Judah in her own right.",
        },
        {
          canonical: "Amaziah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 14, verseStart: 1, verseEnd: 22, display: "2 Kings 14:1-22" }],
          explanation: "Amaziah rules Judah, defeats Edom, then is defeated and humiliated by Israel's king Jehoash.",
        },
        {
          canonical: "Jehoiakim",
          aliases: ["Eliakim"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 34, verseEnd: 24, display: "2 Kings 23:34-24:6" }],
          explanation: "Jehoiakim is installed as king of Judah by Pharaoh Necho and later burns Jeremiah's prophetic scroll.",
        },
        {
          canonical: "Jehoiachin",
          aliases: ["Jeconiah","Coniah"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 6, verseEnd: 16, display: "2 Kings 24:6-16" }],
          explanation: "Jehoiachin reigns only three months before Nebuchadnezzar exiles him to Babylon.",
        },
        {
          canonical: "Abijah",
          aliases: ["Abijam"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 15, verseStart: 1, verseEnd: 8, display: "1 Kings 15:1-8" }],
          explanation: "Abijah reigns briefly over Judah between Rehoboam and Asa while warring with Jeroboam of Israel.",
        },
        {
          canonical: "Jehoram",
          aliases: ["Joram"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 8, verseStart: 16, verseEnd: 24, display: "2 Kings 8:16-24" }],
          explanation: "Jehoram marries Ahab's daughter Athaliah and kills his own brothers to secure Judah's throne.",
        },
        {
          canonical: "Ahaziah of Judah",
          aliases: ["Ahaziah"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 8, verseStart: 25, verseEnd: 29, display: "2 Kings 8:25-29" }],
          explanation: "Ahaziah reigns over Judah for only one year before being killed by Jehu.",
        },
        {
          canonical: "Jehoahaz of Judah",
          aliases: ["Jehoahaz","Shallum"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 31, verseEnd: 34, display: "2 Kings 23:31-34" }],
          explanation: "Jehoahaz reigns just three months before Pharaoh Necho deposes him and takes him to Egypt.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a parable told by Jesus.",
      instructions: "You get one guess.",
      whatCounts: "Any parable the Gospels explicitly attribute to Jesus.",
      answers: [
        {
          canonical: "The Prodigal Son",
          aliases: ["the lost son", "prodigal son"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 11, verseEnd: 32, display: "Luke 15:11-32" }],
          explanation: "A father welcomes home his wayward son who squandered his inheritance.",
        },
        {
          canonical: "The Good Samaritan",
          aliases: ["good samaritan"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 10, verseStart: 25, verseEnd: 37, display: "Luke 10:25-37" }],
          explanation: "A Samaritan stops to help a wounded traveler after religious leaders pass him by.",
        },
        {
          canonical: "The Sower",
          aliases: ["parable of the sower", "sower"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 3, verseEnd: 9, display: "Matthew 13:3-9" }],
          explanation: "A farmer scatters seed that falls on different types of soil with different results.",
        },
        {
          canonical: "The Mustard Seed",
          aliases: ["mustard seed"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 31, verseEnd: 32, display: "Matthew 13:31-32" }],
          explanation: "The kingdom of heaven is compared to a tiny mustard seed that grows into a large tree.",
        },
        {
          canonical: "The Lost Sheep",
          aliases: ["lost sheep"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 3, verseEnd: 7, display: "Luke 15:3-7" }],
          explanation: "A shepherd leaves ninety-nine sheep to search for the one that is lost.",
        },
        {
          canonical: "The Ten Virgins",
          aliases: ["the ten bridesmaids", "ten virgins", "ten bridesmaids"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 25, verseStart: 1, verseEnd: 13, display: "Matthew 25:1-13" }],
          explanation: "Five wise and five foolish virgins wait for a bridegroom, only some of them prepared.",
        },
        {
          canonical: "The Persistent Widow",
          aliases: ["the unjust judge", "persistent widow", "unjust judge"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 18, verseStart: 1, verseEnd: 8, display: "Luke 18:1-8" }],
          explanation: "A widow's persistence wears down an unjust judge into granting her justice.",
        },
        {
          canonical: "The Sheep and the Goats",
          aliases: ["sheep and goats"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 25, verseStart: 31, verseEnd: 46, display: "Matthew 25:31-46" }],
          explanation: "The Son of Man separates the nations as a shepherd separates sheep from goats, based on how they treated \"the least of these.\"",
        },
        {
          canonical: "The Leaven",
          aliases: ["the yeast", "leaven", "yeast"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 33, display: "Matthew 13:33" }],
          explanation: "Jesus compares the kingdom of heaven to leaven a woman works through a large batch of flour.",
        },
        {
          canonical: "The Unjust Steward",
          aliases: ["the dishonest manager", "dishonest manager", "unjust steward"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 16, verseStart: 1, verseEnd: 13, display: "Luke 16:1-13" }],
          explanation: "A manager about to be fired shrewdly reduces his master's debtors' bills to secure his own future.",
        },
        {
          canonical: "The Ten Minas",
          aliases: ["the ten pounds", "ten minas", "ten pounds", "minas"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 19, verseStart: 11, verseEnd: 27, display: "Luke 19:11-27" }],
          explanation: "A nobleman gives ten servants a mina each to invest while he is away, then rewards them in proportion to what they earned.",
        },
        {
          canonical: "The Rich Fool",
          aliases: ["rich fool"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 12, verseStart: 16, verseEnd: 21, display: "Luke 12:16-21" }],
          explanation:
            "A rich man plans bigger barns for his abundant crops, not knowing his life will end that very night.",
        },
        {
          canonical: "The Talents",
          aliases: ["Talents","Parable of the Talents"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 25, verseStart: 14, verseEnd: 30, display: "Matthew 25:14-30" }],
          explanation: "A master entrusts his servants with talents and rewards the ones who put the money to work.",
        },
        {
          canonical: "The Wise and Foolish Builders",
          aliases: ["Wise and Foolish Builders","House on the Rock","Two Builders"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 7, verseStart: 24, verseEnd: 27, display: "Matthew 7:24-27" }],
          explanation: "Jesus contrasts the wise man who builds his house on rock with the foolish man who builds on sand.",
        },
        {
          canonical: "The Rich Man and Lazarus",
          aliases: ["Rich Man and Lazarus","Lazarus and the Rich Man"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 16, verseStart: 19, verseEnd: 31, display: "Luke 16:19-31" }],
          explanation: "A rich man ignores the beggar Lazarus at his gate, and their fortunes reverse after death.",
        },
        {
          canonical: "The Lost Coin",
          aliases: ["Lost Coin","Woman and the Lost Coin"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 8, verseEnd: 10, display: "Luke 15:8-10" }],
          explanation: "A woman sweeps her house searching for one lost coin and rejoices with her neighbors when she finds it.",
        },
        {
          canonical: "The Workers in the Vineyard",
          aliases: ["Workers in the Vineyard","Laborers in the Vineyard"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 20, verseStart: 1, verseEnd: 16, display: "Matthew 20:1-16" }],
          explanation: "A vineyard owner pays workers the same wage whether they labored all day or just one hour.",
        },
        {
          canonical: "The Wedding Feast",
          aliases: ["Wedding Feast","Great Banquet","Marriage Feast"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 22, verseStart: 1, verseEnd: 14, display: "Matthew 22:1-14" }],
          explanation: "A king invites guests to his son's wedding feast, and when the invited refuse, he fills the hall with strangers.",
        },
        {
          canonical: "The Unforgiving Servant",
          aliases: ["Unforgiving Servant","Unmerciful Servant"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 18, verseStart: 23, verseEnd: 35, display: "Matthew 18:23-35" }],
          explanation: "A servant forgiven a huge debt refuses to forgive a fellow servant's small debt and is punished.",
        },
        {
          canonical: "The Pharisee and the Tax Collector",
          aliases: ["Pharisee and Tax Collector","Pharisee and Publican"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 18, verseStart: 9, verseEnd: 14, display: "Luke 18:9-14" }],
          explanation: "A Pharisee boasts in prayer while a tax collector humbly begs for mercy, and Jesus says the latter goes home justified.",
        },
        {
          canonical: "The Wicked Tenants",
          aliases: ["Wicked Tenants","Vineyard and the Tenants"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 21, verseStart: 33, verseEnd: 46, display: "Matthew 21:33-46" }],
          explanation: "Tenants beat and kill the servants a vineyard owner sends, then kill his son, so he gives the vineyard to others.",
        },
        {
          canonical: "The Hidden Treasure",
          aliases: ["Hidden Treasure","Treasure in the Field"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 44, verseEnd: 44, display: "Matthew 13:44" }],
          explanation: "A man finds treasure hidden in a field and sells everything he has to buy that field.",
        },
        {
          canonical: "The Pearl of Great Price",
          aliases: ["Pearl of Great Price","Pearl of Great Value"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 45, verseEnd: 46, display: "Matthew 13:45-46" }],
          explanation: "A merchant sells all he has to buy one pearl of great value.",
        },
        {
          canonical: "The Seed Growing Secretly",
          aliases: ["seed growing secretly","the growing seed","growing seed"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Mark", chapterStart: 4, verseStart: 26, verseEnd: 29, display: "Mark 4:26-29" }],
          explanation: "A man scatters seed that grows on its own while he sleeps and rises, night and day, and he does not know how.",
        },
        {
          canonical: "The Barren Fig Tree",
          aliases: ["barren fig tree"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 13, verseStart: 6, verseEnd: 9, display: "Luke 13:6-9" }],
          explanation: "A vineyard owner wants to cut down a fig tree that bears no fruit, but the gardener asks for one more year to tend it.",
        },
        {
          canonical: "The Friend at Midnight",
          aliases: ["friend at midnight"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 11, verseStart: 5, verseEnd: 8, display: "Luke 11:5-8" }],
          explanation: "A man persistently knocks on a friend's door at midnight to borrow bread, and his shameless persistence gets him what he needs.",
        },
        {
          canonical: "The Two Sons",
          aliases: ["two sons"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 21, verseStart: 28, verseEnd: 32, display: "Matthew 21:28-32" }],
          explanation: "A father asks two sons to work in his vineyard; one refuses but later goes, the other agrees but does not.",
        },
        {
          canonical: "The Net",
          aliases: ["the dragnet","dragnet"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 47, verseEnd: 50, display: "Matthew 13:47-50" }],
          explanation: "A net cast into the sea gathers fish of every kind, and at the end of the age the angels separate the good from the bad.",
        },
        {
          canonical: "The Lamp Under a Basket",
          aliases: ["lamp under a bushel","hidden lamp"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 14, verseEnd: 15, display: "Matthew 5:14-15" }],
          explanation: "Jesus says no one lights a lamp and hides it under a basket, but sets it on a stand to give light to the house.",
        },
        {
          canonical: "The Master and Servant",
          aliases: ["unworthy servants","master and servant"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 17, verseStart: 7, verseEnd: 10, display: "Luke 17:7-10" }],
          explanation: "Jesus describes a servant who plows the field then serves his master's meal before eating himself, owed no special thanks for simply doing his duty.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a plague that struck Egypt.",
      instructions: "You get one guess.",
      whatCounts: "Any of the ten plagues the book of Exodus describes striking Egypt.",
      answers: [
        {
          canonical: "Blood",
          aliases: ["water turned to blood"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 7, verseStart: 20, verseEnd: 21, display: "Exodus 7:20-21" }],
          explanation: "The waters of Egypt's river turn to blood, killing the fish.",
        },
        {
          canonical: "Frogs",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 8, verseStart: 6, display: "Exodus 8:6" }],
          explanation: "Frogs cover the land of Egypt.",
        },
        {
          canonical: "Gnats",
          aliases: ["lice"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 8, verseStart: 16, verseEnd: 17, display: "Exodus 8:16-17" }],
          explanation: "Aaron strikes the dust and it becomes gnats throughout Egypt — the third plague.",
        },
        {
          canonical: "Flies",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 8, verseStart: 24, display: "Exodus 8:24" }],
          explanation: "Dense swarms of flies fill Egypt's houses and land — the fourth plague.",
        },
        {
          canonical: "Death of the Firstborn",
          aliases: ["firstborn", "death of firstborn"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 12, verseStart: 29, display: "Exodus 12:29" }],
          explanation: "The LORD strikes down every firstborn in Egypt at midnight.",
        },
        {
          canonical: "Hail",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 9, verseStart: 23, verseEnd: 25, display: "Exodus 9:23-25" }],
          explanation: "A devastating hailstorm strikes Egypt's crops and livestock.",
        },
        {
          canonical: "Locusts",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 10, verseStart: 14, verseEnd: 15, display: "Exodus 10:14-15" }],
          explanation: "Swarms of locusts devour every plant left after the hail.",
        },
        {
          canonical: "Darkness",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 10, verseStart: 22, display: "Exodus 10:22" }],
          explanation: "Thick darkness covers Egypt for three days.",
        },
        {
          canonical: "Boils",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 9, verseStart: 10, display: "Exodus 9:10" }],
          explanation: "Festering boils break out on people and animals throughout Egypt.",
        },
        {
          canonical: "Pestilence on Livestock",
          aliases: ["plague on livestock", "pestilence"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 9, verseStart: 3, verseEnd: 6, display: "Exodus 9:3-6" }],
          explanation:
            "A severe plague kills the livestock of Egypt, while none of Israel's animals die — often the most forgotten of the ten.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a place in the Book of Revelation.",
      instructions: "You get one guess.",
      whatCounts: "Any place explicitly named in the book of Revelation.",
      answers: [
        {
          canonical: "New Jerusalem",
          aliases: ["jerusalem"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 21, verseStart: 2, display: "Revelation 21:2" }],
          explanation: "John sees the holy city, New Jerusalem, coming down out of heaven.",
        },
        {
          canonical: "Babylon",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 18, verseStart: 2, display: "Revelation 18:2" }],
          explanation: "\"Babylon the Great\" is announced as fallen in a vision of judgment.",
        },
        {
          canonical: "Patmos",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 1, verseStart: 9, display: "Revelation 1:9" }],
          explanation: "John receives his vision while on the island of Patmos.",
        },
        {
          canonical: "Ephesus",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 1, display: "Revelation 2:1" }],
          explanation: "Ephesus is the first of the seven churches addressed in Revelation.",
        },
        {
          canonical: "Armageddon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 16, verseStart: 16, display: "Revelation 16:16" }],
          explanation: "The kings of the earth are gathered to the place called Armageddon.",
        },
        {
          canonical: "Mount Zion",
          aliases: ["zion"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 14, verseStart: 1, display: "Revelation 14:1" }],
          explanation: "The Lamb stands on Mount Zion with the 144,000 who bear his name.",
        },
        {
          canonical: "Sea of Glass",
          aliases: ["glass sea"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 6, display: "Revelation 4:6" }],
          explanation: "Something like a sea of glass, clear as crystal, stands before God's throne.",
        },
        {
          canonical: "Euphrates River",
          aliases: ["euphrates"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 16, verseStart: 12, display: "Revelation 16:12" }],
          explanation: "The great river Euphrates is dried up to prepare the way for kings from the east.",
        },
        {
          canonical: "Laodicea",
          aliases: ["Lukewarm Church"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 3, verseStart: 14, verseEnd: 14, display: "Revelation 3:14" }],
          explanation: "John rebukes the church in Laodicea for being lukewarm, neither hot nor cold.",
        },
        {
          canonical: "Smyrna",
          aliases: ["Church of Smyrna"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 8, verseEnd: 8, display: "Revelation 2:8" }],
          explanation: "John addresses one of his seven letters to the church in Smyrna.",
        },
        {
          canonical: "Pergamum",
          aliases: ["Pergamos"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 12, verseEnd: 12, display: "Revelation 2:12" }],
          explanation: "John writes to the church in Pergamum, the city where Satan's throne is said to be.",
        },
        {
          canonical: "Philadelphia",
          aliases: ["Church of Philadelphia"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 3, verseStart: 7, verseEnd: 7, display: "Revelation 3:7" }],
          explanation: "John's letter commends the church in Philadelphia for keeping his word despite having little strength.",
        },
        {
          canonical: "Thyatira",
          aliases: ["Church of Thyatira"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 18, verseEnd: 18, display: "Revelation 2:18" }],
          explanation: "John's letter warns the church in Thyatira against tolerating the prophetess Jezebel.",
        },
        {
          canonical: "Sardis",
          aliases: ["Church of Sardis"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 3, verseStart: 1, verseEnd: 1, display: "Revelation 3:1" }],
          explanation: "John writes to the church in Sardis, telling it to wake up because its deeds are incomplete.",
        },
        {
          canonical: "The Abyss",
          aliases: ["Abyss","Bottomless Pit"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 9, verseStart: 1, verseEnd: 2, display: "Revelation 9:1-2" }],
          explanation: "A star given the key to the Abyss opens it, releasing smoke and locusts upon the earth.",
        },
        {
          canonical: "The Lake of Fire",
          aliases: ["lake of fire"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 20, verseStart: 14, verseEnd: 15, display: "Revelation 20:14-15" }],
          explanation: "Death, Hades, and anyone not found in the book of life are thrown into the lake of fire.",
        },
        {
          canonical: "The Tree of Life",
          aliases: ["tree of life"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 22, verseStart: 1, verseEnd: 2, display: "Revelation 22:1-2" }],
          explanation: "The tree of life stands on either side of the river flowing from the throne, bearing twelve kinds of fruit for the healing of the nations.",
        },
        {
          canonical: "The River of the Water of Life",
          aliases: ["river of life","the river of life"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 22, verseStart: 1, display: "Revelation 22:1" }],
          explanation: "John sees a river of the water of life, bright as crystal, flowing from the throne of God and of the Lamb.",
        },
        {
          canonical: "The Throne of God",
          aliases: ["the throne","throne of god","throne"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 2, display: "Revelation 4:2" }],
          explanation: "John is taken up in the Spirit and sees a throne in heaven with one seated on it.",
        },
        {
          canonical: "The Temple",
          aliases: ["temple","temple of god"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 11, verseStart: 19, display: "Revelation 11:19" }],
          explanation: "The temple of God in heaven opens, revealing the ark of his covenant within it.",
        },
        {
          canonical: "Hades",
          aliases: ["hell"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 20, verseStart: 13, verseEnd: 14, display: "Revelation 20:13-14" }],
          explanation: "Death and Hades give up their dead for judgment, and then Death and Hades themselves are thrown into the lake of fire.",
        },
      ],
    },
  ],
};
