import type { SeedDay } from "./types";

export const DAY_02: SeedDay = {
  dayNumber: 2,
  date: "2026-09-19",
  scriptureBonus: {
    displayText:
      "For God so loved the world, that he gave his only born Son, that whoever believes in him should not perish, but have eternal life.",
    book: "John",
    chapter: 3,
    verseStart: 16,
    referenceDisplay: "John 3:16",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote:
      "One of the most quoted verses in the New Testament, summarizing God's love and the offer of eternal life through Jesus.",
    acceptedBookAliases: ["gospel of john"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person who received a dream or vision from God.",
      instructions: "You get one guess.",
      whatCounts:
        "Any named person the biblical text explicitly describes receiving a dream or vision from God (or an angel within a dream).",
      answers: [
        {
          canonical: "Joseph",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 37, verseStart: 5, verseEnd: 11, display: "Genesis 37:5-11" }],
          explanation: "Joseph dreams that his brothers' sheaves, then the sun, moon, and stars, bow down to him.",
        },
        {
          canonical: "Jacob",
          aliases: ["israel"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 28, verseStart: 12, verseEnd: 13, display: "Genesis 28:12-13" }],
          explanation:
            "Jacob dreams of a ladder reaching to heaven with angels ascending and descending, and God speaks to him from above it.",
        },
        {
          canonical: "Daniel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 7, verseStart: 1, display: "Daniel 7:1" }],
          explanation: "Daniel has his own vision of four great beasts rising from the sea.",
        },
        {
          canonical: "Pharaoh",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 25, verseEnd: 28, display: "Genesis 41:25-28" }],
          explanation:
            "Pharaoh dreams of seven fat and seven lean cows; Joseph tells him \"God has shown Pharaoh what he is about to do.\"",
        },
        {
          canonical: "Peter",
          aliases: ["simon peter"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 9, verseEnd: 16, display: "Acts 10:9-16" }],
          explanation:
            "Peter sees a vision of a sheet full of animals lowered from heaven, teaching him not to call anyone unclean.",
        },
        {
          canonical: "Paul",
          aliases: ["saul"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 9, display: "Acts 16:9" }],
          explanation: "Paul sees a vision of a man of Macedonia pleading, \"Come over and help us.\"",
        },
        {
          canonical: "Nebuchadnezzar",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 2, verseStart: 1, display: "Daniel 2:1" }],
          explanation:
            "Nebuchadnezzar's troubling dream of a great statue is revealed and interpreted by Daniel.",
        },
        {
          canonical: "Abimelech",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 20, verseStart: 3, verseEnd: 7, display: "Genesis 20:3-7" }],
          explanation:
            "God comes to King Abimelech in a dream, warning him that Sarah is Abraham's wife.",
        },
        {
          canonical: "Pilate's Wife",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 19, display: "Matthew 27:19" }],
          explanation:
            "Pilate's wife sends word that she has suffered much in a dream because of Jesus, urging Pilate to have nothing to do with him.",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 3, verseStart: 5, display: "1 Kings 3:5" }],
          explanation: "The LORD appears to Solomon in a dream at Gibeon and offers to grant him whatever he asks.",
        },
        {
          canonical: "John",
          aliases: ["john the apostle","john of patmos"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 1, verseStart: 10, verseEnd: 19, display: "Revelation 1:10-19" }],
          explanation: "John, in the Spirit on Patmos, receives a vision of the risen Christ that opens the book of Revelation.",
        },
        {
          canonical: "Isaiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Isaiah", chapterStart: 6, verseStart: 1, verseEnd: 8, display: "Isaiah 6:1-8" }],
          explanation: "Isaiah sees a vision of the LORD enthroned in the temple and is commissioned as a prophet.",
        },
        {
          canonical: "Cornelius",
          aliases: ["the centurion cornelius"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 3, verseEnd: 6, display: "Acts 10:3-6" }],
          explanation: "An angel of God appears to Cornelius in a vision, instructing him to send for Peter.",
        },
        {
          canonical: "Abraham",
          aliases: ["abram"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 15, verseStart: 1, verseEnd: 12, display: "Genesis 15:1-12" }],
          explanation: "The word of the LORD comes to Abram in a vision, and a deep sleep and vision later confirm the covenant.",
        },
        {
          canonical: "Zechariah",
          aliases: ["father of john the baptist"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 11, verseEnd: 20, display: "Luke 1:11-20" }],
          explanation: "An angel of the Lord appears to Zechariah in the temple, announcing the birth of John the Baptist.",
        },
        {
          canonical: "Ananias",
          aliases: ["ananias of damascus"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 10, verseEnd: 16, display: "Acts 9:10-16" }],
          explanation: "The Lord speaks to Ananias in a vision, sending him to restore Paul's sight in Damascus.",
        },
        {
          canonical: "Joseph (Husband of Mary)",
          aliases: ["joseph husband of mary","mary's husband","st joseph","joseph the carpenter"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 20, verseEnd: 20, display: "Matthew 1:20" }],
          explanation: "An angel of the Lord appears to Joseph in a dream, telling him to take Mary as his wife.",
        },
        {
          canonical: "Ezekiel",
          aliases: ["ezekiel's vision","wheels","valley of dry bones"],
          score: 60,
          tier: "veil",
          references: [{ book: "Ezekiel", chapterStart: 1, verseStart: 1, verseEnd: 28, display: "Ezekiel 1:1-28" }],
          explanation: "Ezekiel sees a vision of God's glory with four living creatures and wheels beside the Kebar River.",
        },
        {
          canonical: "Amos",
          aliases: ["amos's visions","locust vision","plumb line"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Amos", chapterStart: 7, verseStart: 1, verseEnd: 9, display: "Amos 7:1-9" }],
          explanation: "Amos receives a series of visions from God, including locusts, fire, and a plumb line.",
        },
        {
          canonical: "Micaiah",
          aliases: ["micaiah son of imlah","heavenly throne room vision"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 17, verseEnd: 23, display: "1 Kings 22:17-23" }],
          explanation: "Micaiah son of Imlah describes a vision of the Lord on his throne surrounded by the host of heaven.",
        },
        {
          canonical: "Balaam",
          aliases: ["balaam's oracle","vision of the almighty"],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 24, verseStart: 4, verseEnd: 4, display: "Numbers 24:4" }],
          explanation: "Balaam's oracle is explicitly framed as coming from one who sees the vision of the Almighty.",
        },
        {
          canonical: "Eliphaz",
          aliases: ["eliphaz the temanite","spirit in the night"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Job", chapterStart: 4, verseStart: 12, verseEnd: 16, display: "Job 4:12-16" }],
          explanation: "Eliphaz the Temanite describes a spirit gliding past his face in a vision during the night.",
        },
        {
          canonical: "Moses",
          aliases: ["burning bush"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 3, verseStart: 2, verseEnd: 4, display: "Exodus 3:2-4" }],
          explanation: "God appears to Moses in a flame of fire from within a bush — a sight Stephen's speech in Acts 7:30-31 explicitly calls a vision.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a mountain mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any mountain explicitly named in the biblical text.",
      answers: [
        {
          canonical: "Mount Sinai",
          aliases: ["sinai", "mount horeb", "horeb"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 1, verseEnd: 2, display: "Exodus 19:1-2" }],
          explanation: "Moses receives the Ten Commandments on Mount Sinai.",
        },
        {
          canonical: "Mount Ararat",
          aliases: ["ararat"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 8, verseStart: 4, display: "Genesis 8:4" }],
          explanation: "Noah's ark comes to rest on the mountains of Ararat.",
        },
        {
          canonical: "Mount Zion",
          aliases: ["zion", "mount sion"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 7, display: "2 Samuel 5:7" }],
          explanation:
            "David captures the stronghold of Zion, and the name becomes closely associated with Jerusalem and God's presence throughout the Psalms and prophets.",
        },
        {
          canonical: "Mount of Olives",
          aliases: ["olivet"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 1, verseStart: 9, verseEnd: 12, display: "Acts 1:9-12" }],
          explanation: "Jesus ascends to heaven from the Mount of Olives.",
        },
        {
          canonical: "Mount Moriah",
          aliases: ["moriah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 22, verseStart: 2, display: "Genesis 22:2" }],
          explanation: "God tells Abraham to offer Isaac on a mountain in the region of Moriah.",
        },
        {
          canonical: "Mount Carmel",
          aliases: ["carmel"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 19, verseEnd: 40, display: "1 Kings 18:19-40" }],
          explanation: "Elijah confronts the prophets of Baal on Mount Carmel.",
        },
        {
          canonical: "Mount Gilboa",
          aliases: ["gilboa"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Samuel", chapterStart: 31, verseStart: 1, display: "1 Samuel 31:1" }],
          explanation: "Saul and his sons die in battle against the Philistines on Mount Gilboa.",
        },
        {
          canonical: "Mount Nebo",
          aliases: ["nebo"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Deuteronomy", chapterStart: 34, verseStart: 1, display: "Deuteronomy 34:1" }],
          explanation: "Moses views the promised land from Mount Nebo before he dies.",
        },
        {
          canonical: "Mount Gerizim",
          aliases: ["gerizim"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Joshua", chapterStart: 8, verseStart: 33, display: "Joshua 8:33" }],
          explanation:
            "Mount Gerizim is designated for pronouncing blessings over Israel when they enter the promised land.",
        },
        {
          canonical: "Mount Hermon",
          aliases: ["hermon","sirion"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Deuteronomy", chapterStart: 3, verseStart: 8, display: "Deuteronomy 3:8" }],
          explanation: "Named as the northern boundary of the land Israel took from the Amorite kings.",
        },
        {
          canonical: "Mount Ebal",
          aliases: ["ebal"],
          score: 60,
          tier: "veil",
          references: [{ book: "Deuteronomy", chapterStart: 27, verseStart: 4, display: "Deuteronomy 27:4" }],
          explanation: "Israel is commanded to set up stones and build an altar on Mount Ebal after crossing into the land.",
        },
        {
          canonical: "Mount Tabor",
          aliases: ["tabor"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 4, verseStart: 6, display: "Judges 4:6" }],
          explanation: "Deborah summons Barak and the tribes to muster at Mount Tabor before the battle against Sisera.",
        },
        {
          canonical: "Mount Hor",
          aliases: ["hor"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 20, verseStart: 22, verseEnd: 29, display: "Numbers 20:22-29" }],
          explanation: "Aaron dies on Mount Hor after Moses strips him of his priestly garments for Eleazar.",
        },
        {
          canonical: "Mount Seir",
          aliases: ["seir","mount seir"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 36, verseStart: 8, verseEnd: 9, display: "Genesis 36:8-9" }],
          explanation: "Mount Seir is the hill country settled by Esau and his descendants, the Edomites.",
        },
        {
          canonical: "Mount Abarim",
          aliases: ["abarim","mount abarim"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 27, verseStart: 12, verseEnd: 12, display: "Numbers 27:12" }],
          explanation: "Mount Abarim is the range from which God tells Moses to view the promised land before his death.",
        },
        {
          canonical: "Mount Pisgah",
          aliases: ["pisgah","mount pisgah","the pisgah"],
          score: 60,
          tier: "veil",
          references: [{ book: "Deuteronomy", chapterStart: 34, verseStart: 1, verseEnd: 1, display: "Deuteronomy 34:1" }],
          explanation: "Pisgah is the specific ridge of the Abarim range, part of Nebo, from which Moses views Canaan.",
        },
        {
          canonical: "Mount Gilead",
          aliases: ["gilead","mount gilead"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 31, verseStart: 21, verseEnd: 25, display: "Genesis 31:21-25" }],
          explanation: "Mount Gilead is where Laban overtakes the fleeing Jacob and the two make a covenant.",
        },
        {
          canonical: "Mount Gaash",
          aliases: ["gaash","mount gaash"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Joshua", chapterStart: 24, verseStart: 30, verseEnd: 30, display: "Joshua 24:30" }],
          explanation: "Mount Gaash is named as the site north of which Joshua is buried.",
        },
        {
          canonical: "Mount Ephraim",
          aliases: ["ephraim","hill country of ephraim","mount ephraim"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 17, verseStart: 15, verseEnd: 15, display: "Joshua 17:15" }],
          explanation: "Mount Ephraim is the hill country repeatedly named as the territory of the tribe of Ephraim and the setting for several judges.",
        },
        {
          canonical: "Mount Paran",
          aliases: ["paran","mount paran"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Deuteronomy", chapterStart: 33, verseStart: 2, verseEnd: 2, display: "Deuteronomy 33:2" }],
          explanation: "Mount Paran is named in poetic descriptions of God coming in glory from Sinai.",
        },
        {
          canonical: "Mount Bashan",
          aliases: ["bashan","mount bashan"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Psalm", chapterStart: 68, verseStart: 15, verseEnd: 15, display: "Psalm 68:15" }],
          explanation: "Mount Bashan is called a majestic mountain of many peaks in the Psalms.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a miracle performed by Moses.",
      instructions: "You get one guess.",
      whatCounts:
        "Any miracle the biblical text explicitly attributes to Moses, other than the ten plagues on Egypt.",
      answers: [
        {
          canonical: "Parting the Red Sea",
          aliases: [
            "red sea",
            "parting the sea",
            "splitting the red sea",
            "dividing the red sea",
            "parting the water",
            "crossing the red sea",
            "walking through the red sea on dry ground",
          ],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 14, verseStart: 21, verseEnd: 22, display: "Exodus 14:21-22" }],
          explanation:
            "Moses stretches out his hand and the LORD divides the Red Sea so Israel crosses on dry ground.",
        },
        {
          canonical: "Staff into a Serpent",
          aliases: [
            "staff",
            "staff to snake",
            "staff turning into a snake",
            "rod into a snake",
            "turning his staff into a snake",
            "staff became a snake",
            "his staff turned into a serpent",
          ],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 4, verseStart: 2, verseEnd: 4, display: "Exodus 4:2-4" }],
          explanation: "Moses' staff turns into a serpent and back again as a sign for Pharaoh and Israel.",
        },
        {
          canonical: "Victory Over Amalek",
          aliases: [
            "amalek",
            "battle with amalek",
            "raising his hands",
            "holding up his hands",
            "raised staff over the battle",
            "rod above his head",
            "raising his arms with his staff",
            "raising his arms above his head with his staff",
            "moses raising his arms above his head with his staff",
            "holding his staff above his head",
            "arms raised with the staff",
            "raising his staff during the battle",
            "keeping his arms up during the battle",
            "aaron and hur holding up his arms",
            "holding up his hands with the staff of god",
          ],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 17, verseStart: 8, verseEnd: 13, display: "Exodus 17:8-13" }],
          explanation:
            "As long as Moses holds up his hands (with Aaron and Hur supporting them), Israel prevails over Amalek in battle.",
        },
        {
          canonical: "Sweetening the Waters of Marah",
          aliases: [
            "marah",
            "sweetening the water",
            "bitter water sweetened",
            "throwing wood into the water",
            "wood into bitter water",
            "turning bitter water sweet",
            "purifying the water at marah",
          ],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 22, verseEnd: 25, display: "Exodus 15:22-25" }],
          explanation:
            "Moses throws a piece of wood into the bitter water at Marah, and it becomes sweet to drink.",
        },
        {
          canonical: "Water from the Rock",
          aliases: [
            "water from rock",
            "striking the rock",
            "hitting the rock with his staff",
            "water from a rock",
            "striking the rock with his staff",
            "moses strikes the rock",
          ],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 17, verseStart: 6, display: "Exodus 17:6" }],
          explanation: "Moses strikes the rock at Horeb and water flows out for the thirsty people.",
        },
        {
          canonical: "Hand Turning Leprous",
          aliases: [
            "leprous hand",
            "hand became leprous",
            "putting his hand in his cloak",
            "hand turned white as snow",
            "moses hand turning white",
            "hand turning leprous then clean",
          ],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 4, verseStart: 6, verseEnd: 7, display: "Exodus 4:6-7" }],
          explanation:
            "Moses' hand becomes leprous and then clean again as a sign to convince Israel of his calling.",
        },
        {
          canonical: "Bronze Serpent",
          aliases: [
            "the bronze snake",
            "bronze snake",
            "nehushtan",
            "snake on a pole",
            "serpent on a pole",
            "bronze snake on a staff",
            "brass serpent",
            "looking at the bronze snake to be healed",
          ],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 21, verseStart: 8, verseEnd: 9, display: "Numbers 21:8-9" }],
          explanation:
            "Moses makes a bronze serpent on a pole so that anyone bitten by a snake who looks at it lives.",
        },
        {
          canonical: "The Earth Swallowing Korah",
          aliases: [
            "korah",
            "swallowing korah",
            "korahs rebellion",
            "ground swallowed korah",
            "earth opened and swallowed them",
            "the ground opened up and swallowed korah",
            "korah dathan and abiram",
            "earth swallowing the rebels",
          ],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Numbers", chapterStart: 16, verseStart: 31, verseEnd: 33, display: "Numbers 16:31-33" }],
          explanation:
            "At Moses' word, the ground opens and swallows Korah, Dathan, Abiram, and their households after they rebel.",
        },
        {
          canonical: "Miriam's Healing",
          aliases: ["miriam","miriam's leprosy","healing miriam","moses prays for miriam"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 12, verseStart: 10, verseEnd: 15, display: "Numbers 12:10-15" }],
          explanation: "Moses intercedes in prayer, crying out for God to heal Miriam after she is struck with leprosy.",
        },
        {
          canonical: "Water from the Rock at Kadesh",
          aliases: ["kadesh","meribah kadesh","striking the rock twice","barred from the promised land"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 20, verseStart: 1, verseEnd: 13, display: "Numbers 20:1-13" }],
          explanation: "At Kadesh, decades after Horeb, Moses strikes the rock twice instead of speaking to it and still brings forth water, though the act costs him entry into the promised land.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a book traditionally attributed to Paul.",
      instructions: "You get one guess.",
      whatCounts:
        "Any of the thirteen epistles traditionally attributed to Paul, not including Hebrews (whose Pauline authorship is disputed).",
      answers: [
        {
          canonical: "Romans",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Romans", chapterStart: 1, verseStart: 1, display: "Romans 1:1" }],
          explanation: "Romans opens by identifying Paul as its author and apostle.",
        },
        {
          canonical: "1 Corinthians",
          aliases: ["first corinthians"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 1, verseStart: 1, display: "1 Corinthians 1:1" }],
          explanation: "1 Corinthians opens identifying Paul, called to be an apostle.",
        },
        {
          canonical: "2 Corinthians",
          aliases: ["second corinthians"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Corinthians", chapterStart: 1, verseStart: 1, display: "2 Corinthians 1:1" }],
          explanation: "2 Corinthians opens identifying Paul as an apostle of Christ Jesus by God's will.",
        },
        {
          canonical: "Galatians",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Galatians", chapterStart: 1, verseStart: 1, display: "Galatians 1:1" }],
          explanation: "Galatians opens identifying Paul as an apostle.",
        },
        {
          canonical: "Ephesians",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ephesians", chapterStart: 1, verseStart: 1, display: "Ephesians 1:1" }],
          explanation: "Ephesians opens identifying Paul as an apostle by the will of God.",
        },
        {
          canonical: "Philippians",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Philippians", chapterStart: 1, verseStart: 1, display: "Philippians 1:1" }],
          explanation: "Philippians opens with Paul and Timothy as servants of Jesus Christ.",
        },
        {
          canonical: "Colossians",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Colossians", chapterStart: 1, verseStart: 1, display: "Colossians 1:1" }],
          explanation: "Colossians opens identifying Paul as an apostle of Christ Jesus by God's will.",
        },
        {
          canonical: "1 Thessalonians",
          aliases: ["first thessalonians"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Thessalonians", chapterStart: 1, verseStart: 1, display: "1 Thessalonians 1:1" }],
          explanation: "1 Thessalonians opens naming Paul, Silvanus, and Timothy.",
        },
        {
          canonical: "2 Thessalonians",
          aliases: ["second thessalonians"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Thessalonians", chapterStart: 1, verseStart: 1, display: "2 Thessalonians 1:1" }],
          explanation: "2 Thessalonians opens naming Paul, Silvanus, and Timothy.",
        },
        {
          canonical: "1 Timothy",
          aliases: ["first timothy"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Timothy", chapterStart: 1, verseStart: 1, display: "1 Timothy 1:1" }],
          explanation: "1 Timothy opens identifying Paul as an apostle by the command of God.",
        },
        {
          canonical: "2 Timothy",
          aliases: ["second timothy"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Timothy", chapterStart: 1, verseStart: 1, display: "2 Timothy 1:1" }],
          explanation: "2 Timothy opens identifying Paul as an apostle of Jesus Christ.",
        },
        {
          canonical: "Titus",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Titus", chapterStart: 1, verseStart: 1, display: "Titus 1:1" }],
          explanation: "Titus opens identifying Paul as a servant of God and apostle of Jesus Christ.",
        },
        {
          canonical: "Philemon",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Philemon", chapterStart: 1, verseStart: 1, display: "Philemon 1:1" }],
          explanation:
            "Philemon, a short personal letter about the runaway slave Onesimus, opens naming Paul as a prisoner of Christ Jesus.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name an animal/creature mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any animal or creature explicitly named in the biblical text.",
      answers: [
        {
          canonical: "Locusts",
          aliases: ["locust", "swarm of locusts"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 10, verseStart: 12, verseEnd: 15, display: "Exodus 10:12-15" }],
          explanation: "Locusts sweep over Egypt in the eighth plague, devouring everything left after the hail.",
        },
        {
          canonical: "Donkey",
          aliases: ["ass"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Numbers", chapterStart: 22, verseStart: 28, display: "Numbers 22:28" }],
          explanation: "The LORD opens the mouth of Balaam's donkey, and it speaks to him.",
        },
        {
          canonical: "Dove",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 8, verseStart: 11, display: "Genesis 8:11" }],
          explanation: "Noah sends out a dove that returns with a freshly plucked olive leaf.",
        },
        {
          canonical: "Lamb",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 12, verseStart: 3, verseEnd: 6, display: "Exodus 12:3-6" }],
          explanation: "A lamb without blemish is prescribed for the first Passover, and lambs recur throughout the sacrificial law.",
        },
        {
          canonical: "Hyrax",
          aliases: ["coney", "rock hyrax", "rock badger"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 5, display: "Leviticus 11:5" }],
          explanation:
            "The hyrax (rendered \"coney\" in older translations) is listed among the animals Israel may not eat because it chews the cud but does not have a split hoof.",
        },
        {
          canonical: "Lion",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 6, verseStart: 16, verseEnd: 22, display: "Daniel 6:16-22" }],
          explanation: "Daniel is cast into a den of lions and is kept unharmed.",
        },
        {
          canonical: "Ram",
          aliases: ["ram caught in the thicket", "abraham's ram"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 22, verseStart: 13, display: "Genesis 22:13" }],
          explanation: "Abraham sacrifices a ram caught by its horns in a thicket in place of Isaac.",
        },
        {
          canonical: "Bull",
          aliases: ["ox", "oxen", "bullock"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Leviticus", chapterStart: 4, verseStart: 3, display: "Leviticus 4:3" }],
          explanation: "A young bull is repeatedly prescribed as a sin offering throughout the Levitical sacrificial law.",
        },
        {
          canonical: "Raven",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 4, verseEnd: 6, display: "1 Kings 17:4-6" }],
          explanation: "Ravens bring Elijah bread and meat by the brook Cherith.",
        },
        {
          canonical: "Great Fish",
          aliases: ["the great fish", "big fish"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jonah", chapterStart: 1, verseStart: 17, display: "Jonah 1:17" }],
          explanation: "A great fish swallows Jonah, who remains inside it for three days and three nights.",
        },
        {
          canonical: "Serpent",
          aliases: ["snake"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 1, display: "Genesis 3:1" }],
          explanation: "The serpent tempts Eve in the garden of Eden.",
        },
        {
          canonical: "Behemoth",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Job", chapterStart: 40, verseStart: 15, display: "Job 40:15" }],
          explanation: "God describes the great creature Behemoth to Job as a display of his power.",
        },
        {
          canonical: "Leviathan",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Job", chapterStart: 41, verseStart: 1, display: "Job 41:1" }],
          explanation:
            "God describes the fearsome sea creature Leviathan, underscoring his supremacy over all creation.",
        },
        {
          canonical: "Tobias's Dog",
          aliases: ["tobit's dog"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Tobit", chapterStart: 11, display: "Tobit 11" }],
          explanation:
            "A dog accompanies Tobias and the angel Raphael on their journey and runs ahead of them on the way home.",
          catholicOnly: true,
        },
        {
          canonical: "The Dragon",
          aliases: ["dragon", "bel's dragon"],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 14, display: "Daniel 14 (Bel and the Dragon)" }],
          explanation:
            "In the \"Bel and the Dragon\" addition to Daniel, Daniel proves a great dragon worshipped by the Babylonians is not a god by feeding it cakes that cause it to burst.",
          catholicOnly: true,
        },
        {
          canonical: "Eagle",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 4, display: "Exodus 19:4" }],
          explanation: "The LORD tells Israel he bore them on eagles' wings out of Egypt.",
        },
        {
          canonical: "Horse",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 6, verseStart: 2, display: "Revelation 6:2" }],
          explanation: "The first of four apocalyptic horses appears, a white horse whose rider carries a bow.",
        },
        {
          canonical: "Goat",
          aliases: ["scapegoat"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 16, verseStart: 9, verseEnd: 10, display: "Leviticus 16:9-10" }],
          explanation: "On the Day of Atonement one goat is sacrificed and a second, the scapegoat, is sent into the wilderness.",
        },
        {
          canonical: "Camel",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 4, display: "Matthew 3:4" }],
          explanation: "John the Baptist wears a garment of camel's hair with a leather belt around his waist.",
        },
        {
          canonical: "Bear",
          aliases: ["she-bears"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 2, verseStart: 24, display: "2 Kings 2:24" }],
          explanation: "Two bears come out of the woods and maul forty-two youths who mocked Elisha.",
        },
        {
          canonical: "Ant",
          aliases: ["ants"],
          score: 60,
          tier: "veil",
          references: [{ book: "Proverbs", chapterStart: 6, verseStart: 6, display: "Proverbs 6:6" }],
          explanation: "Solomon points the sluggard to the ant, which stores up food without a commander.",
        },
        {
          canonical: "Sheep",
          aliases: ["ewe","flock"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Psalm", chapterStart: 23, verseStart: 1, verseEnd: 1, display: "Psalm 23:1" }],
          explanation: "Sheep appear throughout scripture, from David's Psalm 23 shepherd imagery to Jesus as the good shepherd of John 10.",
        },
        {
          canonical: "Dog",
          aliases: ["dogs","am i a dog"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 16, verseStart: 21, verseEnd: 21, display: "Luke 16:21" }],
          explanation: "Dogs lick the sores of the beggar Lazarus outside the rich man's gate.",
        },
        {
          canonical: "Fox",
          aliases: ["foxes","samson's foxes","little foxes"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 15, verseStart: 4, verseEnd: 4, display: "Judges 15:4" }],
          explanation: "Samson catches three hundred foxes and uses them to burn the Philistines' fields.",
        },
        {
          canonical: "Wolf",
          aliases: ["wolves","wolf in sheep's clothing"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 7, verseStart: 15, verseEnd: 15, display: "Matthew 7:15" }],
          explanation: "Jesus warns of false prophets who come as wolves in sheep's clothing.",
        },
        {
          canonical: "Deer",
          aliases: ["hind","stag","as the deer pants"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Psalm", chapterStart: 42, verseStart: 1, verseEnd: 1, display: "Psalm 42:1" }],
          explanation: "The psalmist compares his soul's longing for God to a deer panting for water.",
        },
        {
          canonical: "Ostrich",
          aliases: ["ostriches"],
          score: 60,
          tier: "veil",
          references: [{ book: "Job", chapterStart: 39, verseStart: 13, verseEnd: 18, display: "Job 39:13-18" }],
          explanation: "God describes the ostrich's strange, forgetful nature as part of his speech to Job.",
        },
        {
          canonical: "Bee",
          aliases: ["bees","swarm of bees"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 14, verseStart: 8, verseEnd: 8, display: "Judges 14:8" }],
          explanation: "Samson finds a swarm of bees and honey in the carcass of the lion he killed.",
        },
        {
          canonical: "Scorpion",
          aliases: ["scorpions"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 12, verseStart: 11, verseEnd: 11, display: "1 Kings 12:11" }],
          explanation: "Rehoboam threatens to chastise Israel with scorpions in place of his father's whips.",
        },
        {
          canonical: "Frog",
          aliases: ["frogs","plague of frogs"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 8, verseStart: 2, verseEnd: 14, display: "Exodus 8:2-14" }],
          explanation: "Frogs overrun Egypt as the second of the ten plagues sent against Pharaoh.",
        },
      ],
    },
  ],
};
