import type { SeedDay } from "./types";

export const DAY_04: SeedDay = {
  dayNumber: 4,
  date: "2026-09-21",
  scriptureBonus: {
    displayText:
      "Haven't I commanded you? Be strong and courageous. Don't be afraid. Don't be dismayed, for Yahweh your God is with you wherever you go.",
    book: "Joshua",
    chapter: 1,
    verseStart: 9,
    referenceDisplay: "Joshua 1:9",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote:
      "God commissions Joshua to lead Israel into the promised land, assuring him of his presence.",
    acceptedBookAliases: [],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name an apostle of Jesus.",
      instructions: "You get one guess.",
      whatCounts:
        "Any of the twelve apostles named in the Gospels' lists of the twelve (e.g. Matthew 10:2-4), plus Matthias, chosen by lot in Acts 1 to replace Judas Iscariot.",
      answers: [
        {
          canonical: "Peter",
          aliases: ["simon peter"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Peter is named first among the twelve apostles Jesus sends out.",
        },
        {
          canonical: "John",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "John, son of Zebedee, is one of the twelve apostles.",
        },
        {
          canonical: "Andrew",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Andrew, Peter's brother, is one of the twelve apostles.",
        },
        {
          canonical: "James",
          aliases: ["james son of zebedee"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "James, son of Zebedee and brother of John, is one of the twelve apostles.",
        },
        {
          canonical: "Matthew",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Matthew, identified elsewhere as a tax collector, is named among the twelve.",
        },
        {
          canonical: "Philip",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Philip is named among the twelve apostles and later brings Nathanael to Jesus.",
        },
        {
          canonical: "Bartholomew",
          aliases: ["nathanael"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Bartholomew, often identified with Nathanael in John's Gospel, is one of the twelve.",
        },
        {
          canonical: "Thomas",
          aliases: ["doubting thomas"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Thomas, later famous for doubting the resurrection, is named among the twelve.",
        },
        {
          canonical: "James Son of Alphaeus",
          aliases: ["james the less"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "James son of Alphaeus is one of the two apostles named James in the twelve.",
        },
        {
          canonical: "Judas Iscariot",
          aliases: ["judas"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Judas Iscariot, who later betrays Jesus, is listed among the twelve apostles.",
        },
        {
          canonical: "Thaddaeus",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Thaddaeus is named among the twelve apostles in Matthew's list.",
        },
        {
          canonical: "Matthias",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 1, verseStart: 23, verseEnd: 26, display: "Acts 1:23-26" }],
          explanation: "Matthias is chosen by lot to take Judas Iscariot's place among the twelve.",
        },
        {
          canonical: "Simon the Zealot",
          aliases: ["zealot"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 2, verseEnd: 4, display: "Matthew 10:2-4" }],
          explanation: "Simon the Zealot is the least-remembered name in Matthew's list of the twelve.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person Jesus raised from the dead.",
      instructions: "You get one guess.",
      whatCounts: "Any person (or group) the Gospels explicitly describe Jesus raising from the dead.",
      answers: [
        {
          canonical: "Lazarus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 11, verseStart: 38, verseEnd: 44, display: "John 11:38-44" }],
          explanation: "Jesus calls Lazarus out of the tomb four days after his death.",
        },
        {
          canonical: "Jairus's Daughter",
          aliases: ["daughter of jairus"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 21, verseEnd: 43, display: "Mark 5:21-43" }],
          explanation: "Jesus raises the daughter of the synagogue leader Jairus.",
        },
        {
          canonical: "The Widow of Nain's Son",
          aliases: ["nain"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 7, verseStart: 11, verseEnd: 17, display: "Luke 7:11-17" }],
          explanation: "Jesus stops a funeral procession and raises the only son of a widow in Nain.",
        },
        {
          canonical: "Saints Raised at the Crucifixion",
          aliases: ["saints raised", "the saints"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 52, verseEnd: 53, display: "Matthew 27:52-53" }],
          explanation:
            "At Jesus' death, tombs open and many bodies of the saints who had died are raised.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a book of the Minor Prophets.",
      instructions: "You get one guess.",
      whatCounts: "Any of the twelve Minor Prophets books.",
      answers: [
        {
          canonical: "Jonah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Jonah", chapterStart: 1, verseStart: 1, display: "Jonah 1:1" }],
          explanation: "Jonah is sent to preach to Nineveh and is famously swallowed by a great fish.",
        },
        {
          canonical: "Hosea",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Hosea", chapterStart: 1, verseStart: 1, display: "Hosea 1:1" }],
          explanation: "Hosea is the first of the twelve Minor Prophets books.",
        },
        {
          canonical: "Amos",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Amos", chapterStart: 1, verseStart: 1, display: "Amos 1:1" }],
          explanation: "Amos, a shepherd from Tekoa, prophesies against Israel's injustice.",
        },
        {
          canonical: "Micah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Micah", chapterStart: 1, verseStart: 1, display: "Micah 1:1" }],
          explanation: "Micah prophesies concerning Samaria and Jerusalem.",
        },
        {
          canonical: "Joel",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joel", chapterStart: 1, verseStart: 1, display: "Joel 1:1" }],
          explanation: "Joel prophesies about a locust plague and the coming Day of the LORD.",
        },
        {
          canonical: "Habakkuk",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Habakkuk", chapterStart: 1, verseStart: 1, display: "Habakkuk 1:1" }],
          explanation: "Habakkuk wrestles with why God allows injustice to go unpunished.",
        },
        {
          canonical: "Nahum",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Nahum", chapterStart: 1, verseStart: 1, display: "Nahum 1:1" }],
          explanation: "Nahum pronounces judgment on the city of Nineveh.",
        },
        {
          canonical: "Zephaniah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Zephaniah", chapterStart: 1, verseStart: 1, display: "Zephaniah 1:1" }],
          explanation: "Zephaniah prophesies during the reign of King Josiah of Judah.",
        },
        {
          canonical: "Haggai",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Haggai", chapterStart: 1, verseStart: 1, display: "Haggai 1:1" }],
          explanation: "Haggai urges the returned exiles to rebuild the temple.",
        },
        {
          canonical: "Zechariah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Zechariah", chapterStart: 1, verseStart: 1, display: "Zechariah 1:1" }],
          explanation: "Zechariah prophesies alongside Haggai, encouraging the temple's rebuilding.",
          inclusionNotes: "Distinct from the priest Zechariah, father of John the Baptist, named elsewhere.",
        },
        {
          canonical: "Malachi",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Malachi", chapterStart: 1, verseStart: 1, display: "Malachi 1:1" }],
          explanation: "Malachi is the last of the twelve Minor Prophets and the final book of the Old Testament.",
        },
        {
          canonical: "Obadiah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Obadiah", chapterStart: 1, verseStart: 1, display: "Obadiah 1:1" }],
          explanation: "Obadiah, the shortest book in the Old Testament at just one chapter, pronounces judgment on Edom.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a precious stone mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts:
        "Any precious stone explicitly named in the biblical text, such as the high priest's breastplate in Exodus 28 or the foundations of the New Jerusalem in Revelation 21.",
      answers: [
        {
          canonical: "Jasper",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 21, verseStart: 19, display: "Revelation 21:19" }],
          explanation: "Jasper is named as the first foundation stone of the New Jerusalem.",
        },
        {
          canonical: "Sapphire",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 17, verseEnd: 20, display: "Exodus 28:17-20" }],
          explanation: "Sapphire is one of the twelve stones set in the high priest's breastplate.",
        },
        {
          canonical: "Emerald",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 3, display: "Revelation 4:3" }],
          explanation: "A rainbow that looks like an emerald encircles God's throne.",
        },
        {
          canonical: "Topaz",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 17, verseEnd: 20, display: "Exodus 28:17-20" }],
          explanation: "Topaz is named among the stones of the priestly breastplate.",
        },
        {
          canonical: "Onyx",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 17, verseEnd: 20, display: "Exodus 28:17-20" }],
          explanation: "Onyx is included among the breastplate's twelve stones.",
        },
        {
          canonical: "Amethyst",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 21, verseStart: 20, display: "Revelation 21:20" }],
          explanation: "Amethyst is named as one of the foundation stones of the New Jerusalem.",
        },
        {
          canonical: "Beryl",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 17, verseEnd: 20, display: "Exodus 28:17-20" }],
          explanation: "Beryl is named among the breastplate's twelve stones.",
        },
        {
          canonical: "Chalcedony",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 21, verseStart: 19, display: "Revelation 21:19" }],
          explanation: "Chalcedony is named as the third foundation stone of the New Jerusalem.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a miracle performed by Elijah or Elisha.",
      instructions: "You get one guess.",
      whatCounts: "Any miracle the biblical text explicitly attributes to Elijah or Elisha.",
      answers: [
        {
          canonical: "Fire from Heaven on Mount Carmel",
          aliases: ["fire on carmel", "carmel"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 38, display: "1 Kings 18:38" }],
          explanation: "Fire falls from heaven and consumes Elijah's sacrifice before the prophets of Baal.",
        },
        {
          canonical: "Healing Naaman's Leprosy",
          aliases: ["naaman"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 1, verseEnd: 14, display: "2 Kings 5:1-14" }],
          explanation: "Elisha instructs Naaman to wash in the Jordan seven times, healing his leprosy.",
        },
        {
          canonical: "Raising the Widow's Son at Zarephath",
          aliases: ["zarephath"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 17, verseEnd: 24, display: "1 Kings 17:17-24" }],
          explanation: "Elijah prays and the widow of Zarephath's son is restored to life.",
        },
        {
          canonical: "Raising the Shunammite's Son",
          aliases: ["shunammite", "shunammite's son"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 4, verseStart: 32, verseEnd: 37, display: "2 Kings 4:32-37" }],
          explanation: "Elisha raises the Shunammite woman's son back to life.",
        },
        {
          canonical: "Multiplying the Widow's Oil",
          aliases: ["widow's oil", "oil"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 4, verseStart: 1, verseEnd: 7, display: "2 Kings 4:1-7" }],
          explanation: "Elisha causes a widow's small jar of oil to fill many borrowed jars.",
        },
        {
          canonical: "Parting the Jordan River",
          aliases: ["jordan"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 2, verseStart: 8, display: "2 Kings 2:8" }],
          explanation: "Elijah strikes the Jordan with his cloak, and the waters part.",
        },
        {
          canonical: "Making an Axe Head Float",
          aliases: ["axe head", "floating axe head"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 6, verseStart: 1, verseEnd: 7, display: "2 Kings 6:1-7" }],
          explanation: "Elisha makes a borrowed iron axe head float to the surface of the water.",
        },
        {
          canonical: "Elisha's Bones Reviving a Dead Man",
          aliases: ["elisha's bones"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 13, verseStart: 20, verseEnd: 21, display: "2 Kings 13:20-21" }],
          explanation:
            "A dead man is revived when his body touches Elisha's bones — after Elisha himself had already died.",
        },
      ],
    },
  ],
};
