import type { SeedDay } from "./types";

export const DAY_03: SeedDay = {
  dayNumber: 3,
  date: "2026-10-03",
  scriptureBonus: {
    displayText: "I can do all things through Christ, who strengthens me.",
    book: "Philippians",
    chapter: 4,
    verseStart: 13,
    referenceDisplay: "Philippians 4:13",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote:
      "Paul writes this from prison, describing the contentment he has learned in every circumstance through Christ's strength.",
    acceptedBookAliases: ["phil"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person who spoke with an angel.",
      instructions: "You get one guess.",
      whatCounts:
        "Any named person the biblical text explicitly describes speaking with an angel (including \"the angel of the LORD\").",
      answers: [
        {
          canonical: "Mary",
          aliases: ["mary mother of jesus", "virgin mary"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 26, verseEnd: 38, display: "Luke 1:26-38" }],
          explanation: "The angel Gabriel announces to Mary that she will bear Jesus.",
        },
        {
          canonical: "Zechariah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 11, verseEnd: 20, display: "Luke 1:11-20" }],
          explanation:
            "Gabriel appears to Zechariah in the temple, announcing the birth of John the Baptist.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 20, verseEnd: 21, display: "Matthew 1:20-21" }],
          explanation: "An angel speaks to Joseph in a dream, telling him to take Mary as his wife.",
        },
        {
          canonical: "Hagar",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 16, verseStart: 7, verseEnd: 13, display: "Genesis 16:7-13" }],
          explanation: "The angel of the LORD speaks with Hagar in the wilderness.",
        },
        {
          canonical: "Gideon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 11, verseEnd: 24, display: "Judges 6:11-24" }],
          explanation: "The angel of the LORD appears to Gideon and commissions him to deliver Israel.",
        },
        {
          canonical: "Manoah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 13, verseStart: 3, verseEnd: 20, display: "Judges 13:3-20" }],
          explanation:
            "The angel of the LORD appears to Manoah and his wife, announcing the birth of Samson.",
        },
        {
          canonical: "Daniel",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Daniel", chapterStart: 9, verseStart: 21, verseEnd: 22, display: "Daniel 9:21-22" }],
          explanation: "The angel Gabriel speaks with Daniel to give him understanding of a vision.",
        },
        {
          canonical: "Philip",
          aliases: ["philip the evangelist"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 26, display: "Acts 8:26" }],
          explanation:
            "An angel of the Lord speaks to Philip, sending him south to meet the Ethiopian official.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a king of Judah.",
      instructions: "You get one guess.",
      whatCounts:
        "Any king who ruled over Judah, including David and Solomon of the united kingdom and the later kings of the southern kingdom after the division of Israel.",
      answers: [
        {
          canonical: "David",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 3, verseEnd: 5, display: "2 Samuel 5:3-5" }],
          explanation: "David is anointed king over all Israel and Judah.",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 1, verseStart: 39, display: "1 Kings 1:39" }],
          explanation: "Solomon is anointed king, succeeding his father David.",
        },
        {
          canonical: "Hezekiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 18, verseStart: 1, verseEnd: 3, display: "2 Kings 18:1-3" }],
          explanation: "Hezekiah reigns in Judah and is remembered for doing right in the LORD's eyes.",
        },
        {
          canonical: "Josiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 22, verseStart: 1, verseEnd: 2, display: "2 Kings 22:1-2" }],
          explanation:
            "Josiah becomes king at age eight and leads a major religious reform after the Law is rediscovered.",
        },
        {
          canonical: "Rehoboam",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 12, verseStart: 1, verseEnd: 17, display: "1 Kings 12:1-17" }],
          explanation: "Solomon's son Rehoboam's harsh response to Israel leads to the kingdom's division.",
        },
        {
          canonical: "Manasseh",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 21, verseStart: 1, verseEnd: 9, display: "2 Kings 21:1-9" }],
          explanation: "Manasseh reigns fifty-five years in Judah and leads it into idolatry.",
        },
        {
          canonical: "Amon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 21, verseStart: 19, verseEnd: 22, display: "2 Kings 21:19-22" }],
          explanation: "Amon, Manasseh's son, reigns briefly in Judah and follows his father's idolatry.",
        },
        {
          canonical: "Jotham",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 32, verseEnd: 35, display: "2 Kings 15:32-35" }],
          explanation: "Jotham, son of Uzziah, reigns over Judah and does what is right in the LORD's eyes.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a parable told by Jesus.",
      instructions: "You get one guess.",
      whatCounts: "Any parable the Gospels explicitly attribute to Jesus.",
      answers: [
        {
          canonical: "The Prodigal Son",
          aliases: ["the lost son"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 11, verseEnd: 32, display: "Luke 15:11-32" }],
          explanation: "A father welcomes home his wayward son who squandered his inheritance.",
        },
        {
          canonical: "The Good Samaritan",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 10, verseStart: 25, verseEnd: 37, display: "Luke 10:25-37" }],
          explanation: "A Samaritan stops to help a wounded traveler after religious leaders pass him by.",
        },
        {
          canonical: "The Sower",
          aliases: ["parable of the sower"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 3, verseEnd: 9, display: "Matthew 13:3-9" }],
          explanation: "A farmer scatters seed that falls on different types of soil with different results.",
        },
        {
          canonical: "The Mustard Seed",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 31, verseEnd: 32, display: "Matthew 13:31-32" }],
          explanation: "The kingdom of heaven is compared to a tiny mustard seed that grows into a large tree.",
        },
        {
          canonical: "The Lost Sheep",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 3, verseEnd: 7, display: "Luke 15:3-7" }],
          explanation: "A shepherd leaves ninety-nine sheep to search for the one that is lost.",
        },
        {
          canonical: "The Ten Virgins",
          aliases: ["the ten bridesmaids"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 25, verseStart: 1, verseEnd: 13, display: "Matthew 25:1-13" }],
          explanation: "Five wise and five foolish virgins wait for a bridegroom, only some of them prepared.",
        },
        {
          canonical: "The Persistent Widow",
          aliases: ["the unjust judge"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 18, verseStart: 1, verseEnd: 8, display: "Luke 18:1-8" }],
          explanation: "A widow's persistence wears down an unjust judge into granting her justice.",
        },
        {
          canonical: "The Rich Fool",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Luke", chapterStart: 12, verseStart: 16, verseEnd: 21, display: "Luke 12:16-21" }],
          explanation:
            "A rich man plans bigger barns for his abundant crops, not knowing his life will end that very night.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a plague that struck Egypt.",
      instructions: "You get one guess.",
      whatCounts: "Any of the ten plagues the book of Exodus describes striking Egypt.",
      answers: [
        {
          canonical: "Blood",
          aliases: ["water turned to blood"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 7, verseStart: 20, verseEnd: 21, display: "Exodus 7:20-21" }],
          explanation: "The waters of Egypt's river turn to blood, killing the fish.",
        },
        {
          canonical: "Frogs",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 8, verseStart: 6, display: "Exodus 8:6" }],
          explanation: "Frogs cover the land of Egypt.",
        },
        {
          canonical: "Gnats",
          aliases: ["lice"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 8, verseStart: 16, verseEnd: 17, display: "Exodus 8:16-17" }],
          explanation: "Aaron strikes the dust and it becomes gnats throughout Egypt — the third plague.",
        },
        {
          canonical: "Flies",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 8, verseStart: 24, display: "Exodus 8:24" }],
          explanation: "Dense swarms of flies fill Egypt's houses and land — the fourth plague.",
        },
        {
          canonical: "Death of the Firstborn",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 12, verseStart: 29, display: "Exodus 12:29" }],
          explanation: "The LORD strikes down every firstborn in Egypt at midnight.",
        },
        {
          canonical: "Hail",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 9, verseStart: 23, verseEnd: 25, display: "Exodus 9:23-25" }],
          explanation: "A devastating hailstorm strikes Egypt's crops and livestock.",
        },
        {
          canonical: "Locusts",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 10, verseStart: 14, verseEnd: 15, display: "Exodus 10:14-15" }],
          explanation: "Swarms of locusts devour every plant left after the hail.",
        },
        {
          canonical: "Darkness",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 10, verseStart: 22, display: "Exodus 10:22" }],
          explanation: "Thick darkness covers Egypt for three days.",
        },
        {
          canonical: "Boils",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 9, verseStart: 10, display: "Exodus 9:10" }],
          explanation: "Festering boils break out on people and animals throughout Egypt.",
        },
        {
          canonical: "Pestilence on Livestock",
          aliases: ["plague on livestock"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 9, verseStart: 3, verseEnd: 6, display: "Exodus 9:3-6" }],
          explanation:
            "A severe plague kills the livestock of Egypt, while none of Israel's animals die — often the most forgotten of the ten.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a place in the Book of Revelation.",
      instructions: "You get one guess.",
      whatCounts: "Any place explicitly named in the book of Revelation.",
      answers: [
        {
          canonical: "New Jerusalem",
          aliases: ["jerusalem"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 21, verseStart: 2, display: "Revelation 21:2" }],
          explanation: "John sees the holy city, New Jerusalem, coming down out of heaven.",
        },
        {
          canonical: "Babylon",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 18, verseStart: 2, display: "Revelation 18:2" }],
          explanation: "\"Babylon the Great\" is announced as fallen in a vision of judgment.",
        },
        {
          canonical: "Patmos",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 1, verseStart: 9, display: "Revelation 1:9" }],
          explanation: "John receives his vision while on the island of Patmos.",
        },
        {
          canonical: "Ephesus",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 1, display: "Revelation 2:1" }],
          explanation: "Ephesus is the first of the seven churches addressed in Revelation.",
        },
        {
          canonical: "Armageddon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 16, verseStart: 16, display: "Revelation 16:16" }],
          explanation: "The kings of the earth are gathered to the place called Armageddon.",
        },
        {
          canonical: "Mount Zion",
          aliases: ["zion"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 14, verseStart: 1, display: "Revelation 14:1" }],
          explanation: "The Lamb stands on Mount Zion with the 144,000 who bear his name.",
        },
        {
          canonical: "Sea of Glass",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 6, display: "Revelation 4:6" }],
          explanation: "Something like a sea of glass, clear as crystal, stands before God's throne.",
        },
        {
          canonical: "Euphrates River",
          aliases: ["euphrates"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 16, verseStart: 12, display: "Revelation 16:12" }],
          explanation: "The great river Euphrates is dried up to prepare the way for kings from the east.",
        },
      ],
    },
  ],
};
