import type { SeedDay } from "./types";

export const DAY_06: SeedDay = {
  dayNumber: 6,
  date: "2026-09-23",
  scriptureBonus: {
    displayText:
      "We know that all things work together for good for those who love God, for those who are called according to his purpose.",
    book: "Romans",
    chapter: 8,
    verseStart: 28,
    referenceDisplay: "Romans 8:28",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul assures believers that God works even difficult circumstances toward good for those who love him.",
    acceptedBookAliases: ["rom"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person exiled to Babylon.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text describes as taken into exile in Babylon.",
      answers: [
        {
          canonical: "Daniel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 1, verseEnd: 6, display: "Daniel 1:1-6" }],
          explanation: "Daniel is taken to Babylon among the young nobles of Judah.",
        },
        {
          canonical: "Ezekiel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ezekiel", chapterStart: 1, verseStart: 1, verseEnd: 3, display: "Ezekiel 1:1-3" }],
          explanation: "Ezekiel prophesies among the exiles by the river Chebar in Babylon.",
        },
        {
          canonical: "Shadrach",
          aliases: ["hananiah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 6, verseEnd: 7, display: "Daniel 1:6-7" }],
          explanation: "Hananiah, renamed Shadrach in Babylon, is exiled alongside Daniel.",
        },
        {
          canonical: "Meshach",
          aliases: ["mishael"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 6, verseEnd: 7, display: "Daniel 1:6-7" }],
          explanation: "Mishael, renamed Meshach in Babylon, is exiled alongside Daniel.",
        },
        {
          canonical: "Abednego",
          aliases: ["azariah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 6, verseEnd: 7, display: "Daniel 1:6-7" }],
          explanation: "Azariah, renamed Abednego in Babylon, is exiled alongside Daniel.",
        },
        {
          canonical: "Zedekiah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 25, verseStart: 6, verseEnd: 7, display: "2 Kings 25:6-7" }],
          explanation: "King Zedekiah, the last king of Judah, is captured and taken to Babylon.",
        },
        {
          canonical: "Jehoiachin",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 12, verseEnd: 15, display: "2 Kings 24:12-15" }],
          explanation: "King Jehoiachin surrenders to Nebuchadnezzar and is taken into exile in Babylon.",
        },
        {
          canonical: "Mordecai",
          aliases: ["Mordecai the Jew","Esther's cousin"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 6, display: "Esther 2:6" }],
          explanation: "Esther identifies Mordecai as having been carried away from Jerusalem among the captives taken with Jeconiah to Babylon.",
        },
        {
          canonical: "Nehushta",
          aliases: ["mother of Jehoiachin","queen mother"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 8, display: "2 Kings 24:8" }, { book: "2 Kings", chapterStart: 24, verseStart: 15, display: "2 Kings 24:15" }],
          explanation: "Nehushta, the queen mother, is carried into exile in Babylon along with her son King Jehoiachin.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a miracle performed by Jesus.",
      instructions: "You get one guess.",
      whatCounts: "Any miracle the Gospels explicitly attribute to Jesus.",
      answers: [
        {
          canonical: "Turning Water into Wine",
          aliases: ["water into wine", "water to wine"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 2, verseStart: 1, verseEnd: 11, display: "John 2:1-11" }],
          explanation: "Jesus turns water into wine at a wedding in Cana.",
        },
        {
          canonical: "Feeding the 5,000",
          aliases: ["feeding the 5000", "feeding five thousand"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 13, verseEnd: 21, display: "Matthew 14:13-21" }],
          explanation: "Jesus feeds five thousand people with five loaves and two fish.",
        },
        {
          canonical: "Walking on Water",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 22, verseEnd: 33, display: "Matthew 14:22-33" }],
          explanation: "Jesus walks on the surface of the sea toward his disciples' boat.",
        },
        {
          canonical: "Calming the Storm",
          aliases: ["calming the sea", "stilling the storm"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 4, verseStart: 35, verseEnd: 41, display: "Mark 4:35-41" }],
          explanation: "Jesus rebukes a violent storm and the sea becomes calm.",
        },
        {
          canonical: "Healing a Man Born Blind",
          aliases: ["man born blind", "blind man"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 9, verseStart: 1, verseEnd: 7, display: "John 9:1-7" }],
          explanation: "Jesus heals a man who had been blind from birth.",
        },
        {
          canonical: "Healing the Centurion's Servant",
          aliases: ["centurion's servant"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 5, verseEnd: 13, display: "Matthew 8:5-13" }],
          explanation: "Jesus heals a Roman centurion's servant from a distance, at the centurion's request.",
        },
        {
          canonical: "Catch of 153 Fish",
          aliases: ["153 fish"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "John", chapterStart: 21, verseStart: 1, verseEnd: 11, display: "John 21:1-11" }],
          explanation:
            "After his resurrection, Jesus directs the disciples to a miraculous catch of exactly 153 fish.",
        },
        {
          canonical: "Cursing the Fig Tree",
          aliases: ["fig tree", "cursing fig tree", "cursing the fig tree", "jesus curses a fig tree", "curses the fig tree"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Mark", chapterStart: 11, verseStart: 12, verseEnd: 14, display: "Mark 11:12-14" }],
          explanation:
            "Jesus curses a fruitless fig tree, which is found withered from the roots the next day.",
        },
        {
          canonical: "Raising of Lazarus",
          aliases: ["Lazarus raised from the dead","raising Lazarus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 11, verseStart: 43, verseEnd: 44, display: "John 11:43-44" }],
          explanation: "Jesus calls Lazarus out of the tomb four days after his death, raising him back to life.",
        },
        {
          canonical: "Feeding the 4,000",
          aliases: ["feeding four thousand","seven loaves and a few fish"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 15, verseStart: 32, verseEnd: 38, display: "Matthew 15:32-38" }],
          explanation: "Jesus multiplies seven loaves and a few small fish to feed four thousand people.",
        },
        {
          canonical: "Healing the Gerasene Demoniac",
          aliases: ["Legion","demons into pigs","healing the man with Legion"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 1, verseEnd: 13, display: "Mark 5:1-13" }],
          explanation: "Jesus casts a legion of demons out of a tormented man and sends them into a herd of pigs.",
        },
        {
          canonical: "Healing Blind Bartimaeus",
          aliases: ["Bartimaeus","blind beggar of Jericho"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 10, verseStart: 46, verseEnd: 52, display: "Mark 10:46-52" }],
          explanation: "Jesus restores the sight of the blind beggar Bartimaeus outside Jericho.",
        },
        {
          canonical: "Coin in the Fish's Mouth",
          aliases: ["temple tax fish","coin from a fish"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 17, verseStart: 24, verseEnd: 27, display: "Matthew 17:24-27" }],
          explanation: "Jesus tells Peter he will find a coin in the mouth of the first fish he catches to pay the temple tax.",
        },
        {
          canonical: "Healing the Royal Official's Son",
          aliases: ["nobleman's son","official's son","healing at a distance"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "John", chapterStart: 4, verseStart: 46, verseEnd: 54, display: "John 4:46-54" }],
          explanation: "Jesus heals a royal official's dying son from a distance, with a word spoken in Cana.",
        },
        {
          canonical: "Healing the Bent-Over Woman",
          aliases: ["bent over woman","crippled woman","woman bound 18 years"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 13, verseStart: 10, verseEnd: 13, display: "Luke 13:10-13" }],
          explanation: "Jesus heals a woman who had been crippled and bent over for eighteen years on the Sabbath.",
        },
        {
          canonical: "Healing the Man with Dropsy",
          aliases: ["dropsy","man with dropsy","swelling disease"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 14, verseStart: 1, verseEnd: 4, display: "Luke 14:1-4" }],
          explanation: "Jesus heals a man suffering from dropsy at a Pharisee's house on the Sabbath.",
        },
        {
          canonical: "Restoring Malchus's Ear",
          aliases: ["malchus","servant's ear","healing the severed ear"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 22, verseStart: 50, verseEnd: 51, display: "Luke 22:50-51" }],
          explanation: "At his arrest, Jesus heals the ear of the high priest's servant after Peter cuts it off.",
        },
        {
          canonical: "Cleansing the Ten Lepers",
          aliases: ["ten lepers","where are the other nine","healing ten lepers"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 17, verseStart: 11, verseEnd: 19, display: "Luke 17:11-19" }],
          explanation: "Jesus cleanses ten men of leprosy on the road, and only one returns to give thanks.",
        },
        {
          canonical: "Raising the Widow of Nain's Son",
          aliases: ["widow of nain","widow of nain's son","raising the widow's son","resurrected the widows son"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 7, verseStart: 11, verseEnd: 15, display: "Luke 7:11-15" }],
          explanation: "Jesus raises the only son of a widow from Nain back to life during his funeral procession.",
        },
        {
          canonical: "Healing the Woman with the Flow of Blood",
          aliases: [
            "woman with the issue of blood",
            "woman touching jesus cloak",
            "woman touching his cloak",
            "woman who touched his garment",
            "touching the hem of his garment",
            "bleeding woman",
            "hemorrhaging woman",
            "woman with the flow of blood",
            "issue of blood",
          ],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 25, verseEnd: 34, display: "Mark 5:25-34" }],
          explanation:
            "A woman who had suffered bleeding for twelve years is healed the moment she touches the fringe of Jesus' cloak in faith.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a food or meal mentioned in the Gospels.",
      instructions: "You get one guess.",
      whatCounts: "Any specific food or meal explicitly mentioned in the four Gospels.",
      answers: [
        {
          canonical: "Bread",
          aliases: ["bread and fish", "fish and bread", "loaves and fish", "loaf and fish"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 19, display: "Matthew 14:19" }],
          explanation: "Jesus breaks loaves of bread while feeding the five thousand.",
        },
        {
          canonical: "Fish",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 17, display: "Matthew 14:17" }],
          explanation: "Five loaves and two fish feed the crowd of five thousand.",
        },
        {
          canonical: "Wine",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 2, verseStart: 1, verseEnd: 11, display: "John 2:1-11" }],
          explanation: "Jesus turns water into wine at the wedding in Cana.",
        },
        {
          canonical: "Locusts and Wild Honey",
          aliases: ["locusts", "wild honey"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 4, display: "Matthew 3:4" }],
          explanation: "John the Baptist's diet in the wilderness is locusts and wild honey.",
        },
        {
          canonical: "Passover Lamb",
          aliases: ["passover"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 22, verseStart: 7, verseEnd: 8, display: "Luke 22:7-8" }],
          explanation: "Jesus sends Peter and John to prepare the Passover meal before the Last Supper.",
        },
        {
          canonical: "Barley Loaves",
          aliases: ["barley", "loaves"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 6, verseStart: 9, display: "John 6:9" }],
          explanation: "John's account specifies the boy's loaves in the feeding of the 5,000 were barley loaves.",
        },
        {
          canonical: "Broiled Fish",
          aliases: ["grilled fish"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 24, verseStart: 42, verseEnd: 43, display: "Luke 24:42-43" }],
          explanation: "The risen Jesus eats a piece of broiled fish in front of his disciples.",
        },
        {
          canonical: "Heads of Grain",
          aliases: ["grain"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 12, verseStart: 1, display: "Matthew 12:1" }],
          explanation: "Jesus' disciples pick heads of grain to eat while walking through the fields on the Sabbath.",
        },
        {
          canonical: "Fatted Calf",
          aliases: ["the fattened calf","prodigal son's feast"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 23, display: "Luke 15:23" }],
          explanation: "The father orders the fatted calf killed and prepared for a feast to celebrate his prodigal son's return.",
        },
        {
          canonical: "Vinegar",
          aliases: ["sour wine","vinegar on a sponge"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 48, display: "Matthew 27:48" }],
          explanation: "A soldier offers Jesus a sponge soaked in sour wine while he hangs on the cross.",
        },
        {
          canonical: "Manna",
          aliases: ["bread from heaven","manna in the wilderness"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 6, verseStart: 31, display: "John 6:31" }],
          explanation: "The crowd reminds Jesus that their fathers ate manna in the wilderness, prompting his 'bread of life' teaching.",
        },
        {
          canonical: "Mint, Dill, and Cumin",
          aliases: ["mint and dill","tithed herbs and spices"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 23, verseStart: 23, display: "Matthew 23:23" }],
          explanation: "Jesus rebukes the Pharisees for meticulously tithing mint, dill, and cumin while neglecting justice and mercy.",
        },
        {
          canonical: "Unleavened Bread",
          aliases: ["unleavened bread","bread of unleavened bread","the feast of unleavened bread"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 17, display: "Matthew 26:17" }],
          explanation: "The disciples ask Jesus where to prepare the Passover on \"the first day of unleavened bread.\"",
        },
        {
          canonical: "The Last Supper",
          aliases: ["last supper", "the lords supper"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 26, verseEnd: 29, display: "Matthew 26:26-29" }],
          explanation: "Jesus shares a final Passover meal with his disciples before his arrest, instituting the bread and cup.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a Roman official mentioned in the New Testament.",
      instructions: "You get one guess.",
      whatCounts:
        "Any Roman government or military official (governor, centurion, tribune, client king under Rome, etc.) explicitly named in the New Testament.",
      answers: [
        {
          canonical: "Pontius Pilate",
          aliases: ["pilate", "pilot", "pontius pilot"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 2, display: "Matthew 27:2" }],
          explanation: "Pontius Pilate, the Roman governor, presides over Jesus' trial.",
        },
        {
          canonical: "Herod Antipas",
          aliases: ["herod"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 7, display: "Luke 23:7" }],
          explanation: "Herod Antipas, tetrarch of Galilee, questions Jesus before his crucifixion.",
        },
        {
          canonical: "Cornelius",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 1, display: "Acts 10:1" }],
          explanation: "Cornelius, a Roman centurion, becomes one of the first Gentile converts.",
        },
        {
          canonical: "Felix",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 24, verseStart: 1, display: "Acts 24:1" }],
          explanation: "Felix, the Roman governor, hears Paul's case in Caesarea.",
        },
        {
          canonical: "Festus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 25, verseStart: 1, display: "Acts 25:1" }],
          explanation: "Festus succeeds Felix as governor and continues Paul's case.",
        },
        {
          canonical: "Sergius Paulus",
          aliases: ["paulus"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 6, verseEnd: 12, display: "Acts 13:6-12" }],
          explanation: "Sergius Paulus, proconsul of Cyprus, believes after witnessing Paul's ministry.",
        },
        {
          canonical: "Gallio",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 12, verseEnd: 17, display: "Acts 18:12-17" }],
          explanation: "Gallio, proconsul of Achaia, dismisses charges brought against Paul in Corinth.",
        },
        {
          canonical: "Claudius Lysias",
          aliases: ["lysias"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 23, verseStart: 26, display: "Acts 23:26" }],
          explanation:
            "Claudius Lysias, the Roman tribune, is named in his own letter explaining why he is sending Paul to the governor.",
        },
        {
          canonical: "Caesar Augustus",
          aliases: ["Augustus","Emperor Augustus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 1, display: "Luke 2:1" }],
          explanation: "Caesar Augustus issues the decree for a census that brings Joseph and Mary to Bethlehem.",
        },
        {
          canonical: "Tiberius Caesar",
          aliases: ["Tiberius","Emperor Tiberius"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 1, display: "Luke 3:1" }],
          explanation: "Luke dates the start of John the Baptist's ministry to the fifteenth year of the reign of Tiberius Caesar.",
        },
        {
          canonical: "Emperor Claudius",
          aliases: ["Claudius Caesar","Claudius"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 2, display: "Acts 18:2" }],
          explanation: "Acts notes that Claudius had ordered all Jews to leave Rome, which is why Priscilla and Aquila met Paul in Corinth.",
        },
        {
          canonical: "King Agrippa",
          aliases: ["Herod Agrippa II","Agrippa"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 25, verseStart: 13, display: "Acts 25:13" }],
          explanation: "King Agrippa hears Paul's defense and famously tells him he has almost persuaded him to become a Christian.",
        },
        {
          canonical: "Julius the Centurion",
          aliases: ["Julius","centurion of the Augustan Cohort"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 1, verseEnd: 3, display: "Acts 27:1-3" }],
          explanation: "Julius, a centurion of the Augustan Cohort, is given custody of Paul for the voyage to Rome.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a weapon mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any weapon explicitly named in the biblical text.",
      answers: [
        {
          canonical: "Sword",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 24, display: "Genesis 3:24" }],
          explanation: "A flaming sword guards the way to the tree of life after Eden.",
        },
        {
          canonical: "Sling",
          aliases: ["slingshot", "sling shot", "stone", "a stone"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 17, verseStart: 40, display: "1 Samuel 17:40" }],
          explanation: "David uses a sling and stone to defeat Goliath.",
        },
        {
          canonical: "Spear",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 18, verseStart: 10, verseEnd: 11, display: "1 Samuel 18:10-11" }],
          explanation: "Saul hurls his spear at David in a jealous rage.",
        },
        {
          canonical: "Bow and Arrow",
          aliases: ["bow", "arrows"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 20, verseStart: 20, display: "1 Samuel 20:20" }],
          explanation: "Jonathan uses a bow and arrows as a secret signal to warn David.",
        },
        {
          canonical: "Ox Goad",
          aliases: ["goad"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 3, verseStart: 31, display: "Judges 3:31" }],
          explanation: "Shamgar strikes down six hundred Philistines with an ox goad.",
        },
        {
          canonical: "Jawbone of a Donkey",
          aliases: ["jawbone", "donkey jawbone", "jawbone of an ass"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 15, verseStart: 15, verseEnd: 16, display: "Judges 15:15-16" }],
          explanation: "Samson strikes down a thousand Philistines with the jawbone of a donkey.",
        },
        {
          canonical: "Battle-Axe",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jeremiah", chapterStart: 51, verseStart: 20, display: "Jeremiah 51:20" }],
          explanation: "God calls a nation his \"battle-axe and weapons of war\" in a message against Babylon.",
        },
        {
          canonical: "Goliath's Sword",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 21, verseStart: 9, display: "1 Samuel 21:9" }],
          explanation:
            "David later takes Goliath's own sword, which had been kept behind the ephod at Nob.",
        },
        {
          canonical: "Holofernes' Sword",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judith", chapterStart: 13, display: "Judith 13" }],
          explanation:
            "Judith beheads the enemy general Holofernes with his own sword after he falls into a drunken sleep.",
          catholicOnly: true,
        },
        {
          canonical: "Shield",
          aliases: ["shields"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 16, display: "Ephesians 6:16" }],
          explanation: "The shield is named repeatedly across the Bible as a standard weapon of defense in battle.",
        },
        {
          canonical: "Jael's Tent Peg",
          aliases: ["tent peg and hammer","Jael's hammer","stake"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 4, verseStart: 21, display: "Judges 4:21" }],
          explanation: "Jael drives a tent peg through Sisera's temple with a hammer while he sleeps.",
        },
        {
          canonical: "Ehud's Dagger",
          aliases: ["Ehud's sword","two-edged dagger","dagger"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 3, verseStart: 16, display: "Judges 3:16" }],
          explanation: "The left-handed judge Ehud makes himself a two-edged dagger and uses it to kill King Eglon of Moab.",
        },
      ],
    },
  ],
};
