import type { SeedDay } from "./types";

export const DAY_09: SeedDay = {
  dayNumber: 9,
  date: "2026-09-26",
  scriptureBonus: {
    displayText:
      "For I know the thoughts that I think toward you, says Yahweh, thoughts of peace, and not of evil, to give you hope and a future.",
    book: "Jeremiah",
    chapter: 29,
    verseStart: 11,
    referenceDisplay: "Jeremiah 29:11",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Part of Jeremiah's letter to the exiles in Babylon, promising future restoration.",
    acceptedBookAliases: ["jer"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person whose name was changed by God.",
      instructions: "You get one guess.",
      whatCounts:
        "Any person the biblical text explicitly describes God (or a prophet speaking for God) giving a new name.",
      answers: [
        {
          canonical: "Abraham",
          aliases: ["abram"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 17, verseStart: 5, display: "Genesis 17:5" }],
          explanation: "God changes Abram's name to Abraham, \"father of many nations.\"",
        },
        {
          canonical: "Sarah",
          aliases: ["sarai"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 17, verseStart: 15, display: "Genesis 17:15" }],
          explanation: "God changes Sarai's name to Sarah.",
        },
        {
          canonical: "Jacob",
          aliases: ["israel"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 32, verseStart: 28, display: "Genesis 32:28" }],
          explanation: "After wrestling through the night, Jacob is given the new name Israel.",
        },
        {
          canonical: "Peter",
          aliases: ["simon"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 1, verseStart: 42, display: "John 1:42" }],
          explanation: "Jesus renames Simon as Peter (Cephas), meaning \"rock.\"",
        },
        {
          canonical: "Solomon",
          aliases: ["jedidiah"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Samuel", chapterStart: 12, verseStart: 24, verseEnd: 25, display: "2 Samuel 12:24-25" }],
          explanation:
            "Through the prophet Nathan, the LORD gives the infant Solomon the additional name Jedidiah, meaning \"loved by the LORD.\"",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person who built something at God's command.",
      instructions: "You get one guess.",
      whatCounts:
        "Any person the biblical text explicitly describes building something — an ark, altar, tabernacle, temple, or wall — at God's command.",
      answers: [
        {
          canonical: "Noah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 6, verseStart: 14, verseEnd: 22, display: "Genesis 6:14-22" }],
          explanation: "God commands Noah to build an ark to save his family and the animals.",
        },
        {
          canonical: "Moses",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 8, verseEnd: 9, display: "Exodus 25:8-9" }],
          explanation: "God commands Moses to build the tabernacle according to a shown pattern.",
        },
        {
          canonical: "Bezalel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 31, verseStart: 1, verseEnd: 6, display: "Exodus 31:1-6" }],
          explanation: "Bezalel is filled with God's Spirit and skill to craft the tabernacle's furnishings.",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 6, verseStart: 1, display: "1 Kings 6:1" }],
          explanation: "Solomon builds the temple in Jerusalem.",
        },
        {
          canonical: "Nehemiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Nehemiah", chapterStart: 2, verseStart: 17, verseEnd: 18, display: "Nehemiah 2:17-18" }],
          explanation: "Nehemiah leads the rebuilding of Jerusalem's wall.",
        },
        {
          canonical: "Gideon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 26, display: "Judges 6:26" }],
          explanation: "God commands Gideon to build an altar to the LORD on the height.",
        },
        {
          canonical: "Zerubbabel",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ezra", chapterStart: 3, verseStart: 8, verseEnd: 10, display: "Ezra 3:8-10" }],
          explanation: "Zerubbabel leads the rebuilding of the temple after the exiles return.",
        },
        {
          canonical: "Elijah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 31, verseEnd: 32, display: "1 Kings 18:31-32" }],
          explanation:
            "Elijah rebuilds the altar of the LORD on Mount Carmel using twelve stones before calling down fire.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a wife of a patriarch.",
      instructions: "You get one guess.",
      whatCounts: "Any woman the biblical text explicitly identifies as a wife of Abraham, Isaac, or Jacob.",
      answers: [
        {
          canonical: "Sarah",
          aliases: ["sarai"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 17, verseStart: 15, display: "Genesis 17:15" }],
          explanation: "Sarah is Abraham's wife and the mother of Isaac.",
        },
        {
          canonical: "Rebekah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 24, verseStart: 67, display: "Genesis 24:67" }],
          explanation: "Rebekah becomes Isaac's wife.",
        },
        {
          canonical: "Rachel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 28, display: "Genesis 29:28" }],
          explanation: "Rachel, Jacob's beloved wife, is the mother of Joseph and Benjamin.",
        },
        {
          canonical: "Leah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 23, display: "Genesis 29:23" }],
          explanation: "Leah, Rachel's older sister, is also given to Jacob as a wife.",
        },
        {
          canonical: "Hagar",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 16, verseStart: 3, display: "Genesis 16:3" }],
          explanation: "Hagar is given to Abraham as a wife by Sarah.",
        },
        {
          canonical: "Bilhah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 4, display: "Genesis 30:4" }],
          explanation: "Rachel gives her servant Bilhah to Jacob as a wife.",
        },
        {
          canonical: "Zilpah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 9, display: "Genesis 30:9" }],
          explanation: "Leah gives her servant Zilpah to Jacob as a wife.",
        },
        {
          canonical: "Keturah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 1, display: "Genesis 25:1" }],
          explanation: "After Sarah's death, Abraham takes Keturah as a wife.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a prophet who confronted a king.",
      instructions: "You get one guess.",
      whatCounts: "Any prophet the biblical text explicitly describes confronting or rebuking a king.",
      answers: [
        {
          canonical: "Nathan",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 12, verseStart: 1, verseEnd: 7, display: "2 Samuel 12:1-7" }],
          explanation: "Nathan confronts King David over his sin with Bathsheba using a parable.",
        },
        {
          canonical: "Elijah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 17, verseEnd: 18, display: "1 Kings 18:17-18" }],
          explanation: "Elijah confronts King Ahab over Israel's idolatry.",
        },
        {
          canonical: "Samuel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 15, verseStart: 10, verseEnd: 23, display: "1 Samuel 15:10-23" }],
          explanation: "Samuel confronts King Saul for disobeying the LORD's command.",
        },
        {
          canonical: "Isaiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Isaiah", chapterStart: 7, verseStart: 3, verseEnd: 13, display: "Isaiah 7:3-13" }],
          explanation: "Isaiah confronts King Ahaz for refusing to ask God for a sign.",
        },
        {
          canonical: "Jeremiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 38, verseStart: 14, verseEnd: 23, display: "Jeremiah 38:14-23" }],
          explanation: "Jeremiah confronts King Zedekiah with a warning about Jerusalem's fall.",
        },
        {
          canonical: "Micaiah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 8, verseEnd: 28, display: "1 Kings 22:8-28" }],
          explanation: "Micaiah confronts King Ahab with a true prophecy of defeat, against the court's false prophets.",
        },
        {
          canonical: "Amos",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Amos", chapterStart: 7, verseStart: 10, verseEnd: 13, display: "Amos 7:10-13" }],
          explanation: "Amos's prophecy against Jeroboam II's house leads to conflict with the king's priest.",
        },
        {
          canonical: "Ahijah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 14, verseStart: 6, verseEnd: 16, display: "1 Kings 14:6-16" }],
          explanation: "The prophet Ahijah pronounces judgment on the house of Jeroboam I.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a city destroyed in the Bible.",
      instructions: "You get one guess.",
      whatCounts:
        "Any city the biblical text explicitly describes — through narrative or prophetic pronouncement — as being destroyed.",
      answers: [
        {
          canonical: "Sodom",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 24, verseEnd: 25, display: "Genesis 19:24-25" }],
          explanation: "God rains down sulfur and fire on Sodom and Gomorrah.",
        },
        {
          canonical: "Jericho",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Joshua", chapterStart: 6, verseStart: 20, verseEnd: 21, display: "Joshua 6:20-21" }],
          explanation: "Jericho's walls fall and the city is destroyed after Israel marches around it.",
        },
        {
          canonical: "Gomorrah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 24, verseEnd: 25, display: "Genesis 19:24-25" }],
          explanation: "Gomorrah is destroyed alongside Sodom.",
        },
        {
          canonical: "Ai",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 8, verseStart: 19, verseEnd: 28, display: "Joshua 8:19-28" }],
          explanation: "Israel burns and destroys the city of Ai after their second attack.",
        },
        {
          canonical: "Jerusalem",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 25, verseStart: 8, verseEnd: 10, display: "2 Kings 25:8-10" }],
          explanation: "Nebuchadnezzar's forces burn Jerusalem and break down its walls.",
        },
        {
          canonical: "Nineveh",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Nahum", chapterStart: 3, verseStart: 1, display: "Nahum 3" }],
          explanation: "The prophet Nahum pronounces the destruction of Nineveh.",
        },
        {
          canonical: "Babylon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Isaiah", chapterStart: 13, verseStart: 19, display: "Isaiah 13:19" }],
          explanation: "Isaiah pronounces that Babylon will be overthrown like Sodom and Gomorrah.",
        },
        {
          canonical: "Shechem",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 34, verseStart: 25, verseEnd: 29, display: "Genesis 34:25-29" }],
          explanation: "Simeon and Levi attack and destroy the city of Shechem in retaliation for their sister Dinah.",
        },
      ],
    },
  ],
};
