import type { SeedDay } from "./types";

export const DAY_05: SeedDay = {
  dayNumber: 5,
  date: "2026-09-22",
  scriptureBonus: {
    displayText:
      "Trust in Yahweh with all your heart, and don't lean on your own understanding.",
    book: "Proverbs",
    chapter: 3,
    verseStart: 5,
    referenceDisplay: "Proverbs 3:5",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A foundational proverb about trusting God rather than relying solely on one's own reasoning.",
    acceptedBookAliases: ["prov"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a son of Jacob.",
      instructions: "You get one guess.",
      whatCounts:
        "Any of the twelve sons of Jacob named in Genesis, ancestors of the twelve tribes of Israel.",
      answers: [
        {
          canonical: "Judah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 35, display: "Genesis 29:35" }],
          explanation: "Judah is Jacob's fourth son by Leah, ancestor of the tribe of Judah.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 24, display: "Genesis 30:24" }],
          explanation: "Joseph is Jacob's eleventh son, born to Rachel.",
        },
        {
          canonical: "Reuben",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 32, display: "Genesis 29:32" }],
          explanation: "Reuben is Jacob's firstborn son, by Leah.",
        },
        {
          canonical: "Benjamin",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 35, verseStart: 18, display: "Genesis 35:18" }],
          explanation: "Benjamin is Jacob's twelfth and youngest son, born to Rachel as she died.",
        },
        {
          canonical: "Levi",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 34, display: "Genesis 29:34" }],
          explanation: "Levi is Jacob's third son by Leah, ancestor of the priestly tribe.",
        },
        {
          canonical: "Zebulun",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 20, display: "Genesis 30:20" }],
          explanation: "Zebulun is Jacob's sixth son by Leah.",
        },
        {
          canonical: "Asher",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 13, display: "Genesis 30:13" }],
          explanation: "Asher is Jacob's son by Leah's servant Zilpah.",
        },
        {
          canonical: "Simeon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 33, display: "Genesis 29:33" }],
          explanation: "Simeon is Jacob's second son, by Leah.",
        },
        {
          canonical: "Dan",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 6, display: "Genesis 30:6" }],
          explanation: "Dan is Jacob's son by Rachel's servant Bilhah.",
        },
        {
          canonical: "Naphtali",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 8, display: "Genesis 30:8" }],
          explanation: "Naphtali is Jacob's son by Rachel's servant Bilhah.",
        },
        {
          canonical: "Gad",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 11, display: "Genesis 30:11" }],
          explanation: "Gad is Jacob's son by Leah's servant Zilpah.",
        },
        {
          canonical: "Issachar",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 18, display: "Genesis 30:18" }],
          explanation: "Issachar is Jacob's ninth son, born to Leah.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person present at Jesus' crucifixion.",
      instructions: "You get one guess.",
      whatCounts: "Any person the Gospels explicitly place at the scene of Jesus' crucifixion at Golgotha.",
      answers: [
        {
          canonical: "Mary",
          aliases: ["mary mother of jesus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 19, verseStart: 25, display: "John 19:25" }],
          explanation: "Jesus' mother Mary stands near the cross.",
        },
        {
          canonical: "Mary Magdalene",
          aliases: ["magdalene"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 19, verseStart: 25, display: "John 19:25" }],
          explanation: "Mary Magdalene is named among the women standing near the cross.",
        },
        {
          canonical: "John",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 19, verseStart: 26, verseEnd: 27, display: "John 19:26-27" }],
          explanation: "Jesus entrusts his mother to the care of \"the disciple he loved,\" traditionally John.",
        },
        {
          canonical: "The Centurion",
          aliases: ["centurion"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 54, display: "Matthew 27:54" }],
          explanation: "A Roman centurion overseeing the crucifixion declares Jesus was the Son of God.",
        },
        {
          canonical: "Simon of Cyrene",
          aliases: ["cyrene"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 32, display: "Matthew 27:32" }],
          explanation: "Simon of Cyrene is compelled to carry Jesus' cross.",
        },
        {
          canonical: "The Two Criminals Crucified with Jesus",
          aliases: ["two criminals", "the thieves", "the good thief", "good thief", "the penitent thief", "penitent thief"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 32, verseEnd: 33, display: "Luke 23:32-33" }],
          explanation: "Two criminals are crucified alongside Jesus, one on each side.",
        },
        {
          canonical: "Mary the Wife of Clopas",
          aliases: ["wife of clopas", "clopas"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "John", chapterStart: 19, verseStart: 25, display: "John 19:25" }],
          explanation: "Mary the wife of Clopas is named specifically among the women near the cross.",
        },
        {
          canonical: "Salome",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Mark", chapterStart: 15, verseStart: 40, display: "Mark 15:40" }],
          explanation: "Salome is named among the women watching the crucifixion from a distance.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a river mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any river explicitly named in the biblical text.",
      answers: [
        {
          canonical: "Jordan River",
          aliases: ["jordan"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Joshua", chapterStart: 3, verseStart: 14, verseEnd: 17, display: "Joshua 3:14-17" }],
          explanation: "Israel crosses the Jordan River on dry ground to enter the promised land.",
        },
        {
          canonical: "Euphrates",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 14, display: "Genesis 2:14" }],
          explanation: "The Euphrates is named as one of the four rivers flowing out of Eden.",
        },
        {
          canonical: "Tigris",
          aliases: ["hiddekel"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 14, display: "Genesis 2:14" }],
          explanation: "The Tigris (Hiddekel) is another of the four rivers flowing out of Eden.",
        },
        {
          canonical: "Nile",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 7, verseStart: 20, display: "Exodus 7:20" }],
          explanation: "Egypt's great river — commonly identified as the Nile — turns to blood in the first plague.",
        },
        {
          canonical: "Pishon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 11, display: "Genesis 2:11" }],
          explanation: "The Pishon is named as one of the four rivers flowing out of Eden.",
        },
        {
          canonical: "Gihon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 13, display: "Genesis 2:13" }],
          explanation: "The Gihon is named as one of the four rivers flowing out of Eden.",
        },
        {
          canonical: "Jabbok",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 32, verseStart: 22, display: "Genesis 32:22" }],
          explanation: "Jacob crosses the ford of the Jabbok the night he wrestles with God.",
        },
        {
          canonical: "Kishon",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Judges", chapterStart: 5, verseStart: 21, display: "Judges 5:21" }],
          explanation: "The river Kishon sweeps away Sisera's army in Deborah and Barak's victory.",
        },
        {
          canonical: "Chebar",
          aliases: ["river Chebar","Chebar canal","Kebar","Ezekiel's river"],
          score: 60,
          tier: "veil",
          references: [{ book: "Ezekiel", chapterStart: 1, verseStart: 1, display: "Ezekiel 1:1" }],
          explanation: "Ezekiel sees his opening vision of God's glory among the exiles by the river Chebar.",
        },
        {
          canonical: "Arnon",
          aliases: ["river Arnon","Arnon River","Arnon valley"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 21, verseStart: 13, display: "Numbers 21:13" }],
          explanation: "The Arnon marks the border between the Amorites and Moab as Israel journeys toward the Promised Land.",
        },
        {
          canonical: "Ulai",
          aliases: ["river Ulai","Ulai canal"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Daniel", chapterStart: 8, verseStart: 2, display: "Daniel 8:2" }],
          explanation: "Daniel sees his vision of the ram and the goat while standing beside the river Ulai.",
        },
        {
          canonical: "Abana",
          aliases: ["river abana", "abanah"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 12, display: "2 Kings 5:12" }],
          explanation: "Naaman scorns bathing in the Jordan, protesting that Abana, a river of Damascus, is better.",
        },
        {
          canonical: "Pharpar",
          aliases: ["river pharpar"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 12, display: "2 Kings 5:12" }],
          explanation: "Naaman scorns bathing in the Jordan, protesting that Pharpar, a river of Damascus, is better.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a covenant God made in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any covenant the biblical text explicitly describes God establishing.",
      answers: [
        {
          canonical: "The Noahic Covenant",
          aliases: ["covenant with noah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 9, verseStart: 8, verseEnd: 17, display: "Genesis 9:8-17" }],
          explanation: "God promises Noah never again to destroy the earth by flood, with the rainbow as its sign.",
        },
        {
          canonical: "The Abrahamic Covenant",
          aliases: ["covenant with abraham"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 17, verseStart: 1, verseEnd: 8, display: "Genesis 17:1-8" }],
          explanation: "God promises Abraham numerous descendants and the land of Canaan.",
          exclusions: ["abraham"],
        },
        {
          canonical: "The Mosaic Covenant",
          aliases: ["covenant at sinai"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 24, verseStart: 7, verseEnd: 8, display: "Exodus 24:7-8" }],
          explanation: "Israel agrees to keep the Law given through Moses at Sinai.",
        },
        {
          canonical: "The Davidic Covenant",
          aliases: ["covenant with david"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 7, verseStart: 12, verseEnd: 16, display: "2 Samuel 7:12-16" }],
          explanation: "God promises David that his throne will be established forever.",
        },
        {
          canonical: "The New Covenant",
          aliases: ["new covenant"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 31, verseStart: 31, verseEnd: 34, display: "Jeremiah 31:31-34" }],
          explanation: "God promises a new covenant, writing his law on the hearts of his people.",
        },
        {
          canonical: "The Covenant of Circumcision",
          aliases: ["circumcision"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 17, verseStart: 9, verseEnd: 14, display: "Genesis 17:9-14" }],
          explanation: "Circumcision is given as the sign of God's covenant with Abraham's household.",
        },
        {
          canonical: "The Covenant of Salt",
          aliases: ["covenant of salt", "salt covenant"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 18, verseStart: 19, display: "Numbers 18:19" }],
          explanation: "God describes the priestly offerings as belonging to Aaron under \"a covenant of salt forever.\"",
        },
        {
          canonical: "The Covenant with Phinehas",
          aliases: ["phinehas covenant", "phinehas"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Numbers", chapterStart: 25, verseStart: 10, verseEnd: 13, display: "Numbers 25:10-13" }],
          explanation:
            "God grants Phinehas a covenant of peace and a lasting priesthood for his zeal.",
        },
        {
          canonical: "The Covenant with Levi",
          aliases: ["covenant of Levi","Levitical covenant","covenant of life and peace"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Malachi", chapterStart: 2, verseStart: 4, verseEnd: 5, display: "Malachi 2:4-5" }],
          explanation: "Through Malachi, the LORD recalls his covenant of life and peace made with Levi.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a musician or songwriter in the Bible.",
      instructions: "You get one guess.",
      whatCounts:
        "Any person the biblical text credits with composing or performing music or song, including Psalm titles that attribute authorship.",
      answers: [
        {
          canonical: "David",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 16, verseStart: 23, display: "1 Samuel 16:23" }],
          explanation: "David plays the lyre for Saul and is credited as author of many Psalms.",
        },
        {
          canonical: "Miriam",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 20, verseEnd: 21, display: "Exodus 15:20-21" }],
          explanation: "Miriam leads the women in song and tambourine after crossing the Red Sea.",
        },
        {
          canonical: "Asaph",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Chronicles", chapterStart: 16, verseStart: 5, display: "1 Chronicles 16:5" }],
          explanation: "Asaph is appointed by David as a chief musician and is credited with several Psalms.",
        },
        {
          canonical: "Deborah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 5, verseStart: 1, display: "Judges 5:1" }],
          explanation: "Deborah sings a victory song with Barak after defeating Sisera.",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Song of Solomon", chapterStart: 1, verseStart: 1, display: "Song of Solomon 1:1" }],
          explanation: "Solomon is traditionally credited with the Song of Solomon and some Psalms.",
        },
        {
          canonical: "Heman",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Chronicles", chapterStart: 15, verseStart: 19, display: "1 Chronicles 15:19" }],
          explanation: "Heman is named among the Levitical musicians appointed to play cymbals.",
        },
        {
          canonical: "Ethan the Ezrahite",
          aliases: ["ethan"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Psalms", chapterStart: 89, verseStart: 1, display: "Psalm 89 (title)" }],
          explanation: "Ethan the Ezrahite is named as the author in the title of Psalm 89.",
        },
        {
          canonical: "Jeduthun",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Chronicles", chapterStart: 16, verseStart: 41, verseEnd: 42, display: "1 Chronicles 16:41-42" }],
          explanation: "Jeduthun is named as one of David's chief musicians and appears in several Psalm titles.",
        },
        {
          canonical: "Judith",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judith", chapterStart: 16, display: "Judith 16" }],
          explanation: "After her victory over Holofernes, Judith leads Israel in a song of thanksgiving to God.",
          catholicOnly: true,
        },
        {
          canonical: "Moses",
          aliases: ["Song of Moses","Song of the Sea","Moses sings"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 1, display: "Exodus 15:1" }],
          explanation: "Moses and the Israelites sing the Song of the Sea after the LORD delivers them at the Red Sea.",
        },
        {
          canonical: "Barak",
          aliases: ["Barak son of Abinoam","Song of Deborah and Barak"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 5, verseStart: 1, display: "Judges 5:1" }],
          explanation: "Barak sings alongside Deborah in celebration of Israel's victory over Sisera.",
        },
        {
          canonical: "Sons of Korah",
          aliases: ["Korahites","Korah's sons","sons of Korah psalms"],
          score: 60,
          tier: "veil",
          references: [{ book: "Psalms", chapterStart: 42, verseStart: 1, display: "Psalm 42 (title)" }],
          explanation: "Several psalm titles credit a psalm 'of the Sons of Korah,' a guild of temple musicians.",
        },
        {
          canonical: "Jubal",
          aliases: ["father of musicians","father of the lyre and pipe"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 4, verseStart: 21, display: "Genesis 4:21" }],
          explanation: "Genesis names Jubal as the father of all who play the lyre and pipe.",
        },
        {
          canonical: "Hezekiah",
          aliases: ["writing of Hezekiah","Hezekiah's song"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Isaiah", chapterStart: 38, verseStart: 9, verseEnd: 20, display: "Isaiah 38:9-20" }],
          explanation: "After his recovery from illness, King Hezekiah writes a song of thanksgiving to be sung in the temple.",
        },
      ],
    },
  ],
};
