import type { SeedDay } from "./types";

export const DAY_06: SeedDay = {
  dayNumber: 6,
  date: "2026-09-23",
  scriptureBonus: {
    displayText:
      "We know that all things work together for good for those who love God, for those who are called according to his purpose.",
    book: "Romans",
    chapter: 8,
    verseStart: 28,
    referenceDisplay: "Romans 8:28",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul assures believers that God works even difficult circumstances toward good for those who love him.",
    acceptedBookAliases: ["rom"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person exiled to Babylon.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text describes as taken into exile in Babylon.",
      answers: [
        {
          canonical: "Daniel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 1, verseEnd: 6, display: "Daniel 1:1-6" }],
          explanation: "Daniel is taken to Babylon among the young nobles of Judah.",
        },
        {
          canonical: "Ezekiel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ezekiel", chapterStart: 1, verseStart: 1, verseEnd: 3, display: "Ezekiel 1:1-3" }],
          explanation: "Ezekiel prophesies among the exiles by the river Chebar in Babylon.",
        },
        {
          canonical: "Shadrach",
          aliases: ["hananiah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 6, verseEnd: 7, display: "Daniel 1:6-7" }],
          explanation: "Hananiah, renamed Shadrach in Babylon, is exiled alongside Daniel.",
        },
        {
          canonical: "Meshach",
          aliases: ["mishael"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 6, verseEnd: 7, display: "Daniel 1:6-7" }],
          explanation: "Mishael, renamed Meshach in Babylon, is exiled alongside Daniel.",
        },
        {
          canonical: "Abednego",
          aliases: ["azariah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 6, verseEnd: 7, display: "Daniel 1:6-7" }],
          explanation: "Azariah, renamed Abednego in Babylon, is exiled alongside Daniel.",
        },
        {
          canonical: "Zedekiah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 25, verseStart: 6, verseEnd: 7, display: "2 Kings 25:6-7" }],
          explanation: "King Zedekiah, the last king of Judah, is captured and taken to Babylon.",
        },
        {
          canonical: "Jehoiachin",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 12, verseEnd: 15, display: "2 Kings 24:12-15" }],
          explanation: "King Jehoiachin surrenders to Nebuchadnezzar and is taken into exile in Babylon.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a miracle performed by Jesus.",
      instructions: "You get one guess.",
      whatCounts: "Any miracle the Gospels explicitly attribute to Jesus.",
      answers: [
        {
          canonical: "Turning Water into Wine",
          aliases: ["water into wine", "water to wine"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 2, verseStart: 1, verseEnd: 11, display: "John 2:1-11" }],
          explanation: "Jesus turns water into wine at a wedding in Cana.",
        },
        {
          canonical: "Feeding the 5,000",
          aliases: ["feeding the 5000", "feeding five thousand"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 13, verseEnd: 21, display: "Matthew 14:13-21" }],
          explanation: "Jesus feeds five thousand people with five loaves and two fish.",
        },
        {
          canonical: "Walking on Water",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 22, verseEnd: 33, display: "Matthew 14:22-33" }],
          explanation: "Jesus walks on the surface of the sea toward his disciples' boat.",
        },
        {
          canonical: "Calming the Storm",
          aliases: ["calming the sea", "stilling the storm"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 4, verseStart: 35, verseEnd: 41, display: "Mark 4:35-41" }],
          explanation: "Jesus rebukes a violent storm and the sea becomes calm.",
        },
        {
          canonical: "Healing a Man Born Blind",
          aliases: ["man born blind", "blind man"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 9, verseStart: 1, verseEnd: 7, display: "John 9:1-7" }],
          explanation: "Jesus heals a man who had been blind from birth.",
        },
        {
          canonical: "Healing the Centurion's Servant",
          aliases: ["centurion's servant"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 5, verseEnd: 13, display: "Matthew 8:5-13" }],
          explanation: "Jesus heals a Roman centurion's servant from a distance, at the centurion's request.",
        },
        {
          canonical: "Catch of 153 Fish",
          aliases: ["153 fish"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "John", chapterStart: 21, verseStart: 1, verseEnd: 11, display: "John 21:1-11" }],
          explanation:
            "After his resurrection, Jesus directs the disciples to a miraculous catch of exactly 153 fish.",
        },
        {
          canonical: "Cursing the Fig Tree",
          aliases: ["fig tree"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Mark", chapterStart: 11, verseStart: 12, verseEnd: 14, display: "Mark 11:12-14" }],
          explanation:
            "Jesus curses a fruitless fig tree, which is found withered from the roots the next day.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a food or meal mentioned in the Gospels.",
      instructions: "You get one guess.",
      whatCounts: "Any specific food or meal explicitly mentioned in the four Gospels.",
      answers: [
        {
          canonical: "Bread",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 19, display: "Matthew 14:19" }],
          explanation: "Jesus breaks loaves of bread while feeding the five thousand.",
        },
        {
          canonical: "Fish",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 17, display: "Matthew 14:17" }],
          explanation: "Five loaves and two fish feed the crowd of five thousand.",
        },
        {
          canonical: "Wine",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 2, verseStart: 1, verseEnd: 11, display: "John 2:1-11" }],
          explanation: "Jesus turns water into wine at the wedding in Cana.",
        },
        {
          canonical: "Locusts and Wild Honey",
          aliases: ["locusts", "wild honey"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 4, display: "Matthew 3:4" }],
          explanation: "John the Baptist's diet in the wilderness is locusts and wild honey.",
        },
        {
          canonical: "Passover Lamb",
          aliases: ["passover"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 22, verseStart: 7, verseEnd: 8, display: "Luke 22:7-8" }],
          explanation: "Jesus sends Peter and John to prepare the Passover meal before the Last Supper.",
        },
        {
          canonical: "Barley Loaves",
          aliases: ["barley", "loaves"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 6, verseStart: 9, display: "John 6:9" }],
          explanation: "John's account specifies the boy's loaves in the feeding of the 5,000 were barley loaves.",
        },
        {
          canonical: "Broiled Fish",
          aliases: ["fish", "grilled fish"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 24, verseStart: 42, verseEnd: 43, display: "Luke 24:42-43" }],
          explanation: "The risen Jesus eats a piece of broiled fish in front of his disciples.",
        },
        {
          canonical: "Heads of Grain",
          aliases: ["grain"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 12, verseStart: 1, display: "Matthew 12:1" }],
          explanation: "Jesus' disciples pick heads of grain to eat while walking through the fields on the Sabbath.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a Roman official mentioned in the New Testament.",
      instructions: "You get one guess.",
      whatCounts:
        "Any Roman government or military official (governor, centurion, tribune, client king under Rome, etc.) explicitly named in the New Testament.",
      answers: [
        {
          canonical: "Pontius Pilate",
          aliases: ["pilate"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 2, display: "Matthew 27:2" }],
          explanation: "Pontius Pilate, the Roman governor, presides over Jesus' trial.",
        },
        {
          canonical: "Herod Antipas",
          aliases: ["herod"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 7, display: "Luke 23:7" }],
          explanation: "Herod Antipas, tetrarch of Galilee, questions Jesus before his crucifixion.",
        },
        {
          canonical: "Cornelius",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 1, display: "Acts 10:1" }],
          explanation: "Cornelius, a Roman centurion, becomes one of the first Gentile converts.",
        },
        {
          canonical: "Felix",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 24, verseStart: 1, display: "Acts 24:1" }],
          explanation: "Felix, the Roman governor, hears Paul's case in Caesarea.",
        },
        {
          canonical: "Festus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 25, verseStart: 1, display: "Acts 25:1" }],
          explanation: "Festus succeeds Felix as governor and continues Paul's case.",
        },
        {
          canonical: "Sergius Paulus",
          aliases: ["paulus"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 6, verseEnd: 12, display: "Acts 13:6-12" }],
          explanation: "Sergius Paulus, proconsul of Cyprus, believes after witnessing Paul's ministry.",
        },
        {
          canonical: "Gallio",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 12, verseEnd: 17, display: "Acts 18:12-17" }],
          explanation: "Gallio, proconsul of Achaia, dismisses charges brought against Paul in Corinth.",
        },
        {
          canonical: "Claudius Lysias",
          aliases: ["lysias"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 23, verseStart: 26, display: "Acts 23:26" }],
          explanation:
            "Claudius Lysias, the Roman tribune, is named in his own letter explaining why he is sending Paul to the governor.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a weapon mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any weapon explicitly named in the biblical text.",
      answers: [
        {
          canonical: "Sword",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 24, display: "Genesis 3:24" }],
          explanation: "A flaming sword guards the way to the tree of life after Eden.",
        },
        {
          canonical: "Sling",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 17, verseStart: 40, display: "1 Samuel 17:40" }],
          explanation: "David uses a sling and stone to defeat Goliath.",
        },
        {
          canonical: "Spear",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 18, verseStart: 10, verseEnd: 11, display: "1 Samuel 18:10-11" }],
          explanation: "Saul hurls his spear at David in a jealous rage.",
        },
        {
          canonical: "Bow and Arrow",
          aliases: ["bow", "arrows"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 20, verseStart: 20, display: "1 Samuel 20:20" }],
          explanation: "Jonathan uses a bow and arrows as a secret signal to warn David.",
        },
        {
          canonical: "Ox Goad",
          aliases: ["goad"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 3, verseStart: 31, display: "Judges 3:31" }],
          explanation: "Shamgar strikes down six hundred Philistines with an ox goad.",
        },
        {
          canonical: "Jawbone of a Donkey",
          aliases: ["jawbone", "donkey jawbone"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 15, verseStart: 15, verseEnd: 16, display: "Judges 15:15-16" }],
          explanation: "Samson strikes down a thousand Philistines with the jawbone of a donkey.",
        },
        {
          canonical: "Battle-Axe",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jeremiah", chapterStart: 51, verseStart: 20, display: "Jeremiah 51:20" }],
          explanation: "God calls a nation his \"battle-axe and weapons of war\" in a message against Babylon.",
        },
        {
          canonical: "Goliath's Sword",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 21, verseStart: 9, display: "1 Samuel 21:9" }],
          explanation:
            "David later takes Goliath's own sword, which had been kept behind the ephod at Nob.",
        },
        {
          canonical: "Holofernes' Sword",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judith", chapterStart: 13, display: "Judith 13" }],
          explanation:
            "Judith beheads the enemy general Holofernes with his own sword after he falls into a drunken sleep.",
          catholicOnly: true,
        },
      ],
    },
  ],
};
