import type { SeedDay } from "./types";

export const DAY_13: SeedDay = {
  dayNumber: 13,
  date: "2026-09-30",
  scriptureBonus: {
    displayText: "We love him, because he first loved us.",
    book: "1 John",
    chapter: 4,
    verseStart: 19,
    referenceDisplay: "1 John 4:19",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "John grounds our ability to love in the love God first showed us.",
    acceptedBookAliases: ["1 jn", "1john", "i john"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a prophetess mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any woman the biblical text explicitly calls a prophetess or describes prophesying.",
      answers: [
        {
          canonical: "Miriam",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 20, display: "Exodus 15:20" }],
          explanation: "Miriam the prophetess leads the women of Israel in song after crossing the Red Sea.",
        },
        {
          canonical: "Deborah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Judges", chapterStart: 4, verseStart: 4, display: "Judges 4:4" }],
          explanation: "Deborah, a prophetess, judges Israel and leads it to victory over Sisera.",
        },
        {
          canonical: "Huldah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 22, verseStart: 14, display: "2 Kings 22:14" }],
          explanation: "King Josiah's officials consult the prophetess Huldah after the book of the law is found.",
        },
        {
          canonical: "Anna",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 36, display: "Luke 2:36" }],
          explanation: "Anna the prophetess recognizes the infant Jesus in the temple.",
        },
        {
          canonical: "Philip's Daughters",
          aliases: ["four daughters of philip", "philip's four daughters"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 9, display: "Acts 21:9" }],
          explanation: "Philip the evangelist has four unmarried daughters who prophesy.",
        },
        {
          canonical: "Isaiah's Wife",
          aliases: ["the prophetess (isaiah's wife)"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Isaiah", chapterStart: 8, verseStart: 3, display: "Isaiah 8:3" }],
          explanation: "Isaiah calls his own wife \"the prophetess\" when she bears a symbolically-named son.",
        },
        {
          canonical: "Noadiah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Nehemiah", chapterStart: 6, verseStart: 14, display: "Nehemiah 6:14" }],
          explanation: "Nehemiah prays against the prophetess Noadiah, who tried to intimidate him.",
        },
        {
          canonical: "Jezebel of Thyatira",
          aliases: ["jezebel (revelation)", "that woman jezebel"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 20, display: "Revelation 2:20" }],
          explanation:
            "The risen Christ rebukes the church in Thyatira for tolerating \"that woman Jezebel, who calls herself a prophetess\" — a separate figure from the Old Testament queen of the same name.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a false prophet mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person or group the biblical text explicitly identifies as a false prophet or condemns for false prophecy.",
      answers: [
        {
          canonical: "The Prophets of Baal",
          aliases: ["prophets of baal"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 19, display: "1 Kings 18:19" }],
          explanation: "Elijah confronts 450 prophets of Baal in a contest of fire atop Mount Carmel.",
        },
        {
          canonical: "Bar-Jesus",
          aliases: ["elymas"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 6, verseEnd: 8, display: "Acts 13:6-8" }],
          explanation: "Bar-Jesus, also called Elymas, a Jewish false prophet and sorcerer, is struck blind for opposing Paul.",
        },
        {
          canonical: "Hananiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 28, verseStart: 1, display: "Jeremiah 28:1" }],
          explanation: "Hananiah falsely prophesies Babylon's yoke will soon be broken and dies within the year, as Jeremiah foretold.",
        },
        {
          canonical: "Zedekiah Son of Chenaanah",
          aliases: ["zedekiah the prophet"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 11, display: "1 Kings 22:11" }],
          explanation: "Zedekiah son of Chenaanah makes iron horns and promises Ahab victory, then strikes the true prophet Micaiah.",
        },
        {
          canonical: "The Old Prophet of Bethel",
          aliases: ["old prophet of bethel", "prophet who lied"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 13, verseStart: 11, verseEnd: 19, display: "1 Kings 13:11-19" }],
          explanation: "An old prophet in Bethel lies to a man of God, leading to that man's death for disobeying God's command.",
        },
        {
          canonical: "Shemaiah the Nehelamite",
          aliases: ["shemaiah"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jeremiah", chapterStart: 29, verseStart: 24, verseEnd: 32, display: "Jeremiah 29:24-32" }],
          explanation: "Shemaiah writes from exile urging the priests to silence Jeremiah, earning condemnation for prophesying falsely.",
        },
        {
          canonical: "Balaam",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Peter", chapterStart: 2, verseStart: 15, verseEnd: 16, display: "2 Peter 2:15-16" }],
          explanation:
            "Though he spoke true oracles, Balaam is later condemned as loving \"the wages of wrongdoing\" and named in Revelation as leading Israel astray.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a person whose name was changed by a king or foreign ruler (not by God).",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text describes being given a new name by a human king or ruler.",
      answers: [
        {
          canonical: "Shadrach",
          aliases: ["hananiah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 7, display: "Daniel 1:7" }],
          explanation: "The chief of the eunuchs renames Hananiah as Shadrach in Babylon.",
        },
        {
          canonical: "Meshach",
          aliases: ["mishael"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 7, display: "Daniel 1:7" }],
          explanation: "Mishael is renamed Meshach by the chief of the eunuchs in Babylon.",
        },
        {
          canonical: "Abednego",
          aliases: ["azariah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 7, display: "Daniel 1:7" }],
          explanation: "Azariah is renamed Abednego by the chief of the eunuchs in Babylon.",
        },
        {
          canonical: "Belteshazzar",
          aliases: ["daniel"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 7, display: "Daniel 1:7" }],
          explanation: "Daniel himself is given the Babylonian name Belteshazzar.",
        },
        {
          canonical: "Jehoiakim",
          aliases: ["eliakim"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 34, display: "2 Kings 23:34" }],
          explanation: "Pharaoh Neco renames Eliakim as Jehoiakim after installing him as king of Judah.",
        },
        {
          canonical: "Zedekiah",
          aliases: ["mattaniah"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 17, display: "2 Kings 24:17" }],
          explanation: "Nebuchadnezzar renames Mattaniah as Zedekiah after installing him as king of Judah.",
        },
        {
          canonical: "Zaphenath-Paneah",
          aliases: ["joseph's egyptian name"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 45, display: "Genesis 41:45" }],
          explanation: "Pharaoh gives Joseph the Egyptian name Zaphenath-Paneah upon making him ruler over Egypt.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a musical instrument mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any musical instrument the biblical text explicitly names.",
      answers: [
        {
          canonical: "Harp",
          aliases: ["lyre"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 16, verseStart: 23, display: "1 Samuel 16:23" }],
          explanation: "David plays the harp to soothe King Saul's troubled spirit.",
        },
        {
          canonical: "Trumpet",
          aliases: ["shofar", "ram's horn trumpet"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Joshua", chapterStart: 6, verseStart: 4, display: "Joshua 6:4" }],
          explanation: "Trumpets sound as Israel marches around Jericho before its walls fall.",
        },
        {
          canonical: "Cymbals",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Chronicles", chapterStart: 16, verseStart: 5, display: "1 Chronicles 16:5" }],
          explanation: "Cymbals are among the instruments David appoints Levites to play before the ark.",
        },
        {
          canonical: "Tambourine",
          aliases: ["timbrel"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 20, display: "Exodus 15:20" }],
          explanation: "Miriam takes a tambourine in her hand to lead the women in celebration.",
        },
        {
          canonical: "Flute",
          aliases: ["pipe"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 10, verseStart: 5, display: "1 Samuel 10:5" }],
          explanation: "A group of prophets comes down from the high place with harp, tambourine, flute, and lyre.",
        },
        {
          canonical: "Lute",
          aliases: ["psaltery"],
          score: 60,
          tier: "veil",
          references: [{ book: "Psalms", chapterStart: 33, verseStart: 2, display: "Psalm 33:2" }],
          explanation: "The psalmist calls worshipers to praise the LORD with the lyre and a ten-stringed lute.",
        },
        {
          canonical: "Ten-Stringed Instrument",
          aliases: ["instrument of ten strings"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Psalms", chapterStart: 144, verseStart: 9, display: "Psalm 144:9" }],
          explanation: "The psalmist sings a new song to God with a ten-stringed instrument.",
        },
        {
          canonical: "Sistrum",
          aliases: ["castanets"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 6, verseStart: 5, display: "2 Samuel 6:5" }],
          explanation: "David and Israel celebrate before the ark with sistrums, alongside harps, lyres, tambourines, and cymbals.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a gate of Jerusalem mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named gate of Jerusalem's walls the biblical text explicitly mentions, especially in Nehemiah's account of rebuilding the walls.",
      answers: [
        {
          canonical: "Sheep Gate",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 1, display: "Nehemiah 3:1" }],
          explanation: "The high priest and his fellow priests rebuild the Sheep Gate first.",
        },
        {
          canonical: "Fish Gate",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 3, display: "Nehemiah 3:3" }],
          explanation: "The sons of Hassenaah rebuild the Fish Gate.",
        },
        {
          canonical: "Valley Gate",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 13, display: "Nehemiah 3:13" }],
          explanation: "Hanun and the inhabitants of Zanoah repair the Valley Gate.",
        },
        {
          canonical: "Dung Gate",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 14, display: "Nehemiah 3:14" }],
          explanation: "Malchijah repairs the Dung Gate, through which refuse was carried out of the city.",
        },
        {
          canonical: "Fountain Gate",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 15, display: "Nehemiah 3:15" }],
          explanation: "Shallun repairs the Fountain Gate near the King's Garden.",
        },
        {
          canonical: "Water Gate",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 26, display: "Nehemiah 3:26" }],
          explanation: "The Water Gate is where Ezra later reads the Law aloud to the assembled people.",
        },
        {
          canonical: "Horse Gate",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 28, display: "Nehemiah 3:28" }],
          explanation: "Priests repair the wall above the Horse Gate, each in front of his own house.",
        },
        {
          canonical: "Old Gate",
          aliases: ["jeshanah gate"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 6, display: "Nehemiah 3:6" }],
          explanation: "Joiada and Meshullam repair the Old Gate.",
        },
        {
          canonical: "East Gate",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 29, display: "Nehemiah 3:29" }],
          explanation: "Shemaiah, keeper of the East Gate, repairs the section of wall beside it.",
        },
        {
          canonical: "Muster Gate",
          aliases: ["inspection gate", "hammiphkad gate"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Nehemiah", chapterStart: 3, verseStart: 31, display: "Nehemiah 3:31" }],
          explanation: "Malchijah repairs the wall as far as the Muster Gate, near the corner room.",
        },
      ],
    },
  ],
};
