import type { SeedDay } from "./types";

export const DAY_14: SeedDay = {
  dayNumber: 14,
  date: "2026-10-01",
  scriptureBonus: {
    displayText:
      "He has shown you, man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?",
    book: "Micah",
    chapter: 6,
    verseStart: 8,
    referenceDisplay: "Micah 6:8",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Micah summarizes what genuine devotion to God looks like, over empty ritual.",
    acceptedBookAliases: ["mic"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a pagan or foreign nation/people group mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any foreign nation or people group the biblical text explicitly names.",
      answers: [
        {
          canonical: "Philistines",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 17, verseStart: 1, display: "1 Samuel 17:1" }],
          explanation: "The Philistines, longtime rivals of Israel, gather for battle against Saul, including their champion Goliath.",
        },
        {
          canonical: "Canaanites",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Joshua", chapterStart: 3, verseStart: 10, display: "Joshua 3:10" }],
          explanation: "The Canaanites are among the nations Israel is to drive out of the promised land.",
        },
        {
          canonical: "Moabites",
          aliases: ["moab"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 1, verseStart: 4, display: "Ruth 1:4" }],
          explanation: "Ruth is a Moabite woman who marries into Naomi's family.",
        },
        {
          canonical: "Ammonites",
          aliases: ["ammon"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 11, verseStart: 4, display: "Judges 11:4" }],
          explanation: "The Ammonites make war against Israel, and Jephthah is called to lead against them.",
        },
        {
          canonical: "Amalekites",
          aliases: ["amalek"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 17, verseStart: 8, display: "Exodus 17:8" }],
          explanation: "The Amalekites attack Israel at Rephidim shortly after the exodus.",
        },
        {
          canonical: "Babylonians",
          aliases: ["chaldeans"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 25, verseStart: 1, display: "2 Kings 25:1" }],
          explanation: "The Babylonians besiege and eventually destroy Jerusalem under Nebuchadnezzar.",
        },
        {
          canonical: "Amorites",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 21, verseStart: 21, display: "Numbers 21:21" }],
          explanation: "Israel defeats Sihon, king of the Amorites, on the way to the promised land.",
        },
        {
          canonical: "Hittites",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 23, verseStart: 10, display: "Genesis 23:10" }],
          explanation: "Abraham buys a burial cave from Ephron the Hittite for Sarah.",
        },
        {
          canonical: "Assyrians",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 17, verseStart: 6, display: "2 Kings 17:6" }],
          explanation: "The Assyrians conquer the northern kingdom of Israel and carry its people into exile.",
        },
        {
          canonical: "Midianites",
          aliases: ["midian"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 1, display: "Judges 6:1" }],
          explanation: "The Midianites oppress Israel until Gideon defeats them with three hundred men.",
        },
        {
          canonical: "Jebusites",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 6, display: "2 Samuel 5:6" }],
          explanation: "The Jebusites hold Jerusalem until David captures their stronghold.",
        },
        {
          canonical: "Hivites",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 9, verseStart: 7, display: "Joshua 9:7" }],
          explanation: "The Hivites of Gibeon trick Israel into a peace treaty by disguising themselves as distant travelers.",
        },
        {
          canonical: "Perizzites",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 15, verseStart: 20, display: "Genesis 15:20" }],
          explanation: "The Perizzites are listed among the nations whose land God promises to Abraham's descendants.",
        },
        {
          canonical: "Girgashites",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Deuteronomy", chapterStart: 7, verseStart: 1, display: "Deuteronomy 7:1" }],
          explanation: "The Girgashites are named among the seven nations greater and mightier than Israel that God would drive out.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a type of sacrifice or offering prescribed in the Law of Moses.",
      instructions: "You get one guess.",
      whatCounts: "Any category of offering the Law of Moses (chiefly Leviticus and Numbers) explicitly names.",
      answers: [
        {
          canonical: "Burnt Offering",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Leviticus", chapterStart: 1, verseStart: 3, display: "Leviticus 1:3" }],
          explanation: "The burnt offering is wholly consumed on the altar as an offering to the LORD.",
        },
        {
          canonical: "Sin Offering",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 4, verseStart: 3, display: "Leviticus 4:3" }],
          explanation: "The sin offering atones for unintentional sin, varying by who has sinned.",
        },
        {
          canonical: "Peace Offering",
          aliases: ["fellowship offering"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 3, verseStart: 1, display: "Leviticus 3:1" }],
          explanation: "The peace offering is shared in a meal between the offerer, the priests, and God.",
        },
        {
          canonical: "Grain Offering",
          aliases: ["meal offering"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 2, verseStart: 1, display: "Leviticus 2:1" }],
          explanation: "The grain offering consists of fine flour, oil, and frankincense.",
        },
        {
          canonical: "Guilt Offering",
          aliases: ["trespass offering"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 5, verseStart: 15, display: "Leviticus 5:15" }],
          explanation: "The guilt offering atones for sins requiring restitution, such as misuse of holy things.",
        },
        {
          canonical: "Wave Offering",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Leviticus", chapterStart: 7, verseStart: 30, display: "Leviticus 7:30" }],
          explanation: "The wave offering is presented by waving it before the LORD before the priest's portion is set aside.",
        },
        {
          canonical: "Drink Offering",
          aliases: ["libation"],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 15, verseStart: 5, display: "Numbers 15:5" }],
          explanation: "A drink offering of wine accompanies the burnt or peace offering.",
        },
        {
          canonical: "Freewill Offering",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 22, verseStart: 23, display: "Leviticus 22:23" }],
          explanation: "A freewill offering may be given voluntarily, with slightly looser requirements than a vow offering.",
        },
        {
          canonical: "Thank Offering",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 7, verseStart: 12, display: "Leviticus 7:12" }],
          explanation: "The thank offering is a specific kind of peace offering given in gratitude, eaten the same day it is offered.",
        },
        {
          canonical: "Heave Offering",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Leviticus", chapterStart: 7, verseStart: 14, display: "Leviticus 7:14" }],
          explanation: "A portion of certain offerings is set aside as a heave offering, lifted up and given to the priest.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a feast or festival of Israel.",
      instructions: "You get one guess.",
      whatCounts: "Any named religious feast or festival of Israel the biblical text describes.",
      answers: [
        {
          canonical: "Passover",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 12, verseStart: 11, display: "Exodus 12:11" }],
          explanation: "Passover commemorates the night the LORD passed over Israel's homes in Egypt.",
        },
        {
          canonical: "Feast of Unleavened Bread",
          aliases: ["days of unleavened bread"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 12, verseStart: 17, display: "Exodus 12:17" }],
          explanation: "Israel eats unleavened bread for seven days, commemorating the haste of leaving Egypt.",
        },
        {
          canonical: "Feast of Weeks",
          aliases: ["pentecost", "feast of harvest", "shavuot"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 34, verseStart: 22, display: "Exodus 34:22" }],
          explanation: "The Feast of Weeks, later called Pentecost, celebrates the wheat harvest fifty days after Passover.",
        },
        {
          canonical: "Feast of Tabernacles",
          aliases: ["feast of booths", "sukkot"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 23, verseStart: 34, display: "Leviticus 23:34" }],
          explanation: "Israel dwells in temporary shelters for seven days to remember the wilderness wanderings.",
        },
        {
          canonical: "Day of Atonement",
          aliases: ["yom kippur"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 16, verseStart: 29, verseEnd: 30, display: "Leviticus 16:29-30" }],
          explanation: "On the Day of Atonement, the high priest makes atonement once a year for the sins of Israel.",
        },
        {
          canonical: "Feast of Trumpets",
          aliases: ["rosh hashanah"],
          score: 60,
          tier: "veil",
          references: [{ book: "Leviticus", chapterStart: 23, verseStart: 24, display: "Leviticus 23:24" }],
          explanation: "The Feast of Trumpets is marked with a sacred assembly and trumpet blasts on the first day of the seventh month.",
        },
        {
          canonical: "Purim",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Esther", chapterStart: 9, verseStart: 26, display: "Esther 9:26" }],
          explanation: "Purim commemorates the Jews' deliverance from Haman's plot in the book of Esther.",
        },
        {
          canonical: "Feast of Dedication",
          aliases: ["hanukkah"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "John", chapterStart: 10, verseStart: 22, display: "John 10:22" }],
          explanation: "Jesus is at the temple during the Feast of Dedication, later called Hanukkah.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a unit of ancient weight, length, or volume measurement mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named unit of weight, length, or volume measurement (not currency) the biblical text explicitly mentions.",
      answers: [
        {
          canonical: "Cubit",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 6, verseStart: 15, display: "Genesis 6:15" }],
          explanation: "The ark's dimensions are given in cubits, roughly the length of a forearm.",
        },
        {
          canonical: "Shekel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 23, verseStart: 16, display: "Genesis 23:16" }],
          explanation: "Abraham weighs out four hundred shekels of silver to buy Sarah's burial cave.",
        },
        {
          canonical: "Talent",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 38, verseStart: 24, display: "Exodus 38:24" }],
          explanation: "The gold used for the tabernacle is reckoned in talents, the largest biblical weight unit.",
        },
        {
          canonical: "Span",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 17, verseStart: 4, display: "1 Samuel 17:4" }],
          explanation: "Goliath's height is given as six cubits and a span.",
        },
        {
          canonical: "Handbreadth",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 25, verseStart: 25, display: "Exodus 25:25" }],
          explanation: "The table of showbread has a rim a handbreadth wide.",
        },
        {
          canonical: "Ephah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Ruth", chapterStart: 2, verseStart: 17, display: "Ruth 2:17" }],
          explanation: "Ruth gleans about an ephah of barley in Boaz's field.",
        },
        {
          canonical: "Omer",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 16, verseStart: 16, display: "Exodus 16:16" }],
          explanation: "Each person is to gather an omer of manna per day in the wilderness.",
        },
        {
          canonical: "Hin",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 29, verseStart: 40, display: "Exodus 29:40" }],
          explanation: "A quarter hin of wine is prescribed alongside the daily lamb offering.",
        },
        {
          canonical: "Gerah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 13, display: "Exodus 30:13" }],
          explanation: "The gerah is the smallest weight unit, twenty to a shekel, used for the temple tax.",
        },
        {
          canonical: "Bath",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 7, verseStart: 26, display: "1 Kings 7:26" }],
          explanation: "Solomon's bronze sea holds two thousand baths, a large liquid measure.",
        },
        {
          canonical: "Cor",
          aliases: ["kor"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 4, verseStart: 22, display: "1 Kings 4:22" }],
          explanation: "Solomon's daily provisions include thirty cors of fine flour, the largest biblical dry-volume measure.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a coin or unit of currency mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named coin or monetary unit the biblical text explicitly mentions.",
      answers: [
        {
          canonical: "Denarius",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 22, verseStart: 19, display: "Matthew 22:19" }],
          explanation: "Jesus asks for a denarius, the coin used for the Roman poll tax, bearing Caesar's image.",
        },
        {
          canonical: "Drachma",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 8, display: "Luke 15:8" }],
          explanation: "A woman searches her house for a lost drachma coin in Jesus' parable.",
        },
        {
          canonical: "Stater",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 17, verseStart: 27, display: "Matthew 17:27" }],
          explanation: "Peter finds a stater coin in a fish's mouth, enough to pay the temple tax for himself and Jesus.",
        },
        {
          canonical: "Mite",
          aliases: ["lepton", "widow's mite"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 12, verseStart: 42, display: "Mark 12:42" }],
          explanation: "A poor widow gives two mites, the smallest coins, and Jesus praises her generosity.",
        },
        {
          canonical: "Didrachma",
          aliases: ["two-drachma coin", "half-shekel"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 17, verseStart: 24, display: "Matthew 17:24" }],
          explanation: "Collectors ask Peter whether Jesus pays the didrachma temple tax.",
        },
        {
          canonical: "Thirty Pieces of Silver",
          aliases: ["thirty silver coins"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 15, display: "Matthew 26:15" }],
          explanation: "The chief priests pay Judas thirty pieces of silver to betray Jesus.",
        },
        {
          canonical: "Assarion",
          aliases: ["penny", "copper coin"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 29, display: "Matthew 10:29" }],
          explanation: "Jesus notes that two sparrows are sold for an assarion, a small copper coin, to illustrate God's care.",
        },
      ],
    },
  ],
};
