import type { SeedDay } from "./types";

export const DAY_18: SeedDay = {
  dayNumber: 18,
  date: "2026-10-05",
  scriptureBonus: {
    displayText:
      "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.",
    book: "Philippians",
    chapter: 4,
    verseStart: 6,
    referenceDisplay: "Philippians 4:6",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul encourages the Philippians to bring every worry to God in prayer rather than carrying it alone.",
    acceptedBookAliases: ["phil"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a city of refuge in the Old Testament.",
      instructions: "You get one guess.",
      whatCounts: "Any of the six cities of refuge established for accidental manslayers in Numbers 35 and Joshua 20.",
      answers: [
        {
          canonical: "Kedesh",
          aliases: ["kedesh in galilee"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Joshua", chapterStart: 20, verseStart: 7, display: "Joshua 20:7" }],
          explanation: "Kedesh in Galilee is appointed as a city of refuge in the hill country of Naphtali.",
        },
        {
          canonical: "Hebron",
          aliases: ["kiriath-arba"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Joshua", chapterStart: 20, verseStart: 7, display: "Joshua 20:7" }],
          explanation: "Hebron, already famous as Abraham's burial place, is also appointed a city of refuge in Judah.",
        },
        {
          canonical: "Shechem",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 20, verseStart: 7, display: "Joshua 20:7" }],
          explanation: "Shechem in the hill country of Ephraim is appointed a city of refuge.",
        },
        {
          canonical: "Ramoth in Gilead",
          aliases: ["ramoth-gilead", "ramoth gilead"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joshua", chapterStart: 20, verseStart: 8, display: "Joshua 20:8" }],
          explanation: "Ramoth in Gilead is appointed a city of refuge east of the Jordan in the tribe of Gad.",
        },
        {
          canonical: "Bezer",
          aliases: ["bezer in the wilderness"],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 20, verseStart: 8, display: "Joshua 20:8" }],
          explanation: "Bezer in the wilderness plateau is appointed a city of refuge in the tribe of Reuben.",
        },
        {
          canonical: "Golan",
          aliases: ["golan in bashan"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Joshua", chapterStart: 20, verseStart: 8, display: "Joshua 20:8" }],
          explanation: "Golan in Bashan is appointed a city of refuge in the tribe of Manasseh, east of the Jordan.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a metal mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any metal the biblical text explicitly names.",
      answers: [
        {
          canonical: "Gold",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 11, display: "Genesis 2:11" }],
          explanation: "Genesis describes the land of Havilah, encircled by a river, as a source of gold.",
        },
        {
          canonical: "Silver",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 23, verseStart: 16, display: "Genesis 23:16" }],
          explanation: "Abraham weighs out four hundred shekels of silver to buy the cave of Machpelah.",
        },
        {
          canonical: "Bronze",
          aliases: ["brass"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 27, verseStart: 2, display: "Exodus 27:2" }],
          explanation: "God instructs that the horns of the bronze altar be overlaid with bronze.",
        },
        {
          canonical: "Iron",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Deuteronomy", chapterStart: 8, verseStart: 9, display: "Deuteronomy 8:9" }],
          explanation: "Moses describes the Promised Land as a place whose hills can be mined for iron.",
        },
        {
          canonical: "Tin",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 31, verseStart: 22, display: "Numbers 31:22" }],
          explanation: "Tin is listed among the metals from the Midianite plunder that must pass through fire to be purified.",
        },
        {
          canonical: "Lead",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 10, display: "Exodus 15:10" }],
          explanation: "The Song of the Sea describes Pharaoh's army sinking like lead in the mighty waters.",
        },
        {
          canonical: "Copper",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ezra", chapterStart: 8, verseStart: 27, display: "Ezra 8:27" }],
          explanation: "Ezra records twenty bowls of gold and two vessels of fine polished copper among the temple gifts.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a fruit of the Spirit listed in Galatians.",
      instructions: "You get one guess.",
      whatCounts: "Any of the nine qualities Paul lists in Galatians 5:22-23 as the fruit of the Spirit.",
      answers: [
        {
          canonical: "Love",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 22, display: "Galatians 5:22" }],
          explanation: "Love heads Paul's list of the fruit the Spirit produces in a believer's life.",
        },
        {
          canonical: "Joy",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 22, display: "Galatians 5:22" }],
          explanation: "Joy is named second among the fruit of the Spirit.",
        },
        {
          canonical: "Peace",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 22, display: "Galatians 5:22" }],
          explanation: "Peace is named third among the fruit of the Spirit.",
        },
        {
          canonical: "Patience",
          aliases: ["longsuffering", "forbearance"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 22, display: "Galatians 5:22" }],
          explanation: "Patience, sometimes rendered \"longsuffering,\" is named among the fruit of the Spirit.",
        },
        {
          canonical: "Kindness",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 22, display: "Galatians 5:22" }],
          explanation: "Kindness is named among the fruit of the Spirit.",
        },
        {
          canonical: "Goodness",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 22, display: "Galatians 5:22" }],
          explanation: "Goodness is named among the fruit of the Spirit.",
        },
        {
          canonical: "Faithfulness",
          aliases: ["faith"],
          score: 60,
          tier: "veil",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 22, display: "Galatians 5:22" }],
          explanation: "Faithfulness is named among the fruit of the Spirit.",
        },
        {
          canonical: "Gentleness",
          aliases: ["meekness"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 23, display: "Galatians 5:23" }],
          explanation: "Gentleness, sometimes rendered \"meekness,\" is named among the fruit of the Spirit.",
        },
        {
          canonical: "Self-Control",
          aliases: ["temperance"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Galatians", chapterStart: 5, verseStart: 23, display: "Galatians 5:23" }],
          explanation: "Self-control closes Paul's list of the fruit of the Spirit, against which he says there is no law.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name one of the Ten Commandments by its content.",
      instructions: "You get one guess.",
      whatCounts: "Any of the ten commandments given to Moses, described by its substance (e.g. \"don't steal\" or \"honor your parents\").",
      answers: [
        {
          canonical: "You Shall Have No Other Gods",
          aliases: ["no other gods", "no other gods before me"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 3, display: "Exodus 20:3" }],
          explanation: "The first commandment forbids Israel from having any other gods before the LORD.",
        },
        {
          canonical: "You Shall Not Murder",
          aliases: ["do not murder", "no killing", "do not kill"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 13, display: "Exodus 20:13" }],
          explanation: "The sixth commandment forbids murder.",
        },
        {
          canonical: "You Shall Not Steal",
          aliases: ["do not steal", "no stealing"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 15, display: "Exodus 20:15" }],
          explanation: "The eighth commandment forbids stealing.",
        },
        {
          canonical: "Honor Your Father and Mother",
          aliases: ["honor thy father and mother", "honor your parents"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 12, display: "Exodus 20:12" }],
          explanation: "The fifth commandment instructs Israel to honor their father and mother.",
        },
        {
          canonical: "You Shall Not Commit Adultery",
          aliases: ["do not commit adultery", "no adultery"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 14, display: "Exodus 20:14" }],
          explanation: "The seventh commandment forbids adultery.",
        },
        {
          canonical: "Remember the Sabbath",
          aliases: ["keep the sabbath", "sabbath day holy"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 8, display: "Exodus 20:8" }],
          explanation: "The fourth commandment instructs Israel to remember the Sabbath day and keep it holy.",
        },
        {
          canonical: "You Shall Not Bear False Witness",
          aliases: ["no false witness", "do not lie", "false testimony"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 16, display: "Exodus 20:16" }],
          explanation: "The ninth commandment forbids bearing false witness against your neighbor.",
        },
        {
          canonical: "You Shall Not Make Idols",
          aliases: ["no graven images", "no idols"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 4, display: "Exodus 20:4" }],
          explanation: "The second commandment forbids making carved images to bow down to.",
        },
        {
          canonical: "You Shall Not Covet",
          aliases: ["do not covet", "no coveting"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 17, display: "Exodus 20:17" }],
          explanation: "The tenth commandment forbids coveting anything that belongs to your neighbor.",
        },
        {
          canonical: "You Shall Not Take the LORD's Name in Vain",
          aliases: ["do not take the lords name in vain", "no vain use of gods name"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 7, display: "Exodus 20:7" }],
          explanation: "The third commandment forbids misusing the name of the LORD your God.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a city where Paul preached in a synagogue, according to Acts.",
      instructions: "You get one guess.",
      whatCounts: "Any city the book of Acts explicitly describes Paul teaching or reasoning in a synagogue.",
      answers: [
        {
          canonical: "Damascus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 20, display: "Acts 9:20" }],
          explanation: "Newly converted, Saul immediately proclaims Jesus in the synagogues of Damascus.",
        },
        {
          canonical: "Antioch in Pisidia",
          aliases: ["pisidian antioch"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 14, display: "Acts 13:14" }],
          explanation: "Paul and Barnabas enter the synagogue at Antioch in Pisidia on the Sabbath and Paul preaches there.",
        },
        {
          canonical: "Iconium",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 1, display: "Acts 14:1" }],
          explanation: "Paul and Barnabas go together into the synagogue at Iconium and speak so effectively that a great number believe.",
        },
        {
          canonical: "Thessalonica",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 1, display: "Acts 17:1" }],
          explanation: "Paul reasons with the Jews in the synagogue at Thessalonica from the scriptures for three Sabbaths.",
        },
        {
          canonical: "Berea",
          aliases: ["beroea"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 10, display: "Acts 17:10" }],
          explanation: "Paul and Silas go into the synagogue at Berea, whose Jews examine the scriptures daily to test his teaching.",
        },
        {
          canonical: "Corinth",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 4, display: "Acts 18:4" }],
          explanation: "Paul reasons in the synagogue at Corinth every Sabbath, persuading both Jews and Greeks.",
        },
        {
          canonical: "Athens",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 17, display: "Acts 17:17" }],
          explanation: "Paul reasons in the synagogue at Athens with the Jews and God-fearing Greeks before addressing the Areopagus.",
        },
        {
          canonical: "Ephesus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 19, verseStart: 8, display: "Acts 19:8" }],
          explanation: "Paul speaks boldly in the synagogue at Ephesus for three months, arguing persuasively about the Kingdom of God.",
        },
        {
          canonical: "Salamis",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 5, display: "Acts 13:5" }],
          explanation: "Arriving on Cyprus, Barnabas and Saul proclaim God's word in the Jewish synagogues at Salamis.",
        },
      ],
    },
  ],
};
