import type { SeedDay } from "./types";

export const DAY_12: SeedDay = {
  dayNumber: 12,
  date: "2026-09-29",
  scriptureBonus: {
    displayText: "And whatever you do, work heartily, as for the Lord, and not for men.",
    book: "Colossians",
    chapter: 3,
    verseStart: 23,
    referenceDisplay: "Colossians 3:23",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul instructs believers to bring wholehearted devotion to their everyday work, as service to Christ.",
    acceptedBookAliases: ["col"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a governor or provincial administrator mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly places in a governing/administrative role over a province, region, or nation on behalf of another ruler.",
      answers: [
        {
          canonical: "Pontius Pilate",
          aliases: ["pilate"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 2, display: "Matthew 27:2" }],
          explanation: "Pontius Pilate governs Judea as the Roman prefect who presides over Jesus' trial.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 41, display: "Genesis 41:41" }],
          explanation: "Pharaoh sets Joseph over all the land of Egypt.",
        },
        {
          canonical: "Nehemiah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Nehemiah", chapterStart: 5, verseStart: 14, display: "Nehemiah 5:14" }],
          explanation: "Nehemiah serves as governor of the land of Judah for twelve years.",
        },
        {
          canonical: "Daniel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 2, verseStart: 48, display: "Daniel 2:48" }],
          explanation: "Nebuchadnezzar makes Daniel ruler over the whole province of Babylon.",
        },
        {
          canonical: "Felix",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 24, verseStart: 1, display: "Acts 24:1" }],
          explanation: "Felix, the Roman governor, hears Paul's case in Caesarea.",
        },
        {
          canonical: "Festus",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 25, verseStart: 1, display: "Acts 25:1" }],
          explanation: "Festus succeeds Felix as governor and continues Paul's case.",
        },
        {
          canonical: "Zerubbabel",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Haggai", chapterStart: 1, verseStart: 1, display: "Haggai 1:1" }],
          explanation: "Zerubbabel governs Judah under Persian authority and leads the temple's rebuilding.",
        },
        {
          canonical: "Sheshbazzar",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ezra", chapterStart: 5, verseStart: 14, display: "Ezra 5:14" }],
          explanation: "Sheshbazzar, appointed governor, leads the first group of exiles back to Judah with the temple vessels.",
        },
        {
          canonical: "Tattenai",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ezra", chapterStart: 5, verseStart: 3, verseEnd: 6, display: "Ezra 5:3-6" }],
          explanation: "Tattenai, governor of the province beyond the Euphrates, questions the Jews rebuilding the temple and reports to Darius.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a foreign king or emperor mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any king, emperor, or monarch of a non-Israelite nation the biblical text names.",
      answers: [
        {
          canonical: "Pharaoh",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 5, verseStart: 1, display: "Exodus 5:1" }],
          explanation: "Pharaoh, king of Egypt, refuses to let Israel go until the plagues break his resistance.",
        },
        {
          canonical: "Nebuchadnezzar",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 1, display: "Daniel 1:1" }],
          explanation: "Nebuchadnezzar, king of Babylon, besieges Jerusalem and carries its people into exile.",
        },
        {
          canonical: "Cyrus",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ezra", chapterStart: 1, verseStart: 1, display: "Ezra 1:1" }],
          explanation: "Cyrus of Persia issues the decree allowing the exiles to return and rebuild the temple.",
        },
        {
          canonical: "Ahasuerus",
          aliases: ["xerxes"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Esther", chapterStart: 1, verseStart: 1, display: "Esther 1:1" }],
          explanation: "King Ahasuerus rules from India to Ethiopia and later makes Esther his queen.",
        },
        {
          canonical: "Darius",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 6, verseStart: 1, display: "Daniel 6:1" }],
          explanation: "Darius the Mede sets Daniel over his kingdom and, against his will, has him thrown to the lions.",
        },
        {
          canonical: "Artaxerxes",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Nehemiah", chapterStart: 2, verseStart: 1, display: "Nehemiah 2:1" }],
          explanation: "Artaxerxes, king of Persia, grants Nehemiah leave to rebuild Jerusalem's walls.",
        },
        {
          canonical: "Belshazzar",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Daniel", chapterStart: 5, verseStart: 1, display: "Daniel 5:1" }],
          explanation: "Belshazzar sees handwriting on the wall at his feast the night Babylon falls.",
        },
        {
          canonical: "Sennacherib",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 18, verseStart: 13, display: "2 Kings 18:13" }],
          explanation: "Sennacherib of Assyria invades Judah and besieges Jerusalem under Hezekiah.",
        },
        {
          canonical: "Hazael",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 8, verseStart: 13, verseEnd: 15, display: "2 Kings 8:13-15" }],
          explanation: "Hazael, anointed by Elisha to become king of Aram, murders his master Ben-Hadad to take the throne.",
        },
        {
          canonical: "Ben-Hadad",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 20, verseStart: 1, display: "1 Kings 20:1" }],
          explanation: "Ben-Hadad of Aram besieges Samaria but is defeated by Ahab's forces.",
        },
        {
          canonical: "Tiglath-Pileser",
          aliases: ["tiglath-pileser iii", "pul"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 29, display: "2 Kings 15:29" }],
          explanation: "Tiglath-Pileser of Assyria carries off portions of Israel's northern territory.",
        },
        {
          canonical: "Shalmaneser",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 17, verseStart: 3, display: "2 Kings 17:3" }],
          explanation: "Shalmaneser of Assyria besieges Samaria, ending the northern kingdom of Israel.",
        },
        {
          canonical: "Antiochus",
          aliases: ["antiochus iv", "antiochus epiphanes"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Maccabees", chapterStart: 1, verseStart: 10, display: "1 Maccabees 1:10" }],
          explanation: "Antiochus IV Epiphanes desecrates the Jerusalem temple, sparking the Maccabean revolt.",
          catholicOnly: true,
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a member of Herod's family mentioned in the New Testament.",
      instructions: "You get one guess.",
      whatCounts: "Any member of the Herodian dynasty the biblical text names.",
      answers: [
        {
          canonical: "Herod the Great",
          aliases: ["herod"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 2, verseStart: 1, display: "Matthew 2:1" }],
          explanation: "Herod the Great rules Judea when the Magi come seeking the newborn king of the Jews.",
        },
        {
          canonical: "Herod Antipas",
          aliases: ["herod the tetrarch"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 7, display: "Luke 23:7" }],
          explanation: "Herod Antipas, tetrarch of Galilee and son of Herod the Great, questions Jesus before his crucifixion.",
        },
        {
          canonical: "Herodias",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 3, display: "Matthew 14:3" }],
          explanation: "Herodias, married to her brother-in-law Herod Antipas, orchestrates John the Baptist's execution.",
        },
        {
          canonical: "Herod Agrippa I",
          aliases: ["agrippa i", "herod the king"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 1, verseEnd: 2, display: "Acts 12:1-2" }],
          explanation: "Herod Agrippa I has James, brother of John, put to death and later dies struck by an angel.",
        },
        {
          canonical: "Herod Agrippa II",
          aliases: ["king agrippa", "agrippa ii"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 25, verseStart: 13, display: "Acts 25:13" }],
          explanation: "King Agrippa II hears Paul's defense and tells him he has almost persuaded him to become a Christian.",
        },
        {
          canonical: "Philip the Tetrarch",
          aliases: ["philip"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 1, display: "Luke 3:1" }],
          explanation: "Philip, another son of Herod the Great, is tetrarch of the region of Ituraea and Trachonitis.",
        },
        {
          canonical: "Archelaus",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 2, verseStart: 22, display: "Matthew 2:22" }],
          explanation: "Fearing Archelaus, who reigns over Judea after his father Herod's death, Joseph withdraws to Galilee instead.",
        },
        {
          canonical: "Bernice",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 25, verseStart: 13, display: "Acts 25:13" }],
          explanation: "Bernice, sister of Agrippa II, is present with him when Paul makes his defense before Festus.",
        },
        {
          canonical: "Drusilla",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 24, verseStart: 24, display: "Acts 24:24" }],
          explanation: "Drusilla, Felix's Jewish wife and Agrippa's sister, listens with him as Paul speaks about the faith.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a cupbearer, eunuch, or personal court servant of a king mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text places in personal service to a king's household — cupbearer, eunuch, steward, or similar.",
      answers: [
        {
          canonical: "Nehemiah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Nehemiah", chapterStart: 1, verseStart: 11, display: "Nehemiah 1:11" }],
          explanation: "Nehemiah serves as cupbearer to King Artaxerxes of Persia before returning to rebuild Jerusalem.",
        },
        {
          canonical: "Potiphar",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 39, verseStart: 1, display: "Genesis 39:1" }],
          explanation: "Potiphar, captain of Pharaoh's guard, buys Joseph and puts him in charge of his household.",
        },
        {
          canonical: "Ebed-Melech",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Jeremiah", chapterStart: 38, verseStart: 7, verseEnd: 13, display: "Jeremiah 38:7-13" }],
          explanation: "Ebed-Melech, an Ethiopian eunuch in the king's house, rescues Jeremiah from a muddy cistern.",
        },
        {
          canonical: "Hegai",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 8, verseEnd: 9, display: "Esther 2:8-9" }],
          explanation: "Hegai, the king's eunuch in charge of the women, immediately favors Esther.",
        },
        {
          canonical: "Ashpenaz",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 3, display: "Daniel 1:3" }],
          explanation: "Ashpenaz, chief of Nebuchadnezzar's eunuchs, is charged with training Daniel and his friends.",
        },
        {
          canonical: "Obadiah",
          aliases: ["ahab's steward"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 3, verseEnd: 4, display: "1 Kings 18:3-4" }],
          explanation: "Obadiah, in charge of Ahab's palace, secretly hides a hundred prophets from Jezebel.",
        },
        {
          canonical: "Shebna",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Isaiah", chapterStart: 22, verseStart: 15, display: "Isaiah 22:15" }],
          explanation: "Isaiah rebukes Shebna, steward over the king's household, and pronounces he will be replaced by Eliakim.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a person healed or raised from the dead by one of Jesus' apostles (not by Jesus himself).",
      instructions: "You get one guess.",
      whatCounts: "Any person the book of Acts explicitly describes an apostle healing or raising.",
      answers: [
        {
          canonical: "The Lame Beggar at the Temple Gate",
          aliases: ["lame beggar", "man at the beautiful gate", "beggar at the gate"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 3, verseStart: 6, verseEnd: 8, display: "Acts 3:6-8" }],
          explanation: "Peter and John heal a man lame from birth at the temple's Beautiful Gate.",
        },
        {
          canonical: "Aeneas",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 32, verseEnd: 35, display: "Acts 9:32-35" }],
          explanation: "Peter heals Aeneas, paralyzed and bedridden for eight years, in Lydda.",
        },
        {
          canonical: "Tabitha",
          aliases: ["dorcas"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 36, verseEnd: 41, display: "Acts 9:36-41" }],
          explanation: "Peter raises Tabitha (also called Dorcas) back to life in Joppa.",
        },
        {
          canonical: "The Crippled Man at Lystra",
          aliases: ["cripple at lystra", "lame man at lystra"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 8, verseEnd: 10, display: "Acts 14:8-10" }],
          explanation: "Paul heals a man in Lystra who had been lame from birth.",
        },
        {
          canonical: "Eutychus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 9, verseEnd: 12, display: "Acts 20:9-12" }],
          explanation: "Paul restores Eutychus to life after the young man falls asleep and drops from a third-story window.",
        },
        {
          canonical: "The Slave Girl with a Spirit of Divination",
          aliases: ["slave girl", "fortune telling slave girl"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 16, verseEnd: 18, display: "Acts 16:16-18" }],
          explanation: "Paul casts a spirit of divination out of an enslaved girl in Philippi.",
        },
        {
          canonical: "Publius's Father",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 8, display: "Acts 28:8" }],
          explanation: "Paul heals the feverish, dysentery-stricken father of Publius, chief man of Malta.",
        },
      ],
    },
  ],
};
