import type { SeedDay } from "./types";

export const DAY_11: SeedDay = {
  dayNumber: 11,
  date: "2026-09-28",
  scriptureBonus: {
    displayText: "For God gave us a spirit not of fear, but of power, love, and self-control.",
    book: "2 Timothy",
    chapter: 1,
    verseStart: 7,
    referenceDisplay: "2 Timothy 1:7",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul encourages Timothy to hold fast to his calling rather than shrink back in fear.",
    acceptedBookAliases: ["2 tim", "2tim", "ii timothy"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name an angel (by name or title/class) mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific angel named, or class of angelic being explicitly named, in the biblical text.",
      answers: [
        {
          canonical: "Gabriel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 26, verseEnd: 27, display: "Luke 1:26-27" }],
          explanation: "Gabriel announces to Mary that she will bear Jesus; he also appears to Zechariah and Daniel.",
        },
        {
          canonical: "Michael",
          aliases: ["archangel michael"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Jude", chapterStart: 1, verseStart: 9, display: "Jude 1:9" }],
          explanation: "Michael the archangel disputes with the devil over the body of Moses and fights the dragon in Revelation.",
        },
        {
          canonical: "Cherubim",
          aliases: ["cherub", "cherubs"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 24, display: "Genesis 3:24" }],
          explanation: "Cherubim guard the way to the tree of life after Eden and are depicted atop the Ark of the Covenant.",
        },
        {
          canonical: "Seraphim",
          aliases: ["seraph", "seraphs"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Isaiah", chapterStart: 6, verseStart: 2, verseEnd: 3, display: "Isaiah 6:2-3" }],
          explanation: "Six-winged seraphim surround God's throne in Isaiah's temple vision, calling out \"holy, holy, holy.\"",
        },
        {
          canonical: "Abaddon",
          aliases: ["apollyon", "the destroyer"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 9, verseStart: 11, display: "Revelation 9:11" }],
          explanation: "The angel of the abyss is named Abaddon in Hebrew and Apollyon in Greek, both meaning \"destroyer.\"",
        },
        {
          canonical: "Raphael",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Tobit", chapterStart: 12, verseStart: 15, display: "Tobit 12:15" }],
          explanation: "Raphael identifies himself as one of the seven holy angels who stand before God, guiding Tobias throughout the book.",
          catholicOnly: true,
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a foreign god or idol mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any false god, idol, or pagan deity the biblical text names by name.",
      answers: [
        {
          canonical: "Baal",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 21, display: "1 Kings 18:21" }],
          explanation: "Baal, the Canaanite storm god, is challenged by Elijah at Mount Carmel.",
        },
        {
          canonical: "Asherah",
          aliases: ["asherah pole", "asherah poles"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 25, display: "Judges 6:25" }],
          explanation: "Asherah, a Canaanite goddess, is worshiped through wooden poles that faithful kings repeatedly tear down.",
        },
        {
          canonical: "Dagon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 5, verseStart: 2, verseEnd: 4, display: "1 Samuel 5:2-4" }],
          explanation: "The Philistine god Dagon's idol falls face-down before the captured Ark of the Covenant.",
        },
        {
          canonical: "Artemis",
          aliases: ["diana"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 19, verseStart: 28, display: "Acts 19:28" }],
          explanation: "Silversmiths in Ephesus riot in defense of \"Artemis of the Ephesians\" after Paul's preaching hurts their idol trade.",
        },
        {
          canonical: "Molech",
          aliases: ["moloch"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 18, verseStart: 21, display: "Leviticus 18:21" }],
          explanation: "Israel is forbidden from giving children to Molech, a god associated with child sacrifice.",
        },
        {
          canonical: "Ashtoreth",
          aliases: ["astarte", "ashtaroth"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 11, verseStart: 5, display: "1 Kings 11:5" }],
          explanation: "Solomon follows Ashtoreth, goddess of the Sidonians, in his old age.",
        },
        {
          canonical: "Hermes",
          aliases: ["mercury"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 12, display: "Acts 14:12" }],
          explanation: "The Lystrans call Paul \"Hermes\" because he was the chief speaker, and Barnabas \"Zeus.\"",
        },
        {
          canonical: "Chemosh",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 11, verseStart: 7, display: "1 Kings 11:7" }],
          explanation: "Chemosh, the national god of Moab, gets a high place built for him by Solomon.",
        },
        {
          canonical: "Rimmon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 18, display: "2 Kings 5:18" }],
          explanation: "Naaman asks forgiveness for having to bow in the temple of Rimmon while assisting his king.",
        },
        {
          canonical: "Zeus",
          aliases: ["jupiter"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 12, verseEnd: 13, display: "Acts 14:12-13" }],
          explanation: "The priest of Zeus at Lystra brings oxen to sacrifice to Paul and Barnabas, mistaken for Zeus and Hermes.",
        },
        {
          canonical: "Nisroch",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 19, verseStart: 37, display: "2 Kings 19:37" }],
          explanation: "Sennacherib of Assyria is assassinated by his own sons while worshiping in the house of his god Nisroch.",
        },
        {
          canonical: "Marduk",
          aliases: ["merodach", "bel-merodach"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jeremiah", chapterStart: 50, verseStart: 2, display: "Jeremiah 50:2" }],
          explanation: "Jeremiah declares that Merodach, Babylon's chief god, is dismayed and put to shame.",
        },
        {
          canonical: "Tammuz",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ezekiel", chapterStart: 8, verseStart: 14, display: "Ezekiel 8:14" }],
          explanation: "Ezekiel sees women at the temple gate weeping for Tammuz, a Mesopotamian fertility god.",
        },
        {
          canonical: "Bel",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Bel and the Dragon", chapterStart: 1, verseStart: 3, display: "Bel and the Dragon 1:3" }],
          explanation: "Daniel exposes the priests of Bel, who secretly eat the idol's offerings themselves, as fraud.",
          catholicOnly: true,
        },
        {
          canonical: "Nehushtan",
          aliases: ["bronze serpent", "the bronze snake"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 18, verseStart: 4, display: "2 Kings 18:4" }],
          explanation:
            "King Hezekiah destroys the bronze serpent Moses made in the wilderness after it had become an idol called Nehushtan.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a title or name used for Jesus in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any name or title the biblical text applies to Jesus.",
      answers: [
        {
          canonical: "Christ",
          aliases: ["messiah", "the messiah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 16, verseStart: 16, display: "Matthew 16:16" }],
          explanation: "Peter confesses Jesus as \"the Christ, the Son of the living God.\"",
        },
        {
          canonical: "Son of God",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 17, display: "Matthew 3:17" }],
          explanation: "A voice from heaven declares Jesus \"my beloved Son\" at his baptism.",
        },
        {
          canonical: "Son of Man",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 20, display: "Matthew 8:20" }],
          explanation: "Jesus repeatedly refers to himself as \"the Son of Man\" throughout the Gospels.",
        },
        {
          canonical: "Good Shepherd",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 10, verseStart: 11, display: "John 10:11" }],
          explanation: "Jesus declares, \"I am the good shepherd. The good shepherd lays down his life for the sheep.\"",
        },
        {
          canonical: "Lamb of God",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 1, verseStart: 29, display: "John 1:29" }],
          explanation: "John the Baptist points to Jesus and says, \"Behold, the Lamb of God, who takes away the sin of the world!\"",
        },
        {
          canonical: "Immanuel",
          aliases: ["emmanuel"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 23, display: "Matthew 1:23" }],
          explanation: "Matthew applies Isaiah's prophecy of a child called Immanuel, \"God with us,\" to Jesus' birth.",
        },
        {
          canonical: "Alpha and Omega",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 22, verseStart: 13, display: "Revelation 22:13" }],
          explanation: "The risen Christ declares, \"I am the Alpha and the Omega, the First and the Last, the Beginning and the End.\"",
        },
        {
          canonical: "The Word",
          aliases: ["logos", "the word of god"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 1, verseStart: 1, display: "John 1:1" }],
          explanation: "John opens his Gospel calling Jesus \"the Word,\" who was with God and was God from the beginning.",
        },
        {
          canonical: "Light of the World",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 8, verseStart: 12, display: "John 8:12" }],
          explanation: "Jesus proclaims, \"I am the light of the world. He who follows me will not walk in the darkness.\"",
        },
        {
          canonical: "Bread of Life",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 6, verseStart: 35, display: "John 6:35" }],
          explanation: "Jesus tells the crowd, \"I am the bread of life. Whoever comes to me will not be hungry.\"",
        },
        {
          canonical: "Prince of Peace",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Isaiah", chapterStart: 9, verseStart: 6, display: "Isaiah 9:6" }],
          explanation: "Isaiah's messianic prophecy names the coming child \"Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.\"",
        },
        {
          canonical: "Lion of the Tribe of Judah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 5, verseStart: 5, display: "Revelation 5:5" }],
          explanation: "An elder tells John that \"the Lion of the tribe of Judah, the Root of David\" has overcome to open the scroll.",
        },
        {
          canonical: "Root of David",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 22, verseStart: 16, display: "Revelation 22:16" }],
          explanation: "Jesus identifies himself as \"the root and the offspring of David, the bright, morning star.\"",
        },
        {
          canonical: "Faithful Witness",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 1, verseStart: 5, display: "Revelation 1:5" }],
          explanation: "John greets his readers from Jesus Christ, \"the faithful witness, the firstborn of the dead.\"",
        },
        {
          canonical: "Rabboni",
          aliases: ["rabbouni"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "John", chapterStart: 20, verseStart: 16, display: "John 20:16" }],
          explanation:
            "Recognizing the risen Jesus, Mary Magdalene cries out \"Rabboni!\" — Aramaic for \"my great teacher.\"",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a title used for Satan or the devil in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any name or title the biblical text applies to Satan.",
      answers: [
        {
          canonical: "Satan",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Job", chapterStart: 1, verseStart: 6, display: "Job 1:6" }],
          explanation: "Satan appears among the sons of God to accuse Job before the LORD.",
        },
        {
          canonical: "The Devil",
          aliases: ["devil"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 1, display: "Matthew 4:1" }],
          explanation: "Jesus is led into the wilderness to be tempted by the devil.",
        },
        {
          canonical: "The Serpent",
          aliases: ["that old serpent", "ancient serpent"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 12, verseStart: 9, display: "Revelation 12:9" }],
          explanation: "Revelation identifies \"the great dragon\" as \"the old serpent, called the devil and Satan.\"",
        },
        {
          canonical: "The Dragon",
          aliases: ["great dragon"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 12, verseStart: 9, display: "Revelation 12:9" }],
          explanation: "John sees \"the great dragon\" thrown down from heaven with his angels.",
        },
        {
          canonical: "The Tempter",
          aliases: ["tempter"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 3, display: "Matthew 4:3" }],
          explanation: "\"The tempter\" comes to Jesus in the wilderness, urging him to turn stones to bread.",
        },
        {
          canonical: "Beelzebub",
          aliases: ["beelzebul", "prince of demons"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 12, verseStart: 24, display: "Matthew 12:24" }],
          explanation: "Pharisees accuse Jesus of casting out demons \"by Beelzebul, the prince of the demons.\"",
        },
        {
          canonical: "Prince of This World",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 12, verseStart: 31, display: "John 12:31" }],
          explanation: "Jesus says \"the prince of this world\" will now be cast out, referring to Satan.",
        },
        {
          canonical: "The Accuser",
          aliases: ["accuser of our brothers"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 12, verseStart: 10, display: "Revelation 12:10" }],
          explanation: "A voice in heaven celebrates that \"the accuser of our brothers has been thrown down.\"",
        },
        {
          canonical: "Father of Lies",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 8, verseStart: 44, display: "John 8:44" }],
          explanation: "Jesus tells his opponents that the devil \"is a liar, and the father of it.\"",
        },
        {
          canonical: "Belial",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Corinthians", chapterStart: 6, verseStart: 15, display: "2 Corinthians 6:15" }],
          explanation: "Paul asks, \"What agreement has Christ with Belial?\" using a name associated with Satan.",
        },
        {
          canonical: "Shining One, Son of the Dawn",
          aliases: ["lucifer", "shining one", "son of the dawn", "morning star"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Isaiah", chapterStart: 14, verseStart: 12, display: "Isaiah 14:12" }],
          explanation:
            "Isaiah's taunt against the king of Babylon — \"How you have fallen from heaven, shining one, son of the dawn!\" — is traditionally read (via the Latin \"Lucifer\") as describing Satan's fall.",
          inclusionNotes: "The WEB text used in this game renders the Hebrew directly rather than using the Latin-derived name \"Lucifer,\" but that name is accepted as the common label for this passage.",
        },
        {
          canonical: "The God of This Age",
          aliases: ["god of this world"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Corinthians", chapterStart: 4, verseStart: 4, display: "2 Corinthians 4:4" }],
          explanation: "Paul writes that \"the god of this age has blinded the minds of the unbelieving,\" referring to Satan.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a title used for the Holy Spirit in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any name or title the biblical text applies to the Holy Spirit.",
      answers: [
        {
          canonical: "Holy Spirit",
          aliases: ["the holy spirit"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 2, verseStart: 4, display: "Acts 2:4" }],
          explanation: "The disciples are filled with the Holy Spirit at Pentecost.",
        },
        {
          canonical: "Spirit of God",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 2, display: "Genesis 1:2" }],
          explanation: "The Spirit of God hovers over the waters at creation.",
        },
        {
          canonical: "Helper",
          aliases: ["comforter", "counselor", "advocate", "paraclete"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 14, verseStart: 16, display: "John 14:16" }],
          explanation: "Jesus promises the Father will give \"another Helper,\" traditionally rendered Comforter or Counselor.",
        },
        {
          canonical: "Spirit of Truth",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 14, verseStart: 17, display: "John 14:17" }],
          explanation: "Jesus describes the coming Helper as \"the Spirit of truth.\"",
        },
        {
          canonical: "Spirit of Christ",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Romans", chapterStart: 8, verseStart: 9, display: "Romans 8:9" }],
          explanation: "Paul writes that anyone without \"the Spirit of Christ\" does not belong to him.",
        },
        {
          canonical: "Spirit of Grace",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Hebrews", chapterStart: 10, verseStart: 29, display: "Hebrews 10:29" }],
          explanation: "Hebrews warns against insulting \"the Spirit of grace.\"",
        },
        {
          canonical: "Spirit of Wisdom",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ephesians", chapterStart: 1, verseStart: 17, display: "Ephesians 1:17" }],
          explanation: "Paul prays that God would give the Ephesians \"a spirit of wisdom and revelation.\"",
        },
        {
          canonical: "Spirit of Adoption",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Romans", chapterStart: 8, verseStart: 15, display: "Romans 8:15" }],
          explanation: "Paul says believers did not receive a spirit of bondage but \"the Spirit of adoption, by whom we cry, 'Abba! Father!'\"",
        },
      ],
    },
  ],
};
