import type { SeedDay } from "./types";

export const DAY_16: SeedDay = {
  dayNumber: 16,
  date: "2026-10-03",
  scriptureBonus: {
    displayText:
      "but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.",
    book: "Isaiah",
    chapter: 40,
    verseStart: 31,
    referenceDisplay: "Isaiah 40:31",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Isaiah promises renewed strength to the weary who trust in God, closing a passage on God's incomparable power.",
    acceptedBookAliases: ["isa"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a color mentioned in a biblical description.",
      instructions: "You get one guess.",
      whatCounts: "Any specific color the biblical text uses to describe something.",
      answers: [
        {
          canonical: "White",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 7, verseStart: 9, display: "Daniel 7:9" }],
          explanation: "Daniel describes the Ancient of Days' clothing as white as snow.",
        },
        {
          canonical: "Purple",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 15, verseStart: 17, display: "Mark 15:17" }],
          explanation: "Soldiers mockingly dress Jesus in a purple robe before his crucifixion.",
        },
        {
          canonical: "Scarlet",
          aliases: ["crimson"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 2, verseStart: 18, display: "Joshua 2:18" }],
          explanation: "Rahab ties a scarlet cord in her window as the sign for the spies to spare her household.",
        },
        {
          canonical: "Blue",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 15, verseStart: 38, display: "Numbers 15:38" }],
          explanation: "The Israelites are commanded to put a blue cord on the tassels of their garments.",
        },
        {
          canonical: "Red",
          aliases: ["reddish"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 25, display: "Genesis 25:25" }],
          explanation: "Esau is born red and covered with hair like a hairy garment.",
        },
        {
          canonical: "Black",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 6, verseStart: 12, display: "Revelation 6:12" }],
          explanation: "At the opening of the sixth seal, the sun becomes black as sackcloth made of hair.",
        },
        {
          canonical: "Green",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Psalms", chapterStart: 23, verseStart: 2, display: "Psalm 23:2" }],
          explanation: "The Lord makes the psalmist lie down in green pastures.",
        },
        {
          canonical: "Gray",
          aliases: ["grey", "gray hair"],
          score: 60,
          tier: "veil",
          references: [{ book: "Proverbs", chapterStart: 20, verseStart: 29, display: "Proverbs 20:29" }],
          explanation: "Proverbs calls gray hair the splendor of old men.",
        },
        {
          canonical: "Dappled",
          aliases: ["grizzled", "speckled horses"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Zechariah", chapterStart: 6, verseStart: 3, display: "Zechariah 6:3" }],
          explanation: "Zechariah's vision of four chariots includes horses that are red, black, white, and dappled gray.",
        },
        {
          canonical: "Vermilion",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ezekiel", chapterStart: 23, verseStart: 14, display: "Ezekiel 23:14" }],
          explanation: "Ezekiel describes images of Chaldeans painted in vermilion on a wall.",
        },
        {
          canonical: "Amber",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Ezekiel", chapterStart: 1, verseStart: 4, display: "Ezekiel 1:4" }],
          explanation: "Ezekiel describes the brightness at the center of his opening vision as the color of amber.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a valley mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any valley the biblical text names or clearly identifies by a specific name.",
      answers: [
        {
          canonical: "Valley of Elah",
          aliases: ["elah", "valley of the terebinth"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 17, verseStart: 2, display: "1 Samuel 17:2" }],
          explanation: "David faces Goliath in the Valley of Elah while the armies of Israel and the Philistines look on.",
        },
        {
          canonical: "Kidron Valley",
          aliases: ["kidron", "brook kidron"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 18, verseStart: 1, display: "John 18:1" }],
          explanation: "Jesus crosses the Kidron Valley with his disciples on the way to Gethsemane.",
        },
        {
          canonical: "Valley of Hinnom",
          aliases: ["hinnom", "gehenna", "ge hinnom"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 15, verseStart: 8, display: "Joshua 15:8" }],
          explanation: "This valley south of Jerusalem later lends its name (Gehenna) to Jesus' warnings about hell.",
        },
        {
          canonical: "Valley of Dry Bones",
          aliases: ["dry bones", "valley of bones"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ezekiel", chapterStart: 37, verseStart: 1, display: "Ezekiel 37:1" }],
          explanation: "The Spirit sets Ezekiel down in a valley full of dry bones and asks if they can live again.",
        },
        {
          canonical: "Valley of Jehoshaphat",
          aliases: ["jehoshaphat"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joel", chapterStart: 3, verseStart: 2, display: "Joel 3:2" }],
          explanation: "Joel names this valley as the place where God will gather and judge the nations.",
        },
        {
          canonical: "Valley of Achor",
          aliases: ["achor", "valley of trouble"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joshua", chapterStart: 7, verseStart: 24, verseEnd: 26, display: "Joshua 7:24-26" }],
          explanation: "Achan is stoned here after taking devoted plunder from Jericho, giving the valley its name.",
        },
        {
          canonical: "Valley of Sorek",
          aliases: ["sorek"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 16, verseStart: 4, display: "Judges 16:4" }],
          explanation: "Samson falls in love with Delilah, who lives in the Valley of Sorek.",
        },
        {
          canonical: "Valley of Salt",
          aliases: ["salt valley"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 8, verseStart: 13, display: "2 Samuel 8:13" }],
          explanation: "David strikes down the Edomites in the Valley of Salt, as Amaziah later does as well.",
        },
        {
          canonical: "Valley of Baca",
          aliases: ["baca"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Psalms", chapterStart: 84, verseStart: 6, display: "Psalm 84:6" }],
          explanation: "The psalmist describes pilgrims passing through this dry valley and turning it into springs.",
        },
        {
          canonical: "Valley of Shaveh",
          aliases: ["shaveh", "kings valley", "king's valley"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 14, verseStart: 17, display: "Genesis 14:17" }],
          explanation: "The king of Sodom meets Abram in this valley after Abram's victory over the eastern kings.",
        },
        {
          canonical: "Valley of Rephaim",
          aliases: ["rephaim"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 18, display: "2 Samuel 5:18" }],
          explanation: "The Philistines spread out in the Valley of Rephaim to attack David after he becomes king.",
        },
        {
          canonical: "Valley of Zeboim",
          aliases: ["zeboim"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 13, verseStart: 18, display: "1 Samuel 13:18" }],
          explanation: "One of the Philistine raiding companies heads toward this valley during Saul's war with the Philistines.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a boat or ship mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific boat, ship, or vessel the biblical text explicitly describes.",
      answers: [
        {
          canonical: "Noah's Ark",
          aliases: ["the ark", "noahs ark"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 6, verseStart: 14, display: "Genesis 6:14" }],
          explanation: "God instructs Noah to build an ark of gopher wood to survive the flood.",
        },
        {
          canonical: "The Sea of Galilee Fishing Boat",
          aliases: ["jesus boat", "disciples boat", "simons boat"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 5, verseStart: 3, display: "Luke 5:3" }],
          explanation: "Jesus teaches the crowds from Simon's fishing boat, pushed out a little from the shore.",
        },
        {
          canonical: "Jonah's Ship",
          aliases: ["ship to tarshish"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Jonah", chapterStart: 1, verseStart: 3, display: "Jonah 1:3" }],
          explanation: "Jonah boards a ship bound for Tarshish to flee from the LORD's call to Nineveh.",
        },
        {
          canonical: "Paul's Ship from Caesarea",
          aliases: ["adramyttian ship", "ship of adramyttium"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 2, display: "Acts 27:2" }],
          explanation: "Paul is put aboard a ship of Adramyttium to begin the voyage toward Rome.",
        },
        {
          canonical: "The Alexandrian Grain Ship",
          aliases: ["alexandrian ship", "ship of alexandria"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 6, display: "Acts 27:6" }],
          explanation: "At Myra, the centurion transfers Paul and the other prisoners onto a ship of Alexandria sailing for Italy.",
        },
        {
          canonical: "Solomon's Ships at Ezion-geber",
          aliases: ["ezion geber ships", "solomons navy"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 9, verseStart: 26, display: "1 Kings 9:26" }],
          explanation: "Solomon builds a fleet of ships at Ezion-geber on the shore of the Red Sea.",
        },
        {
          canonical: "Jehoshaphat's Wrecked Ships",
          aliases: ["jehoshaphats ships", "ships of tarshish wrecked"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 48, display: "1 Kings 22:48" }],
          explanation: "Jehoshaphat builds ships to sail for gold, but they are wrecked at Ezion-geber before they ever set sail.",
        },
        {
          canonical: "The Ship's Skiff",
          aliases: ["the boat cut loose", "small boat acts 27"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 30, verseEnd: 32, display: "Acts 27:30-32" }],
          explanation: "Sailors try to escape the storm by lowering the ship's skiff, so the soldiers cut its ropes away.",
        },
        {
          canonical: "The Twin Brothers",
          aliases: ["castor and pollux", "twin brothers ship"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 11, display: "Acts 28:11" }],
          explanation: "After the shipwreck at Malta, Paul sails on an Alexandrian ship with the figurehead of the Twin Brothers.",
        },
        {
          canonical: "Ships of Tarshish",
          aliases: ["tarshish fleet", "trading ships"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 10, verseStart: 22, display: "1 Kings 10:22" }],
          explanation: "Solomon's fleet of trading ships of Tarshish brings gold, silver, ivory, and exotic goods every three years.",
        },
        {
          canonical: "The Overloaded Fishing Boats",
          aliases: ["boats beginning to sink", "great catch of fish boats"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Luke", chapterStart: 5, verseStart: 6, verseEnd: 7, display: "Luke 5:6-7" }],
          explanation: "At Jesus' word, Simon's net encloses so many fish that both boats begin to sink under the catch.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a wilderness or desert region mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any wilderness or desert region the biblical text names specifically.",
      answers: [
        {
          canonical: "Wilderness of Sinai",
          aliases: ["sinai wilderness", "desert of sinai"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 1, verseEnd: 2, display: "Exodus 19:1-2" }],
          explanation: "Israel camps in the wilderness of Sinai, where the Law is given at the mountain.",
        },
        {
          canonical: "Wilderness of Judea",
          aliases: ["judean wilderness", "judean desert", "wilderness of judah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 1, display: "Matthew 3:1" }],
          explanation: "John the Baptist preaches repentance in the wilderness of Judea.",
        },
        {
          canonical: "Wilderness of Sin",
          aliases: ["desert of sin"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 16, verseStart: 1, display: "Exodus 16:1" }],
          explanation: "God provides manna and quail to Israel in the wilderness of Sin.",
        },
        {
          canonical: "Wilderness of Paran",
          aliases: ["desert of paran"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 10, verseStart: 12, display: "Numbers 10:12" }],
          explanation: "Israel's camp sets out from Sinai and settles in the wilderness of Paran; Ishmael later lives here too.",
        },
        {
          canonical: "Wilderness of Zin",
          aliases: ["desert of zin"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 20, verseStart: 1, display: "Numbers 20:1" }],
          explanation: "Miriam dies here at Kadesh, and Moses strikes the rock in anger instead of speaking to it.",
        },
        {
          canonical: "Wilderness of En-gedi",
          aliases: ["en gedi", "en-gedi wilderness"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 24, verseStart: 1, display: "1 Samuel 24:1" }],
          explanation: "Saul pursues David into the strongholds of En-gedi, where David spares his life in a cave.",
        },
        {
          canonical: "Wilderness of Shur",
          aliases: ["desert of shur"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 22, display: "Exodus 15:22" }],
          explanation: "Israel travels three days into the wilderness of Shur without finding water before reaching Marah.",
        },
        {
          canonical: "Wilderness of Maon",
          aliases: ["maon"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Samuel", chapterStart: 23, verseStart: 24, verseEnd: 25, display: "1 Samuel 23:24-25" }],
          explanation: "David hides in the wilderness of Maon while Saul closes in on him from the other side of a mountain.",
        },
        {
          canonical: "Wilderness of Ziph",
          aliases: ["ziph"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Samuel", chapterStart: 23, verseStart: 14, verseEnd: 15, display: "1 Samuel 23:14-15" }],
          explanation: "David hides in the wilderness of Ziph, and Jonathan visits him there to strengthen his faith.",
        },
        {
          canonical: "Wilderness of Beersheba",
          aliases: ["beersheba wilderness"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 21, verseStart: 14, display: "Genesis 21:14" }],
          explanation: "Hagar and Ishmael wander in the wilderness of Beersheba after Abraham sends them away.",
        },
        {
          canonical: "Wilderness of Tekoa",
          aliases: ["tekoa wilderness"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Chronicles", chapterStart: 20, verseStart: 20, display: "2 Chronicles 20:20" }],
          explanation: "Jehoshaphat's army marches out into the wilderness of Tekoa as singers lead the way with praise.",
        },
        {
          canonical: "Wilderness of Damascus",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 15, display: "1 Kings 19:15" }],
          explanation: "God directs Elijah, at Horeb, to go by way of the wilderness of Damascus to anoint Hazael as king.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a sea, lake, or other standing body of water mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any sea, lake, or other named standing body of water — rivers have their own question and don't count here.",
      answers: [
        {
          canonical: "Sea of Galilee",
          aliases: ["lake gennesaret", "sea of tiberias", "sea of chinnereth", "galilee"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 18, display: "Matthew 4:18" }],
          explanation: "Jesus calls his first disciples while walking beside the Sea of Galilee.",
        },
        {
          canonical: "Red Sea",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 14, verseStart: 21, verseEnd: 22, display: "Exodus 14:21-22" }],
          explanation: "God parts the Red Sea so Israel can cross on dry ground, fleeing Egypt.",
        },
        {
          canonical: "Dead Sea",
          aliases: ["salt sea", "sea of the arabah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 14, verseStart: 3, display: "Genesis 14:3" }],
          explanation: "The Dead Sea, called the Salt Sea, borders the region where Sodom and Gomorrah once stood.",
        },
        {
          canonical: "Mediterranean Sea",
          aliases: ["great sea", "the sea"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 1, verseStart: 4, display: "Joshua 1:4" }],
          explanation: "The \"Great Sea\" marks the western boundary of the land promised to Israel.",
        },
        {
          canonical: "Pool of Bethesda",
          aliases: ["bethesda"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 5, verseStart: 2, display: "John 5:2" }],
          explanation: "Jesus heals a man who had been an invalid for 38 years beside the Pool of Bethesda.",
        },
        {
          canonical: "Pool of Siloam",
          aliases: ["siloam"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 9, verseStart: 7, display: "John 9:7" }],
          explanation: "Jesus sends a man born blind to wash in the Pool of Siloam, and he comes back seeing.",
        },
        {
          canonical: "Marah",
          aliases: ["waters of marah", "bitter waters"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 23, display: "Exodus 15:23" }],
          explanation: "Israel finds bitter water at Marah, and Moses sweetens it by throwing in a tree God shows him.",
        },
        {
          canonical: "Meribah",
          aliases: ["waters of meribah"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 17, verseStart: 7, display: "Exodus 17:7" }],
          explanation: "Moses names this place Meribah, meaning \"quarreling,\" after Israel tests the LORD over water.",
        },
        {
          canonical: "Bronze Sea",
          aliases: ["molten sea", "brazen sea", "sea of cast bronze"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 7, verseStart: 23, display: "1 Kings 7:23" }],
          explanation: "Solomon has a massive round bronze basin cast for the temple, resting on twelve bronze oxen.",
        },
        {
          canonical: "Adriatic Sea",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 27, display: "Acts 27:27" }],
          explanation: "Paul's ship is driven across the Adriatic Sea for two weeks during the storm on the voyage to Rome.",
        },
        {
          canonical: "Sea of Jazer",
          aliases: ["jazer"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Jeremiah", chapterStart: 48, verseStart: 32, display: "Jeremiah 48:32" }],
          explanation: "Jeremiah's oracle against Moab poetically compares its ruin to vines that once reached the sea of Jazer.",
        },
      ],
    },
  ],
};
