import type { SeedDay } from "./types";

export const DAY_17: SeedDay = {
  dayNumber: 17,
  date: "2026-10-04",
  scriptureBonus: {
    displayText:
      "God is our refuge and strength, a very present help in trouble.",
    book: "Psalms",
    chapter: 46,
    verseStart: 1,
    referenceDisplay: "Psalm 46:1",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A psalm of confidence in God's protection, even amid upheaval.",
    acceptedBookAliases: ["psalm", "psalms"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a grain, legume, or field crop mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any grain, legume, or cultivated field crop the biblical text explicitly names.",
      answers: [
        {
          canonical: "Wheat",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 25, display: "Matthew 13:25" }],
          explanation: "In Jesus' parable, an enemy sows weeds among the wheat while everyone sleeps.",
        },
        {
          canonical: "Barley",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 6, verseStart: 9, display: "John 6:9" }],
          explanation: "A boy's five barley loaves and two fish feed the five thousand.",
        },
        {
          canonical: "Flax",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 2, verseStart: 6, display: "Joshua 2:6" }],
          explanation: "Rahab hides the Israelite spies under stalks of flax drying on her roof.",
        },
        {
          canonical: "Lentils",
          aliases: ["lentil stew"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 34, display: "Genesis 25:34" }],
          explanation: "Esau sells his birthright to Jacob for bread and a stew of lentils.",
        },
        {
          canonical: "Spelt",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 9, verseStart: 32, display: "Exodus 9:32" }],
          explanation: "The plague of hail spares Egypt's spelt and wheat because they ripen later than the flax and barley.",
        },
        {
          canonical: "Beans",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 17, verseStart: 28, display: "2 Samuel 17:28" }],
          explanation: "Supporters bring David beans, lentils, and other provisions when he flees from Absalom.",
        },
        {
          canonical: "Millet",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ezekiel", chapterStart: 4, verseStart: 9, display: "Ezekiel 4:9" }],
          explanation: "God tells Ezekiel to make bread from a mixture including wheat, barley, beans, lentils, millet, and spelt.",
        },
        {
          canonical: "Cumin",
          aliases: ["cummin"],
          score: 60,
          tier: "veil",
          references: [{ book: "Isaiah", chapterStart: 28, verseStart: 25, display: "Isaiah 28:25" }],
          explanation: "Isaiah describes a farmer who plants cumin and other crops each in their proper place.",
        },
        {
          canonical: "Mustard Seed",
          aliases: ["mustard"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 31, display: "Matthew 13:31" }],
          explanation: "Jesus compares the Kingdom of Heaven to a tiny mustard seed that grows into a large plant.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a region or province mentioned in the New Testament.",
      instructions: "You get one guess.",
      whatCounts: "Any named region, province, or territory the New Testament explicitly mentions.",
      answers: [
        {
          canonical: "Galilee",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 23, display: "Matthew 4:23" }],
          explanation: "Jesus teaches and heals throughout Galilee, the region of his upbringing and early ministry.",
        },
        {
          canonical: "Judea",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 4, display: "Luke 2:4" }],
          explanation: "Joseph and Mary travel to Bethlehem in Judea for the census before Jesus' birth.",
        },
        {
          canonical: "Samaria",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 4, verseStart: 4, display: "John 4:4" }],
          explanation: "Jesus passes through Samaria and meets the Samaritan woman at Jacob's well.",
        },
        {
          canonical: "Galatia",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Galatians", chapterStart: 1, verseStart: 2, display: "Galatians 1:2" }],
          explanation: "Paul writes his letter to the Galatians to the churches of this region.",
        },
        {
          canonical: "Macedonia",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 9, display: "Acts 16:9" }],
          explanation: "Paul sees a vision of a man from Macedonia begging him to come and help them.",
        },
        {
          canonical: "Achaia",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 12, display: "Acts 18:12" }],
          explanation: "Gallio serves as proconsul of Achaia when Paul is brought before him in Corinth.",
        },
        {
          canonical: "Cappadocia",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Peter", chapterStart: 1, verseStart: 1, display: "1 Peter 1:1" }],
          explanation: "Peter addresses his letter to the exiles scattered through Cappadocia and other regions.",
        },
        {
          canonical: "Bithynia",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 7, display: "Acts 16:7" }],
          explanation: "Paul and his companions try to enter Bithynia, but the Spirit of Jesus does not allow them.",
        },
        {
          canonical: "Pontus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 2, verseStart: 9, display: "Acts 2:9" }],
          explanation: "Visitors from Pontus are among the crowd in Jerusalem who hear the apostles at Pentecost.",
        },
        {
          canonical: "Phrygia",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 6, display: "Acts 16:6" }],
          explanation: "Paul and Timothy travel through Phrygia and the region of Galatia, forbidden to preach in Asia.",
        },
        {
          canonical: "Pamphylia",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 13, display: "Acts 13:13" }],
          explanation: "Paul's missionary team sails to Perga in Pamphylia, where John Mark leaves them to return home.",
        },
        {
          canonical: "Cilicia",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 39, display: "Acts 21:39" }],
          explanation: "Paul identifies himself as a Jew of Tarsus in Cilicia, no ordinary city, before the Jerusalem crowd.",
        },
        {
          canonical: "Illyricum",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Romans", chapterStart: 15, verseStart: 19, display: "Romans 15:19" }],
          explanation: "Paul writes that he has fully preached the gospel of Christ all the way from Jerusalem to Illyricum.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name an article of clothing or garment mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific named garment, article of clothing, or clothing-related item the biblical text describes.",
      answers: [
        {
          canonical: "Coat of Many Colors",
          aliases: ["coat of many colours", "joseph's coat", "richly ornamented robe"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 37, verseStart: 3, display: "Genesis 37:3" }],
          explanation: "Jacob gives Joseph an elaborate coat, a gift his brothers resent.",
        },
        {
          canonical: "Fig Leaves",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 7, display: "Genesis 3:7" }],
          explanation: "Adam and Eve sew fig leaves together to cover themselves after eating the forbidden fruit.",
        },
        {
          canonical: "Sackcloth",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Jonah", chapterStart: 3, verseStart: 5, display: "Jonah 3:5" }],
          explanation: "Nineveh's people put on sackcloth as a sign of mourning and repentance after Jonah's warning.",
        },
        {
          canonical: "Linen Ephod",
          aliases: ["ephod"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 6, verseStart: 14, display: "2 Samuel 6:14" }],
          explanation: "David, wearing a linen ephod, dances before the LORD as the ark enters Jerusalem.",
        },
        {
          canonical: "Camel's Hair Garment",
          aliases: ["camel hair clothing", "camel's hair clothes"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 4, display: "Matthew 3:4" }],
          explanation: "John the Baptist wears clothing made of camel's hair with a leather belt around his waist.",
        },
        {
          canonical: "Seamless Robe",
          aliases: ["seamless tunic", "jesus's robe"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 19, verseStart: 23, display: "John 19:23" }],
          explanation: "The soldiers at the crucifixion cast lots for Jesus' seamless robe rather than tear it.",
        },
        {
          canonical: "Purple Robe",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 19, verseStart: 2, display: "John 19:2" }],
          explanation: "Roman soldiers dress Jesus in a purple robe to mock him as a king before the crucifixion.",
        },
        {
          canonical: "Elijah's Leather Belt",
          aliases: ["leather girdle", "leather belt"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 1, verseStart: 8, display: "2 Kings 1:8" }],
          explanation: "Ahaziah's messengers describe a hairy man with a leather belt, and the king recognizes him as Elijah.",
        },
        {
          canonical: "Priestly Breastpiece",
          aliases: ["breastplate of judgment", "breastpiece of judgment"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 15, display: "Exodus 28:15" }],
          explanation: "God instructs Moses to make a jeweled breastpiece of judgment for the high priest to wear.",
        },
        {
          canonical: "Achan's Babylonian Garment",
          aliases: ["achan's robe", "beautiful mantle from shinar", "babylonish garment"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Joshua", chapterStart: 7, verseStart: 21, display: "Joshua 7:21" }],
          explanation: "Achan confesses he stole and buried a beautiful robe from Babylon along with silver and gold from Jericho's plunder.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a tribe of Israel.",
      instructions: "You get one guess.",
      whatCounts: "Any of the twelve tribes of Israel, named for one of Jacob's sons or (for Joseph) his two sons.",
      answers: [
        {
          canonical: "Judah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 49, verseStart: 8, display: "Genesis 49:8" }],
          explanation: "Judah becomes the leading tribe, from which David's royal line descends.",
        },
        {
          canonical: "Benjamin",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 49, verseStart: 27, display: "Genesis 49:27" }],
          explanation: "Benjamin's tribe, the smallest, later produces Israel's first king, Saul.",
        },
        {
          canonical: "Levi",
          aliases: ["Levites"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 3, verseStart: 6, display: "Numbers 3:6" }],
          explanation: "The tribe of Levi is set apart for priestly and tabernacle service instead of receiving a land allotment.",
        },
        {
          canonical: "Ephraim",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 16, verseStart: 5, display: "Joshua 16:5" }],
          explanation: "Ephraim, one of Joseph's two sons, becomes a tribe and later gives its name to the whole northern kingdom.",
        },
        {
          canonical: "Manasseh",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joshua", chapterStart: 17, verseStart: 1, display: "Joshua 17:1" }],
          explanation: "Manasseh, Joseph's other son, becomes a tribe whose land is split on both sides of the Jordan.",
        },
        {
          canonical: "Reuben",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 32, verseStart: 1, display: "Numbers 32:1" }],
          explanation: "Reuben's tribe, along with Gad, asks to settle east of the Jordan for its abundant livestock land.",
        },
        {
          canonical: "Simeon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 19, verseStart: 1, display: "Joshua 19:1" }],
          explanation: "Simeon's tribe receives territory within Judah's allotment rather than its own separate region.",
        },
        {
          canonical: "Gad",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 13, verseStart: 24, display: "Joshua 13:24" }],
          explanation: "The tribe of Gad settles east of the Jordan, in the territory Moses assigned before his death.",
        },
        {
          canonical: "Asher",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 19, verseStart: 24, display: "Joshua 19:24" }],
          explanation: "Asher's tribe receives fertile coastal land in the north of Canaan.",
        },
        {
          canonical: "Naphtali",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Joshua", chapterStart: 19, verseStart: 32, display: "Joshua 19:32" }],
          explanation: "Naphtali's tribe settles in Galilee, territory Isaiah later prophesies will see a great light.",
        },
        {
          canonical: "Issachar",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Joshua", chapterStart: 19, verseStart: 17, display: "Joshua 19:17" }],
          explanation: "Issachar's tribe, described by Jacob as a strong donkey, settles in the fertile Jezreel Valley.",
        },
        {
          canonical: "Zebulun",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Joshua", chapterStart: 19, verseStart: 10, display: "Joshua 19:10" }],
          explanation: "Zebulun's tribe settles near the coast, fulfilling Jacob's blessing that they would dwell by the sea.",
        },
        {
          canonical: "Dan",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Joshua", chapterStart: 19, verseStart: 40, verseEnd: 48, display: "Joshua 19:40-48" }],
          explanation: "Dan's tribe, too small for its original allotment, migrates north and captures the city of Laish, renaming it Dan.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a siege described in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any military siege of a city that the biblical text explicitly describes, identified by the besieged city or attacking party.",
      answers: [
        {
          canonical: "Siege of Jericho",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Joshua", chapterStart: 6, verseStart: 1, display: "Joshua 6:1" }],
          explanation: "Israel marches around Jericho for seven days until its walls collapse.",
        },
        {
          canonical: "Ben-Hadad's Siege of Samaria",
          aliases: ["siege of samaria famine", "famine in samaria"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Kings", chapterStart: 6, verseStart: 24, verseEnd: 25, display: "2 Kings 6:24-25" }],
          explanation: "Aram's siege of Samaria brings a famine so severe a donkey's head sells for eighty pieces of silver.",
        },
        {
          canonical: "Nebuchadnezzar's Siege of Jerusalem",
          aliases: ["babylonian siege of jerusalem", "fall of jerusalem"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 25, verseStart: 1, display: "2 Kings 25:1" }],
          explanation: "Nebuchadnezzar's army besieges Jerusalem until the city falls and the temple is destroyed.",
        },
        {
          canonical: "Sennacherib's Siege of Jerusalem",
          aliases: ["assyrian siege of jerusalem"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 18, verseStart: 13, display: "2 Kings 18:13" }],
          explanation: "Sennacherib of Assyria besieges Jerusalem in Hezekiah's reign, and an angel strikes down his army overnight.",
        },
        {
          canonical: "Siege of Ai",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joshua", chapterStart: 8, verseStart: 1, display: "Joshua 8:1" }],
          explanation: "Israel captures Ai through an ambush after an earlier defeat there.",
        },
        {
          canonical: "Siege of Rabbah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 11, verseStart: 1, display: "2 Samuel 11:1" }],
          explanation: "Joab besieges the Ammonite city of Rabbah while David remains in Jerusalem and sends Uriah to his death.",
        },
        {
          canonical: "Assyria's Siege of Samaria",
          aliases: ["fall of samaria", "shalmaneser's siege of samaria"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 17, verseStart: 5, display: "2 Kings 17:5" }],
          explanation: "The king of Assyria besieges Samaria for three years before the northern kingdom falls and its people are exiled.",
        },
        {
          canonical: "Siege of Lachish",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 18, verseStart: 14, display: "2 Kings 18:14" }],
          explanation: "Sennacherib's forces besiege the fortified city of Lachish during his campaign against Judah.",
        },
        {
          canonical: "Siege of Gibeah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Judges", chapterStart: 20, verseStart: 1, display: "Judges 20:1" }],
          explanation: "The other tribes of Israel besiege and burn Gibeah to punish the tribe of Benjamin for a horrific crime.",
        },
        {
          canonical: "Siege of Jabesh-Gilead",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Samuel", chapterStart: 11, verseStart: 1, display: "1 Samuel 11:1" }],
          explanation: "Nahash the Ammonite besieges Jabesh-Gilead, and Saul rallies Israel to rescue the city.",
        },
      ],
    },
  ],
};
