import type { SeedDay } from "./types";

export const DAY_10: SeedDay = {
  dayNumber: 10,
  date: "2026-09-27",
  scriptureBonus: {
    displayText: "Love is patient and is kind. Love doesn't envy. Love doesn't brag, is not proud.",
    book: "1 Corinthians",
    chapter: 13,
    verseStart: 4,
    referenceDisplay: "1 Corinthians 13:4",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "The opening of Paul's celebrated description of love in his letter to the Corinthian church.",
    acceptedBookAliases: ["first corinthians"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person associated with the Exodus.",
      instructions: "You get one guess.",
      whatCounts:
        "Any person the book of Exodus explicitly names or titles in connection with Israel's exodus from Egypt.",
      answers: [
        {
          canonical: "Moses",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 3, verseStart: 10, display: "Exodus 3:10" }],
          explanation: "Moses is sent by God to lead Israel out of Egypt.",
        },
        {
          canonical: "Aaron",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 4, verseStart: 14, display: "Exodus 4:14" }],
          explanation: "Aaron serves as Moses' spokesman before Pharaoh.",
        },
        {
          canonical: "Pharaoh",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 5, verseStart: 1, display: "Exodus 5:1" }],
          explanation: "Pharaoh repeatedly refuses to let Israel go until the tenth plague.",
        },
        {
          canonical: "Miriam",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 20, display: "Exodus 15:20" }],
          explanation: "Miriam, Moses' sister, leads the women in celebration after crossing the Red Sea.",
        },
        {
          canonical: "Joshua",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 17, verseStart: 9, display: "Exodus 17:9" }],
          explanation: "Joshua leads Israel's fight against Amalek during the wilderness journey.",
        },
        {
          canonical: "Pharaoh's Daughter",
          aliases: ["daughter of pharaoh"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 2, verseStart: 5, verseEnd: 10, display: "Exodus 2:5-10" }],
          explanation: "Pharaoh's daughter finds the infant Moses among the reeds and raises him.",
        },
        {
          canonical: "Puah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 1, verseStart: 15, display: "Exodus 1:15" }],
          explanation: "Puah, one of two Hebrew midwives, defies Pharaoh's order to kill Hebrew baby boys.",
        },
        {
          canonical: "Shiphrah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 1, verseStart: 15, display: "Exodus 1:15" }],
          explanation:
            "Shiphrah, alongside Puah, is one of the two named Hebrew midwives who defy Pharaoh out of reverence for God.",
        },
        {
          canonical: "Jethro",
          aliases: ["Moses' father-in-law","Reuel"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 18, verseStart: 1, verseEnd: 1, display: "Exodus 18:1" }],
          explanation: "Jethro, priest of Midian and Moses' father-in-law, hears of all God did for Israel and comes out to advise Moses in the wilderness.",
        },
        {
          canonical: "Zipporah",
          aliases: ["Moses' wife"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 4, verseStart: 24, verseEnd: 26, display: "Exodus 4:24-26" }],
          explanation: "Zipporah, Moses' wife, circumcises their son on the journey back to Egypt to turn away the LORD's anger from Moses.",
        },
        {
          canonical: "Hur",
          aliases: ["Aaron and Hur"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 17, verseStart: 10, verseEnd: 12, display: "Exodus 17:10-12" }],
          explanation: "Hur, together with Aaron, holds up Moses' hands during the battle with Amalek so that Israel prevails.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name an event from the days of creation.",
      instructions: "You get one guess.",
      whatCounts: "Any distinct creative act the Genesis creation account (Genesis 1-2) explicitly describes.",
      answers: [
        {
          canonical: "Light",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 3, verseEnd: 5, display: "Genesis 1:3-5" }],
          explanation: "On the first day, God creates light and separates it from darkness.",
        },
        {
          canonical: "Land Animals and Humans",
          aliases: ["animals and humans"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 24, verseEnd: 31, display: "Genesis 1:24-31" }],
          explanation: "On the sixth day, God creates land animals and then humankind.",
        },
        {
          canonical: "The Sky",
          aliases: ["firmament", "expanse"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 6, verseEnd: 8, display: "Genesis 1:6-8" }],
          explanation: "On the second day, God forms an expanse to separate the waters, calling it sky.",
        },
        {
          canonical: "Sun, Moon, and Stars",
          aliases: ["sun and moon", "stars"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 14, verseEnd: 19, display: "Genesis 1:14-19" }],
          explanation: "On the fourth day, God creates the sun, moon, and stars to mark seasons and days.",
        },
        {
          canonical: "Dry Land and Seas",
          aliases: ["dry land", "seas"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 9, verseEnd: 10, display: "Genesis 1:9-10" }],
          explanation: "On the third day, God gathers the waters and dry land appears.",
        },
        {
          canonical: "Plants and Vegetation",
          aliases: ["plants", "vegetation"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 11, verseEnd: 13, display: "Genesis 1:11-13" }],
          explanation: "Also on the third day, God causes vegetation and fruit trees to grow.",
        },
        {
          canonical: "Sea Creatures and Birds",
          aliases: ["sea creatures", "birds and fish"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 1, verseStart: 20, verseEnd: 23, display: "Genesis 1:20-23" }],
          explanation: "On the fifth day, God creates the creatures of the sea and the birds of the sky.",
        },
        {
          canonical: "God's Rest on the Seventh Day",
          aliases: ["sabbath rest"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 2, verseEnd: 3, display: "Genesis 2:2-3" }],
          explanation: "On the seventh day, God rests from his work and blesses the day.",
        },
        {
          canonical: "Creation of Woman",
          aliases: ["Eve created","Adam's rib","formation of Eve"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 21, verseEnd: 22, display: "Genesis 2:21-22" }],
          explanation: "God causes a deep sleep to fall on Adam, takes one of his ribs, and forms it into a woman.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a person healed by Jesus.",
      instructions: "You get one guess.",
      whatCounts: "Any person (named or specifically described though unnamed) the Gospels explicitly describe Jesus healing.",
      answers: [
        {
          canonical: "Blind Bartimaeus",
          aliases: ["bartimaeus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 10, verseStart: 46, verseEnd: 52, display: "Mark 10:46-52" }],
          explanation: "Jesus restores the sight of the blind beggar Bartimaeus outside Jericho.",
        },
        {
          canonical: "A Man with Leprosy",
          aliases: ["leper", "leprosy"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 1, verseStart: 40, verseEnd: 42, display: "Mark 1:40-42" }],
          explanation: "Jesus touches and heals a man covered with leprosy.",
        },
        {
          canonical: "The Centurion's Servant",
          aliases: ["centurion"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 5, verseEnd: 13, display: "Matthew 8:5-13" }],
          explanation: "Jesus heals a Roman centurion's servant from a distance.",
        },
        {
          canonical: "The Paralytic Lowered Through the Roof",
          aliases: ["paralytic", "man lowered through roof"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 2, verseStart: 1, verseEnd: 12, display: "Mark 2:1-12" }],
          explanation: "Friends lower a paralyzed man through a roof to reach Jesus, who heals him.",
        },
        {
          canonical: "The Woman with the Issue of Blood",
          aliases: ["bleeding woman"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 25, verseEnd: 34, display: "Mark 5:25-34" }],
          explanation: "A woman who had bled for twelve years is healed by touching Jesus' cloak.",
        },
        {
          canonical: "Malchus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 22, verseStart: 50, verseEnd: 51, display: "Luke 22:50-51" }],
          explanation: "Jesus heals the ear of Malchus, the high priest's servant, cut off in Gethsemane.",
        },
        {
          canonical: "The Man with the Withered Hand",
          aliases: ["withered hand"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Mark", chapterStart: 3, verseStart: 1, verseEnd: 5, display: "Mark 3:1-5" }],
          explanation: "Jesus heals a man's withered hand in the synagogue on the Sabbath.",
        },
        {
          canonical: "The Man at the Pool of Bethesda",
          aliases: ["bethesda", "pool of bethesda"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "John", chapterStart: 5, verseStart: 1, verseEnd: 9, display: "John 5:1-9" }],
          explanation: "Jesus heals a man who had been sick for thirty-eight years beside the pool of Bethesda.",
        },
        {
          canonical: "Peter's Mother-in-Law",
          aliases: ["Simon's mother-in-law","the fever healing"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 14, verseEnd: 15, display: "Matthew 8:14-15" }],
          explanation: "Jesus touches the hand of Peter's mother-in-law and her fever leaves her.",
        },
        {
          canonical: "The Man Born Blind",
          aliases: ["blind man healed with mud","man born blind"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 9, verseStart: 1, verseEnd: 7, display: "John 9:1-7" }],
          explanation: "Jesus anoints the eyes of a man born blind with mud and sends him to wash in the pool of Siloam, and he receives his sight.",
        },
        {
          canonical: "The Ten Lepers",
          aliases: ["ten men with leprosy"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 17, verseStart: 11, verseEnd: 19, display: "Luke 17:11-19" }],
          explanation: "Jesus heals ten men with leprosy on the way to the priests, and only one returns to give thanks.",
        },
        {
          canonical: "The Deaf and Mute Man",
          aliases: ["Ephphatha","deaf man with speech impediment"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 7, verseStart: 31, verseEnd: 37, display: "Mark 7:31-37" }],
          explanation: "Jesus puts his fingers in a deaf man's ears, touches his tongue, and says 'Ephphatha,' and the man hears and speaks plainly.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a garden mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any garden explicitly mentioned in the biblical text.",
      answers: [
        {
          canonical: "The Garden of Eden",
          aliases: ["eden"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 8, display: "Genesis 2:8" }],
          explanation: "God plants a garden in Eden and places the first man there.",
        },
        {
          canonical: "The Garden of Gethsemane",
          aliases: ["gethsemane"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 36, display: "Matthew 26:36" }],
          explanation: "Jesus prays in the garden of Gethsemane the night before his crucifixion.",
        },
        {
          canonical: "The Garden Where Jesus Was Buried",
          aliases: ["garden tomb"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 19, verseStart: 41, display: "John 19:41" }],
          explanation: "John notes that a garden with a new tomb stood at the place of the crucifixion.",
        },
        {
          canonical: "The King's Garden",
          aliases: ["king's garden", "kings garden"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 25, verseStart: 4, display: "2 Kings 25:4" }],
          explanation: "Zedekiah and his soldiers flee Jerusalem by the gate near the king's garden.",
        },
        {
          canonical: "The Enclosed Garden",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Song of Solomon", chapterStart: 4, verseStart: 12, display: "Song of Solomon 4:12" }],
          explanation: "The beloved is poetically described as \"a garden enclosed\" in the Song of Solomon.",
        },
        {
          canonical: "Solomon's Gardens",
          aliases: ["solomon's garden", "solomons garden"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Ecclesiastes", chapterStart: 2, verseStart: 5, display: "Ecclesiastes 2:5" }],
          explanation: "In Ecclesiastes, Solomon describes making gardens and parks for himself.",
        },
        {
          canonical: "The Garden of Herbs",
          aliases: ["Naboth's garden","garden of herbs"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 21, verseStart: 2, verseEnd: 2, display: "1 Kings 21:2" }],
          explanation: "Ahab asks Naboth for his vineyard to use as a garden of herbs, a request that leads to Naboth's unjust death.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a patriarch of Israel — Abraham, Isaac, Jacob, or one of Jacob's twelve sons.",
      instructions: "You get one guess.",
      whatCounts:
        "Abraham, Isaac, Jacob, or any of Jacob's twelve sons — traditionally counted among the patriarchs of Israel.",
      answers: [
        {
          canonical: "Abraham",
          aliases: ["abram"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 17, verseStart: 5, display: "Genesis 17:5" }],
          explanation: "Abraham is the first patriarch, father of Isaac.",
        },
        {
          canonical: "Jacob",
          aliases: ["israel"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 32, verseStart: 28, display: "Genesis 32:28" }],
          explanation: "Jacob, renamed Israel, is the father of the twelve tribes.",
        },
        {
          canonical: "Isaac",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 21, verseStart: 3, display: "Genesis 21:3" }],
          explanation: "Isaac, Abraham's son of promise, is the second patriarch.",
        },
        {
          canonical: "Judah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 35, display: "Genesis 29:35" }],
          explanation: "Judah, Jacob's fourth son, becomes ancestor of the tribe of Judah.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 24, display: "Genesis 30:24" }],
          explanation: "Joseph, Jacob's eleventh son, rises to power in Egypt.",
        },
        {
          canonical: "Reuben",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 32, display: "Genesis 29:32" }],
          explanation: "Reuben is Jacob's firstborn son.",
        },
        {
          canonical: "Levi",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 34, display: "Genesis 29:34" }],
          explanation: "Levi, Jacob's third son, becomes ancestor of the priestly tribe.",
        },
        {
          canonical: "Simeon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 33, display: "Genesis 29:33" }],
          explanation: "Simeon is Jacob's second son, by Leah.",
        },
        {
          canonical: "Benjamin",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 35, verseStart: 18, display: "Genesis 35:18" }],
          explanation: "Benjamin is Jacob's twelfth and youngest son, born to Rachel as she died.",
        },
        {
          canonical: "Dan",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 6, display: "Genesis 30:6" }],
          explanation: "Dan is Jacob's son by Rachel's servant Bilhah.",
        },
        {
          canonical: "Zebulun",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 20, display: "Genesis 30:20" }],
          explanation: "Zebulun is Jacob's sixth son, by Leah.",
        },
        {
          canonical: "Asher",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 13, display: "Genesis 30:13" }],
          explanation: "Asher is Jacob's son by Leah's servant Zilpah.",
        },
        {
          canonical: "Issachar",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 18, display: "Genesis 30:18" }],
          explanation: "Issachar is Jacob's ninth son, by Leah.",
        },
        {
          canonical: "Gad",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 11, display: "Genesis 30:11" }],
          explanation: "Gad is Jacob's son by Leah's servant Zilpah.",
        },
        {
          canonical: "Naphtali",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 8, display: "Genesis 30:8" }],
          explanation: "Naphtali is Jacob's son by Rachel's servant Bilhah, one of the lesser-recalled twelve.",
        },
      ],
    },
  ],
};
