import type { SeedDay } from "./types";

export const DAY_19: SeedDay = {
  dayNumber: 19,
  date: "2026-10-06",
  scriptureBonus: {
    displayText: "Be strong and courageous. Don't be afraid or scared of them; for Yahweh your God himself is who goes with you. He will not fail you nor forsake you.",
    book: "Deuteronomy",
    chapter: 31,
    verseStart: 6,
    referenceDisplay: "Deuteronomy 31:6",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Moses charges Israel to be strong and courageous as they prepare to enter the promised land without him.",
    acceptedBookAliases: ["deut", "dt"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a divine judgment or plague other than the ten plagues of Egypt.",
      instructions: "You get one guess.",
      whatCounts: "Any specific judgment, plague, or disaster the biblical text describes God sending, not counting the ten plagues on Egypt in Exodus.",
      answers: [
        {
          canonical: "The Flood",
          aliases: ["noahs flood", "the great flood"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 7, verseStart: 17, display: "Genesis 7:17" }],
          explanation: "God floods the whole earth, sparing only Noah, his family, and the animals on the ark.",
        },
        {
          canonical: "Fire on Sodom and Gomorrah",
          aliases: ["destruction of sodom", "sodom and gomorrah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 24, display: "Genesis 19:24" }],
          explanation: "The LORD rains burning sulfur down on Sodom and Gomorrah, destroying the cities.",
        },
        {
          canonical: "Fiery Serpents in the Wilderness",
          aliases: ["fiery serpents", "bronze serpent plague"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 21, verseStart: 6, display: "Numbers 21:6" }],
          explanation: "God sends venomous snakes among the complaining Israelites, and many die from their bites.",
        },
        {
          canonical: "Plague After the Golden Calf",
          aliases: ["golden calf plague"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 32, verseStart: 35, display: "Exodus 32:35" }],
          explanation: "The LORD strikes Israel with a plague for worshiping the golden calf while Moses was on the mountain.",
        },
        {
          canonical: "Korah's Rebellion Swallowed Up",
          aliases: ["korahs rebellion", "earth swallowed korah"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 16, verseStart: 32, display: "Numbers 16:32" }],
          explanation: "The earth opens and swallows Korah and his fellow rebels alive for challenging Moses' authority.",
        },
        {
          canonical: "David's Census Plague",
          aliases: ["census plague", "plague after the census"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 24, verseStart: 15, display: "2 Samuel 24:15" }],
          explanation: "A plague strikes Israel after David takes a census against God's will, killing seventy thousand.",
        },
        {
          canonical: "Plague at Baal Peor",
          aliases: ["baal peor plague"],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 25, verseStart: 9, display: "Numbers 25:9" }],
          explanation: "A plague kills twenty-four thousand Israelites after they join in worship of Baal of Peor.",
        },
        {
          canonical: "Quail Plague at Kibroth Hattaavah",
          aliases: ["quail plague", "graves of craving"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 11, verseStart: 33, display: "Numbers 11:33" }],
          explanation: "While the meat is still in their teeth, God strikes the people with a plague for craving meat.",
        },
        {
          canonical: "Nadab and Abihu Consumed by Fire",
          aliases: ["nadab and abihu"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 10, verseStart: 2, display: "Leviticus 10:2" }],
          explanation: "Fire from the LORD consumes Aaron's sons Nadab and Abihu for offering unauthorized fire.",
        },
        {
          canonical: "Assyrian Army Struck Down",
          aliases: ["angel strikes assyrian army", "185000 assyrians"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 19, verseStart: 35, display: "2 Kings 19:35" }],
          explanation: "The angel of the LORD strikes down 185,000 in the Assyrian camp in a single night.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a beatitude Jesus taught in the Sermon on the Mount.",
      instructions: "You get one guess.",
      whatCounts: "Any of the \"blessed are...\" statements Jesus makes in Matthew 5:3-11.",
      answers: [
        {
          canonical: "Blessed Are the Poor in Spirit",
          aliases: ["poor in spirit"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 3, display: "Matthew 5:3" }],
          explanation: "The first beatitude blesses the poor in spirit, promising them the kingdom of heaven.",
        },
        {
          canonical: "Blessed Are Those Who Mourn",
          aliases: ["those who mourn"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 4, display: "Matthew 5:4" }],
          explanation: "The second beatitude blesses those who mourn, promising they will be comforted.",
        },
        {
          canonical: "Blessed Are the Meek",
          aliases: ["the meek"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 5, display: "Matthew 5:5" }],
          explanation: "The third beatitude blesses the meek, promising they will inherit the earth.",
        },
        {
          canonical: "Blessed Are Those Who Hunger and Thirst for Righteousness",
          aliases: ["hunger and thirst for righteousness"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 6, display: "Matthew 5:6" }],
          explanation: "The fourth beatitude blesses those who hunger and thirst for righteousness, promising they will be filled.",
        },
        {
          canonical: "Blessed Are the Merciful",
          aliases: ["the merciful"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 7, display: "Matthew 5:7" }],
          explanation: "The fifth beatitude blesses the merciful, promising they will obtain mercy.",
        },
        {
          canonical: "Blessed Are the Pure in Heart",
          aliases: ["pure in heart"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 8, display: "Matthew 5:8" }],
          explanation: "The sixth beatitude blesses the pure in heart, promising they will see God.",
        },
        {
          canonical: "Blessed Are the Peacemakers",
          aliases: ["the peacemakers"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 9, display: "Matthew 5:9" }],
          explanation: "The seventh beatitude blesses the peacemakers, calling them children of God.",
        },
        {
          canonical: "Blessed Are Those Persecuted for Righteousness",
          aliases: ["persecuted for righteousness"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 10, display: "Matthew 5:10" }],
          explanation: "The eighth beatitude blesses those persecuted for righteousness, promising them the kingdom of heaven.",
        },
        {
          canonical: "Blessed Are You When Reviled for My Sake",
          aliases: ["reviled for my sake", "reviled and persecuted"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 11, display: "Matthew 5:11" }],
          explanation: "Jesus closes with a ninth blessing on those reviled and slandered falsely because of him.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name an animal used in a Bible sacrifice or offering.",
      instructions: "You get one guess.",
      whatCounts: "Any animal the biblical text explicitly describes being offered as a sacrifice.",
      answers: [
        {
          canonical: "Lamb",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 12, verseStart: 3, display: "Exodus 12:3" }],
          explanation: "A lamb is prescribed for each household as the Passover sacrifice.",
        },
        {
          canonical: "Goat",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Leviticus", chapterStart: 16, verseStart: 9, display: "Leviticus 16:9" }],
          explanation: "A goat is sacrificed as a sin offering on the Day of Atonement.",
        },
        {
          canonical: "Bull",
          aliases: ["ox", "bullock"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 4, verseStart: 3, display: "Leviticus 4:3" }],
          explanation: "A young bull is prescribed as a sin offering for the anointed priest.",
        },
        {
          canonical: "Ram",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 22, verseStart: 13, display: "Genesis 22:13" }],
          explanation: "Abraham sacrifices a ram caught in a thicket in place of Isaac.",
        },
        {
          canonical: "Dove",
          aliases: ["turtledove", "pigeon"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 12, verseStart: 8, display: "Leviticus 12:8" }],
          explanation: "Two turtledoves or pigeons are offered by those who cannot afford a lamb for purification.",
        },
        {
          canonical: "Heifer",
          aliases: ["red heifer"],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 19, verseStart: 2, display: "Numbers 19:2" }],
          explanation: "A red heifer without defect or blemish is prescribed for a special purification ritual.",
        },
        {
          canonical: "Two Birds for Cleansing a Leper",
          aliases: ["two birds", "leper cleansing birds"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 14, verseStart: 4, display: "Leviticus 14:4" }],
          explanation: "Two live clean birds are used in the ritual for cleansing someone healed of a skin disease.",
        },
        {
          canonical: "Scapegoat",
          aliases: ["azazel goat"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Leviticus", chapterStart: 16, verseStart: 10, display: "Leviticus 16:10" }],
          explanation: "A second goat is not slaughtered but sent alive into the wilderness, carrying away Israel's sins.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a unit or period of time named in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific named unit, period, or calendar term for time the biblical text explicitly uses.",
      answers: [
        {
          canonical: "Sabbath",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 20, verseStart: 8, display: "Exodus 20:8" }],
          explanation: "God commands Israel to remember the Sabbath day and keep it holy as a weekly day of rest.",
        },
        {
          canonical: "Jubilee",
          aliases: ["year of jubilee"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Leviticus", chapterStart: 25, verseStart: 10, display: "Leviticus 25:10" }],
          explanation: "Every fiftieth year is consecrated as a Jubilee, when land returns to its original owners and debts are released.",
        },
        {
          canonical: "Sabbatical Year",
          aliases: ["year of release", "seventh year"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Deuteronomy", chapterStart: 15, verseStart: 1, display: "Deuteronomy 15:1" }],
          explanation: "Every seventh year, the Law requires Israel to release debts owed by fellow Israelites.",
        },
        {
          canonical: "Fourth Watch of the Night",
          aliases: ["night watch", "fourth watch"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 25, display: "Matthew 14:25" }],
          explanation: "Jesus comes to the disciples walking on the sea during the fourth watch of the night.",
        },
        {
          canonical: "Forty Days and Forty Nights",
          aliases: ["forty days and nights"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 7, verseStart: 12, display: "Genesis 7:12" }],
          explanation: "Rain falls on the earth for forty days and forty nights during the flood.",
        },
        {
          canonical: "Ninth Hour",
          aliases: ["hour of prayer"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 3, verseStart: 1, display: "Acts 3:1" }],
          explanation: "Peter and John go up to the temple at the ninth hour, the hour of prayer.",
        },
        {
          canonical: "Time, Times, and Half a Time",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 7, verseStart: 25, display: "Daniel 7:25" }],
          explanation: "Daniel describes a period of a time, times, and half a time in his vision of the four beasts.",
        },
        {
          canonical: "The Seventy Years of Exile",
          aliases: ["seventy years", "seventy years of captivity"],
          score: 60,
          tier: "veil",
          references: [{ book: "Jeremiah", chapterStart: 25, verseStart: 11, display: "Jeremiah 25:11" }],
          explanation: "Jeremiah prophesies that the nations will serve the king of Babylon for seventy years.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a name or title used for the nation of Israel in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any name or title the biblical text applies to Israel as a people or nation, beyond the name \"Israel\" itself.",
      answers: [
        {
          canonical: "Zion",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Isaiah", chapterStart: 51, verseStart: 16, display: "Isaiah 51:16" }],
          explanation: "Isaiah records God calling Zion \"my people,\" using the name as a poetic stand-in for Israel.",
        },
        {
          canonical: "Jacob",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Isaiah", chapterStart: 41, verseStart: 8, display: "Isaiah 41:8" }],
          explanation: "Isaiah addresses \"Israel, my servant, Jacob whom I have chosen,\" using the patriarch's name for the nation.",
        },
        {
          canonical: "Apple of His Eye",
          aliases: ["apple of my eye"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Deuteronomy", chapterStart: 32, verseStart: 10, display: "Deuteronomy 32:10" }],
          explanation: "Moses' song describes God guarding Israel in the wilderness, keeping them as the apple of his eye.",
        },
        {
          canonical: "Vineyard of the LORD",
          aliases: ["the vineyard"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Isaiah", chapterStart: 5, verseStart: 7, display: "Isaiah 5:7" }],
          explanation: "Isaiah identifies the vineyard of the LORD of Hosts in his parable as the house of Israel.",
        },
        {
          canonical: "Ephraim",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Hosea", chapterStart: 11, verseStart: 8, display: "Hosea 11:8" }],
          explanation: "Hosea uses Ephraim, one of Israel's tribes, as a poetic name for the whole nation.",
        },
        {
          canonical: "Bride of the LORD",
          aliases: ["the bride"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Isaiah", chapterStart: 62, verseStart: 5, display: "Isaiah 62:5" }],
          explanation: "Isaiah pictures God rejoicing over Israel the way a bridegroom rejoices over his bride.",
        },
        {
          canonical: "Kingdom of Priests",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 6, display: "Exodus 19:6" }],
          explanation: "God tells Moses that Israel will be to him a kingdom of priests if they keep his covenant.",
        },
        {
          canonical: "Holy Nation",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 6, display: "Exodus 19:6" }],
          explanation: "In the same verse, God calls Israel to be a holy nation set apart to him.",
        },
        {
          canonical: "Treasured Possession",
          aliases: ["peculiar treasure", "special possession"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 5, display: "Exodus 19:5" }],
          explanation: "God tells Israel that of all the peoples on earth, they will be his own treasured possession.",
        },
        {
          canonical: "Jeshurun",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Deuteronomy", chapterStart: 32, verseStart: 15, display: "Deuteronomy 32:15" }],
          explanation: "Moses' song uses the rare poetic name Jeshurun for Israel, who grew fat and forsook God.",
        },
      ],
    },
  ],
};
