import type { SeedDay } from "./types";

export const DAY_15: SeedDay = {
  dayNumber: 15,
  date: "2026-10-02",
  scriptureBonus: {
    displayText: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control.",
    book: "Galatians",
    chapter: 5,
    verseStart: 22,
    verseEnd: 23,
    referenceDisplay: "Galatians 5:22-23",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul contrasts the works of the flesh with the character the Holy Spirit produces in believers.",
    acceptedBookAliases: ["gal"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a dream interpreted in the Bible (name the dreamer).",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly describes having a dream that is interpreted or given clear meaning.",
      answers: [
        {
          canonical: "Joseph",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 37, verseStart: 5, display: "Genesis 37:5" }],
          explanation: "Joseph dreams that his brothers' sheaves bow to his, a dream his family understands all too well.",
        },
        {
          canonical: "Pharaoh",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 15, display: "Genesis 41:15" }],
          explanation: "Joseph interprets Pharaoh's dreams of seven fat and seven lean cows as seven years of plenty and famine.",
        },
        {
          canonical: "Nebuchadnezzar",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 2, verseStart: 1, display: "Daniel 2:1" }],
          explanation: "Daniel interprets Nebuchadnezzar's dream of a great statue made of different metals.",
        },
        {
          canonical: "Jacob",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 28, verseStart: 12, display: "Genesis 28:12" }],
          explanation: "Jacob dreams of a ladder reaching to heaven at Bethel, and the LORD speaks the dream's meaning to him directly.",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 3, verseStart: 5, display: "1 Kings 3:5" }],
          explanation: "The LORD appears to Solomon in a dream at Gibeon and grants his request for wisdom.",
        },
        {
          canonical: "Pharaoh's Cupbearer",
          aliases: ["cupbearer", "chief cupbearer"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 40, verseStart: 9, display: "Genesis 40:9" }],
          explanation: "Joseph interprets the cupbearer's dream of a vine as his restoration to Pharaoh's service in three days.",
        },
        {
          canonical: "Pharaoh's Baker",
          aliases: ["baker", "chief baker"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 40, verseStart: 16, display: "Genesis 40:16" }],
          explanation: "Joseph interprets the baker's dream of birds eating from baskets as his execution in three days.",
        },
        {
          canonical: "Joseph (Husband of Mary)",
          aliases: ["joseph, mary's husband"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 20, display: "Matthew 1:20" }],
          explanation: "An angel explains in a dream that Mary's child is conceived by the Holy Spirit; further dreams direct Joseph to flee to Egypt and return.",
        },
        {
          canonical: "The Magi",
          aliases: ["the wise men", "the three wise men"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 2, verseStart: 12, display: "Matthew 2:12" }],
          explanation: "The Magi are warned in a dream not to return to Herod and go home another way.",
        },
        {
          canonical: "Pilate's Wife",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 19, display: "Matthew 27:19" }],
          explanation:
            "Pilate's wife sends word that she has \"suffered many things today in a dream\" because of Jesus, urging Pilate to have nothing to do with him.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person who fasted in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person (or group) the biblical text explicitly describes fasting.",
      answers: [
        {
          canonical: "Moses",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 34, verseStart: 28, display: "Exodus 34:28" }],
          explanation: "Moses fasts forty days and nights on Mount Sinai while receiving the law.",
        },
        {
          canonical: "Elijah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 8, display: "1 Kings 19:8" }],
          explanation: "Strengthened by one meal, Elijah travels forty days and nights to Horeb without eating.",
        },
        {
          canonical: "Jesus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 2, display: "Matthew 4:2" }],
          explanation: "Jesus fasts forty days and nights in the wilderness before being tempted.",
        },
        {
          canonical: "Esther and the Jews",
          aliases: ["esther", "the jews of susa"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Esther", chapterStart: 4, verseStart: 16, display: "Esther 4:16" }],
          explanation: "Esther asks Mordecai to gather the Jews of Susa to fast for three days before she approaches the king.",
        },
        {
          canonical: "David",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 12, verseStart: 16, display: "2 Samuel 12:16" }],
          explanation: "David fasts and pleads with God for his sick child's life.",
        },
        {
          canonical: "Daniel",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Daniel", chapterStart: 10, verseStart: 2, verseEnd: 3, display: "Daniel 10:2-3" }],
          explanation: "Daniel mourns and abstains from rich food for three full weeks before receiving a vision.",
        },
        {
          canonical: "Nehemiah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Nehemiah", chapterStart: 1, verseStart: 4, display: "Nehemiah 1:4" }],
          explanation: "Nehemiah fasts and prays for days after hearing that Jerusalem's walls lie broken.",
        },
        {
          canonical: "Ezra",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ezra", chapterStart: 8, verseStart: 21, display: "Ezra 8:21" }],
          explanation: "Ezra proclaims a fast at the river Ahava to seek a safe journey from God.",
        },
        {
          canonical: "The Ninevites",
          aliases: ["nineveh"],
          score: 60,
          tier: "veil",
          references: [{ book: "Jonah", chapterStart: 3, verseStart: 5, display: "Jonah 3:5" }],
          explanation: "The people of Nineveh believe God's warning through Jonah and proclaim a citywide fast.",
        },
        {
          canonical: "Anna",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 37, display: "Luke 2:37" }],
          explanation: "The elderly prophetess Anna worships continually in the temple with fasting and prayer.",
        },
        {
          canonical: "Saul (Paul)",
          aliases: ["paul", "saul of tarsus"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 9, display: "Acts 9:9" }],
          explanation: "After his encounter on the road to Damascus, Saul is blind and neither eats nor drinks for three days.",
        },
        {
          canonical: "Cornelius",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 30, display: "Acts 10:30" }],
          explanation: "Cornelius tells Peter he was fasting and praying when an angel appeared to him.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a pool, well, or spring mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named pool, well, or spring the biblical text explicitly mentions (not a major sea or river).",
      answers: [
        {
          canonical: "Jacob's Well",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 4, verseStart: 6, display: "John 4:6" }],
          explanation: "Jesus rests at Jacob's Well and speaks with the Samaritan woman.",
        },
        {
          canonical: "Pool of Siloam",
          aliases: ["siloam"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 9, verseStart: 7, display: "John 9:7" }],
          explanation: "Jesus sends a man born blind to wash in the Pool of Siloam, and he receives his sight.",
        },
        {
          canonical: "Pool of Bethesda",
          aliases: ["bethesda"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 5, verseStart: 2, display: "John 5:2" }],
          explanation: "Jesus heals a man who had been an invalid for thirty-eight years at the Pool of Bethesda.",
        },
        {
          canonical: "Beersheba",
          aliases: ["well of the oath"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 21, verseStart: 31, display: "Genesis 21:31" }],
          explanation: "Abraham and Abimelech make a covenant at a well, naming the place Beersheba.",
        },
        {
          canonical: "En-gedi",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 24, verseStart: 1, display: "1 Samuel 24:1" }],
          explanation: "David hides from Saul in the strongholds of En-gedi, a spring-fed oasis by the Dead Sea.",
        },
        {
          canonical: "Beer Lahai Roi",
          aliases: ["well of the living one who sees me"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 16, verseStart: 14, display: "Genesis 16:14" }],
          explanation: "Hagar names the well where God met her in the wilderness Beer Lahai Roi.",
        },
        {
          canonical: "Pool of Gibeon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 2, verseStart: 13, display: "2 Samuel 2:13" }],
          explanation: "The forces of David and Saul's house meet at the pool of Gibeon before a deadly contest between their young men.",
        },
        {
          canonical: "King's Pool",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Nehemiah", chapterStart: 2, verseStart: 14, display: "Nehemiah 2:14" }],
          explanation: "Nehemiah surveys Jerusalem's ruined walls by night, passing the King's Pool where his mount could not get through.",
        },
        {
          canonical: "Pool of Hebron",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Samuel", chapterStart: 4, verseStart: 12, display: "2 Samuel 4:12" }],
          explanation: "David has the hands and feet of Ish-bosheth's murderers hung up beside the pool of Hebron.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name an occupation or trade mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any occupation, trade, or profession the biblical text explicitly names someone practicing.",
      answers: [
        {
          canonical: "Shepherd",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 8, display: "Luke 2:8" }],
          explanation: "Shepherds keeping watch over their flocks by night are the first to hear of Jesus' birth.",
        },
        {
          canonical: "Fisherman",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 18, display: "Matthew 4:18" }],
          explanation: "Peter and Andrew are fishermen when Jesus calls them to follow him.",
        },
        {
          canonical: "Tax Collector",
          aliases: ["publican"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 19, verseStart: 2, display: "Luke 19:2" }],
          explanation: "Zacchaeus is a chief tax collector who climbs a tree to see Jesus.",
        },
        {
          canonical: "Carpenter",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 55, display: "Matthew 13:55" }],
          explanation: "The crowd identifies Jesus as \"the carpenter's son,\" a trade he shared with Joseph.",
        },
        {
          canonical: "Tentmaker",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 3, display: "Acts 18:3" }],
          explanation: "Paul works as a tentmaker alongside Aquila and Priscilla in Corinth.",
        },
        {
          canonical: "Physician",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Colossians", chapterStart: 4, verseStart: 14, display: "Colossians 4:14" }],
          explanation: "Paul greets Luke, calling him \"the beloved physician.\"",
        },
        {
          canonical: "Farmer",
          aliases: ["vinedresser"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 15, verseStart: 1, display: "John 15:1" }],
          explanation: "Jesus calls his Father \"the farmer\" who tends the true vine.",
        },
        {
          canonical: "Potter",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 18, verseStart: 3, display: "Jeremiah 18:3" }],
          explanation: "Jeremiah watches a potter reworking spoiled clay on his wheel.",
        },
        {
          canonical: "Scribe",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Ezra", chapterStart: 7, verseStart: 6, display: "Ezra 7:6" }],
          explanation: "Ezra is described as a scribe skilled in the Law of Moses.",
        },
        {
          canonical: "Merchant",
          aliases: ["trader"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 45, display: "Matthew 13:45" }],
          explanation: "Jesus compares the Kingdom of Heaven to a merchant seeking fine pearls.",
        },
        {
          canonical: "Midwife",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 1, verseStart: 15, display: "Exodus 1:15" }],
          explanation: "The Hebrew midwives Shiphrah and Puah defy Pharaoh's order to kill newborn boys.",
        },
        {
          canonical: "Coppersmith",
          aliases: ["metalworker"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Timothy", chapterStart: 4, verseStart: 14, display: "2 Timothy 4:14" }],
          explanation: "Paul warns Timothy that Alexander the coppersmith did him great harm.",
        },
        {
          canonical: "Silversmith",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 19, verseStart: 24, display: "Acts 19:24" }],
          explanation: "Demetrius the silversmith incites a riot in Ephesus after Paul's preaching threatens his idol trade.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a spiritual gift listed in the New Testament.",
      instructions: "You get one guess.",
      whatCounts: "Any spiritual gift explicitly listed in the New Testament (chiefly 1 Corinthians 12, Romans 12, and Ephesians 4).",
      answers: [
        {
          canonical: "Wisdom",
          aliases: ["word of wisdom"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 8, display: "1 Corinthians 12:8" }],
          explanation: "Paul lists \"the word of wisdom\" first among the gifts given through the Spirit.",
        },
        {
          canonical: "Knowledge",
          aliases: ["word of knowledge"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 8, display: "1 Corinthians 12:8" }],
          explanation: "\"The word of knowledge\" is given to another through the same Spirit.",
        },
        {
          canonical: "Faith",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 9, display: "1 Corinthians 12:9" }],
          explanation: "Faith is listed as a gift of the same Spirit distinct from saving faith itself.",
        },
        {
          canonical: "Healing",
          aliases: ["gifts of healing"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 9, display: "1 Corinthians 12:9" }],
          explanation: "Gifts of healing are given by the one Spirit.",
        },
        {
          canonical: "Prophecy",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Romans", chapterStart: 12, verseStart: 6, display: "Romans 12:6" }],
          explanation: "Paul lists prophecy among the gifts to be used according to the proportion of one's faith.",
        },
        {
          canonical: "Tongues",
          aliases: ["speaking in tongues", "diverse kinds of tongues"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 10, display: "1 Corinthians 12:10" }],
          explanation: "\"Various kinds of languages\" are listed among the manifestations of the Spirit.",
        },
        {
          canonical: "Teaching",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Romans", chapterStart: 12, verseStart: 7, display: "Romans 12:7" }],
          explanation: "Paul lists teaching among the gifts believers are to exercise faithfully.",
        },
        {
          canonical: "Miracles",
          aliases: ["working of miracles"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 10, display: "1 Corinthians 12:10" }],
          explanation: "\"The working of miracles\" is given to another believer by the Spirit.",
        },
        {
          canonical: "Giving",
          aliases: ["generosity"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Romans", chapterStart: 12, verseStart: 8, display: "Romans 12:8" }],
          explanation: "Paul instructs the one who gives to do so with generosity.",
        },
        {
          canonical: "Mercy",
          aliases: ["showing mercy"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Romans", chapterStart: 12, verseStart: 8, display: "Romans 12:8" }],
          explanation: "Paul instructs the one who shows mercy to do it cheerfully.",
        },
        {
          canonical: "Interpretation of Tongues",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 10, display: "1 Corinthians 12:10" }],
          explanation: "The interpretation of tongues is listed as its own distinct spiritual gift.",
        },
        {
          canonical: "Discerning of Spirits",
          aliases: ["distinguishing between spirits"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 10, display: "1 Corinthians 12:10" }],
          explanation: "\"Discerning of spirits\" is listed among the manifestations given for the common good.",
        },
        {
          canonical: "Leadership",
          aliases: ["governing", "administration"],
          score: 60,
          tier: "veil",
          references: [{ book: "Romans", chapterStart: 12, verseStart: 8, display: "Romans 12:8" }],
          explanation: "Paul instructs the one who leads to do so with diligence.",
        },
        {
          canonical: "Apostleship",
          aliases: ["apostles"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ephesians", chapterStart: 4, verseStart: 11, display: "Ephesians 4:11" }],
          explanation: "Christ gave some to be apostles as a gift to equip the church.",
        },
        {
          canonical: "Evangelism",
          aliases: ["evangelists"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ephesians", chapterStart: 4, verseStart: 11, display: "Ephesians 4:11" }],
          explanation: "Christ gave some to be evangelists as a gift to equip the church.",
        },
        {
          canonical: "Helps",
          aliases: ["helping"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 28, display: "1 Corinthians 12:28" }],
          explanation: "Paul lists \"helps\" among the gifts God has appointed in the church, alongside apostles and prophets.",
        },
      ],
    },
  ],
};
