import type { SeedDay } from "./types";

export const DAY_24: SeedDay = {
  dayNumber: 24,
  date: "2026-10-11",
  scriptureBonus: {
    displayText: "Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the strength of my life. Of whom shall I be afraid?",
    book: "Psalms",
    chapter: 27,
    verseStart: 1,
    referenceDisplay: "Psalm 27:1",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "David opens a psalm of confidence, grounding his fearlessness in the LORD's protection.",
    acceptedBookAliases: ["ps", "psalm"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a specific name given to hell, the grave, or the place of the dead in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific name the biblical text uses for the realm of the dead, hell, or a place of final judgment.",
      answers: [
        {
          canonical: "Sheol",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 37, verseStart: 35, display: "Genesis 37:35" }],
          explanation: "Jacob says he will go down to Sheol mourning for his son Joseph.",
        },
        {
          canonical: "Hades",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 16, verseStart: 18, display: "Matthew 16:18" }],
          explanation: "Jesus says the gates of Hades will not overpower his church.",
        },
        {
          canonical: "Gehenna",
          aliases: ["hell fire"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 5, verseStart: 22, display: "Matthew 5:22" }],
          explanation: "Jesus warns that whoever calls another a fool is in danger of Gehenna, the fire of hell.",
        },
        {
          canonical: "The Pit",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Isaiah", chapterStart: 14, verseStart: 15, display: "Isaiah 14:15" }],
          explanation: "Isaiah declares that the king of Babylon will be brought down to the pit.",
        },
        {
          canonical: "The Abyss",
          aliases: ["bottomless pit"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 8, verseStart: 31, display: "Luke 8:31" }],
          explanation: "The demons beg Jesus not to command them to depart into the Abyss.",
        },
        {
          canonical: "Tartarus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Peter", chapterStart: 2, verseStart: 4, display: "2 Peter 2:4" }],
          explanation: "Peter says God cast the sinning angels down to Tartarus, held for judgment.",
        },
        {
          canonical: "The Lake of Fire",
          aliases: ["lake of fire and sulfur"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 20, verseStart: 14, display: "Revelation 20:14" }],
          explanation: "Death and Hades are thrown into the lake of fire, called the second death.",
        },
        {
          canonical: "Abaddon",
          aliases: ["apollyon"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 9, verseStart: 11, display: "Revelation 9:11" }],
          explanation: "The angel of the Abyss is named Abaddon in Hebrew and Apollyon in Greek.",
        },
        {
          canonical: "The Outer Darkness",
          aliases: ["outer darkness"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 12, display: "Matthew 8:12" }],
          explanation: "Jesus warns that the sons of the kingdom will be thrown into the outer darkness.",
        },
        {
          canonical: "Topheth",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Jeremiah", chapterStart: 7, verseStart: 31, display: "Jeremiah 7:31" }],
          explanation: "Jeremiah condemns the high places of Topheth in the Valley of Hinnom, where judgment is pronounced.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name an insect or small creature mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any insect or small creature the biblical text explicitly names.",
      answers: [
        {
          canonical: "Locust",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 10, verseStart: 4, display: "Exodus 10:4" }],
          explanation: "God sends a plague of locusts on Egypt after Pharaoh refuses to let Israel go.",
        },
        {
          canonical: "Ant",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Proverbs", chapterStart: 6, verseStart: 6, display: "Proverbs 6:6" }],
          explanation: "The sluggard is told to consider the ant's ways and be wise.",
        },
        {
          canonical: "Bee",
          aliases: ["bees"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 14, verseStart: 8, display: "Judges 14:8" }],
          explanation: "Samson finds a swarm of bees and honey in the carcass of the lion he killed.",
        },
        {
          canonical: "Moth",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 6, verseStart: 19, display: "Matthew 6:19" }],
          explanation: "Jesus warns against storing treasures on earth where moth and rust destroy.",
        },
        {
          canonical: "Flea",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 24, verseStart: 14, display: "1 Samuel 24:14" }],
          explanation: "David asks Saul whom he is pursuing, comparing himself to a single flea.",
        },
        {
          canonical: "Gnat",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 23, verseStart: 24, display: "Matthew 23:24" }],
          explanation: "Jesus rebukes the Pharisees for straining out a gnat while swallowing a camel.",
        },
        {
          canonical: "Scorpion",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 10, verseStart: 19, display: "Luke 10:19" }],
          explanation: "Jesus gives his disciples authority to tread on serpents and scorpions.",
        },
        {
          canonical: "Spider",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Job", chapterStart: 8, verseStart: 14, display: "Job 8:14" }],
          explanation: "Bildad compares the godless person's trust to a spider's fragile web.",
        },
        {
          canonical: "Hornet",
          aliases: ["hornets"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 23, verseStart: 28, display: "Exodus 23:28" }],
          explanation: "God promises to send hornets ahead of Israel to drive out their enemies.",
        },
        {
          canonical: "Caterpillar",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 8, verseStart: 37, display: "1 Kings 8:37" }],
          explanation: "Solomon's temple dedication prayer names the caterpillar among crop-devouring judgments.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a cave or rock hideout mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific cave or rock refuge the biblical text explicitly names or clearly identifies by location.",
      answers: [
        {
          canonical: "Cave of Machpelah",
          aliases: ["machpelah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 23, verseStart: 9, display: "Genesis 23:9" }],
          explanation: "Abraham buys the cave of Machpelah from Ephron the Hittite as a burial site for Sarah.",
        },
        {
          canonical: "Cave of Adullam",
          aliases: ["adullam"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 22, verseStart: 1, display: "1 Samuel 22:1" }],
          explanation: "David flees to the cave of Adullam, where his family and 400 men gather to him.",
        },
        {
          canonical: "Cave at En Gedi",
          aliases: ["en gedi cave", "cave of en gedi"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 24, verseStart: 3, display: "1 Samuel 24:3" }],
          explanation: "Saul enters the cave at En Gedi to relieve himself, unaware David is hiding inside.",
        },
        {
          canonical: "Elijah's Cave at Horeb",
          aliases: ["cave at horeb", "cave on mount horeb"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 9, display: "1 Kings 19:9" }],
          explanation: "Elijah lodges in a cave at Horeb, where the LORD speaks to him in a still small voice.",
        },
        {
          canonical: "Obadiah's Cave",
          aliases: ["cave where obadiah hid the prophets"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 4, display: "1 Kings 18:4" }],
          explanation: "Obadiah hides a hundred prophets in two caves to save them from Jezebel.",
        },
        {
          canonical: "Cave of Makkedah",
          aliases: ["makkedah"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joshua", chapterStart: 10, verseStart: 16, display: "Joshua 10:16" }],
          explanation: "Five Amorite kings hide in the cave of Makkedah, where Joshua seals them in.",
        },
        {
          canonical: "Lot's Cave",
          aliases: ["the cave lot lived in"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 30, display: "Genesis 19:30" }],
          explanation: "Lot and his daughters take refuge in a cave after fleeing Zoar.",
        },
        {
          canonical: "Rock of Rimmon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 20, verseStart: 47, display: "Judges 20:47" }],
          explanation: "Six hundred surviving Benjamites flee to the rock of Rimmon for four months.",
        },
        {
          canonical: "Rock of Etam",
          aliases: ["cleft of the rock of etam"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Judges", chapterStart: 15, verseStart: 8, display: "Judges 15:8" }],
          explanation: "Samson goes to live in the cleft of the rock of Etam after striking down the Philistines.",
        },
        {
          canonical: "Sela Hammahlekoth",
          aliases: ["rock of escape", "rock of division"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 23, verseStart: 28, display: "1 Samuel 23:28" }],
          explanation: "Saul breaks off pursuing David at Sela Hammahlekoth, 'the rock of escape,' to fight the Philistines.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a place where Jesus performed a miracle.",
      instructions: "You get one guess.",
      whatCounts: "Any location the Gospels explicitly describe Jesus performing a miracle.",
      answers: [
        {
          canonical: "Cana",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 2, verseStart: 11, display: "John 2:11" }],
          explanation: "Jesus turns water into wine at a wedding in Cana, his first sign.",
        },
        {
          canonical: "Capernaum",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 1, verseStart: 21, display: "Mark 1:21" }],
          explanation: "Capernaum, Jesus' ministry base, is the site of many healings, including a paralytic lowered through a roof.",
        },
        {
          canonical: "Bethesda Pool",
          aliases: ["pool of bethesda"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 5, verseStart: 2, display: "John 5:2" }],
          explanation: "Jesus heals a man who had been an invalid for 38 years at the pool of Bethesda in Jerusalem.",
        },
        {
          canonical: "Nain",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 7, verseStart: 11, display: "Luke 7:11" }],
          explanation: "Jesus raises a widow's only son at the town of Nain.",
        },
        {
          canonical: "Gerasenes",
          aliases: ["gadara", "country of the gerasenes"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 1, display: "Mark 5:1" }],
          explanation: "Jesus casts demons into a herd of pigs in the region of the Gerasenes.",
        },
        {
          canonical: "Bethsaida",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 8, verseStart: 22, display: "Mark 8:22" }],
          explanation: "Jesus heals a blind man in stages at Bethsaida.",
        },
        {
          canonical: "Jericho",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 10, verseStart: 46, display: "Mark 10:46" }],
          explanation: "Jesus restores the sight of blind Bartimaeus as he leaves Jericho.",
        },
        {
          canonical: "Bethany",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 11, verseStart: 43, display: "John 11:43" }],
          explanation: "Jesus raises Lazarus from the dead at Bethany, near Jerusalem.",
        },
        {
          canonical: "Region of Tyre and Sidon",
          aliases: ["tyre and sidon", "syrophoenician region"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Mark", chapterStart: 7, verseStart: 24, verseEnd: 30, display: "Mark 7:24-30" }],
          explanation: "Jesus heals the Syrophoenician woman's daughter from a distance in the region of Tyre and Sidon.",
        },
        {
          canonical: "Jerusalem Temple Courts",
          aliases: ["temple courts after cleansing"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 21, verseStart: 14, display: "Matthew 21:14" }],
          explanation: "After cleansing the temple, Jesus heals the blind and lame who come to him in its courts.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a false god or idol named in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any false god, idol, or object of pagan worship the biblical text explicitly names.",
      answers: [
        {
          canonical: "Baal",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 21, display: "1 Kings 18:21" }],
          explanation: "Baal, the Canaanite storm god, is Israel's most persistent rival to the worship of the LORD.",
        },
        {
          canonical: "The Golden Calf",
          aliases: ["golden calf"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 32, verseStart: 4, display: "Exodus 32:4" }],
          explanation: "Aaron fashions a golden calf for Israel to worship while Moses is on Sinai.",
        },
        {
          canonical: "Ashtoreth",
          aliases: ["astarte"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 11, verseStart: 5, display: "1 Kings 11:5" }],
          explanation: "Solomon follows Ashtoreth, goddess of the Sidonians, in his later years.",
        },
        {
          canonical: "Dagon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 16, verseStart: 23, display: "Judges 16:23" }],
          explanation: "Dagon, the Philistine god, has a temple where Samson pulls down the pillars.",
        },
        {
          canonical: "Molech",
          aliases: ["molek", "milcom"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 18, verseStart: 21, display: "Leviticus 18:21" }],
          explanation: "Molech is the god associated with child sacrifice, explicitly forbidden in the Law.",
        },
        {
          canonical: "Chemosh",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 11, verseStart: 7, display: "1 Kings 11:7" }],
          explanation: "Chemosh, the national god of Moab, is worshiped on a high place Solomon builds.",
        },
        {
          canonical: "Asherah",
          aliases: ["asherah pole"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 25, display: "Judges 6:25" }],
          explanation: "Gideon is commanded to cut down his father's Asherah pole, an object of pagan worship.",
        },
        {
          canonical: "Artemis",
          aliases: ["diana of the ephesians"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 19, verseStart: 28, display: "Acts 19:28" }],
          explanation: "A riot breaks out in Ephesus in defense of the great goddess Artemis.",
        },
        {
          canonical: "Zeus",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 14, verseStart: 12, display: "Acts 14:12" }],
          explanation: "The crowd at Lystra mistakes Barnabas for Zeus after Paul heals a lame man.",
        },
        {
          canonical: "Rimmon",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 18, display: "2 Kings 5:18" }],
          explanation: "Naaman asks pardon for having to bow in the temple of Rimmon while accompanying his master.",
        },
      ],
    },
  ],
};
