import type { SeedDay } from "./types";

export const DAY_26: SeedDay = {
  dayNumber: 26,
  date: "2026-10-13",
  scriptureBonus: {
    displayText: "A friend loves at all times; and a brother is born for adversity.",
    book: "Proverbs",
    chapter: 17,
    verseStart: 17,
    referenceDisplay: "Proverbs 17:17",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A proverb contrasting the constancy of true friendship with the built-in loyalty expected of family.",
    acceptedBookAliases: ["prov"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a sibling of a well-known biblical figure.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly identifies as the brother or sister of a named figure.",
      answers: [
        {
          canonical: "Aaron",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 7, verseStart: 1, display: "Exodus 7:1" }],
          explanation: "Aaron is Moses' older brother and becomes Israel's first high priest.",
        },
        {
          canonical: "Miriam",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 20, display: "Exodus 15:20" }],
          explanation: "Miriam, sister of Moses and Aaron, leads the women in song after crossing the Red Sea.",
        },
        {
          canonical: "Andrew",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 1, verseStart: 40, verseEnd: 42, display: "John 1:40-42" }],
          explanation: "Andrew, Simon Peter's brother, is among the first disciples called by Jesus.",
        },
        {
          canonical: "Martha",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 11, verseStart: 1, display: "John 11:1" }],
          explanation: "Martha is the sister of Lazarus and Mary of Bethany.",
        },
        {
          canonical: "James Son of Zebedee",
          aliases: ["james", "james the greater", "brother of john"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 21, display: "Matthew 4:21" }],
          exclusions: ["james the less", "james son of alphaeus"],
          explanation: "James, brother of John, is one of the sons of Zebedee called from their fishing boat.",
        },
        {
          canonical: "Rachel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 16, verseEnd: 18, display: "Genesis 29:16-18" }],
          explanation: "Rachel is the younger sister of Leah; Jacob works fourteen years to marry them both.",
        },
        {
          canonical: "Esau",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 25, verseEnd: 26, display: "Genesis 25:25-26" }],
          explanation: "Esau is Jacob's elder twin brother, who sells his birthright for a bowl of stew.",
        },
        {
          canonical: "Moses",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 26, verseStart: 59, display: "Numbers 26:59" }],
          exclusions: ["aaron"],
          explanation: "Moses is the brother of Aaron and Miriam, all three children of Amram and Jochebed.",
        },
        {
          canonical: "Lazarus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 11, verseStart: 2, display: "John 11:2" }],
          exclusions: ["martha"],
          explanation: "Lazarus of Bethany is the brother of Martha and Mary, whom Jesus raises from the dead.",
        },
        {
          canonical: "Laban",
          aliases: ["rebekah's brother"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 24, verseStart: 29, display: "Genesis 24:29" }],
          explanation: "Laban is named as the brother of Rebekah, and later becomes Jacob's father-in-law.",
        },
        {
          canonical: "Nahor",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 11, verseStart: 27, display: "Genesis 11:27" }],
          explanation: "Nahor is Abraham's brother, and grandfather of Rebekah through his son Bethuel.",
        },
        {
          canonical: "Shimei",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Chronicles", chapterStart: 3, verseStart: 19, display: "1 Chronicles 3:19" }],
          explanation: "Shimei is named as the brother of Zerubbabel, the governor who leads the Jews back from exile.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a household servant or slave named in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any servant or slave the biblical text names directly, in any role.",
      answers: [
        {
          canonical: "Hagar",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 16, verseStart: 1, display: "Genesis 16:1" }],
          explanation: "Hagar is Sarah's Egyptian servant, given to Abraham to bear a child.",
        },
        {
          canonical: "Eliezer of Damascus",
          aliases: ["eliezer"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 15, verseStart: 2, display: "Genesis 15:2" }],
          explanation: "Eliezer is Abraham's chief servant, once considered his heir before Isaac was born.",
        },
        {
          canonical: "Onesimus",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Philemon", chapterStart: 1, verseStart: 10, display: "Philemon 1:10" }],
          explanation: "Onesimus is a runaway slave of Philemon whom Paul sends back as a beloved brother in Christ.",
        },
        {
          canonical: "Gehazi",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 4, verseStart: 12, display: "2 Kings 4:12" }],
          explanation: "Gehazi serves as Elisha's attendant and is later struck with leprosy for his greed.",
        },
        {
          canonical: "Ziba",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 9, verseStart: 2, display: "2 Samuel 9:2" }],
          explanation: "Ziba, a former servant of Saul's household, is placed in charge of Mephibosheth's land by David.",
        },
        {
          canonical: "Rhoda",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 13, display: "Acts 12:13" }],
          explanation: "Rhoda, a servant girl, is so overjoyed at Peter's voice at the door that she forgets to let him in.",
        },
        {
          canonical: "Zilpah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 24, display: "Genesis 29:24" }],
          explanation: "Zilpah, Leah's servant, is given to Jacob and bears Gad and Asher.",
        },
        {
          canonical: "Bilhah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 29, display: "Genesis 29:29" }],
          explanation: "Bilhah, Rachel's servant, is given to Jacob and bears Dan and Naphtali.",
        },
        {
          canonical: "Nathan's Servant Malchus",
          aliases: ["malchus"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "John", chapterStart: 18, verseStart: 10, display: "John 18:10" }],
          exclusions: [],
          explanation: "Malchus, a servant of the high priest, has his ear cut off by Peter at Jesus' arrest and is then healed.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name one of a set of twins in the Bible (either twin, by name).",
      instructions: "You get one guess.",
      whatCounts: "Any individual the biblical text explicitly identifies as a twin.",
      answers: [
        {
          canonical: "Esau",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 24, verseEnd: 26, display: "Genesis 25:24-26" }],
          explanation: "Esau is born first, gripping his twin brother Jacob's heel.",
        },
        {
          canonical: "Jacob",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 24, verseEnd: 26, display: "Genesis 25:24-26" }],
          explanation: "Jacob is born second, holding Esau's heel, and is later renamed Israel.",
        },
        {
          canonical: "Perez",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 38, verseStart: 29, display: "Genesis 38:29" }],
          explanation: "Perez, twin son of Judah and Tamar, pushes ahead of his brother Zerah to be born first.",
        },
        {
          canonical: "Zerah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 38, verseStart: 30, display: "Genesis 38:30" }],
          explanation: "Zerah, Perez's twin, first puts out a hand marked with a scarlet thread before his brother is born.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a mother named in the Bible (other than Eve or Mary the mother of Jesus).",
      instructions: "You get one guess.",
      whatCounts: "Any woman the biblical text explicitly identifies as someone's mother.",
      answers: [
        {
          canonical: "Sarah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 21, verseStart: 2, display: "Genesis 21:2" }],
          explanation: "Sarah gives birth to Isaac in her old age, as God had promised.",
        },
        {
          canonical: "Hannah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 20, display: "1 Samuel 1:20" }],
          explanation: "Hannah, long barren, prays for a son and gives birth to Samuel.",
        },
        {
          canonical: "Elizabeth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 57, display: "Luke 1:57" }],
          explanation: "Elizabeth gives birth to John the Baptist in her old age.",
        },
        {
          canonical: "Rebekah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 24, display: "Genesis 25:24" }],
          explanation: "Rebekah gives birth to twin sons, Esau and Jacob.",
        },
        {
          canonical: "Bathsheba",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 12, verseStart: 24, display: "2 Samuel 12:24" }],
          explanation: "Bathsheba, David's wife, is the mother of Solomon.",
        },
        {
          canonical: "Eunice",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Timothy", chapterStart: 1, verseStart: 5, display: "2 Timothy 1:5" }],
          explanation: "Eunice, Timothy's mother, is remembered for her sincere faith.",
        },
        {
          canonical: "Jochebed",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 6, verseStart: 20, display: "Exodus 6:20" }],
          explanation: "Jochebed is the mother of Moses, Aaron, and Miriam.",
        },
        {
          canonical: "Zipporah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 2, verseStart: 21, verseEnd: 22, display: "Exodus 2:21-22" }],
          explanation: "Zipporah, Moses' wife, bears him a son named Gershom.",
        },
        {
          canonical: "Lois",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Timothy", chapterStart: 1, verseStart: 5, display: "2 Timothy 1:5" }],
          exclusions: ["eunice"],
          explanation: "Lois, Timothy's grandmother, is named alongside his mother Eunice for her sincere faith.",
          inclusionNotes: "Lois is a grandmother, not a mother, but is included here as she is one of only a handful of named female ancestors praised by name for faith.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a person who betrayed or denied someone in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly describes as betraying or denying another person.",
      answers: [
        {
          canonical: "Judas Iscariot",
          aliases: ["judas"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 14, verseEnd: 16, display: "Matthew 26:14-16" }],
          explanation: "Judas Iscariot betrays Jesus to the chief priests for thirty pieces of silver.",
        },
        {
          canonical: "Peter",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 69, verseEnd: 75, display: "Matthew 26:69-75" }],
          explanation: "Peter denies knowing Jesus three times before the rooster crows.",
        },
        {
          canonical: "Delilah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 16, verseStart: 18, verseEnd: 19, display: "Judges 16:18-19" }],
          explanation: "Delilah betrays Samson to the Philistines by discovering the secret of his strength.",
        },
        {
          canonical: "Ahithophel",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 15, verseStart: 12, display: "2 Samuel 15:12" }],
          explanation: "Ahithophel, David's trusted counselor, defects to join Absalom's conspiracy.",
        },
        {
          canonical: "Joab",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 3, verseStart: 27, display: "2 Samuel 3:27" }],
          explanation: "Joab treacherously kills Abner under the guise of a peaceful meeting, avenging his brother.",
        },
      ],
    },
  ],
};
