import type { SeedDay } from "./types";

export const DAY_25: SeedDay = {
  dayNumber: 25,
  date: "2026-10-12",
  scriptureBonus: {
    displayText: "Now therefore fear Yahweh, and serve him in sincerity and in truth... but if it seems evil to you to serve Yahweh, choose for yourselves this day whom you will serve... but as for me and my house, we will serve Yahweh.",
    book: "Joshua",
    chapter: 24,
    verseStart: 15,
    referenceDisplay: "Joshua 24:15",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Joshua challenges Israel at Shechem to choose whom they will serve, declaring his own household's allegiance to the LORD.",
    acceptedBookAliases: ["josh"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a well-known \"I am\" statement Jesus made in John's Gospel.",
      instructions: "You get one guess.",
      whatCounts: "Any of Jesus' 'I am' declarations recorded in the Gospel of John. Answer with what he says he is (e.g. 'the Bread of Life').",
      answers: [
        {
          canonical: "The Bread of Life",
          aliases: ["bread of life"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 6, verseStart: 35, display: "John 6:35" }],
          explanation: "Jesus tells the crowd after feeding the five thousand, 'I am the bread of life.'",
        },
        {
          canonical: "The Light of the World",
          aliases: ["light of the world"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 8, verseStart: 12, display: "John 8:12" }],
          explanation: "Jesus declares 'I am the light of the world; he who follows me will not walk in the darkness.'",
        },
        {
          canonical: "The Good Shepherd",
          aliases: ["good shepherd"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 10, verseStart: 11, display: "John 10:11" }],
          explanation: "Jesus says 'I am the good shepherd; the good shepherd lays down his life for the sheep.'",
        },
        {
          canonical: "The Way, the Truth, and the Life",
          aliases: ["way truth and life", "the way the truth the life"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 14, verseStart: 6, display: "John 14:6" }],
          explanation: "Jesus tells Thomas, 'I am the way, the truth, and the life. No one comes to the Father, except through me.'",
        },
        {
          canonical: "The Resurrection and the Life",
          aliases: ["resurrection and the life"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 11, verseStart: 25, display: "John 11:25" }],
          explanation: "Jesus tells Martha before raising Lazarus, 'I am the resurrection and the life.'",
        },
        {
          canonical: "The Door",
          aliases: ["the gate", "door of the sheep"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 10, verseStart: 9, display: "John 10:9" }],
          explanation: "Jesus says 'I am the door. If anyone enters in by me, he will be saved.'",
        },
        {
          canonical: "The True Vine",
          aliases: ["true vine"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 15, verseStart: 1, display: "John 15:1" }],
          explanation: "Jesus tells his disciples, 'I am the true vine, and my Father is the farmer.'",
        },
        {
          canonical: "Before Abraham Was, I Am",
          aliases: ["before abraham was born i am", "i am before abraham"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "John", chapterStart: 8, verseStart: 58, display: "John 8:58" }],
          explanation: "Jesus tells the Jews, 'before Abraham came into existence, I AM,' claiming the divine name for himself.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a chariot or its rider explicitly mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific chariot, or the person riding it, that the biblical text explicitly names or describes.",
      answers: [
        {
          canonical: "Pharaoh's Chariots",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 14, verseStart: 7, display: "Exodus 14:7" }],
          explanation: "Pharaoh takes six hundred chosen chariots to pursue Israel to the Red Sea.",
        },
        {
          canonical: "Elijah's Fiery Chariot",
          aliases: ["chariot of fire"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Kings", chapterStart: 2, verseStart: 11, display: "2 Kings 2:11" }],
          explanation: "A chariot of fire and horses of fire take Elijah up to heaven in a whirlwind.",
        },
        {
          canonical: "Ahab's Chariot",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 35, display: "1 Kings 22:35" }],
          explanation: "King Ahab is propped up in his chariot, mortally wounded, until he dies that evening.",
        },
        {
          canonical: "The Ethiopian Eunuch's Chariot",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 28, display: "Acts 8:28" }],
          explanation: "Philip joins the Ethiopian eunuch as he reads Isaiah in his chariot.",
        },
        {
          canonical: "Sisera's Chariot",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 4, verseStart: 15, display: "Judges 4:15" }],
          explanation: "Sisera abandons his chariot to flee on foot when the LORD routs his army before Barak.",
        },
        {
          canonical: "Solomon's Chariots",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 10, verseStart: 26, display: "1 Kings 10:26" }],
          explanation: "Solomon gathers fourteen hundred chariots, stationed in chariot cities and with him in Jerusalem.",
        },
        {
          canonical: "Jehu's Chariot",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 9, verseStart: 20, display: "2 Kings 9:20" }],
          explanation: "A watchman recognizes Jehu's approach by his furious chariot driving.",
        },
        {
          canonical: "Naaman's Chariot",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 9, display: "2 Kings 5:9" }],
          explanation: "Naaman arrives at Elisha's door with his horses and chariot, seeking healing.",
        },
        {
          canonical: "Absalom's Chariot",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 15, verseStart: 1, display: "2 Samuel 15:1" }],
          explanation: "Absalom prepares a chariot and horses with fifty men to run before him.",
        },
        {
          canonical: "The Chariots of Fire Around Elisha",
          aliases: ["chariots of fire at dothan"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 6, verseStart: 17, display: "2 Kings 6:17" }],
          explanation: "Elisha's servant sees the mountain full of horses and chariots of fire surrounding them at Dothan.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a specific price, in silver or gold, paid for something in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific amount of silver or gold the biblical text explicitly names as a price paid for a person, object, or land.",
      answers: [
        {
          canonical: "Thirty Pieces of Silver",
          aliases: ["30 pieces of silver"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 15, display: "Matthew 26:15" }],
          explanation: "The chief priests weigh out thirty pieces of silver to Judas to betray Jesus.",
        },
        {
          canonical: "Twenty Shekels of Silver",
          aliases: ["20 shekels of silver"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 37, verseStart: 28, display: "Genesis 37:28" }],
          explanation: "Joseph's brothers sell him to the Ishmaelites for twenty pieces of silver.",
        },
        {
          canonical: "Four Hundred Shekels of Silver",
          aliases: ["400 shekels of silver"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 23, verseStart: 16, display: "Genesis 23:16" }],
          explanation: "Abraham weighs out four hundred shekels of silver to buy the cave of Machpelah.",
        },
        {
          canonical: "Fifty Shekels of Silver",
          aliases: ["50 shekels of silver"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 24, verseStart: 24, display: "2 Samuel 24:24" }],
          explanation: "David pays Araunah fifty shekels of silver for his threshing floor and oxen.",
        },
        {
          canonical: "Seventeen Shekels of Silver",
          aliases: ["17 shekels of silver"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 32, verseStart: 9, display: "Jeremiah 32:9" }],
          explanation: "Jeremiah buys a field from his cousin Hanamel for seventeen shekels of silver.",
        },
        {
          canonical: "A Talent of Gold",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 12, verseStart: 30, display: "2 Samuel 12:30" }],
          explanation: "David takes the crown of the Ammonite king, weighing a talent of gold, for his own head.",
        },
        {
          canonical: "A Talent of Silver",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 20, verseStart: 39, display: "1 Kings 20:39" }],
          explanation: "A soldier is told his life will answer for the escaped captive, or he must pay a talent of silver.",
        },
        {
          canonical: "Two Hundred Shekels of Silver",
          aliases: ["200 shekels of silver"],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 7, verseStart: 21, display: "Joshua 7:21" }],
          explanation: "Achan confesses to taking two hundred shekels of silver among the plunder of Jericho.",
        },
        {
          canonical: "A Hundred Pieces of Silver",
          aliases: ["100 pieces of silver", "hundred kesitah"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 33, verseStart: 19, display: "Genesis 33:19" }],
          explanation: "Jacob buys a plot of land near Shechem for a hundred pieces of silver.",
        },
        {
          canonical: "Thirty Shekels for a Gored Slave",
          aliases: ["30 shekels for a slave"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 21, verseStart: 32, display: "Exodus 21:32" }],
          explanation: "The Law sets thirty shekels of silver as the price owed if an ox gores a male or female slave.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a specific tax or tribute mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific tax, tribute, or toll payment the biblical text explicitly describes.",
      answers: [
        {
          canonical: "Temple Tax",
          aliases: ["two-drachma tax", "the didrachma"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 17, verseStart: 24, display: "Matthew 17:24" }],
          explanation: "Collectors of the two-drachma temple tax ask Peter whether Jesus pays it.",
        },
        {
          canonical: "Tribute Money to Caesar",
          aliases: ["the denarius of tribute", "render unto caesar tax"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 22, verseStart: 19, display: "Matthew 22:19" }],
          explanation: "Jesus asks for the coin used to pay the poll tax before saying to render to Caesar what is Caesar's.",
        },
        {
          canonical: "Half-Shekel Atonement Money",
          aliases: ["census tax", "atonement money"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 13, display: "Exodus 30:13" }],
          explanation: "Every man counted in the census pays a half shekel as atonement money for the tabernacle service.",
        },
        {
          canonical: "Tribute Judah Paid Egypt",
          aliases: ["jehoiakim's tribute to pharaoh"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 35, display: "2 Kings 23:35" }],
          explanation: "Jehoiakim taxes the land to pay the tribute Pharaoh Necho demands.",
        },
        {
          canonical: "Tribute Israel Paid Assyria",
          aliases: ["menahem's tribute to pul"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 15, verseStart: 19, verseEnd: 20, display: "2 Kings 15:19-20" }],
          explanation: "King Menahem exacts silver from Israel's wealthy to pay tribute to Pul, king of Assyria.",
        },
        {
          canonical: "Moabite Tribute of Lambs",
          aliases: ["mesha's tribute of wool"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 3, verseStart: 4, display: "2 Kings 3:4" }],
          explanation: "Mesha, king of Moab, regularly pays Israel tribute of lambs and rams' wool.",
        },
        {
          canonical: "Toll and Tribute Named in Ezra",
          aliases: ["custom toll and tribute"],
          score: 60,
          tier: "veil",
          references: [{ book: "Ezra", chapterStart: 4, verseStart: 13, display: "Ezra 4:13" }],
          explanation: "Jerusalem's opponents warn the Persian king that a rebuilt city will stop paying custom, toll, and tribute.",
        },
        {
          canonical: "Gifts Brought to Solomon",
          aliases: ["tribute to solomon"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 10, verseStart: 25, display: "1 Kings 10:25" }],
          explanation: "Visitors bring Solomon tribute of silver, gold, garments, and spices year by year.",
        },
        {
          canonical: "Tribute David Imposed on Aram",
          aliases: ["syrians brought tribute to david"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 8, verseStart: 6, display: "2 Samuel 8:6" }],
          explanation: "The LORD gives David victory over the Arameans of Damascus, who bring him tribute.",
        },
        {
          canonical: "The Coin in the Fish's Mouth",
          aliases: ["stater in the fish", "the fish's coin"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 17, verseStart: 27, display: "Matthew 17:27" }],
          explanation: "Jesus tells Peter to catch a fish, find a coin in its mouth, and use it to pay the temple tax for them both.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name an instance of dancing mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific instance, or explicit mention, of dancing the biblical text describes.",
      answers: [
        {
          canonical: "Miriam's Dance at the Red Sea",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 15, verseStart: 20, display: "Exodus 15:20" }],
          explanation: "Miriam takes a tambourine and leads the women in dancing after crossing the Red Sea.",
        },
        {
          canonical: "Dance Around the Golden Calf",
          aliases: ["dancing at the golden calf"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 32, verseStart: 19, display: "Exodus 32:19" }],
          explanation: "Moses sees the people dancing around the golden calf and shatters the tablets in anger.",
        },
        {
          canonical: "David's Dance Before the Ark",
          aliases: ["david dancing before the ark"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 6, verseStart: 14, display: "2 Samuel 6:14" }],
          explanation: "David dances before the LORD with all his might as the ark is brought into Jerusalem.",
        },
        {
          canonical: "Herodias's Daughter's Dance",
          aliases: ["salome's dance", "the daughter of herodias dancing"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 6, display: "Matthew 14:6" }],
          explanation: "Herodias's daughter dances before Herod, so pleasing him that he offers her anything she asks.",
        },
        {
          canonical: "Women's Dance Celebrating Victory over Goliath",
          aliases: ["women dancing after david killed goliath"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 18, verseStart: 6, display: "1 Samuel 18:6" }],
          explanation: "Women come out of Israel's cities singing and dancing to celebrate David's victory over Goliath.",
        },
        {
          canonical: "The Prodigal Son's Homecoming Dance",
          aliases: ["dancing at the prodigal son's party"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 15, verseStart: 25, display: "Luke 15:25" }],
          explanation: "The elder brother hears music and dancing as he returns from the field to his father's feast.",
        },
        {
          canonical: "Dance of the Daughters of Shiloh",
          aliases: ["dancing daughters of shiloh"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 21, verseStart: 21, display: "Judges 21:21" }],
          explanation: "The Benjamites are told to watch for the daughters of Shiloh coming out to dance at a feast.",
        },
        {
          canonical: "Jephthah's Daughter's Dance to Greet Him",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 11, verseStart: 34, display: "Judges 11:34" }],
          explanation: "Jephthah's daughter comes out to meet him with tambourines and dancing after his victory.",
        },
        {
          canonical: "Dancing Turned to Mourning",
          aliases: ["our dance is turned into mourning"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Lamentations", chapterStart: 5, verseStart: 15, display: "Lamentations 5:15" }],
          explanation: "Lamentations mourns that joy has ceased and Israel's dancing has turned into mourning.",
        },
        {
          canonical: "\"A Time to Dance\"",
          aliases: ["time to dance ecclesiastes"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Ecclesiastes", chapterStart: 3, verseStart: 4, display: "Ecclesiastes 3:4" }],
          explanation: "Ecclesiastes names a time to mourn and 'a time to dance' among life's appointed seasons.",
        },
      ],
    },
  ],
};
