import type { SeedDay } from "./types";

export const DAY_22: SeedDay = {
  dayNumber: 22,
  date: "2026-10-09",
  scriptureBonus: {
    displayText: "Yahweh is my rock, my fortress, and my deliverer; my God, my rock, in whom I take refuge.",
    book: "Psalms",
    chapter: 18,
    verseStart: 2,
    referenceDisplay: "Psalm 18:2",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "David praises God as his protector after being delivered from Saul and his other enemies.",
    acceptedBookAliases: ["psalm", "psalms"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person's last words or dying statement recorded in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any final spoken words or dying statement the biblical text explicitly attributes to a specific person.",
      answers: [
        {
          canonical: "\"It Is Finished\"",
          aliases: ["it is finished", "tetelestai"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 19, verseStart: 30, display: "John 19:30" }],
          explanation: "Jesus speaks his final word from the cross, declaring his work complete before he dies.",
        },
        {
          canonical: "\"Father, Into Your Hands I Commit My Spirit\"",
          aliases: ["into your hands i commit my spirit"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 46, display: "Luke 23:46" }],
          explanation: "Jesus cries out these final words before breathing his last on the cross.",
        },
        {
          canonical: "Stephen's \"Lord Jesus, Receive My Spirit\"",
          aliases: ["lord jesus receive my spirit", "stephen's dying words"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 7, verseStart: 59, display: "Acts 7:59" }],
          explanation: "Stephen calls out these words as he is being stoned to death, the first Christian martyr.",
        },
        {
          canonical: "Joshua's \"As for Me and My House\"",
          aliases: ["as for me and my house", "choose this day"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 24, verseStart: 15, display: "Joshua 24:15" }],
          explanation: "In his farewell address, Joshua declares that he and his household will serve the LORD.",
        },
        {
          canonical: "Jacob's Blessing on His Sons",
          aliases: ["jacob's final blessing", "jacob's deathbed blessing"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 49, verseStart: 1, display: "Genesis 49:1" }],
          explanation: "Jacob gathers his sons to pronounce a final blessing over each of them before he dies.",
        },
        {
          canonical: "Moses' Blessing on Israel",
          aliases: ["moses' final blessing", "moses' deathbed blessing"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Deuteronomy", chapterStart: 33, verseStart: 1, display: "Deuteronomy 33:1" }],
          explanation: "Moses blesses the tribes of Israel by name shortly before his death on Mount Nebo.",
        },
        {
          canonical: "David's Last Words",
          aliases: ["the last words of david"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 23, verseStart: 1, display: "2 Samuel 23:1" }],
          explanation: "Scripture explicitly introduces a poetic oracle as \"the last words of David.\"",
        },
        {
          canonical: "Elisha's Final Prophecy to Joash",
          aliases: ["elisha's dying prophecy"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 13, verseStart: 14, display: "2 Kings 13:14" }],
          explanation: "On his deathbed, Elisha gives King Joash a prophecy about victory over Aram.",
        },
        {
          canonical: "Samson's \"Let Me Die with the Philistines\"",
          aliases: ["let me die with the philistines"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Judges", chapterStart: 16, verseStart: 30, display: "Judges 16:30" }],
          explanation: "Samson prays this final request before pushing down the pillars of the Philistine temple.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a feature of Solomon's Temple.",
      instructions: "You get one guess.",
      whatCounts: "Any specific furnishing, room, or structural feature of Solomon's Temple the biblical text describes.",
      answers: [
        {
          canonical: "The Most Holy Place",
          aliases: ["holy of holies"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 6, verseStart: 16, display: "1 Kings 6:16" }],
          explanation: "Solomon builds an inner sanctuary, the Most Holy Place, to house the ark of the covenant.",
        },
        {
          canonical: "The Bronze Altar",
          aliases: ["altar of burnt offering"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Chronicles", chapterStart: 4, verseStart: 1, display: "2 Chronicles 4:1" }],
          explanation: "Solomon makes a great bronze altar for burnt offerings in the temple courtyard.",
        },
        {
          canonical: "The Bronze Sea",
          aliases: ["molten sea", "the sea"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 7, verseStart: 23, display: "1 Kings 7:23" }],
          explanation: "Huram casts an enormous round bronze basin, the Sea, resting on twelve bronze oxen.",
        },
        {
          canonical: "Jachin and Boaz",
          aliases: ["the two pillars", "jachin", "boaz"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 7, verseStart: 21, display: "1 Kings 7:21" }],
          explanation: "Solomon sets up two bronze pillars at the temple porch, naming them Jachin and Boaz.",
        },
        {
          canonical: "The Golden Lampstands",
          aliases: ["ten lampstands"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 7, verseStart: 49, display: "1 Kings 7:49" }],
          explanation: "Ten gold lampstands, five on each side, stand before the inner sanctuary.",
        },
        {
          canonical: "The Cherubim Over the Ark",
          aliases: ["cherubim in the inner sanctuary"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 6, verseStart: 23, display: "1 Kings 6:23" }],
          explanation: "Solomon carves two large olive-wood cherubim, overlaid with gold, to stand over the ark.",
        },
        {
          canonical: "The Ten Bronze Basins",
          aliases: ["ten lavers"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 7, verseStart: 38, display: "1 Kings 7:38" }],
          explanation: "Ten bronze basins on wheeled stands are made for washing the sacrifices.",
        },
        {
          canonical: "The Inner Veil",
          aliases: ["the temple curtain", "the veil"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Chronicles", chapterStart: 3, verseStart: 14, display: "2 Chronicles 3:14" }],
          explanation: "Solomon makes a veil of blue, purple, and crimson yarn worked with cherubim to screen the inner sanctuary.",
        },
        {
          canonical: "The Golden Altar of Incense",
          aliases: ["altar of incense"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 6, verseStart: 22, display: "1 Kings 6:22" }],
          explanation: "Solomon overlays the altar belonging to the inner sanctuary entirely with gold.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name an ancestor of Jesus listed in his genealogy.",
      instructions: "You get one guess.",
      whatCounts: "Any person explicitly named in Jesus' genealogy in Matthew 1 or Luke 3.",
      answers: [
        {
          canonical: "David",
          aliases: ["king david"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 6, display: "Matthew 1:6" }],
          explanation: "David anchors both genealogies as Israel's great king and ancestor of the Messiah.",
        },
        {
          canonical: "Abraham",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 2, display: "Matthew 1:2" }],
          explanation: "Matthew opens Jesus' genealogy with Abraham, father of the covenant people.",
        },
        {
          canonical: "Ruth",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Ruth the Moabite is named as the mother of Obed in Jesus' line.",
        },
        {
          canonical: "Boaz",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Boaz, Ruth's kinsman-redeemer husband, is named in the genealogy.",
        },
        {
          canonical: "Tamar",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 3, display: "Matthew 1:3" }],
          explanation: "Tamar is named as the mother of Perez and Zerah by Judah.",
        },
        {
          canonical: "Rahab",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Rahab of Jericho is named as the mother of Boaz.",
        },
        {
          canonical: "Jesse",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Jesse, David's father, appears in the line leading to Jesus.",
        },
        {
          canonical: "Zerubbabel",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 12, display: "Matthew 1:12" }],
          explanation: "Zerubbabel, who led the return from Babylonian exile, is named in the post-exilic generations.",
        },
        {
          canonical: "Salmon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Salmon is named as the father of Boaz by Rahab.",
        },
        {
          canonical: "Nahshon",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 4, display: "Matthew 1:4" }],
          explanation: "Nahshon, a tribal leader of Judah in the wilderness generation, appears in the genealogy.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name an altar built in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any altar the biblical text explicitly describes a person building, apart from the tabernacle's own altars.",
      answers: [
        {
          canonical: "Noah's Altar",
          aliases: ["noah's altar after the flood"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 8, verseStart: 20, display: "Genesis 8:20" }],
          explanation: "Noah builds an altar and offers burnt offerings after leaving the ark.",
        },
        {
          canonical: "Abraham's Altar at Moriah",
          aliases: ["altar of isaac's sacrifice", "moriah altar"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 22, verseStart: 9, display: "Genesis 22:9" }],
          explanation: "Abraham builds an altar to sacrifice Isaac before God provides a ram instead.",
        },
        {
          canonical: "Jacob's Altar at Bethel",
          aliases: ["el elohe israel", "bethel altar"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 35, verseStart: 7, display: "Genesis 35:7" }],
          explanation: "Jacob builds an altar at Bethel, the site of his earlier vision of the ladder to heaven.",
        },
        {
          canonical: "Elijah's Altar on Carmel",
          aliases: ["mount carmel altar", "elijah's altar"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 32, display: "1 Kings 18:32" }],
          explanation: "Elijah rebuilds the LORD's altar and calls down fire in his contest with Baal's prophets.",
        },
        {
          canonical: "Gideon's Altar",
          aliases: ["the lord is peace altar", "jehovah shalom"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 24, display: "Judges 6:24" }],
          explanation: "Gideon builds an altar named 'The LORD is Peace' after his encounter with the angel.",
        },
        {
          canonical: "Joshua's Altar on Mount Ebal",
          aliases: ["mount ebal altar"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joshua", chapterStart: 8, verseStart: 30, display: "Joshua 8:30" }],
          explanation: "Joshua builds an altar of uncut stones on Mount Ebal as commanded by Moses.",
        },
        {
          canonical: "David's Altar on Araunah's Threshing Floor",
          aliases: ["araunah's threshing floor", "araunah's altar"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 24, verseStart: 25, display: "2 Samuel 24:25" }],
          explanation: "David buys Araunah's threshing floor and builds an altar to stop the plague on Israel.",
        },
        {
          canonical: "Moses' Altar Called Yahweh Nissi",
          aliases: ["yahweh nissi", "the lord is my banner"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 17, verseStart: 15, display: "Exodus 17:15" }],
          explanation: "Moses builds an altar named 'The LORD is my Banner' after victory over the Amalekites.",
        },
        {
          canonical: "Balaam's Seven Altars",
          aliases: ["balaam's altars", "seven altars"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Numbers", chapterStart: 23, verseStart: 1, display: "Numbers 23:1" }],
          explanation: "Balaam has Balak build seven altars before each of his attempts to curse Israel.",
        },
        {
          canonical: "The Witness Altar of the Transjordan Tribes",
          aliases: ["altar of witness", "altar ed"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Joshua", chapterStart: 22, verseStart: 10, display: "Joshua 22:10" }],
          explanation: "Reuben, Gad, and half of Manasseh build a large altar by the Jordan as a witness, not for sacrifice, nearly sparking civil war until explained.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a natural disaster or catastrophe described in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any flood, earthquake, famine, storm, or similar natural catastrophe the biblical text explicitly describes.",
      answers: [
        {
          canonical: "The Flood",
          aliases: ["noah's flood", "great flood"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 7, verseStart: 17, display: "Genesis 7:17" }],
          explanation: "A flood covers the whole earth in Noah's day, the archetypal biblical catastrophe.",
        },
        {
          canonical: "Famine in Joseph's Egypt",
          aliases: ["seven year famine", "joseph's famine"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 54, display: "Genesis 41:54" }],
          explanation: "A seven-year famine strikes Egypt and the surrounding region, foreseen by Joseph.",
        },
        {
          canonical: "The Storm Jesus Calmed",
          aliases: ["storm on the sea of galilee", "great storm"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 4, verseStart: 37, display: "Mark 4:37" }],
          explanation: "A furious storm threatens to swamp the disciples' boat before Jesus calms it.",
        },
        {
          canonical: "Earthquake at the Crucifixion",
          aliases: ["earthquake at jesus' death"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 51, display: "Matthew 27:51" }],
          explanation: "The earth shakes and rocks split as Jesus dies on the cross.",
        },
        {
          canonical: "Famine in Elijah's Time",
          aliases: ["three year drought", "elijah's drought"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 1, display: "1 Kings 17:1" }],
          explanation: "Elijah declares a drought lasting three and a half years as judgment on Ahab's Israel.",
        },
        {
          canonical: "Earthquake at Korah's Rebellion",
          aliases: ["korah's earthquake", "ground opening for korah"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 16, verseStart: 31, display: "Numbers 16:31" }],
          explanation: "The ground splits open beneath Korah's rebellion, swallowing them alive.",
        },
        {
          canonical: "Earthquake at Paul and Silas's Prison",
          aliases: ["philippi earthquake", "paul and silas prison earthquake"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 26, display: "Acts 16:26" }],
          explanation: "A sudden earthquake shakes the Philippian jail's foundations and opens every door.",
        },
        {
          canonical: "The Storm on Paul's Voyage to Rome",
          aliases: ["paul's shipwreck", "euroclydon"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 14, display: "Acts 27:14" }],
          explanation: "A violent northeaster wrecks Paul's ship on the way to Rome, though all aboard survive.",
        },
        {
          canonical: "The Earthquake in Uzziah's Reign",
          aliases: ["uzziah's earthquake", "amos' earthquake"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Amos", chapterStart: 1, verseStart: 1, display: "Amos 1:1" }],
          explanation: "Amos dates his prophecy to two years before a memorable earthquake in King Uzziah's reign.",
        },
        {
          canonical: "The Famine in Samaria During the Siege",
          aliases: ["siege of samaria famine", "donkey's head famine"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 6, verseStart: 25, display: "2 Kings 6:25" }],
          explanation: "During Ben-Hadad's siege of Samaria, famine grows so severe a donkey's head sells for eighty pieces of silver.",
        },
      ],
    },
  ],
};
