import type { SeedDay } from "./types";

export const DAY_23: SeedDay = {
  dayNumber: 23,
  date: "2026-10-10",
  scriptureBonus: {
    displayText:
      "For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, that no one would boast.",
    book: "Ephesians",
    chapter: 2,
    verseStart: 8,
    verseEnd: 9,
    referenceDisplay: "Ephesians 2:8-9",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul summarizes salvation as an unearned gift received through faith, not achieved by works.",
    acceptedBookAliases: ["eph"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a bird mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any bird explicitly named in the biblical text.",
      answers: [
        {
          canonical: "Dove",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 16, display: "Matthew 3:16" }],
          explanation: "The Spirit of God descends on Jesus at his baptism like a dove.",
        },
        {
          canonical: "Raven",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 4, verseEnd: 6, display: "1 Kings 17:4-6" }],
          explanation: "Ravens bring Elijah bread and meat by the brook Cherith at God's command.",
        },
        {
          canonical: "Eagle",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 4, display: "Exodus 19:4" }],
          explanation: "God tells Israel he bore them out of Egypt 'on eagles' wings.'",
        },
        {
          canonical: "Sparrow",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 10, verseStart: 29, display: "Matthew 10:29" }],
          explanation: "Jesus says not even a sparrow falls to the ground apart from the Father's knowledge.",
        },
        {
          canonical: "Rooster",
          aliases: ["cock", "cockerel"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 34, display: "Matthew 26:34" }],
          explanation: "Jesus tells Peter a rooster will crow before he denies him three times.",
        },
        {
          canonical: "Quail",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 16, verseStart: 13, display: "Exodus 16:13" }],
          explanation: "Quail cover the Israelite camp in the evening, providing meat in the wilderness.",
        },
        {
          canonical: "Owl",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 16, verseEnd: 17, display: "Leviticus 11:16-17" }],
          explanation: "The owl is listed among the birds Israel was forbidden to eat.",
        },
        {
          canonical: "Stork",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 19, display: "Leviticus 11:19" }],
          explanation: "The stork is named among the unclean birds in Israel's dietary law.",
        },
        {
          canonical: "Vulture",
          aliases: ["kite"],
          score: 60,
          tier: "veil",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 13, display: "Leviticus 11:13" }],
          explanation: "The vulture is the first bird named on the unclean-birds list.",
        },
        {
          canonical: "Hoopoe",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 19, display: "Leviticus 11:19" }],
          explanation: "The hoopoe, an easily overlooked crested bird, closes out Leviticus's list of unclean birds.",
        },
        {
          canonical: "Pelican",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Psalms", chapterStart: 102, verseStart: 6, display: "Psalm 102:6" }],
          explanation: "The psalmist compares his loneliness to 'a pelican of the wilderness.'",
        },
        {
          canonical: "Ostrich",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Job", chapterStart: 39, verseStart: 13, verseEnd: 18, display: "Job 39:13-18" }],
          explanation: "God describes the ostrich at length to Job as a bird given no wisdom, yet swifter than a horse.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name an emotion or feeling the Bible explicitly attributes to God.",
      instructions: "You get one guess.",
      whatCounts: "Any emotion or feeling the biblical text explicitly ascribes to God or the LORD.",
      answers: [
        {
          canonical: "Love",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 3, verseStart: 16, display: "John 3:16" }],
          explanation: "John declares that God so loved the world that he gave his only Son.",
        },
        {
          canonical: "Anger",
          aliases: ["wrath"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Psalms", chapterStart: 7, verseStart: 11, display: "Psalm 7:11" }],
          explanation: "The psalmist says God is angry with the wicked every day.",
        },
        {
          canonical: "Jealousy",
          aliases: ["jealous"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 34, verseStart: 14, display: "Exodus 34:14" }],
          explanation: "The LORD, whose name is Jealous, is called a jealous God.",
        },
        {
          canonical: "Compassion",
          aliases: ["pity"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Psalms", chapterStart: 103, verseStart: 13, display: "Psalm 103:13" }],
          explanation: "As a father has compassion on his children, so the LORD has compassion on those who fear him.",
        },
        {
          canonical: "Grief",
          aliases: ["regret", "it grieved him at his heart"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 6, verseStart: 6, display: "Genesis 6:6" }],
          explanation: "The LORD regretted making humanity, and it grieved him at his heart.",
        },
        {
          canonical: "Delight",
          aliases: ["pleasure"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Psalms", chapterStart: 147, verseStart: 11, display: "Psalm 147:11" }],
          explanation: "The LORD takes pleasure in those who fear him and hope in his loving kindness.",
        },
        {
          canonical: "Hatred",
          aliases: ["hate"],
          score: 60,
          tier: "veil",
          references: [{ book: "Malachi", chapterStart: 1, verseStart: 3, display: "Malachi 1:3" }],
          explanation: "The LORD declares 'Esau I hated,' contrasting his love for Jacob.",
        },
        {
          canonical: "Zeal",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Isaiah", chapterStart: 9, verseStart: 7, display: "Isaiah 9:7" }],
          explanation: "The zeal of the LORD of Armies will perform the establishment of David's throne.",
        },
        {
          canonical: "Laughter",
          aliases: ["laughs"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Psalms", chapterStart: 2, verseStart: 4, display: "Psalm 2:4" }],
          explanation: "He who sits in the heavens laughs at the raging of the nations.",
        },
        {
          canonical: "Patience",
          aliases: ["longsuffering"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Peter", chapterStart: 3, verseStart: 9, display: "2 Peter 3:9" }],
          explanation: "The Lord is patient, not wishing that any should perish but that all should reach repentance.",
        },
        {
          canonical: "Weariness",
          aliases: ["wearied"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Isaiah", chapterStart: 43, verseStart: 24, display: "Isaiah 43:24" }],
          explanation: "God tells Israel that their sins have wearied him.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a person killed for their faith in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named individual the biblical text explicitly describes being killed because of their faith, testimony, or righteousness.",
      answers: [
        {
          canonical: "John the Baptist",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 10, display: "Matthew 14:10" }],
          explanation: "John the Baptist is beheaded at Herod's order after Herodias's daughter's request.",
        },
        {
          canonical: "Stephen",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 7, verseStart: 59, display: "Acts 7:59" }],
          explanation: "Stephen becomes the first Christian martyr, stoned for testifying about Jesus.",
        },
        {
          canonical: "Abel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 4, display: "Hebrews 11:4" }],
          explanation: "Hebrews names Abel's death as a testimony of his righteous faith, killed by his brother Cain.",
        },
        {
          canonical: "James, Son of Zebedee",
          aliases: ["james the apostle", "james son of zebedee"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 2, display: "Acts 12:2" }],
          explanation: "Herod Agrippa I has James, John's brother, killed with the sword.",
        },
        {
          canonical: "Zechariah Son of Jehoiada",
          aliases: ["zechariah the priest", "zechariah stoned in the temple"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Chronicles", chapterStart: 24, verseStart: 21, display: "2 Chronicles 24:21" }],
          explanation: "Zechariah is stoned in the temple courtyard for rebuking Judah's idolatry.",
        },
        {
          canonical: "Uriah the Prophet",
          aliases: ["uriah son of shemaiah"],
          score: 60,
          tier: "veil",
          references: [{ book: "Jeremiah", chapterStart: 26, verseStart: 23, display: "Jeremiah 26:23" }],
          explanation: "King Jehoiakim has the prophet Uriah killed after he flees to Egypt for prophesying against Judah.",
        },
        {
          canonical: "Antipas",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 2, verseStart: 13, display: "Revelation 2:13" }],
          explanation: "Jesus calls Antipas 'my faithful witness' who was killed in Pergamum, 'where Satan's throne is.'",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a piece of jewelry or personal adornment mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific item of jewelry or personal adornment the biblical text explicitly names.",
      answers: [
        {
          canonical: "Signet Ring",
          aliases: ["ring"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 42, display: "Genesis 41:42" }],
          explanation: "Pharaoh takes off his signet ring and puts it on Joseph's hand.",
        },
        {
          canonical: "Earrings",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 35, verseStart: 4, display: "Genesis 35:4" }],
          explanation: "Jacob buries the foreign gods and the earrings his household surrenders under the oak near Shechem.",
        },
        {
          canonical: "Bracelets",
          aliases: ["bracelet"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 24, verseStart: 22, display: "Genesis 24:22" }],
          explanation: "Abraham's servant gives Rebekah gold bracelets as a betrothal gift.",
        },
        {
          canonical: "Gold Chain",
          aliases: ["chain", "necklace"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 42, display: "Genesis 41:42" }],
          explanation: "Pharaoh puts a gold chain around Joseph's neck when elevating him.",
        },
        {
          canonical: "Nose Ring",
          aliases: ["nose jewel"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 24, verseStart: 47, display: "Genesis 24:47" }],
          explanation: "Abraham's servant puts a ring on Rebekah's nose and bracelets on her arms.",
        },
        {
          canonical: "Crown",
          aliases: ["royal crown"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 17, display: "Esther 2:17" }],
          explanation: "The king sets the royal crown on Esther's head and makes her queen.",
        },
        {
          canonical: "Anklets",
          aliases: ["ankle chains"],
          score: 60,
          tier: "veil",
          references: [{ book: "Isaiah", chapterStart: 3, verseStart: 18, display: "Isaiah 3:18" }],
          explanation: "Isaiah lists the anklets of Zion's daughters among the finery the LORD will strip away.",
        },
        {
          canonical: "Armlet",
          aliases: ["armband", "bracelet on his arm"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 1, verseStart: 10, display: "2 Samuel 1:10" }],
          explanation: "The Amalekite brings Saul's crown and armlet to David after Saul's death.",
        },
        {
          canonical: "Crescent Ornaments",
          aliases: ["crescents", "moon-shaped ornaments"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Judges", chapterStart: 8, verseStart: 26, display: "Judges 8:26" }],
          explanation: "Gideon's spoil from Midian includes crescent ornaments taken from the necks of camels and kings.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a vow made in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific vow a person makes to God, described by name or circumstance in the biblical text.",
      answers: [
        {
          canonical: "Jephthah's Vow",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Judges", chapterStart: 11, verseStart: 30, display: "Judges 11:30" }],
          explanation: "Jephthah vows to sacrifice whatever comes from his house first if granted victory — tragically, his daughter.",
        },
        {
          canonical: "Nazarite Vow",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 6, verseStart: 2, display: "Numbers 6:2" }],
          explanation: "The Nazarite vow sets a person apart to the LORD, avoiding wine, haircuts, and contact with the dead.",
        },
        {
          canonical: "Jacob's Vow at Bethel",
          aliases: ["jacob's vow"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 28, verseStart: 20, display: "Genesis 28:20" }],
          explanation: "Jacob vows that if God brings him home safely, the LORD will be his God and Bethel God's house.",
        },
        {
          canonical: "Hannah's Vow",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 11, display: "1 Samuel 1:11" }],
          explanation: "Hannah vows to give her son to the LORD's service all his life if granted a child — Samuel.",
        },
        {
          canonical: "Paul's Vow",
          aliases: ["paul's vow at cenchreae"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 18, display: "Acts 18:18" }],
          explanation: "Paul has his hair cut off at Cenchreae because of a vow he had taken.",
        },
        {
          canonical: "Absalom's Vow",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 15, verseStart: 7, display: "2 Samuel 15:7" }],
          explanation: "Absalom cites a vow made in Geshur as his pretext to travel to Hebron, where he launches his rebellion.",
        },
        {
          canonical: "The Rechabites' Vow",
          aliases: ["rechabites", "jonadab's vow"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jeremiah", chapterStart: 35, verseStart: 6, display: "Jeremiah 35:6" }],
          explanation: "The Rechabites keep their ancestor Jonadab's vow to drink no wine and live as nomads, praised by God through Jeremiah.",
        },
        {
          canonical: "David's Vow to Find a Dwelling for the LORD",
          aliases: ["david's vow", "psalm 132 vow"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Psalms", chapterStart: 132, verseStart: 2, verseEnd: 5, display: "Psalm 132:2-5" }],
          explanation: "David swears he will not rest or sleep until he finds a dwelling place for the LORD, recalled in this psalm.",
        },
      ],
    },
  ],
};
