import type { SeedDay } from "./types";

export const DAY_20: SeedDay = {
  dayNumber: 20,
  date: "2026-10-07",
  scriptureBonus: {
    displayText: "casting all your worries on him, because he cares for you.",
    book: "1 Peter",
    chapter: 5,
    verseStart: 7,
    referenceDisplay: "1 Peter 5:7",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Peter encourages believers to hand their anxieties over to God, who cares for them personally.",
    acceptedBookAliases: ["1 pet", "1pt", "first peter"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a spice, incense ingredient, or fragrant substance mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any spice, incense ingredient, or fragrant plant substance the biblical text explicitly names.",
      answers: [
        {
          canonical: "Frankincense",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 2, verseStart: 11, display: "Matthew 2:11" }],
          explanation: "The magi present the infant Jesus with gold, frankincense, and myrrh.",
        },
        {
          canonical: "Myrrh",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 2, verseStart: 11, display: "Matthew 2:11" }],
          explanation: "Myrrh is one of the three gifts the magi bring to the infant Jesus.",
        },
        {
          canonical: "Cinnamon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 23, display: "Exodus 30:23" }],
          explanation: "Cinnamon is one of the spices God commands Moses to use in the holy anointing oil.",
        },
        {
          canonical: "Nard",
          aliases: ["spikenard", "pure nard"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 12, verseStart: 3, display: "John 12:3" }],
          explanation: "Mary anoints Jesus' feet with expensive perfume made of pure nard.",
        },
        {
          canonical: "Hyssop",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 12, verseStart: 22, display: "Exodus 12:22" }],
          explanation: "Israel uses a bunch of hyssop to apply blood to their doorposts at the first Passover.",
        },
        {
          canonical: "Cassia",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 24, display: "Exodus 30:24" }],
          explanation: "Cassia is another spice included in the recipe for the holy anointing oil.",
        },
        {
          canonical: "Calamus",
          aliases: ["sweet cane", "sweet calamus"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 23, display: "Exodus 30:23" }],
          explanation: "Sweet calamus is measured out among the spices for the anointing oil.",
        },
        {
          canonical: "Galbanum",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 34, display: "Exodus 30:34" }],
          explanation: "Galbanum is one of the ingredients God specifies for the sacred incense burned in the tabernacle.",
        },
        {
          canonical: "Onycha",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Exodus", chapterStart: 30, verseStart: 34, display: "Exodus 30:34" }],
          explanation: "Onycha is named alongside stacte and galbanum among the ingredients for the holy incense.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a piece of the full armor of God described in Ephesians.",
      instructions: "You get one guess.",
      whatCounts: "Any piece of spiritual armor Paul names in Ephesians 6:14-17.",
      answers: [
        {
          canonical: "Shield of Faith",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 16, display: "Ephesians 6:16" }],
          explanation: "Paul describes the shield of faith as able to extinguish the flaming arrows of the evil one.",
        },
        {
          canonical: "Sword of the Spirit",
          aliases: ["word of god"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 17, display: "Ephesians 6:17" }],
          explanation: "Paul identifies the sword of the Spirit as the word of God.",
        },
        {
          canonical: "Helmet of Salvation",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 17, display: "Ephesians 6:17" }],
          explanation: "Paul instructs believers to take up the helmet of salvation.",
        },
        {
          canonical: "Belt of Truth",
          aliases: ["girdle of truth"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 14, display: "Ephesians 6:14" }],
          explanation: "Paul opens the list of armor with the belt of truth buckled around the waist.",
        },
        {
          canonical: "Breastplate of Righteousness",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 14, display: "Ephesians 6:14" }],
          explanation: "Paul instructs believers to put on the breastplate of righteousness.",
        },
        {
          canonical: "Shoes of the Gospel of Peace",
          aliases: ["readiness of the gospel of peace", "gospel shoes"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 15, display: "Ephesians 6:15" }],
          explanation: "Paul describes feet fitted with the readiness that comes from the gospel of peace.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a stone or monument set up as a memorial in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific memorial stone, pillar, or monument the biblical text describes being set up.",
      answers: [
        {
          canonical: "Jacob's Pillar at Bethel",
          aliases: ["jacobs pillar", "pillow stone at bethel"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 28, verseStart: 18, display: "Genesis 28:18" }],
          explanation: "Jacob sets up as a pillar the stone he had used as a pillow after his dream of the stairway to heaven.",
        },
        {
          canonical: "Ebenezer",
          aliases: ["ebenezer stone", "stone of help"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 7, verseStart: 12, display: "1 Samuel 7:12" }],
          explanation: "Samuel sets up a stone named Ebenezer, \"stone of help,\" after the LORD gives Israel victory over the Philistines.",
        },
        {
          canonical: "Twelve Stones at Gilgal",
          aliases: ["gilgal stones", "twelve stones"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Joshua", chapterStart: 4, verseStart: 20, display: "Joshua 4:20" }],
          explanation: "Joshua sets up twelve stones taken from the Jordan at Gilgal to commemorate Israel's crossing.",
        },
        {
          canonical: "Joshua's Stone Under the Oak",
          aliases: ["stone under the oak", "witness stone at shechem"],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 24, verseStart: 26, verseEnd: 27, display: "Joshua 24:26-27" }],
          explanation: "Joshua sets up a large stone under an oak at Shechem as a witness to Israel's covenant renewal.",
        },
        {
          canonical: "Altar Called Witness",
          aliases: ["altar of witness", "ed altar"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Joshua", chapterStart: 22, verseStart: 34, display: "Joshua 22:34" }],
          explanation: "The tribes east of the Jordan build an altar they name Witness, testifying to their shared faith.",
        },
        {
          canonical: "Absalom's Monument",
          aliases: ["absaloms pillar", "absaloms monument"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Samuel", chapterStart: 18, verseStart: 18, display: "2 Samuel 18:18" }],
          explanation: "Absalom sets up a pillar for himself in his lifetime, having no son to carry on his name.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a city that served as a capital of Israel or Judah.",
      instructions: "You get one guess.",
      whatCounts: "Any city the biblical text describes as a royal capital or seat of government for Israel or Judah, or the northern or southern kingdom.",
      answers: [
        {
          canonical: "Jerusalem",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 9, display: "2 Samuel 5:9" }],
          explanation: "David captures Jerusalem and makes it his capital, the City of David.",
        },
        {
          canonical: "Samaria",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 16, verseStart: 24, display: "1 Kings 16:24" }],
          explanation: "King Omri builds Samaria and makes it the capital of the northern kingdom of Israel.",
        },
        {
          canonical: "Hebron",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 2, verseStart: 11, display: "2 Samuel 2:11" }],
          explanation: "David reigns from Hebron as king over Judah for seven and a half years before taking Jerusalem.",
        },
        {
          canonical: "Shechem",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 12, verseStart: 25, display: "1 Kings 12:25" }],
          explanation: "Jeroboam rebuilds Shechem and makes it his first capital after the kingdom splits.",
        },
        {
          canonical: "Tirzah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 15, verseStart: 33, display: "1 Kings 15:33" }],
          explanation: "Tirzah serves as an early capital of the northern kingdom before Omri builds Samaria.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name one of Jesus' sayings from the cross.",
      instructions: "You get one guess.",
      whatCounts: "Any of the statements the Gospels record Jesus making while on the cross.",
      answers: [
        {
          canonical: "Father, Forgive Them",
          aliases: ["father forgive them for they know not what they do"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 34, display: "Luke 23:34" }],
          explanation: "Jesus prays for those crucifying him, asking the Father to forgive them.",
        },
        {
          canonical: "It Is Finished",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 19, verseStart: 30, display: "John 19:30" }],
          explanation: "Jesus declares \"It is finished\" just before he gives up his spirit.",
        },
        {
          canonical: "My God, My God, Why Have You Forsaken Me",
          aliases: ["why have you forsaken me", "eli eli lama sabachthani"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 46, display: "Matthew 27:46" }],
          explanation: "Jesus cries out in the words of Psalm 22, asking why God has forsaken him.",
        },
        {
          canonical: "Today You Will Be With Me in Paradise",
          aliases: ["today you will be with me in paradise thief"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 43, display: "Luke 23:43" }],
          explanation: "Jesus promises the repentant criminal beside him that he will be with him in paradise that very day.",
        },
        {
          canonical: "Woman, Behold Your Son",
          aliases: ["behold your son", "behold thy mother"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 19, verseStart: 26, verseEnd: 27, display: "John 19:26-27" }],
          explanation: "Jesus entrusts his mother Mary to the care of the beloved disciple.",
        },
        {
          canonical: "I Thirst",
          aliases: ["i am thirsty"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 19, verseStart: 28, display: "John 19:28" }],
          explanation: "Jesus says he is thirsty, fulfilling Scripture, and is offered sour wine on a sponge.",
        },
        {
          canonical: "Father, Into Your Hands I Commit My Spirit",
          aliases: ["into your hands i commit my spirit"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Luke", chapterStart: 23, verseStart: 46, display: "Luke 23:46" }],
          explanation: "Jesus calls out with a loud voice, committing his spirit into the Father's hands, and breathes his last.",
        },
      ],
    },
  ],
};
