import type { SeedDay } from "./types";

export const DAY_21: SeedDay = {
  dayNumber: 21,
  date: "2026-10-08",
  scriptureBonus: {
    displayText:
      "Yahweh, your God, is in the midst of you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing.",
    book: "Zephaniah",
    chapter: 3,
    verseStart: 17,
    referenceDisplay: "Zephaniah 3:17",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A promise of restoration to Judah, picturing God himself rejoicing over his people.",
    acceptedBookAliases: ["zeph"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a number that carries special significance in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any number the biblical text uses in a way carrying recognized symbolic or thematic weight.",
      answers: [
        {
          canonical: "Seven",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 2, verseStart: 2, display: "Genesis 2:2" }],
          explanation: "God rests on the seventh day, making seven a recurring number of completeness throughout scripture.",
        },
        {
          canonical: "Twelve",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 24, verseStart: 4, display: "Exodus 24:4" }],
          explanation: "Moses sets up twelve pillars at Sinai, one for each tribe of Israel, echoing the twelve apostles later.",
        },
        {
          canonical: "Three",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 12, verseStart: 40, display: "Matthew 12:40" }],
          explanation: "Jesus compares his coming three days in the tomb to Jonah's three days in the fish.",
        },
        {
          canonical: "Forty",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 14, verseStart: 33, display: "Numbers 14:33" }],
          explanation: "Israel wanders forty years in the wilderness, one year for each day the spies scouted Canaan.",
        },
        {
          canonical: "Eight",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Peter", chapterStart: 3, verseStart: 20, display: "1 Peter 3:20" }],
          explanation: "Peter notes that eight souls were saved through water on Noah's ark, a number often tied to new beginnings.",
        },
        {
          canonical: "Six Hundred Sixty-Six",
          aliases: ["666", "number of the beast"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 13, verseStart: 18, display: "Revelation 13:18" }],
          explanation: "Revelation identifies 666 as the number of the beast, calling for wisdom to calculate it.",
        },
        {
          canonical: "Seventy",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 11, verseStart: 16, display: "Numbers 11:16" }],
          explanation: "God tells Moses to gather seventy elders of Israel to share the burden of leadership.",
        },
        {
          canonical: "Three Hundred",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 7, verseStart: 6, display: "Judges 7:6" }],
          explanation: "God narrows Gideon's army to three hundred men so Israel cannot claim the victory for themselves.",
        },
        {
          canonical: "Forty-Two",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 13, verseStart: 5, display: "Revelation 13:5" }],
          explanation: "Revelation gives the beast authority to act for forty-two months.",
        },
        {
          canonical: "Twenty-Four",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 4, display: "Revelation 4:4" }],
          explanation: "John sees twenty-four elders seated on thrones surrounding God's throne in heaven.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name an unclean animal listed in Leviticus 11.",
      instructions: "You get one guess.",
      whatCounts: "Any animal Leviticus 11 explicitly names as unclean or forbidden for Israel to eat.",
      answers: [
        {
          canonical: "Pig",
          aliases: ["swine", "pork"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 7, display: "Leviticus 11:7" }],
          explanation: "The pig is unclean because though it has a split hoof, it does not chew the cud.",
        },
        {
          canonical: "Camel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 4, display: "Leviticus 11:4" }],
          explanation: "The camel is unclean because though it chews the cud, it does not have a split hoof.",
        },
        {
          canonical: "Eagle",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 13, display: "Leviticus 11:13" }],
          explanation: "The eagle heads the list of birds Israel is forbidden to eat.",
        },
        {
          canonical: "Vulture",
          aliases: ["buzzard"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 13, display: "Leviticus 11:13" }],
          explanation: "The vulture is listed among the unclean birds of prey in the same verse as the eagle.",
        },
        {
          canonical: "Raven",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 15, display: "Leviticus 11:15" }],
          explanation: "Every kind of raven is named among the unclean birds.",
        },
        {
          canonical: "Ostrich",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 16, display: "Leviticus 11:16" }],
          explanation: "The ostrich is listed among the unclean birds Israel may not eat.",
        },
        {
          canonical: "Owl",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 16, display: "Leviticus 11:16" }],
          explanation: "The owl is listed alongside the ostrich among the unclean birds.",
        },
        {
          canonical: "Stork",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 19, display: "Leviticus 11:19" }],
          explanation: "The stork is named among the unclean birds Israel may not eat.",
        },
        {
          canonical: "Bat",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 19, display: "Leviticus 11:19" }],
          explanation: "The bat closes the list of unclean flying creatures in Leviticus 11.",
        },
        {
          canonical: "Weasel",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Leviticus", chapterStart: 11, verseStart: 29, display: "Leviticus 11:29" }],
          explanation: "The weasel is named first among the small creatures that swarm on the ground and are unclean.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a New Testament letter not written by Paul.",
      instructions: "You get one guess.",
      whatCounts: "Any of the New Testament epistles traditionally attributed to an author other than Paul. Hebrews is excluded — its authorship is anonymous and disputed even in tradition.",
      answers: [
        {
          canonical: "1 John",
          aliases: ["first john"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 John", chapterStart: 1, verseStart: 1, display: "1 John 1:1" }],
          explanation: "Traditionally attributed to the apostle John, emphasizing love and assurance of salvation.",
        },
        {
          canonical: "James",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "James", chapterStart: 1, verseStart: 1, display: "James 1:1" }],
          explanation: "Traditionally attributed to James, brother of Jesus and leader of the Jerusalem church.",
        },
        {
          canonical: "1 Peter",
          aliases: ["first peter"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Peter", chapterStart: 1, verseStart: 1, display: "1 Peter 1:1" }],
          explanation: "Written by the apostle Peter to believers scattered across Asia Minor.",
        },
        {
          canonical: "2 Peter",
          aliases: ["second peter"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Peter", chapterStart: 1, verseStart: 1, display: "2 Peter 1:1" }],
          explanation: "Warns against false teachers and affirms the certainty of Christ's return.",
        },
        {
          canonical: "Jude",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Jude", chapterStart: 1, verseStart: 1, display: "Jude 1:1" }],
          explanation: "Written by Jude, brother of James, warning against false teachers.",
        },
        {
          canonical: "2 John",
          aliases: ["second john"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 John", chapterStart: 1, verseStart: 1, display: "2 John 1:1" }],
          explanation: "A short letter warning against deceivers who deny Christ came in the flesh.",
        },
        {
          canonical: "3 John",
          aliases: ["third john"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "3 John", chapterStart: 1, verseStart: 1, display: "3 John 1:1" }],
          explanation: "The shortest and least-quoted book of the New Testament, addressed to Gaius.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a place Jesus appeared after his resurrection.",
      instructions: "You get one guess.",
      whatCounts: "Any location the biblical text explicitly describes the risen Jesus appearing at.",
      answers: [
        {
          canonical: "The Road to Emmaus",
          aliases: ["emmaus road", "emmaus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 24, verseStart: 13, display: "Luke 24:13" }],
          explanation: "Jesus walks unrecognized with two disciples on the road to Emmaus, explaining the scriptures about himself.",
        },
        {
          canonical: "The Upper Room",
          aliases: ["locked room", "behind locked doors"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 20, verseStart: 19, display: "John 20:19" }],
          explanation: "Jesus appears among the disciples in a locked room, showing them his hands and side.",
        },
        {
          canonical: "Near the Tomb to Mary Magdalene",
          aliases: ["the garden tomb", "outside the tomb"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 20, verseStart: 14, display: "John 20:14" }],
          explanation: "Mary Magdalene turns and sees Jesus standing near the empty tomb, mistaking him at first for the gardener.",
        },
        {
          canonical: "The Shore of the Sea of Tiberias",
          aliases: ["sea of galilee shore", "sea of tiberias"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 21, verseStart: 1, display: "John 21:1" }],
          explanation: "Jesus appears to the disciples on the shore while they are fishing, and cooks them breakfast.",
        },
        {
          canonical: "A Mountain in Galilee",
          aliases: ["galilee mountain", "the great commission mountain"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 28, verseStart: 16, display: "Matthew 28:16" }],
          explanation: "The eleven disciples go to a mountain in Galilee where Jesus gives them the Great Commission.",
        },
        {
          canonical: "The Mount of Olives",
          aliases: ["bethany ascension", "mount of olives ascension"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 1, verseStart: 12, display: "Acts 1:12" }],
          explanation: "Jesus ascends into heaven from the Mount of Olives after his final appearance to the apostles.",
        },
        {
          canonical: "The Road to Damascus",
          aliases: ["damascus road"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 3, display: "Acts 9:3" }],
          explanation: "The risen Jesus appears to Saul in a blinding light on the road to Damascus.",
        },
        {
          canonical: "Bethany",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 24, verseStart: 50, display: "Luke 24:50" }],
          explanation: "Jesus leads the disciples out as far as Bethany, blesses them, and is carried up into heaven.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a name or metaphor the New Testament uses for the church.",
      instructions: "You get one guess.",
      whatCounts: "Any name, title, or metaphor the New Testament explicitly applies to the church or to believers collectively.",
      answers: [
        {
          canonical: "Body of Christ",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 12, verseStart: 27, display: "1 Corinthians 12:27" }],
          explanation: "Paul tells the Corinthians that together they are the body of Christ, each a member of it.",
        },
        {
          canonical: "Bride of Christ",
          aliases: ["the bride"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 19, verseStart: 7, display: "Revelation 19:7" }],
          explanation: "Revelation pictures the church as the bride, prepared and adorned for the marriage of the Lamb.",
        },
        {
          canonical: "Temple of God",
          aliases: ["god's temple"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Corinthians", chapterStart: 3, verseStart: 16, display: "1 Corinthians 3:16" }],
          explanation: "Paul asks the Corinthians whether they know they are God's temple, with the Spirit dwelling among them.",
        },
        {
          canonical: "Household of God",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ephesians", chapterStart: 2, verseStart: 19, display: "Ephesians 2:19" }],
          explanation: "Paul tells the Ephesians they are no longer strangers, but members of the household of God.",
        },
        {
          canonical: "Flock of God",
          aliases: ["the flock"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Peter", chapterStart: 5, verseStart: 2, display: "1 Peter 5:2" }],
          explanation: "Peter instructs elders to shepherd the flock of God entrusted to their care.",
        },
        {
          canonical: "Living Stones",
          aliases: ["spiritual house"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Peter", chapterStart: 2, verseStart: 5, display: "1 Peter 2:5" }],
          explanation: "Peter describes believers as living stones being built into a spiritual house.",
        },
        {
          canonical: "Pillar and Foundation of the Truth",
          aliases: ["pillar and ground of the truth"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Timothy", chapterStart: 3, verseStart: 15, display: "1 Timothy 3:15" }],
          explanation: "Paul calls the church of the living God the pillar and foundation of the truth.",
        },
        {
          canonical: "Royal Priesthood",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Peter", chapterStart: 2, verseStart: 9, display: "1 Peter 2:9" }],
          explanation: "Peter calls believers a chosen race and a royal priesthood, called out of darkness into God's light.",
        },
        {
          canonical: "Branches of the Vine",
          aliases: ["the branches"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "John", chapterStart: 15, verseStart: 5, display: "John 15:5" }],
          explanation: "Jesus calls himself the vine and his followers the branches, who must remain in him to bear fruit.",
        },
      ],
    },
  ],
};
