import type { SeedDay } from "./types";

export const DAY_27: SeedDay = {
  dayNumber: 27,
  date: "2026-10-14",
  scriptureBonus: {
    displayText: "Iron sharpens iron; so a man sharpens his friend's countenance.",
    book: "Proverbs",
    chapter: 27,
    verseStart: 17,
    referenceDisplay: "Proverbs 27:17",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A proverb about how close companionship refines character.",
    acceptedBookAliases: ["prov"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a member of the Pharisees, Sadducees, or Sanhedrin named in the New Testament.",
      instructions: "You get one guess.",
      whatCounts: "Any named individual the biblical text identifies as a Pharisee, Sadducee, or member of the Sanhedrin.",
      answers: [
        {
          canonical: "Nicodemus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 3, verseStart: 1, display: "John 3:1" }],
          explanation: "Nicodemus, a Pharisee and member of the Sanhedrin, comes to Jesus by night.",
        },
        {
          canonical: "Saul of Tarsus",
          aliases: ["paul", "saul"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Philippians", chapterStart: 3, verseStart: 5, display: "Philippians 3:5" }],
          explanation: "Paul describes himself as a Pharisee, trained under Gamaliel, before his conversion.",
        },
        {
          canonical: "Joseph of Arimathea",
          aliases: ["arimathea"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 15, verseStart: 43, display: "Mark 15:43" }],
          explanation: "Joseph of Arimathea, a respected member of the Council, asks Pilate for Jesus' body.",
        },
        {
          canonical: "Caiaphas",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 3, display: "Matthew 26:3" }],
          explanation: "Caiaphas, the high priest that year, presides over the Sanhedrin that condemns Jesus.",
        },
        {
          canonical: "Annas",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "John", chapterStart: 18, verseStart: 13, display: "John 18:13" }],
          explanation: "Annas, Caiaphas' father-in-law and a former high priest, questions Jesus first after his arrest.",
        },
        {
          canonical: "Gamaliel",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 5, verseStart: 34, display: "Acts 5:34" }],
          explanation: "Gamaliel, a respected Pharisee and teacher of the law, urges caution against persecuting the apostles.",
        },
        {
          canonical: "Nicolas",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 6, verseStart: 5, display: "Acts 6:5" }],
          inclusionNotes: "Nicolas is one of the seven chosen to serve tables, not a Pharisee/Sadducee himself, but a proselyte associated with the Sanhedrin-adjacent Jerusalem leadership circle.",
          exclusions: [],
          explanation: "Nicolas, a proselyte of Antioch, is one of seven men chosen to oversee the daily distribution to widows.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a magician, sorcerer, or occult practitioner mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly identifies as practicing magic, sorcery, or divination.",
      answers: [
        {
          canonical: "Simon Magus",
          aliases: ["simon the sorcerer"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 9, display: "Acts 8:9" }],
          explanation: "Simon practices sorcery in Samaria and amazes the people before believing Philip's preaching.",
        },
        {
          canonical: "The Medium of Endor",
          aliases: ["witch of endor"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 28, verseStart: 7, display: "1 Samuel 28:7" }],
          explanation: "Saul consults a medium at Endor to summon the spirit of Samuel.",
        },
        {
          canonical: "Elymas",
          aliases: ["bar-jesus"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 8, display: "Acts 13:8" }],
          explanation: "The sorcerer Elymas opposes Paul and Barnabas before Paul strikes him blind.",
        },
        {
          canonical: "Balaam",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 22, verseStart: 7, display: "Numbers 22:7" }],
          explanation: "Balak's messengers bring Balaam divination fees, seeking him to curse Israel.",
        },
        {
          canonical: "Jannes and Jambres",
          aliases: ["jannes", "jambres"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Timothy", chapterStart: 3, verseStart: 8, display: "2 Timothy 3:8" }],
          explanation: "Paul names Jannes and Jambres as the magicians who opposed Moses.",
        },
        {
          canonical: "The Sons of Sceva",
          aliases: ["seven sons of sceva"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 19, verseStart: 14, display: "Acts 19:14" }],
          explanation: "Seven sons of the Jewish chief priest Sceva try to exorcise a demon using Jesus' name and are overpowered.",
        },
        {
          canonical: "Pharaoh's Magicians",
          aliases: ["the magicians of egypt"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 7, verseStart: 11, display: "Exodus 7:11" }],
          explanation: "Pharaoh summons wise men and sorcerers who copy Moses' sign by their secret arts.",
        },
        {
          canonical: "Nebuchadnezzar's Magicians and Astrologers",
          aliases: ["babylonian magicians"],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 2, verseStart: 2, display: "Daniel 2:2" }],
          explanation: "Nebuchadnezzar summons magicians, enchanters, sorcerers, and astrologers to interpret his dream.",
        },
        {
          canonical: "The Slave Girl with a Spirit of Divination",
          aliases: ["girl with a python spirit"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 16, display: "Acts 16:16" }],
          explanation: "A slave girl with a spirit of divination earns her owners money by fortune-telling until Paul casts the spirit out.",
        },
        {
          canonical: "Manasseh",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Chronicles", chapterStart: 33, verseStart: 6, display: "2 Chronicles 33:6" }],
          explanation: "King Manasseh practices sorcery, divination, and witchcraft, provoking the LORD to anger.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a scribe mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly identifies as a scribe.",
      answers: [
        {
          canonical: "Ezra",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ezra", chapterStart: 7, verseStart: 6, display: "Ezra 7:6" }],
          explanation: "Ezra is a skilled scribe in the Law of Moses who leads a return to Jerusalem.",
        },
        {
          canonical: "Baruch",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Jeremiah", chapterStart: 36, verseStart: 4, display: "Jeremiah 36:4" }],
          explanation: "Baruch serves as Jeremiah's scribe, writing down the prophet's words on a scroll.",
        },
        {
          canonical: "Shaphan",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 22, verseStart: 8, display: "2 Kings 22:8" }],
          explanation: "Shaphan the scribe reads the newly found Book of the Law to King Josiah.",
        },
        {
          canonical: "Seraiah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 8, verseStart: 17, display: "2 Samuel 8:17" }],
          explanation: "Seraiah serves as David's scribe, recorded among his chief officials.",
        },
        {
          canonical: "Shemaiah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Chronicles", chapterStart: 24, verseStart: 6, display: "1 Chronicles 24:6" }],
          explanation: "Shemaiah the scribe records the priestly divisions assigned under David.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a person's grandparent or grandchild explicitly identified in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly names as someone's grandfather, grandmother, or grandchild.",
      answers: [
        {
          canonical: "Methuselah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 25, verseEnd: 29, display: "Genesis 5:25-29" }],
          explanation: "Methuselah, the longest-lived man in the Bible, is the grandfather of Noah.",
        },
        {
          canonical: "Mephibosheth",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 9, verseStart: 6, display: "2 Samuel 9:6" }],
          explanation: "Mephibosheth, Jonathan's son, is Saul's grandson, shown kindness by David.",
        },
        {
          canonical: "Rehoboam",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 11, verseStart: 43, display: "1 Kings 11:43" }],
          explanation: "Rehoboam, Solomon's son, is David's grandson and becomes king after Solomon.",
        },
        {
          canonical: "Obed",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 17, display: "Ruth 4:17" }],
          explanation: "Obed, son of Boaz and Ruth, is the grandfather of David.",
        },
        {
          canonical: "Timothy",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Timothy", chapterStart: 1, verseStart: 5, display: "2 Timothy 1:5" }],
          explanation: "Timothy is the grandson of Lois, whose sincere faith Paul says lived first in her.",
        },
        {
          canonical: "Jehoiachin",
          aliases: ["jeconiah"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 24, verseStart: 8, display: "2 Kings 24:8" }],
          explanation: "Jehoiachin is Josiah's grandson, the king exiled to Babylon at age eighteen.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a close friend or loyal companion of a biblical figure.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly portrays as a close friend or devoted companion of another named figure.",
      answers: [
        {
          canonical: "Jonathan",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 18, verseStart: 1, display: "1 Samuel 18:1" }],
          explanation: "Jonathan's soul is knit to David's, and he loves him as his own soul.",
        },
        {
          canonical: "Ruth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 1, verseStart: 16, verseEnd: 17, display: "Ruth 1:16-17" }],
          explanation: "Ruth pledges unwavering loyalty to her mother-in-law Naomi.",
        },
        {
          canonical: "Barnabas",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 27, display: "Acts 9:27" }],
          explanation: "Barnabas vouches for the newly converted Saul and becomes his missionary companion.",
        },
        {
          canonical: "Hushai",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 15, verseStart: 37, display: "2 Samuel 15:37" }],
          explanation: "Hushai the Archite, called David's friend, secretly undermines Ahithophel's counsel to Absalom.",
        },
        {
          canonical: "Epaphroditus",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Philippians", chapterStart: 2, verseStart: 25, display: "Philippians 2:25" }],
          explanation: "Paul calls Epaphroditus his brother, fellow worker, and fellow soldier, sent by the Philippians to help him.",
        },
      ],
    },
  ],
};
