import type { SeedDay } from "./types";

export const DAY_28: SeedDay = {
  dayNumber: 28,
  date: "2026-10-15",
  scriptureBonus: {
    displayText: "Two are better than one, because they have a good reward for their labor.",
    book: "Ecclesiastes",
    chapter: 4,
    verseStart: 9,
    referenceDisplay: "Ecclesiastes 4:9",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "The Preacher commends companionship and mutual support over isolation.",
    acceptedBookAliases: ["eccl", "eccles"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a husband of a named biblical woman.",
      instructions: "You get one guess.",
      whatCounts: "Any man the biblical text explicitly identifies as the husband of a named woman (patriarchs excluded — see the separate patriarch's-wife question).",
      answers: [
        {
          canonical: "Boaz",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 13, display: "Ruth 4:13" }],
          explanation: "Boaz marries Ruth the Moabitess, redeeming her as her kinsman.",
        },
        {
          canonical: "Zechariah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 5, display: "Luke 1:5" }],
          exclusions: ["zechariah the prophet"],
          explanation: "Zechariah the priest is the husband of Elizabeth and father of John the Baptist.",
        },
        {
          canonical: "Aquila",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 2, display: "Acts 18:2" }],
          explanation: "Aquila, husband of Priscilla, works alongside Paul as a tentmaker.",
        },
        {
          canonical: "Elkanah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 1, verseEnd: 2, display: "1 Samuel 1:1-2" }],
          explanation: "Elkanah is the husband of Hannah (and Peninnah), and father of Samuel.",
        },
        {
          canonical: "Uriah",
          aliases: ["uriah the hittite"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 11, verseStart: 3, display: "2 Samuel 11:3" }],
          explanation: "Uriah the Hittite, a loyal soldier, is Bathsheba's husband before David has him killed.",
        },
        {
          canonical: "Nabal",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Samuel", chapterStart: 25, verseStart: 3, display: "1 Samuel 25:3" }],
          explanation: "Nabal, a wealthy but harsh man, is the first husband of Abigail, who later marries David.",
        },
        {
          canonical: "Hosea",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Hosea", chapterStart: 1, verseStart: 2, verseEnd: 3, display: "Hosea 1:2-3" }],
          explanation: "God commands the prophet Hosea to marry Gomer as a living picture of Israel's unfaithfulness.",
        },
        {
          canonical: "Ananias",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 5, verseStart: 1, display: "Acts 5:1" }],
          exclusions: ["ananias of damascus"],
          explanation: "Ananias, husband of Sapphira, falls dead after lying to the Holy Spirit about the price of a sold field.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person who raised or cared for a child not their own by birth.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly describes raising, adopting, or caring for a child who was not their biological offspring.",
      answers: [
        {
          canonical: "Joseph",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 24, verseEnd: 25, display: "Matthew 1:24-25" }],
          exclusions: ["joseph son of jacob"],
          explanation: "Joseph raises Jesus as his own son, though Mary conceived him by the Holy Spirit.",
        },
        {
          canonical: "Pharaoh's Daughter",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 2, verseStart: 10, display: "Exodus 2:10" }],
          explanation: "Pharaoh's daughter draws Moses from the Nile and raises him as her own son.",
        },
        {
          canonical: "Mordecai",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 7, display: "Esther 2:7" }],
          explanation: "Mordecai raises his orphaned cousin Esther as his own daughter.",
        },
        {
          canonical: "Naomi",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 16, display: "Ruth 4:16" }],
          explanation: "Naomi takes Ruth's son Obed and nurses him, and the women declare a son is born to Naomi.",
        },
        {
          canonical: "Jehosheba",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 11, verseStart: 2, display: "2 Kings 11:2" }],
          explanation: "Jehosheba hides her infant nephew Joash from Athaliah's purge, saving the royal line of David.",
        },
        {
          canonical: "Eli",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 28, display: "1 Samuel 1:28" }],
          explanation: "Eli the priest raises the boy Samuel at the tabernacle after Hannah dedicates him to the LORD.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a curse pronounced in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific curse the biblical text explicitly records being pronounced.",
      answers: [
        {
          canonical: "Curse on the Serpent",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 14, display: "Genesis 3:14" }],
          explanation: "God curses the serpent above all livestock and wild animals for deceiving Eve.",
        },
        {
          canonical: "Curse on the Ground",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 17, display: "Genesis 3:17" }],
          explanation: "God curses the ground because of Adam, making it yield thorns and thistles.",
        },
        {
          canonical: "Cain's Curse",
          aliases: ["curse on cain"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 4, verseStart: 11, display: "Genesis 4:11" }],
          explanation: "God curses Cain from the ground that opened its mouth to receive Abel's blood.",
        },
        {
          canonical: "Jesus Curses the Fig Tree",
          aliases: ["cursing of the fig tree"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 11, verseStart: 14, display: "Mark 11:14" }],
          explanation: "Jesus tells a fruitless fig tree that no one will ever eat fruit from it again, and it withers.",
        },
        {
          canonical: "Noah's Curse on Canaan",
          aliases: ["curse on canaan"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 9, verseStart: 25, display: "Genesis 9:25" }],
          explanation: "Noah curses Canaan, Ham's son, after waking from his wine and learning what Ham had done.",
        },
        {
          canonical: "Curse on Those Who Rob God",
          aliases: ["malachi's curse on withheld tithes"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Malachi", chapterStart: 3, verseStart: 9, display: "Malachi 3:9" }],
          explanation: "Malachi tells Israel they are cursed with a curse for robbing God of tithes and offerings.",
        },
        {
          canonical: "Curse on Jehoiakim's Line (Coniah)",
          aliases: ["curse on coniah", "curse on jeconiah"],
          score: 60,
          tier: "veil",
          references: [{ book: "Jeremiah", chapterStart: 22, verseStart: 30, display: "Jeremiah 22:30" }],
          explanation: "Jeremiah pronounces that none of Coniah's offspring will prosper sitting on David's throne.",
        },
        {
          canonical: "Paul's Curse on False Gospel Preachers",
          aliases: ["let him be accursed", "anathema galatians"],
          score: 60,
          tier: "veil",
          references: [{ book: "Galatians", chapterStart: 1, verseStart: 8, display: "Galatians 1:8" }],
          explanation: "Paul declares that anyone preaching a different gospel, even an angel, should be accursed.",
        },
        {
          canonical: "The Curses of Deuteronomy 28",
          aliases: ["covenant curses of deuteronomy"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Deuteronomy", chapterStart: 28, verseStart: 15, display: "Deuteronomy 28:15" }],
          explanation: "Moses lists extensive curses that will befall Israel if they disobey the LORD's commands.",
        },
        {
          canonical: "Curse on Meroz",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Judges", chapterStart: 5, verseStart: 23, display: "Judges 5:23" }],
          explanation: "The angel of the LORD curses the town of Meroz for failing to help against Sisera in Deborah's song.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a eunuch mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly identifies as a eunuch.",
      answers: [
        {
          canonical: "The Ethiopian Eunuch",
          aliases: ["ethiopian eunuch"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 27, display: "Acts 8:27" }],
          explanation: "An Ethiopian court official is baptized by Philip after reading Isaiah on the road to Gaza.",
        },
        {
          canonical: "Hegai",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 3, display: "Esther 2:3" }],
          explanation: "Hegai, keeper of the women, oversees Esther's preparation for the king.",
        },
        {
          canonical: "Bigthan",
          aliases: ["bigthana"],
          score: 60,
          tier: "veil",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 21, display: "Esther 2:21" }],
          explanation: "Bigthan, one of the king's eunuchs guarding the door, conspires against King Ahasuerus.",
        },
        {
          canonical: "Teresh",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 21, display: "Esther 2:21" }],
          explanation: "Teresh, along with Bigthan, plots against the king but is exposed by Mordecai.",
        },
        {
          canonical: "Harbona",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Esther", chapterStart: 7, verseStart: 9, display: "Esther 7:9" }],
          explanation: "Harbona, one of the king's eunuchs, points out the gallows Haman built for Mordecai.",
        },
        {
          canonical: "Ebed-Melech",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Jeremiah", chapterStart: 38, verseStart: 7, display: "Jeremiah 38:7" }],
          explanation: "Ebed-Melech, a Cushite eunuch in the king's palace, rescues Jeremiah from a muddy cistern.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a co-worker or companion of Paul named in his letters.",
      instructions: "You get one guess.",
      whatCounts: "Any named individual Paul's letters (or Acts) describe as his traveling companion, co-worker, or helper.",
      answers: [
        {
          canonical: "Timothy",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Philippians", chapterStart: 2, verseStart: 19, display: "Philippians 2:19" }],
          explanation: "Timothy is Paul's frequent companion and the recipient of two letters.",
        },
        {
          canonical: "Titus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Corinthians", chapterStart: 8, verseStart: 23, display: "2 Corinthians 8:23" }],
          explanation: "Titus, Paul's partner and fellow worker, is left in Crete to appoint elders.",
        },
        {
          canonical: "Silas",
          aliases: ["silvanus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 15, verseStart: 40, display: "Acts 15:40" }],
          explanation: "Silas accompanies Paul on his second missionary journey after the split with Barnabas.",
        },
        {
          canonical: "Luke",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Colossians", chapterStart: 4, verseStart: 14, display: "Colossians 4:14" }],
          explanation: "Luke, the beloved physician, travels with Paul and writes the Gospel of Luke and Acts.",
        },
        {
          canonical: "Priscilla",
          aliases: ["prisca"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 18, display: "Acts 18:18" }],
          explanation: "Priscilla, with her husband Aquila, works alongside Paul and instructs Apollos more accurately.",
        },
        {
          canonical: "Epaphras",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Colossians", chapterStart: 1, verseStart: 7, display: "Colossians 1:7" }],
          explanation: "Epaphras, a fellow servant, brings word of the Colossians' faith to Paul.",
        },
        {
          canonical: "Tychicus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ephesians", chapterStart: 6, verseStart: 21, display: "Ephesians 6:21" }],
          explanation: "Tychicus, a beloved brother, carries Paul's letters to the churches and reports on his welfare.",
        },
        {
          canonical: "Aristarchus",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Colossians", chapterStart: 4, verseStart: 10, display: "Colossians 4:10" }],
          explanation: "Aristarchus, Paul's fellow prisoner, travels with him and is named among his companions.",
        },
        {
          canonical: "Demas",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Timothy", chapterStart: 4, verseStart: 10, display: "2 Timothy 4:10" }],
          explanation: "Demas, once a fellow worker, deserts Paul, having loved the present world.",
        },
      ],
    },
  ],
};
