import type { SeedDay } from "./types";

export const DAY_29: SeedDay = {
  dayNumber: 29,
  date: "2026-10-16",
  scriptureBonus: {
    displayText: "Behold, how good and how pleasant it is for brothers to live together in unity!",
    book: "Psalms",
    chapter: 133,
    verseStart: 1,
    referenceDisplay: "Psalm 133:1",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A short psalm of ascents celebrating the joy of unity among family and community.",
    acceptedBookAliases: ["psalm", "psalms"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name the father of one of Jesus' twelve apostles.",
      instructions: "You get one guess.",
      whatCounts: "Any man the biblical text explicitly names as the father of one of the twelve apostles.",
      answers: [
        {
          canonical: "Zebedee",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 21, display: "Matthew 4:21" }],
          explanation: "Zebedee is the father of the apostles James and John.",
        },
        {
          canonical: "Alphaeus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 3, verseStart: 18, display: "Mark 3:18" }],
          exclusions: [],
          explanation: "Alphaeus is named as the father of the apostle James (called James the Less).",
        },
        {
          canonical: "Jonah",
          aliases: ["john", "jona", "bar-jonah"],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 1, verseStart: 42, display: "John 1:42" }],
          exclusions: [],
          explanation: "Jesus addresses Simon Peter as \"son of Jonah\" (rendered \"John\" in some manuscripts/translations).",
          inclusionNotes: "Matthew 16:17 has 'Bar-Jonah'; John's Gospel renders the same figure's name as 'John' in some manuscript traditions — both spellings refer to the same person and are accepted.",
        },
        {
          canonical: "Simon",
          aliases: ["simon father of judas"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "John", chapterStart: 6, verseStart: 71, display: "John 6:71" }],
          exclusions: ["simon peter", "simon the zealot"],
          explanation: "Judas Iscariot is identified as the son of Simon.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a Jewish religious, political, or philosophical group named in the New Testament.",
      instructions: "You get one guess.",
      whatCounts: "Any named group, sect, or party the New Testament text refers to collectively (not an individual).",
      answers: [
        {
          canonical: "Pharisees",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 23, verseStart: 2, display: "Matthew 23:2" }],
          explanation: "The Pharisees are a prominent religious party known for strict observance of the Law.",
        },
        {
          canonical: "Sadducees",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 23, verseStart: 8, display: "Acts 23:8" }],
          explanation: "The Sadducees, a priestly aristocratic party, deny the resurrection and angels.",
        },
        {
          canonical: "Scribes",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 1, verseStart: 22, display: "Mark 1:22" }],
          explanation: "The scribes, experts in the Law, are often paired with the Pharisees as Jesus' critics.",
        },
        {
          canonical: "Herodians",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 3, verseStart: 6, display: "Mark 3:6" }],
          explanation: "The Herodians, political supporters of Herod's dynasty, join the Pharisees in plotting against Jesus.",
        },
        {
          canonical: "Epicureans",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 18, display: "Acts 17:18" }],
          explanation: "Epicurean philosophers debate Paul in the Areopagus at Athens.",
        },
        {
          canonical: "Stoics",
          aliases: ["stoic philosophers"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 17, verseStart: 18, display: "Acts 17:18" }],
          explanation: "Stoic philosophers, alongside the Epicureans, encounter Paul preaching in Athens.",
        },
        {
          canonical: "The Sect of the Nazarenes",
          aliases: ["nazarenes"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 24, verseStart: 5, display: "Acts 24:5" }],
          explanation: "Tertullus accuses Paul before Felix of being a ringleader of the sect of the Nazarenes — an early name for Christians.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a woman who confronted or challenged a king in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any woman the biblical text explicitly describes confronting, rebuking, or boldly challenging a king.",
      answers: [
        {
          canonical: "Abigail",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 25, verseStart: 23, display: "1 Samuel 25:23" }],
          explanation: "Abigail intercepts David to plead against his planned vengeance on Nabal's household.",
        },
        {
          canonical: "Esther",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Esther", chapterStart: 7, verseStart: 3, display: "Esther 7:3" }],
          explanation: "Esther confronts King Xerxes at her banquet, exposing Haman's plot against her people.",
        },
        {
          canonical: "Bathsheba",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 1, verseStart: 15, display: "1 Kings 1:15" }],
          explanation: "Bathsheba goes before the aging David to press Solomon's claim to the throne.",
        },
        {
          canonical: "Michal",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 6, verseStart: 20, display: "2 Samuel 6:20" }],
          explanation: "Michal comes out to meet David and sharply rebukes him for dancing before the ark.",
        },
        {
          canonical: "The Wise Woman of Tekoa",
          aliases: ["woman of tekoa"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 14, verseStart: 4, display: "2 Samuel 14:4" }],
          explanation: "A wise woman from Tekoa uses a parable to challenge David into recalling his exiled son Absalom.",
        },
        {
          canonical: "Vashti",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Esther", chapterStart: 1, verseStart: 12, display: "Esther 1:12" }],
          explanation: "Queen Vashti refuses King Xerxes' summons to display herself before his guests.",
        },
        {
          canonical: "The Queen of Sheba",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 10, verseStart: 1, display: "1 Kings 10:1" }],
          explanation: "The Queen of Sheba comes to test Solomon with hard questions about his famed wisdom.",
        },
        {
          canonical: "The Shunammite Woman",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 8, verseStart: 3, display: "2 Kings 8:3" }],
          explanation: "The Shunammite woman comes before the king to petition for the return of her house and land.",
        },
        {
          canonical: "The Medium of Endor",
          aliases: ["witch of endor"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 28, verseStart: 12, display: "1 Samuel 28:12" }],
          explanation: "The medium at Endor cries out and rebukes Saul for deceiving her once she recognizes him.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a person who worked as a craftsman or artisan in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly names as skilled in a craft, trade, or construction work.",
      answers: [
        {
          canonical: "Bezalel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 31, verseStart: 2, display: "Exodus 31:2" }],
          explanation: "Bezalel is filled with the Spirit of God and skill to craft the tabernacle's furnishings.",
        },
        {
          canonical: "Oholiab",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 31, verseStart: 6, display: "Exodus 31:6" }],
          explanation: "Oholiab assists Bezalel as a skilled craftsman on the tabernacle project.",
        },
        {
          canonical: "Hiram of Tyre",
          aliases: ["hiram the craftsman"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 7, verseStart: 13, verseEnd: 14, display: "1 Kings 7:13-14" }],
          exclusions: ["hiram king of tyre"],
          explanation: "Hiram, a bronze craftsman from Tyre, casts the pillars and furnishings for Solomon's temple.",
        },
        {
          canonical: "Alexander the Coppersmith",
          aliases: ["alexander"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Timothy", chapterStart: 4, verseStart: 14, display: "2 Timothy 4:14" }],
          exclusions: ["alexander the great"],
          explanation: "Alexander the coppersmith does Paul great harm, and Paul warns Timothy to be wary of him.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a shepherd named in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text explicitly describes as tending sheep or flocks.",
      answers: [
        {
          canonical: "David",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 16, verseStart: 11, display: "1 Samuel 16:11" }],
          explanation: "David is tending his father's sheep when Samuel comes to anoint him king.",
        },
        {
          canonical: "Moses",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 3, verseStart: 1, display: "Exodus 3:1" }],
          explanation: "Moses is keeping Jethro's flock when he encounters the burning bush.",
        },
        {
          canonical: "Rachel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 9, display: "Genesis 29:9" }],
          explanation: "Rachel is a shepherdess, tending her father Laban's flock, when Jacob first meets her.",
        },
        {
          canonical: "Jacob",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 30, verseStart: 31, display: "Genesis 30:31" }],
          explanation: "Jacob shepherds Laban's flocks for twenty years, growing wealthy through selective breeding.",
        },
        {
          canonical: "Abel",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 4, verseStart: 2, display: "Genesis 4:2" }],
          explanation: "Abel is a keeper of sheep, and his offering of the firstborn of his flock is accepted by God.",
        },
        {
          canonical: "Amos",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Amos", chapterStart: 1, verseStart: 1, display: "Amos 1:1" }],
          explanation: "Amos identifies himself as a shepherd from Tekoa before God calls him to prophesy.",
        },
      ],
    },
  ],
};
