import type { SeedDay } from "./types";

export const DAY_36: SeedDay = {
  dayNumber: 36,
  date: "2026-10-23",
  scriptureBonus: {
    displayText: "I will lift up my eyes to the mountains. Where does my help come from? My help comes from Yahweh, who made heaven and earth.",
    book: "Psalms",
    chapter: 121,
    verseStart: 1,
    verseEnd: 2,
    referenceDisplay: "Psalm 121:1-2",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A pilgrim psalm expressing confidence that help comes from the Creator, not from the surrounding hills.",
    acceptedBookAliases: ["ps", "psalm"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a book of the Bible named after a person.",
      instructions: "You get one guess.",
      whatCounts: "Any book of the 66-book Protestant canon whose title is a person's proper name.",
      answers: [
        {
          canonical: "Matthew",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 1, display: "Matthew 1:1" }],
          explanation: "The first Gospel, traditionally attributed to the tax collector turned apostle Matthew.",
        },
        {
          canonical: "Mark",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 1, verseStart: 1, display: "Mark 1:1" }],
          explanation: "The shortest Gospel, traditionally written by John Mark from Peter's preaching.",
        },
        {
          canonical: "Luke",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 1, display: "Luke 1:1-4" }],
          explanation: "A Gospel traditionally written by Luke the physician, Paul's traveling companion.",
        },
        {
          canonical: "Ruth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 1, verseStart: 1, display: "Ruth 1:1" }],
          explanation: "The story of the Moabite widow Ruth, ancestor of David.",
        },
        {
          canonical: "John",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 1, verseStart: 1, display: "John 1:1" }],
          explanation: "The fourth Gospel, traditionally attributed to the apostle John.",
        },
        {
          canonical: "Esther",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 17, display: "Esther 2:17" }],
          explanation: "The Jewish queen of Persia who saves her people from Haman's plot.",
        },
        {
          canonical: "Daniel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 1, verseStart: 6, display: "Daniel 1:6" }],
          explanation: "The prophet whose visions and lion's-den ordeal fill this book.",
        },
        {
          canonical: "Job",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Job", chapterStart: 1, verseStart: 1, display: "Job 1:1" }],
          explanation: "The wisdom book centered on Job's suffering and God's answer from the whirlwind.",
        },
        {
          canonical: "Isaiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Isaiah", chapterStart: 1, verseStart: 1, display: "Isaiah 1:1" }],
          explanation: "A major prophet whose 66 chapters include many messianic prophecies.",
        },
        {
          canonical: "Jeremiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 1, verseStart: 1, display: "Jeremiah 1:1" }],
          explanation: "The \"weeping prophet\" who warned Judah before the Babylonian exile.",
        },
        {
          canonical: "Ezekiel",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Ezekiel", chapterStart: 1, verseStart: 1, display: "Ezekiel 1:1" }],
          explanation: "A priest-prophet among the exiles, known for vivid visions.",
        },
        {
          canonical: "James",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "James", chapterStart: 1, verseStart: 1, display: "James 1:1" }],
          explanation: "A New Testament letter traditionally attributed to James, brother of Jesus.",
        },
        {
          canonical: "Jonah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Jonah", chapterStart: 1, verseStart: 1, display: "Jonah 1:1" }],
          explanation: "The prophet swallowed by a great fish on his way to Nineveh.",
        },
        {
          canonical: "Joshua",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Joshua", chapterStart: 1, verseStart: 1, display: "Joshua 1:1" }],
          explanation: "Moses' successor, who leads Israel into the promised land.",
        },
        {
          canonical: "Samuel",
          aliases: ["1 samuel", "2 samuel", "first samuel", "second samuel"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 1, display: "1 Samuel 1:1" }],
          explanation: "The prophet-judge for whom 1 and 2 Samuel are named.",
        },
        {
          canonical: "Titus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Titus", chapterStart: 1, verseStart: 1, display: "Titus 1:1" }],
          explanation: "A letter to Paul's associate Titus, left to organize the church on Crete.",
        },
        {
          canonical: "Micah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Micah", chapterStart: 1, verseStart: 1, display: "Micah 1:1" }],
          explanation: "A minor prophet who foretold the Messiah's birthplace, Bethlehem.",
        },
        {
          canonical: "Haggai",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Haggai", chapterStart: 1, verseStart: 1, display: "Haggai 1:1" }],
          explanation: "A minor prophet who urged the returned exiles to rebuild the temple.",
        },
        {
          canonical: "Philemon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Philemon", chapterStart: 1, verseStart: 1, display: "Philemon 1:1" }],
          explanation: "Paul's short personal letter appealing for the runaway slave Onesimus.",
        },
        {
          canonical: "Jude",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jude", chapterStart: 1, verseStart: 1, display: "Jude 1:1" }],
          explanation: "A brief letter warning against false teachers, traditionally by Jesus' brother Jude.",
        },
        {
          canonical: "Obadiah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Obadiah", chapterStart: 1, verseStart: 1, display: "Obadiah 1:1" }],
          explanation: "The shortest book of the Old Testament, a single chapter of judgment on Edom.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a city where Paul was imprisoned.",
      instructions: "You get one guess.",
      whatCounts: "Any city the book of Acts (or Paul's own letters) explicitly places Paul in custody or prison.",
      answers: [
        {
          canonical: "Rome",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 16, display: "Acts 28:16" }],
          explanation: "Paul is kept under house arrest in Rome awaiting trial before Caesar.",
        },
        {
          canonical: "Philippi",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 23, verseEnd: 24, display: "Acts 16:23-24" }],
          explanation: "Paul and Silas are beaten and jailed in Philippi after freeing a slave girl from a spirit.",
        },
        {
          canonical: "Caesarea",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 23, verseStart: 33, display: "Acts 23:33" }],
          explanation: "Paul is held in Herod's palace at Caesarea for two years under Felix and Festus.",
        },
        {
          canonical: "Jerusalem",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 33, display: "Acts 21:33" }],
          explanation: "Roman soldiers arrest Paul in the temple and hold him in the Antonia barracks.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a New Testament letter's recipient (a person or a church).",
      instructions: "You get one guess.",
      whatCounts: "Any person or church a New Testament epistle is explicitly addressed to, per its opening verses.",
      answers: [
        {
          canonical: "The Romans",
          aliases: ["rome", "church at rome", "roman church"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Romans", chapterStart: 1, verseStart: 7, display: "Romans 1:7" }],
          explanation: "Paul's letter to \"all who are in Rome, beloved of God, called to be saints.\"",
        },
        {
          canonical: "The Corinthians",
          aliases: ["corinth", "church at corinth", "corinthian church"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 1, verseStart: 2, display: "1 Corinthians 1:2" }],
          explanation: "Both 1 and 2 Corinthians address \"the assembly of God which is at Corinth.\"",
        },
        {
          canonical: "The Galatians",
          aliases: ["galatia", "churches of galatia"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Galatians", chapterStart: 1, verseStart: 2, display: "Galatians 1:2" }],
          explanation: "Paul writes \"to the assemblies of Galatia,\" correcting a return to the Law.",
        },
        {
          canonical: "The Ephesians",
          aliases: ["ephesus", "church at ephesus"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ephesians", chapterStart: 1, verseStart: 1, display: "Ephesians 1:1" }],
          explanation: "Addressed \"to the saints who are at Ephesus.\"",
        },
        {
          canonical: "Timothy",
          aliases: ["1 timothy", "2 timothy", "first timothy", "second timothy"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Timothy", chapterStart: 1, verseStart: 2, display: "1 Timothy 1:2" }],
          explanation: "Paul's two pastoral letters to his younger co-worker Timothy.",
        },
        {
          canonical: "Titus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Titus", chapterStart: 1, verseStart: 4, display: "Titus 1:4" }],
          explanation: "Addressed to \"Titus, my true child according to a common faith.\"",
        },
        {
          canonical: "Philemon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Philemon", chapterStart: 1, verseStart: 1, display: "Philemon 1:1" }],
          explanation: "Paul's personal appeal \"to Philemon, our beloved fellow worker.\"",
        },
        {
          canonical: "The Hebrews",
          aliases: ["hebrew christians", "hebrew believers"],
          score: 60,
          tier: "veil",
          references: [{ book: "Hebrews", chapterStart: 1, verseStart: 1, display: "Hebrews 1:1" }],
          explanation: "An anonymous letter urging Jewish believers not to abandon their faith.",
        },
        {
          canonical: "The Twelve Tribes in the Dispersion",
          aliases: ["the dispersion", "twelve tribes", "scattered tribes"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "James", chapterStart: 1, verseStart: 1, display: "James 1:1" }],
          explanation: "James addresses his letter \"to the twelve tribes which are in the Dispersion.\"",
        },
        {
          canonical: "Gaius",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "3 John", chapterStart: 1, verseStart: 1, display: "3 John 1:1" }],
          explanation: "3 John is addressed to \"the beloved Gaius,\" commended for his hospitality.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a son of Noah, or one of his descendants listed in Genesis 10.",
      instructions: "You get one guess.",
      whatCounts: "Noah's three sons, or any of their sons/grandsons explicitly named in the Genesis 10 \"Table of Nations.\"",
      answers: [
        {
          canonical: "Shem",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 1, display: "Genesis 10:1" }],
          explanation: "Noah's oldest son, ancestor of the Semitic peoples including Abraham's line.",
        },
        {
          canonical: "Ham",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 1, display: "Genesis 10:1" }],
          explanation: "Noah's son whose descendants include Cush, Egypt, and Canaan.",
        },
        {
          canonical: "Japheth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 1, display: "Genesis 10:1" }],
          explanation: "Noah's son whose descendants are listed as spreading into the coastlands.",
        },
        {
          canonical: "Canaan",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 6, display: "Genesis 10:6" }],
          explanation: "Son of Ham, ancestor of the Canaanite peoples later displaced by Israel.",
        },
        {
          canonical: "Cush",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 6, display: "Genesis 10:6" }],
          explanation: "Son of Ham, ancestor of Nimrod and the region of Cush (Ethiopia/Nubia).",
        },
        {
          canonical: "Nimrod",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 8, verseEnd: 9, display: "Genesis 10:8-9" }],
          explanation: "Grandson of Ham described as \"a mighty hunter before Yahweh\" and founder of Babel.",
        },
        {
          canonical: "Mizraim",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 6, display: "Genesis 10:6" }],
          explanation: "Son of Ham whose name is the Hebrew word for Egypt.",
        },
        {
          canonical: "Javan",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 2, display: "Genesis 10:2" }],
          explanation: "Son of Japheth, traditionally linked to the Greeks (Ionians).",
        },
        {
          canonical: "Tubal",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 2, display: "Genesis 10:2" }],
          explanation: "Son of Japheth, a region later paired with Meshech in prophetic texts.",
        },
        {
          canonical: "Elam",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 10, verseStart: 22, display: "Genesis 10:22" }],
          explanation: "Son of Shem, ancestor of the Elamite people east of Mesopotamia.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name an island mentioned in Paul's travels in the book of Acts.",
      instructions: "You get one guess.",
      whatCounts: "Any island Acts explicitly places Paul visiting, sailing past, or shipwrecked on.",
      answers: [
        {
          canonical: "Malta",
          aliases: ["melita"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 1, display: "Acts 28:1" }],
          explanation: "Paul is shipwrecked on Malta and bitten by a viper without harm.",
        },
        {
          canonical: "Cyprus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 4, display: "Acts 13:4" }],
          explanation: "Paul and Barnabas preach across Cyprus, Barnabas's home island, on their first journey.",
        },
        {
          canonical: "Crete",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 7, display: "Acts 27:7" }],
          explanation: "Paul's prisoner ship sails along the coast of Crete before the storm.",
        },
        {
          canonical: "Rhodes",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 1, display: "Acts 21:1" }],
          explanation: "Paul's ship passes Rhodes on the voyage from Miletus toward Jerusalem.",
        },
        {
          canonical: "Cos",
          aliases: ["kos"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 21, verseStart: 1, display: "Acts 21:1" }],
          explanation: "Paul's ship stops at the island of Cos on the same journey.",
        },
        {
          canonical: "Chios",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 15, display: "Acts 20:15" }],
          explanation: "Paul's ship arrives opposite the island of Chios on the way to Miletus.",
        },
      ],
    },
  ],
};
