import type { SeedDay } from "./types";

export const DAY_30: SeedDay = {
  dayNumber: 30,
  date: "2026-10-17",
  scriptureBonus: {
    displayText: "Pure religion and undefiled before our God and Father is this: to visit the fatherless and widows in their affliction.",
    book: "James",
    chapter: 1,
    verseStart: 27,
    referenceDisplay: "James 1:27",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "James defines true religious devotion in terms of practical care for the most vulnerable.",
    acceptedBookAliases: ["jas"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person's uncle, aunt, nephew, niece, or cousin explicitly identified in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person the biblical text explicitly names in one of these extended-family relationships to another named person.",
      answers: [
        {
          canonical: "Lot",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 12, verseStart: 5, display: "Genesis 12:5" }],
          explanation: "Lot is Abraham's nephew, son of his brother Haran, who travels with him to Canaan.",
        },
        {
          canonical: "Laban",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 10, display: "Genesis 29:10" }],
          explanation: "Laban is Jacob's uncle (his mother Rebekah's brother) and later his father-in-law.",
        },
        {
          canonical: "Elizabeth",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 36, display: "Luke 1:36" }],
          explanation: "Elizabeth is called Mary's relative, traditionally understood as her cousin.",
        },
        {
          canonical: "Barnabas",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Colossians", chapterStart: 4, verseStart: 10, display: "Colossians 4:10" }],
          explanation: "Barnabas is identified as the cousin of John Mark.",
        },
        {
          canonical: "Jehosheba",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 11, verseStart: 2, display: "2 Kings 11:2" }],
          explanation: "Jehosheba, King Ahaziah's sister, hides her infant nephew Joash from Athaliah's slaughter of the royal family.",
        },
        {
          canonical: "Mordecai",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Esther", chapterStart: 2, verseStart: 7, display: "Esther 2:7" }],
          exclusions: [],
          explanation: "Mordecai is identified as Esther's cousin, and raises her after her parents' death.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person identified as a widow in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any woman the biblical text explicitly identifies as a widow.",
      answers: [
        {
          canonical: "Naomi",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 1, verseStart: 3, display: "Ruth 1:3" }],
          explanation: "Naomi is left a widow after her husband Elimelech dies in Moab.",
        },
        {
          canonical: "Ruth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 1, verseStart: 5, display: "Ruth 1:5" }],
          explanation: "Ruth is widowed alongside her mother-in-law Naomi after her husband Mahlon dies.",
        },
        {
          canonical: "Anna",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 37, display: "Luke 2:37" }],
          explanation: "Anna the prophetess had been a widow for eighty-four years, worshiping continually at the temple.",
        },
        {
          canonical: "The Widow of Zarephath",
          aliases: ["widow of zarephath"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 9, display: "1 Kings 17:9" }],
          explanation: "The widow of Zarephath shares her last meal with Elijah, and her flour and oil never run out.",
        },
        {
          canonical: "The Widow of Nain",
          aliases: ["widow of nain"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 7, verseStart: 12, display: "Luke 7:12" }],
          explanation: "Jesus raises the only son of the widow of Nain during his funeral procession.",
        },
        {
          canonical: "The Widow with Two Mites",
          aliases: ["widow's mite", "poor widow"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 12, verseStart: 42, display: "Mark 12:42" }],
          explanation: "A poor widow gives two small copper coins, all she had, which Jesus praises above the rich donors.",
        },
        {
          canonical: "Tamar",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 38, verseStart: 11, display: "Genesis 38:11" }],
          explanation: "Tamar is twice widowed by Judah's sons before disguising herself to secure an heir through Judah himself.",
        },
        {
          canonical: "Judith",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Judith", chapterStart: 8, verseStart: 4, display: "Judith 8:4" }],
          catholicOnly: true,
          explanation: "Judith, a wealthy and devout widow, beheads the general Holofernes to save her city.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a firstborn son named in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named individual the biblical text explicitly identifies as a firstborn son.",
      answers: [
        {
          canonical: "Cain",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 4, verseStart: 1, display: "Genesis 4:1" }],
          explanation: "Cain is the firstborn son of Adam and Eve.",
        },
        {
          canonical: "Reuben",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 29, verseStart: 32, display: "Genesis 29:32" }],
          explanation: "Reuben is Jacob's firstborn son, born to Leah.",
        },
        {
          canonical: "Esau",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 25, display: "Genesis 25:25" }],
          explanation: "Esau emerges from the womb first, making him Isaac's firstborn.",
        },
        {
          canonical: "Manasseh",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 51, display: "Genesis 41:51" }],
          explanation: "Manasseh is Joseph's firstborn son, born in Egypt before the famine.",
        },
        {
          canonical: "Er",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 38, verseStart: 6, display: "Genesis 38:6" }],
          explanation: "Er, Judah's firstborn son, is put to death by the LORD for his wickedness.",
        },
        {
          canonical: "Eliab",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 17, verseStart: 13, display: "1 Samuel 17:13" }],
          explanation: "Eliab is Jesse's firstborn son, passed over by Samuel in favor of his youngest brother David.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name something King Josiah destroyed or removed during his religious reforms.",
      instructions: "You get one guess.",
      whatCounts: "Any object, altar, or practice 2 Kings 23 explicitly describes King Josiah destroying, removing, or abolishing.",
      answers: [
        {
          canonical: "The Asherah Pole from the Temple",
          aliases: ["asherah pole", "the asherah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 6, display: "2 Kings 23:6" }],
          explanation: "Josiah brings the Asherah pole out of the temple and burns it at the Kidron Valley.",
        },
        {
          canonical: "The High Places",
          aliases: ["high places of judah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 8, display: "2 Kings 23:8" }],
          explanation: "Josiah defiles the high places throughout Judah where priests had burned incense.",
        },
        {
          canonical: "The Horses Dedicated to the Sun",
          aliases: ["horses of the sun"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 11, display: "2 Kings 23:11" }],
          explanation: "Josiah removes the horses Judah's kings had dedicated to the sun and burns their chariots.",
        },
        {
          canonical: "The Altars on the Roof",
          aliases: ["ahaz's roof altars"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 12, display: "2 Kings 23:12" }],
          explanation: "Josiah tears down the altars Ahaz had made on the roof and scatters their dust.",
        },
        {
          canonical: "The Topheth in the Valley of Ben Hinnom",
          aliases: ["topheth"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 10, display: "2 Kings 23:10" }],
          explanation: "Josiah defiles the Topheth so no one can offer a child in the fire to Molech there.",
        },
        {
          canonical: "The Mediums and Spiritists",
          aliases: ["mediums, spiritists, and teraphim"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 24, display: "2 Kings 23:24" }],
          explanation: "Josiah puts away the mediums, spiritists, and household gods found in Judah and Jerusalem.",
        },
        {
          canonical: "Solomon's High Places for Ashtoreth, Chemosh, and Molech",
          aliases: ["solomon's high places"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 13, display: "2 Kings 23:13" }],
          explanation: "Josiah defiles the high places Solomon had built east of Jerusalem for foreign gods.",
        },
        {
          canonical: "The Pillars and Asherah Poles Throughout Judah",
          aliases: ["sacred pillars and asherah poles"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 14, display: "2 Kings 23:14" }],
          explanation: "Josiah breaks the sacred pillars in pieces and fills their places with human bones.",
        },
        {
          canonical: "The Altar at Bethel",
          aliases: ["bethel altar"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 15, display: "2 Kings 23:15" }],
          explanation: "Josiah tears down the altar at Bethel that Jeroboam had built, burning bones on it to defile it.",
        },
        {
          canonical: "The Household Gods and Idols",
          aliases: ["teraphim and idols"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "2 Kings", chapterStart: 23, verseStart: 24, display: "2 Kings 23:24" }],
          explanation: "Josiah purges the household gods and idols seen throughout the land, fulfilling the words of the Law.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a person who served as an advisor or counselor to a king.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text explicitly describes giving counsel or advice to a king.",
      answers: [
        {
          canonical: "Nathan",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 12, verseStart: 1, display: "2 Samuel 12:1" }],
          explanation: "The prophet Nathan confronts David with the parable of the ewe lamb after his sin with Bathsheba.",
        },
        {
          canonical: "Ahithophel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 16, verseStart: 23, display: "2 Samuel 16:23" }],
          explanation: "Ahithophel's counsel was regarded as though one consulted the word of God himself.",
        },
        {
          canonical: "Hushai",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Samuel", chapterStart: 17, verseStart: 14, display: "2 Samuel 17:14" }],
          explanation: "Hushai deliberately gives Absalom bad counsel to undermine Ahithophel's better advice.",
        },
        {
          canonical: "Jonadab",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Samuel", chapterStart: 13, verseStart: 3, display: "2 Samuel 13:3" }],
          explanation: "Jonadab, a very crafty man, advises Amnon on a scheme to be alone with his sister Tamar.",
        },
        {
          canonical: "Rehoboam's Young Advisors",
          aliases: ["young men who grew up with rehoboam"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 12, verseStart: 8, display: "1 Kings 12:8" }],
          explanation: "Rehoboam rejects the elders' counsel for that of the young men who grew up with him, splitting the kingdom.",
        },
      ],
    },
  ],
};
