import type { SeedDay } from "./types";

export const DAY_37: SeedDay = {
  dayNumber: 37,
  date: "2026-10-24",
  scriptureBonus: {
    displayText: "As each has received a gift, employ it in serving one another, as good managers of the grace of God in its various forms.",
    book: "1 Peter",
    chapter: 4,
    verseStart: 10,
    referenceDisplay: "1 Peter 4:10",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Peter calls believers to steward whatever gift they have received in service to others.",
    acceptedBookAliases: ["1 pet", "1st peter", "first peter"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person baptized in the book of Acts.",
      instructions: "You get one guess.",
      whatCounts: "Any named individual Acts explicitly describes being baptized.",
      answers: [
        {
          canonical: "Saul",
          aliases: ["paul", "saul of tarsus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 18, display: "Acts 9:18" }],
          explanation: "Saul is baptized in Damascus after Ananias restores his sight.",
        },
        {
          canonical: "The Ethiopian Eunuch",
          aliases: ["ethiopian official", "eunuch"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 38, display: "Acts 8:38" }],
          explanation: "Philip baptizes the Ethiopian court official beside the road from Jerusalem to Gaza.",
        },
        {
          canonical: "Cornelius",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 48, display: "Acts 10:48" }],
          explanation: "Peter has the Roman centurion Cornelius and his household baptized.",
        },
        {
          canonical: "Lydia",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 15, display: "Acts 16:15" }],
          explanation: "Lydia, a dealer in purple cloth, is baptized with her household at Philippi.",
        },
        {
          canonical: "The Philippian Jailer",
          aliases: ["philippian jailor", "jailer"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 33, display: "Acts 16:33" }],
          explanation: "The jailer at Philippi is baptized the same night after an earthquake frees Paul and Silas.",
        },
        {
          canonical: "Crispus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 8, display: "Acts 18:8" }],
          explanation: "Crispus, ruler of the Corinthian synagogue, believes and is baptized.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person who anointed someone with oil in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any person, or group, the biblical text explicitly describes anointing another person (or a sacred object) with oil.",
      answers: [
        {
          canonical: "Samuel (Anointing Saul)",
          aliases: ["samuel anoints saul"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 10, verseStart: 1, display: "1 Samuel 10:1" }],
          explanation: "Samuel pours oil on Saul's head and kisses him, anointing him as Israel's first king.",
        },
        {
          canonical: "Samuel (Anointing David)",
          aliases: ["samuel anoints david"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Samuel", chapterStart: 16, verseStart: 13, display: "1 Samuel 16:13" }],
          explanation: "Samuel anoints David with oil in the midst of his brothers, and the Spirit comes upon him.",
        },
        {
          canonical: "Moses (Anointing Aaron)",
          aliases: ["moses anoints aaron"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Leviticus", chapterStart: 8, verseStart: 12, display: "Leviticus 8:12" }],
          explanation: "Moses pours anointing oil on Aaron's head to consecrate him as high priest.",
        },
        {
          canonical: "Mary of Bethany",
          aliases: ["mary anoints jesus feet"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 12, verseStart: 3, display: "John 12:3" }],
          explanation: "Mary anoints Jesus' feet with expensive perfume and wipes them with her hair.",
        },
        {
          canonical: "The Sinful Woman",
          aliases: ["woman who anointed jesus feet luke", "sinful woman anoints jesus"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 7, verseStart: 38, display: "Luke 7:38" }],
          explanation: "A sinful woman weeps at Jesus' feet, wiping them with her hair and anointing them with ointment.",
        },
        {
          canonical: "A Prophet Sent by Elisha (Anointing Jehu)",
          aliases: ["young prophet anoints jehu"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 9, verseStart: 6, display: "2 Kings 9:6" }],
          explanation: "A young prophet Elisha sends pours oil on Jehu's head, anointing him king over Israel.",
        },
        {
          canonical: "Zadok and Nathan (Anointing Solomon)",
          aliases: ["zadok anoints solomon"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 1, verseStart: 39, display: "1 Kings 1:39" }],
          explanation: "Zadok the priest anoints Solomon with oil from the tabernacle's horn at Gihon.",
        },
        {
          canonical: "The Twelve Apostles",
          aliases: ["disciples anoint the sick with oil"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 6, verseStart: 13, display: "Mark 6:13" }],
          explanation: "The Twelve cast out demons and anoint many sick people with oil, healing them.",
        },
        {
          canonical: "Moses (Anointing the Tabernacle)",
          aliases: ["moses anoints the tabernacle"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Exodus", chapterStart: 40, verseStart: 9, display: "Exodus 40:9" }],
          explanation: "Moses anoints the tabernacle and everything in it with the sacred anointing oil to consecrate them.",
        },
        {
          canonical: "Elijah (Anointing Elisha)",
          aliases: ["elijah anoints elisha as prophet"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 16, display: "1 Kings 19:16" }],
          explanation: "God tells Elijah to anoint Elisha son of Shaphat as prophet in his place.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name someone Paul greets by name in Romans 16.",
      instructions: "You get one guess.",
      whatCounts: "Any person named in Paul's closing greetings in Romans chapter 16.",
      answers: [
        {
          canonical: "Phoebe",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 1, display: "Romans 16:1" }],
          explanation: "Phoebe, a servant of the church at Cenchreae, is commended at the chapter's start.",
        },
        {
          canonical: "Priscilla",
          aliases: ["prisca"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 3, display: "Romans 16:3" }],
          explanation: "Priscilla and her husband Aquila are called Paul's fellow workers.",
        },
        {
          canonical: "Aquila",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 3, display: "Romans 16:3" }],
          explanation: "Aquila, a tentmaker like Paul, is greeted alongside his wife Priscilla.",
        },
        {
          canonical: "Mary",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 6, display: "Romans 16:6" }],
          explanation: "Paul greets a Mary who \"worked hard\" for the Roman believers.",
        },
        {
          canonical: "Andronicus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 7, display: "Romans 16:7" }],
          explanation: "Andronicus and Junia are called \"outstanding among the apostles.\"",
        },
        {
          canonical: "Junia",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 7, display: "Romans 16:7" }],
          explanation: "Junia is named alongside Andronicus as a relative and fellow prisoner of Paul.",
        },
        {
          canonical: "Rufus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 13, display: "Romans 16:13" }],
          explanation: "Paul greets Rufus, \"chosen in the Lord,\" and his mother.",
        },
        {
          canonical: "Tryphena",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 12, display: "Romans 16:12" }],
          explanation: "Tryphena is named among the women who \"labor in the Lord.\"",
        },
        {
          canonical: "Tryphosa",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 12, display: "Romans 16:12" }],
          explanation: "Tryphosa is named alongside Tryphena as a laborer in the Lord.",
        },
        {
          canonical: "Persis",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 12, display: "Romans 16:12" }],
          explanation: "Persis is called \"the beloved,\" who \"labored much in the Lord.\"",
        },
        {
          canonical: "Nereus",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 15, display: "Romans 16:15" }],
          explanation: "Nereus and his sister are greeted near the very end of Paul's long list.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a king listed in Jesus' genealogy in Matthew 1.",
      instructions: "You get one guess.",
      whatCounts: "Any king of Israel or Judah explicitly named in Matthew's genealogy of Jesus.",
      answers: [
        {
          canonical: "David",
          aliases: ["king david"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 6, display: "Matthew 1:6" }],
          explanation: "David is named as the pivot of Matthew's genealogy, \"David the king.\"",
        },
        {
          canonical: "Solomon",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 6, display: "Matthew 1:6" }],
          explanation: "Solomon, David's son by Bathsheba, continues the royal line.",
        },
        {
          canonical: "Hezekiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 9, display: "Matthew 1:9" }],
          explanation: "Hezekiah, a reforming king of Judah, appears in the genealogy's third section.",
        },
        {
          canonical: "Josiah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 10, display: "Matthew 1:10" }],
          explanation: "Josiah, remembered for his sweeping religious reforms, is listed near the exile.",
        },
        {
          canonical: "Jehoshaphat",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 8, display: "Matthew 1:8" }],
          explanation: "Jehoshaphat, a king allied with the northern kingdom, is named in verse 8.",
        },
        {
          canonical: "Uzziah",
          aliases: ["azariah"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 8, display: "Matthew 1:8" }],
          explanation: "Uzziah, whose long reign is detailed in 2 Chronicles, appears as Ozias in Matthew's Greek.",
        },
        {
          canonical: "Rehoboam",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 7, display: "Matthew 1:7" }],
          explanation: "Rehoboam, Solomon's son, oversees the kingdom's split into Israel and Judah.",
        },
        {
          canonical: "Manasseh",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 10, display: "Matthew 1:10" }],
          explanation: "Manasseh, Hezekiah's son, reigns longer than any other king of Judah.",
        },
        {
          canonical: "Jeconiah",
          aliases: ["jehoiachin"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 11, display: "Matthew 1:11" }],
          explanation: "Jeconiah's generation marks the deportation to Babylon in Matthew's outline.",
        },
        {
          canonical: "Abijah",
          aliases: ["abijam"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 7, display: "Matthew 1:7" }],
          explanation: "Abijah, Rehoboam's son, is one of the more obscure names on the royal list.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a town or region where Jesus taught or performed a miracle, named in the Gospels.",
      instructions: "You get one guess.",
      whatCounts: "Any town, village, or region the Gospels explicitly place Jesus teaching, healing, or performing a miracle in.",
      answers: [
        {
          canonical: "Nazareth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 4, verseStart: 16, display: "Luke 4:16" }],
          explanation: "Jesus reads from Isaiah in the synagogue of his hometown, Nazareth.",
        },
        {
          canonical: "Capernaum",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 1, verseStart: 21, display: "Mark 1:21" }],
          explanation: "Jesus makes Capernaum his base of ministry on the Sea of Galilee.",
        },
        {
          canonical: "Cana",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 2, verseStart: 1, display: "John 2:1" }],
          explanation: "Jesus turns water into wine at a wedding in Cana of Galilee.",
        },
        {
          canonical: "Bethany",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 11, verseStart: 1, display: "John 11:1" }],
          explanation: "Jesus raises Lazarus in Bethany, home of Mary, Martha, and Lazarus.",
        },
        {
          canonical: "Jericho",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 19, verseStart: 1, display: "Luke 19:1" }],
          explanation: "Jesus heals Bartimaeus and meets Zacchaeus while passing through Jericho.",
        },
        {
          canonical: "Bethsaida",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 8, verseStart: 22, display: "Mark 8:22" }],
          explanation: "Jesus heals a blind man at Bethsaida, home town of several apostles.",
        },
        {
          canonical: "Nain",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 7, verseStart: 11, display: "Luke 7:11" }],
          explanation: "Jesus raises a widow's only son at the town gate of Nain.",
        },
        {
          canonical: "Sychar",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "John", chapterStart: 4, verseStart: 5, display: "John 4:5" }],
          explanation: "Jesus speaks with the Samaritan woman at Jacob's well near Sychar.",
        },
        {
          canonical: "Caesarea Philippi",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 16, verseStart: 13, display: "Matthew 16:13" }],
          explanation: "Peter confesses Jesus as the Christ near Caesarea Philippi.",
        },
        {
          canonical: "Chorazin",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Matthew", chapterStart: 11, verseStart: 21, display: "Matthew 11:21" }],
          explanation: "Jesus pronounces woe on Chorazin for failing to repent despite his mighty works there.",
        },
      ],
    },
  ],
};
