import type { SeedDay } from "./types";

export const DAY_38: SeedDay = {
  dayNumber: 38,
  date: "2026-10-25",
  scriptureBonus: {
    displayText:
      "Don't be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.",
    book: "Romans",
    chapter: 12,
    verseStart: 2,
    referenceDisplay: "Romans 12:2",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul urges believers toward inward transformation rather than conformity to worldly patterns.",
    acceptedBookAliases: ["rom"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name something John saw in his vision in the book of Revelation.",
      instructions: "You get one guess.",
      whatCounts: "Any specific figure, being, or object John explicitly describes seeing in his vision in Revelation.",
      answers: [
        {
          canonical: "The Lamb",
          aliases: ["lamb as though slain", "lamb that was slain"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 5, verseStart: 6, display: "Revelation 5:6" }],
          explanation: "John sees a Lamb standing as though slain, worthy to open the sealed scroll.",
        },
        {
          canonical: "The Four Living Creatures",
          aliases: ["four living creatures"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 6, display: "Revelation 4:6" }],
          explanation: "Four living creatures full of eyes surround the throne, each with a different face.",
        },
        {
          canonical: "The Twenty-Four Elders",
          aliases: ["twenty four elders"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 4, display: "Revelation 4:4" }],
          explanation: "Twenty-four elders in white robes with golden crowns sit on thrones around God's throne.",
        },
        {
          canonical: "The Four Horsemen",
          aliases: ["four horsemen of the apocalypse"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Revelation", chapterStart: 6, verseStart: 2, display: "Revelation 6:2" }],
          explanation: "The opening of the first four seals releases riders on white, red, black, and pale horses.",
        },
        {
          canonical: "The Woman Clothed with the Sun",
          aliases: ["woman clothed with the sun"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 12, verseStart: 1, display: "Revelation 12:1" }],
          explanation: "John sees a great sign: a woman clothed with the sun, the moon under her feet.",
        },
        {
          canonical: "The Great Red Dragon",
          aliases: ["great red dragon", "the dragon"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Revelation", chapterStart: 12, verseStart: 3, display: "Revelation 12:3" }],
          explanation: "A great red dragon with seven heads and ten horns appears, ready to devour the woman's child.",
        },
        {
          canonical: "The Beast Out of the Sea",
          aliases: ["beast from the sea"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 13, verseStart: 1, display: "Revelation 13:1" }],
          explanation: "John sees a beast rising out of the sea with ten horns and seven heads.",
        },
        {
          canonical: "The Great White Throne",
          aliases: ["great white throne"],
          score: 60,
          tier: "veil",
          references: [{ book: "Revelation", chapterStart: 20, verseStart: 11, display: "Revelation 20:11" }],
          explanation: "John sees a great white throne and him who sits on it, from whose face earth and sky flee away.",
        },
        {
          canonical: "The Sea of Glass",
          aliases: ["sea of glass like crystal"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Revelation", chapterStart: 4, verseStart: 6, display: "Revelation 4:6" }],
          explanation: "Before the throne John sees a sea of glass, like crystal, spread out.",
        },
        {
          canonical: "The Two Witnesses",
          aliases: ["two witnesses"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 11, verseStart: 3, display: "Revelation 11:3" }],
          explanation: "John describes two witnesses who prophesy for 1,260 days clothed in sackcloth.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a woman named in a biblical genealogy.",
      instructions: "You get one guess.",
      whatCounts: "Any woman explicitly named within a genealogical list (Matthew 1, Genesis 11, 25, 35, etc.).",
      answers: [
        {
          canonical: "Mary",
          aliases: ["mary mother of jesus"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 16, display: "Matthew 1:16" }],
          explanation: "Mary closes Matthew's genealogy as the mother of Jesus.",
        },
        {
          canonical: "Ruth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Ruth the Moabite is named as the mother of Obed, David's grandfather.",
        },
        {
          canonical: "Tamar",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 3, display: "Matthew 1:3" }],
          explanation: "Tamar is named as the mother of Perez and Zerah by Judah.",
        },
        {
          canonical: "Rahab",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 5, display: "Matthew 1:5" }],
          explanation: "Rahab of Jericho is named as the mother of Boaz.",
        },
        {
          canonical: "Bathsheba",
          aliases: ["her who had been uriahs wife", "wife of uriah"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 6, display: "Matthew 1:6" }],
          explanation: "Matthew names her indirectly as \"her who had been Uriah's wife.\"",
        },
        {
          canonical: "Sarah",
          aliases: ["sarai"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 11, verseStart: 29, display: "Genesis 11:29" }],
          explanation: "Sarah is named as Abram's wife in the genealogical record of Terah's family.",
        },
        {
          canonical: "Keturah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 25, verseStart: 1, display: "Genesis 25:1" }],
          explanation: "Keturah is named as the wife Abraham takes after Sarah's death.",
        },
        {
          canonical: "Milcah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 11, verseStart: 29, display: "Genesis 11:29" }],
          explanation: "Milcah is named as the wife of Abram's brother Nahor.",
        },
        {
          canonical: "Zilpah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 35, verseStart: 26, display: "Genesis 35:26" }],
          explanation: "Zilpah, Leah's servant, is named as the mother of Gad and Asher in Jacob's family list.",
        },
        {
          canonical: "Bilhah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 35, verseStart: 25, display: "Genesis 35:25" }],
          explanation: "Bilhah, Rachel's servant, is named as the mother of Dan and Naphtali.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a Jewish religious leader, teacher of the Law, or synagogue official named in the Gospels or Acts (not a high priest).",
      instructions: "You get one guess.",
      whatCounts: "Any named Pharisee, scribe, synagogue ruler, council member, or teacher of the Law in the Gospels or Acts, excluding high priests.",
      answers: [
        {
          canonical: "Nicodemus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 3, verseStart: 1, display: "John 3:1" }],
          explanation: "Nicodemus, a Pharisee and ruler of the Jews, visits Jesus by night.",
        },
        {
          canonical: "Jairus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 22, display: "Mark 5:22" }],
          explanation: "Jairus, a synagogue ruler, begs Jesus to heal his dying daughter.",
        },
        {
          canonical: "Gamaliel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 5, verseStart: 34, display: "Acts 5:34" }],
          explanation: "Gamaliel, a respected teacher of the Law, urges caution toward the apostles.",
        },
        {
          canonical: "Joseph of Arimathea",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 15, verseStart: 43, display: "Mark 15:43" }],
          explanation: "Joseph of Arimathea, a respected council member, requests Jesus' body for burial.",
        },
        {
          canonical: "Simon the Pharisee",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 7, verseStart: 36, display: "Luke 7:36" }],
          explanation: "Simon the Pharisee hosts Jesus and questions the woman who anoints his feet.",
        },
        {
          canonical: "Crispus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 8, display: "Acts 18:8" }],
          explanation: "Crispus, ruler of the Corinthian synagogue, believes in the Lord.",
        },
        {
          canonical: "Sosthenes",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 18, verseStart: 17, display: "Acts 18:17" }],
          explanation: "Sosthenes, a synagogue ruler at Corinth, is seized and beaten before the proconsul.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a returning exile leader in the books of Ezra or Nehemiah.",
      instructions: "You get one guess.",
      whatCounts: "Any person Ezra or Nehemiah names as leading, governing, or organizing the Jewish return from Babylonian exile.",
      answers: [
        {
          canonical: "Ezra",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ezra", chapterStart: 7, verseStart: 6, display: "Ezra 7:6" }],
          explanation: "Ezra, a skilled scribe of the Law, leads a later group of exiles back to Jerusalem.",
        },
        {
          canonical: "Nehemiah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Nehemiah", chapterStart: 1, verseStart: 1, display: "Nehemiah 1:1" }],
          explanation: "Nehemiah, cupbearer to the Persian king, leads the rebuilding of Jerusalem's walls.",
        },
        {
          canonical: "Zerubbabel",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ezra", chapterStart: 2, verseStart: 2, display: "Ezra 2:2" }],
          explanation: "Zerubbabel, of David's line, governs the first wave of returning exiles.",
        },
        {
          canonical: "Jeshua",
          aliases: ["joshua the high priest"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Ezra", chapterStart: 2, verseStart: 2, display: "Ezra 2:2" }],
          explanation: "Jeshua the high priest returns with Zerubbabel to help restore temple worship.",
        },
        {
          canonical: "Sheshbazzar",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ezra", chapterStart: 1, verseStart: 8, display: "Ezra 1:8" }],
          explanation: "Sheshbazzar, prince of Judah, carries the temple vessels back from Babylon as the first governor.",
        },
        {
          canonical: "Hanani",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Nehemiah", chapterStart: 1, verseStart: 2, display: "Nehemiah 1:2" }],
          explanation: "Nehemiah's brother Hanani brings the report of Jerusalem's broken walls that prompts his return.",
        },
        {
          canonical: "Zechariah son of Iddo",
          aliases: ["zechariah"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Ezra", chapterStart: 5, verseStart: 1, display: "Ezra 5:1" }],
          explanation: "The prophet Zechariah encourages the returned exiles to resume rebuilding the temple.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a person a New Testament letter names as opposing sound teaching or the apostles' authority.",
      instructions: "You get one guess.",
      whatCounts: "Any named individual a New Testament letter (or Acts) explicitly identifies as a false teacher, sorcerer, or opponent of the apostles.",
      answers: [
        {
          canonical: "Hymenaeus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Timothy", chapterStart: 1, verseStart: 20, display: "1 Timothy 1:20" }],
          explanation: "Hymenaeus is named among those Paul has \"delivered to Satan\" for blasphemy.",
        },
        {
          canonical: "Alexander the Coppersmith",
          aliases: ["alexander"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Timothy", chapterStart: 4, verseStart: 14, display: "2 Timothy 4:14" }],
          explanation: "Paul warns Timothy that Alexander the coppersmith \"did me much harm.\"",
        },
        {
          canonical: "Elymas",
          aliases: ["bar-jesus", "bar jesus"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 8, display: "Acts 13:8" }],
          explanation: "The sorcerer Elymas opposes Paul on Cyprus and is struck blind.",
        },
        {
          canonical: "Philetus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Timothy", chapterStart: 2, verseStart: 17, display: "2 Timothy 2:17" }],
          explanation: "Philetus is named alongside Hymenaeus for teaching that the resurrection had already happened.",
        },
        {
          canonical: "Diotrephes",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "3 John", chapterStart: 1, verseStart: 9, display: "3 John 1:9" }],
          explanation: "Diotrephes \"loves to be first\" and refuses to welcome John's messengers.",
        },
      ],
    },
  ],
};
