import type { SeedDay } from "./types";

export const DAY_34: SeedDay = {
  dayNumber: 34,
  date: "2026-10-21",
  scriptureBonus: {
    displayText: "Yahweh will fight for you, and you shall be still.",
    book: "Exodus",
    chapter: 14,
    verseStart: 14,
    referenceDisplay: "Exodus 14:14",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Moses reassures the Israelites trapped at the Red Sea that God himself will deliver them.",
    acceptedBookAliases: ["exo", "ex"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name an unclean spirit or demon named or described in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any unclean spirit, demon, or demonic name/title the biblical text explicitly uses.",
      answers: [
        {
          canonical: "Legion",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 9, display: "Mark 5:9" }],
          explanation: "The demon-possessed man from the Gerasenes says his name is Legion, \"for we are many.\"",
        },
        {
          canonical: "Beelzebul",
          aliases: ["beelzebub", "prince of demons"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 12, verseStart: 24, display: "Matthew 12:24" }],
          explanation: "The Pharisees accuse Jesus of casting out demons by Beelzebul, the prince of demons.",
        },
        {
          canonical: "The Seven Demons of Mary Magdalene",
          aliases: ["seven demons", "mary magdalene's demons"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 8, verseStart: 2, display: "Luke 8:2" }],
          explanation: "Mary Magdalene had seven demons cast out of her by Jesus.",
        },
        {
          canonical: "The Evil Spirit that Tormented Saul",
          aliases: ["saul's evil spirit", "distressing spirit"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 16, verseStart: 14, display: "1 Samuel 16:14" }],
          explanation: "An evil spirit from the LORD torments Saul, and David's harp-playing brings him relief.",
        },
        {
          canonical: "The Spirit of Divination",
          aliases: ["python spirit", "spirit of divination in acts"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 16, display: "Acts 16:16" }],
          explanation: "A slave girl in Philippi has a spirit of divination that Paul casts out, ending her owners' profit from her fortune-telling.",
        },
        {
          canonical: "The Mute Spirit",
          aliases: ["dumb spirit", "deaf and dumb spirit"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 9, verseStart: 25, display: "Mark 9:25" }],
          explanation: "Jesus rebukes a mute and deaf spirit tormenting a boy with seizures, commanding it to leave and never return.",
        },
        {
          canonical: "The Lying Spirit",
          aliases: ["lying spirit in ahab's prophets"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Kings", chapterStart: 22, verseStart: 22, display: "1 Kings 22:22" }],
          explanation: "In Micaiah's vision, a spirit volunteers to be a lying spirit in the mouths of Ahab's prophets to lure him to his death.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a miraculous escape or deliverance involving water in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person or group the biblical text describes being miraculously saved from or through water.",
      answers: [
        {
          canonical: "Noah and His Family",
          aliases: ["noah's ark", "noah survives the flood"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 7, verseStart: 23, display: "Genesis 7:23" }],
          explanation: "Noah and his family survive the flood that destroys all other life on earth, kept safe in the ark.",
        },
        {
          canonical: "Israel Crossing the Red Sea",
          aliases: ["israel at the red sea"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 14, verseStart: 22, display: "Exodus 14:22" }],
          explanation: "Israel crosses the parted Red Sea on dry ground while the pursuing Egyptian army is later drowned.",
        },
        {
          canonical: "Moses Saved from the Nile",
          aliases: ["baby moses in the basket", "moses in the reeds"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 2, verseStart: 3, verseEnd: 6, display: "Exodus 2:3-6" }],
          explanation: "The infant Moses is placed in a basket among the Nile's reeds and is found and saved by Pharaoh's daughter.",
        },
        {
          canonical: "Jonah Surviving the Great Fish",
          aliases: ["jonah and the whale", "jonah in the fish"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Jonah", chapterStart: 1, verseStart: 17, display: "Jonah 1:17" }],
          explanation: "Jonah is swallowed by a great fish and survives three days and nights inside it before being vomited onto dry land.",
        },
        {
          canonical: "Peter Walking on and Saved from the Water",
          aliases: ["peter saved from sinking"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 30, verseEnd: 31, display: "Matthew 14:30-31" }],
          explanation: "Jesus immediately reaches out and catches Peter as he begins to sink after walking on the water toward him.",
        },
        {
          canonical: "Paul's Shipwreck on Malta",
          aliases: ["paul's shipwreck", "paul survives shipwreck"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 43, verseEnd: 44, display: "Acts 27:43-44" }],
          explanation: "Everyone aboard Paul's storm-wrecked ship reaches land safely at Malta, just as an angel had told him.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a fire-related miracle or sign in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific miracle or sign the biblical text explicitly describes involving fire.",
      answers: [
        {
          canonical: "The Burning Bush",
          aliases: ["burning bush"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 3, verseStart: 2, display: "Exodus 3:2" }],
          explanation: "Moses sees a bush that burns with fire but is not consumed, from which God speaks to him.",
        },
        {
          canonical: "Fire on the Sacrifice at Mount Carmel",
          aliases: ["elijah's fire on carmel", "fire consumes the sacrifice"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 18, verseStart: 38, display: "1 Kings 18:38" }],
          explanation: "Fire falls from the LORD and consumes Elijah's water-soaked sacrifice before the prophets of Baal.",
        },
        {
          canonical: "The Fiery Furnace",
          aliases: ["shadrach meshach and abednego furnace"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Daniel", chapterStart: 3, verseStart: 26, display: "Daniel 3:26" }],
          explanation: "Shadrach, Meshach, and Abednego walk out of a furnace heated seven times hotter than normal without a hair singed.",
        },
        {
          canonical: "Tongues of Fire at Pentecost",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 2, verseStart: 3, display: "Acts 2:3" }],
          explanation: "Tongues like fire distribute themselves and rest on each of the disciples at Pentecost.",
        },
        {
          canonical: "Nadab and Abihu Consumed by Fire",
          aliases: ["strange fire"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Leviticus", chapterStart: 10, verseStart: 2, display: "Leviticus 10:2" }],
          explanation: "Fire from the LORD consumes Nadab and Abihu for offering unauthorized fire before him.",
        },
        {
          canonical: "Fire Consuming Elijah's Two Captains of Fifty",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 1, verseStart: 10, display: "2 Kings 1:10" }],
          explanation: "Fire comes down from heaven at Elijah's word and consumes two companies of soldiers sent to seize him.",
        },
        {
          canonical: "The Pillar of Fire",
          aliases: ["pillar of fire by night"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 13, verseStart: 21, display: "Exodus 13:21" }],
          explanation: "The LORD guides Israel through the wilderness by night in a pillar of fire.",
        },
        {
          canonical: "The Sword of Fire Guarding Eden",
          aliases: ["flaming sword", "sword guarding eden"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 3, verseStart: 24, display: "Genesis 3:24" }],
          explanation: "God places cherubim and a flaming sword that turns every way to guard the way to the tree of life.",
        },
        {
          canonical: "The Smoking Firepot and Flaming Torch",
          aliases: ["abraham's covenant fire", "firepot and torch between the pieces"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 15, verseStart: 17, display: "Genesis 15:17" }],
          explanation: "A smoking firepot and flaming torch pass between the divided animal pieces, sealing God's covenant with Abram.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a specific earthquake mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific earthquake the biblical text explicitly describes or references.",
      answers: [
        {
          canonical: "The Earthquake at Jesus' Crucifixion",
          aliases: ["earthquake at the crucifixion"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 51, display: "Matthew 27:51" }],
          explanation: "The earth shakes and rocks split at the moment Jesus dies on the cross.",
        },
        {
          canonical: "The Earthquake at the Resurrection",
          aliases: ["earthquake at the empty tomb"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 28, verseStart: 2, display: "Matthew 28:2" }],
          explanation: "A great earthquake occurs as an angel descends and rolls back the stone from Jesus' tomb.",
        },
        {
          canonical: "The Earthquake at Mount Sinai",
          aliases: ["sinai quaking"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 19, verseStart: 18, display: "Exodus 19:18" }],
          explanation: "Mount Sinai quakes greatly as the LORD descends on it in fire to give the Law.",
        },
        {
          canonical: "The Earthquake at the Philippian Prison",
          aliases: ["paul and silas earthquake"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 26, display: "Acts 16:26" }],
          explanation: "A sudden earthquake shakes the Philippian prison's foundations, freeing Paul and Silas.",
        },
        {
          canonical: "The Earth Swallowing Korah",
          aliases: ["korah swallowed", "ground opening up"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 16, verseStart: 31, verseEnd: 32, display: "Numbers 16:31-32" }],
          explanation: "The ground splits open and swallows Korah, Dathan, Abiram, and their households alive.",
        },
        {
          canonical: "The Earthquake in Elijah's Encounter at Horeb",
          aliases: ["elijah's earthquake at horeb"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 11, display: "1 Kings 19:11" }],
          explanation: "A great earthquake passes before Elijah at Horeb, though the LORD is not in the earthquake but the still small voice after.",
        },
        {
          canonical: "The Earthquake in Uzziah's Day",
          aliases: ["uzziah's earthquake"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Amos", chapterStart: 1, verseStart: 1, display: "Amos 1:1" }],
          explanation: "Amos dates his prophecies to two years before an earthquake remembered from the reign of King Uzziah.",
        },
        {
          canonical: "Jonathan's Earthquake at Michmash",
          aliases: ["michmash earthquake", "earthquake in the philistine camp"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Samuel", chapterStart: 14, verseStart: 15, display: "1 Samuel 14:15" }],
          explanation: "A trembling sent by God, described alongside the panic, shakes the earth during Jonathan's surprise attack on the Philistine garrison.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name someone filled with the Holy Spirit or who spoke in tongues in a notable recorded instance.",
      instructions: "You get one guess.",
      whatCounts: "Any named person or group the biblical text explicitly describes being filled with the Holy Spirit or speaking in tongues.",
      answers: [
        {
          canonical: "The Apostles at Pentecost",
          aliases: ["apostles at pentecost", "disciples speaking in tongues"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 2, verseStart: 4, display: "Acts 2:4" }],
          explanation: "The apostles are filled with the Holy Spirit at Pentecost and begin speaking in other tongues.",
        },
        {
          canonical: "Cornelius's Household",
          aliases: ["cornelius household spirit"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 10, verseStart: 44, verseEnd: 46, display: "Acts 10:44-46" }],
          explanation: "The Holy Spirit falls on Cornelius's Gentile household as Peter speaks, and they begin speaking in tongues.",
        },
        {
          canonical: "The Ephesian Disciples",
          aliases: ["twelve men at ephesus"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 19, verseStart: 6, display: "Acts 19:6" }],
          explanation: "About twelve disciples at Ephesus speak in tongues and prophesy after Paul lays hands on them.",
        },
        {
          canonical: "Elizabeth",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 41, display: "Luke 1:41" }],
          explanation: "Elizabeth is filled with the Holy Spirit and blesses Mary when the pregnant Mary visits her.",
        },
        {
          canonical: "Zechariah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 67, display: "Luke 1:67" }],
          explanation: "Zechariah is filled with the Holy Spirit and prophesies at the naming of his son John the Baptist.",
        },
        {
          canonical: "Simeon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 2, verseStart: 25, verseEnd: 27, display: "Luke 2:25-27" }],
          explanation: "The Holy Spirit rests on Simeon and leads him into the temple, where he recognizes the infant Jesus.",
        },
        {
          canonical: "John the Baptist",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 15, display: "Luke 1:15" }],
          explanation: "The angel Gabriel tells Zechariah that his son John will be filled with the Holy Spirit even from his mother's womb.",
        },
      ],
    },
  ],
};
