import type { SeedDay } from "./types";

export const DAY_31: SeedDay = {
  dayNumber: 31,
  date: "2026-10-18",
  scriptureBonus: {
    displayText: "For nothing will be impossible with God.",
    book: "Luke",
    chapter: 1,
    verseStart: 37,
    referenceDisplay: "Luke 1:37",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "The angel Gabriel assures Mary that God can accomplish what seems impossible, as with Elizabeth's pregnancy.",
    acceptedBookAliases: ["luke"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a physical ailment or disability Jesus healed.",
      instructions: "You get one guess.",
      whatCounts: "Any specific physical ailment, disability, or disease the Gospels explicitly describe Jesus healing.",
      answers: [
        {
          canonical: "Blindness",
          aliases: ["blind"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 9, verseStart: 1, verseEnd: 7, display: "John 9:1-7" }],
          explanation: "Jesus restores sight to several blind people across the Gospels, including a man born blind.",
        },
        {
          canonical: "Leprosy",
          aliases: ["leper", "leprous"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 1, verseEnd: 4, display: "Matthew 8:1-4" }],
          explanation: "Jesus cleanses a man of leprosy with a touch, and later ten lepers at once.",
        },
        {
          canonical: "Paralysis",
          aliases: ["lameness", "paralyzed", "lame", "unable to walk"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 2, verseStart: 1, verseEnd: 12, display: "Mark 2:1-12" }],
          explanation: "Jesus heals a paralyzed man lowered through a roof by his friends, telling him to take up his mat and walk.",
        },
        {
          canonical: "Deafness and Muteness",
          aliases: ["deaf", "mute", "deaf and dumb", "speech impediment"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 7, verseStart: 31, verseEnd: 37, display: "Mark 7:31-37" }],
          explanation: "Jesus heals a man who was deaf and had a speech impediment, putting his fingers in the man's ears.",
        },
        {
          canonical: "Fever",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 1, verseStart: 29, verseEnd: 31, display: "Mark 1:29-31" }],
          explanation: "Jesus heals Peter's mother-in-law of a fever by taking her hand.",
        },
        {
          canonical: "A Withered Hand",
          aliases: ["withered hand", "shriveled hand"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 3, verseStart: 1, verseEnd: 6, display: "Mark 3:1-6" }],
          explanation: "Jesus heals a man's withered hand in the synagogue on the Sabbath.",
        },
        {
          canonical: "Chronic Bleeding",
          aliases: ["issue of blood", "flow of blood", "hemorrhage", "bleeding woman"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 25, verseEnd: 34, display: "Mark 5:25-34" }],
          explanation: "A woman who had suffered bleeding for twelve years is healed by touching the fringe of Jesus' cloak.",
        },
        {
          canonical: "Being Bent Over",
          aliases: ["crippled", "bent over", "curvature of the spine"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 13, verseStart: 10, verseEnd: 13, display: "Luke 13:10-13" }],
          explanation: "Jesus heals a woman who had been crippled and bent over for eighteen years.",
        },
        {
          canonical: "Dropsy",
          aliases: ["edema", "swelling disease"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 14, verseStart: 1, verseEnd: 4, display: "Luke 14:1-4" }],
          explanation: "Jesus heals a man suffering from dropsy at a Pharisee's house on the Sabbath.",
        },
        {
          canonical: "Seizures",
          aliases: ["epilepsy", "convulsions"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 17, verseStart: 14, verseEnd: 18, display: "Matthew 17:14-18" }],
          explanation: "Jesus heals a boy who convulsed and fell into fire and water, described by his father before the healing.",
        },
        {
          canonical: "A Severed Ear",
          aliases: ["cut off ear", "malchus ear"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 22, verseStart: 50, verseEnd: 51, display: "Luke 22:50-51" }],
          explanation: "At his arrest, Jesus heals the severed ear of the high priest's servant after Peter cuts it off.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person raised from the dead by someone other than Jesus himself.",
      instructions: "You get one guess.",
      whatCounts: "Any named or clearly identified person the biblical text describes being restored to life by someone other than Jesus (not Jesus raising others, and not Jesus' own resurrection).",
      answers: [
        {
          canonical: "The Widow of Zarephath's Son",
          aliases: ["zarephath's son", "widow's son at zarephath"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 17, verseEnd: 24, display: "1 Kings 17:17-24" }],
          explanation: "Elijah stretches himself over the widow of Zarephath's dead son three times, and the boy's life returns.",
        },
        {
          canonical: "The Shunammite's Son",
          aliases: ["shunammite woman's son"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Kings", chapterStart: 4, verseStart: 32, verseEnd: 37, display: "2 Kings 4:32-37" }],
          explanation: "Elisha lies on the Shunammite woman's dead son and restores him to life.",
        },
        {
          canonical: "Tabitha",
          aliases: ["dorcas"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 36, verseEnd: 42, display: "Acts 9:36-42" }],
          explanation: "Peter raises Tabitha (also called Dorcas), a disciple known for her good works, back to life in Joppa.",
        },
        {
          canonical: "Eutychus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 9, verseEnd: 12, display: "Acts 20:9-12" }],
          explanation: "Paul restores Eutychus to life after the young man falls asleep and drops from a third-story window during a long sermon.",
        },
        {
          canonical: "The Man Raised by Touching Elisha's Bones",
          aliases: ["elisha's bones", "man thrown into elisha's tomb"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 13, verseStart: 20, verseEnd: 21, display: "2 Kings 13:20-21" }],
          explanation: "A dead man's body, hastily thrown into Elisha's tomb, comes back to life the moment it touches the prophet's bones.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a notable prayer recorded in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific prayer the biblical text records someone praying, identified by the person praying it or its common name.",
      answers: [
        {
          canonical: "The Lord's Prayer",
          aliases: ["our father", "lord's prayer"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 6, verseStart: 9, verseEnd: 13, display: "Matthew 6:9-13" }],
          explanation: "Jesus teaches his disciples this model prayer beginning \"Our Father in heaven.\"",
        },
        {
          canonical: "Jesus' Prayer in Gethsemane",
          aliases: ["gethsemane prayer", "let this cup pass"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 39, display: "Matthew 26:39" }],
          explanation: "Jesus prays in agony in the Garden of Gethsemane, asking that the cup pass from him yet submitting to the Father's will.",
        },
        {
          canonical: "Hannah's Prayer",
          aliases: ["hannah's song"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 10, verseEnd: 13, display: "1 Samuel 1:10-13" }],
          explanation: "The barren Hannah prays fervently at Shiloh for a son, so silently that Eli mistakes her for drunk.",
        },
        {
          canonical: "Solomon's Prayer of Dedication",
          aliases: ["solomon's dedication prayer", "temple dedication prayer"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 8, verseStart: 22, verseEnd: 53, display: "1 Kings 8:22-53" }],
          explanation: "Solomon prays at the dedication of the temple, asking God to hear prayers offered toward that place.",
        },
        {
          canonical: "Mary's Magnificat",
          aliases: ["magnificat", "mary's song"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 46, verseEnd: 55, display: "Luke 1:46-55" }],
          explanation: "Mary praises God with a song of thanksgiving after visiting Elizabeth, beginning \"My soul magnifies the Lord.\"",
        },
        {
          canonical: "The Tax Collector's Prayer",
          aliases: ["publican's prayer", "be merciful to me a sinner"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 18, verseStart: 13, display: "Luke 18:13" }],
          explanation: "In Jesus' parable, the tax collector beats his chest and prays simply, \"God, be merciful to me, a sinner.\"",
        },
        {
          canonical: "Jonah's Prayer from the Fish",
          aliases: ["jonah's prayer", "prayer from the belly of the fish"],
          score: 60,
          tier: "veil",
          references: [{ book: "Jonah", chapterStart: 2, verseStart: 1, verseEnd: 9, display: "Jonah 2:1-9" }],
          explanation: "Jonah prays to the LORD from inside the great fish, thanking God for deliverance even before he is vomited onto dry land.",
        },
        {
          canonical: "Nehemiah's Prayer",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Nehemiah", chapterStart: 1, verseStart: 4, verseEnd: 11, display: "Nehemiah 1:4-11" }],
          explanation: "Nehemiah weeps, fasts, and prays for days after hearing of Jerusalem's ruined walls, before approaching the king.",
        },
        {
          canonical: "The Prayer of Jabez",
          aliases: ["jabez's prayer"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "1 Chronicles", chapterStart: 4, verseStart: 10, display: "1 Chronicles 4:10" }],
          explanation: "Jabez prays that God would bless him, enlarge his territory, and keep him from harm, and God grants his request.",
        },
        {
          canonical: "Habakkuk's Prayer",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Habakkuk", chapterStart: 3, verseStart: 1, verseEnd: 19, display: "Habakkuk 3:1-19" }],
          explanation: "The prophet Habakkuk closes his book with a prayer of trust in God despite coming disaster, sung to stringed instruments.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a judgment God sent on a specific individual in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific divine punishment or judgment the biblical text describes falling on one named individual (not a whole nation or group).",
      answers: [
        {
          canonical: "Lot's Wife Turned to Salt",
          aliases: ["lot's wife", "pillar of salt"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 26, display: "Genesis 19:26" }],
          explanation: "Lot's wife looks back at Sodom against the angels' warning and becomes a pillar of salt.",
        },
        {
          canonical: "Nebuchadnezzar's Madness",
          aliases: ["nebuchadnezzar eating grass", "nebuchadnezzar's insanity"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 4, verseStart: 28, verseEnd: 33, display: "Daniel 4:28-33" }],
          explanation: "Nebuchadnezzar is driven from human society and eats grass like an ox for his pride, until he acknowledges God.",
        },
        {
          canonical: "Uzzah Struck Dead",
          aliases: ["uzzah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Samuel", chapterStart: 6, verseStart: 6, verseEnd: 7, display: "2 Samuel 6:6-7" }],
          explanation: "Uzzah is struck dead for touching the Ark of the Covenant to steady it during transport.",
        },
        {
          canonical: "Miriam's Leprosy",
          aliases: ["miriam struck with leprosy"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 12, verseStart: 10, display: "Numbers 12:10" }],
          explanation: "Miriam is struck with leprosy for speaking against Moses, though she is later healed after Moses intercedes.",
        },
        {
          canonical: "Gehazi's Leprosy",
          aliases: ["gehazi struck with leprosy"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 20, verseEnd: 27, display: "2 Kings 5:20-27" }],
          explanation: "Elisha's servant Gehazi is struck with Naaman's leprosy for deceitfully taking payment for the healing.",
        },
        {
          canonical: "Herod Agrippa Eaten by Worms",
          aliases: ["herod eaten by worms", "herod struck down by an angel"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 21, verseEnd: 23, display: "Acts 12:21-23" }],
          explanation: "An angel strikes Herod Agrippa I down and he is eaten by worms after accepting worship as a god.",
        },
        {
          canonical: "Ananias and Sapphira",
          aliases: ["ananias", "sapphira"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 5, verseStart: 1, verseEnd: 10, display: "Acts 5:1-10" }],
          explanation: "Ananias and his wife Sapphira each fall dead after lying to the Holy Spirit about money from a land sale.",
        },
        {
          canonical: "Jeroboam's Withered Hand",
          aliases: ["jeroboam's hand"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Kings", chapterStart: 13, verseStart: 4, display: "1 Kings 13:4" }],
          explanation: "King Jeroboam's hand withers when he stretches it out to seize a man of God who confronted him at the altar.",
        },
        {
          canonical: "King Uzziah's Leprosy",
          aliases: ["uzziah struck with leprosy"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Chronicles", chapterStart: 26, verseStart: 16, verseEnd: 21, display: "2 Chronicles 26:16-21" }],
          explanation: "King Uzziah breaks out in leprosy on his forehead for presumptuously burning incense in the temple.",
        },
        {
          canonical: "Nadab and Abihu",
          aliases: ["nadab", "abihu", "strange fire"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Leviticus", chapterStart: 10, verseStart: 1, verseEnd: 2, display: "Leviticus 10:1-2" }],
          explanation: "Aaron's sons Nadab and Abihu are consumed by fire from the LORD for offering unauthorized fire before him.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a miracle performed by an apostle in the book of Acts.",
      instructions: "You get one guess.",
      whatCounts: "Any specific miracle the book of Acts attributes to an apostle (not Jesus).",
      answers: [
        {
          canonical: "Healing the Lame Man at the Temple Gate",
          aliases: ["lame man at the beautiful gate", "peter heals the lame man"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 3, verseStart: 1, verseEnd: 10, display: "Acts 3:1-10" }],
          explanation: "Peter heals a man lame from birth at the temple's Beautiful Gate, telling him to rise and walk.",
        },
        {
          canonical: "Raising Tabitha",
          aliases: ["tabitha raised", "dorcas raised"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 36, verseEnd: 42, display: "Acts 9:36-42" }],
          explanation: "Peter raises the disciple Tabitha (Dorcas) from the dead in Joppa.",
        },
        {
          canonical: "Peter's Escape from Prison",
          aliases: ["angel freeing peter", "peter freed by an angel"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 6, verseEnd: 11, display: "Acts 12:6-11" }],
          explanation: "An angel miraculously frees Peter from prison, loosing his chains and opening the iron gate.",
        },
        {
          canonical: "Paul Blinding Elymas",
          aliases: ["elymas struck blind", "paul strikes elymas blind"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 8, verseEnd: 11, display: "Acts 13:8-11" }],
          explanation: "Paul strikes the sorcerer Elymas blind for opposing his preaching before the proconsul Sergius Paulus.",
        },
        {
          canonical: "The Philippian Jailer's Earthquake",
          aliases: ["prison earthquake", "paul and silas earthquake"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 25, verseEnd: 26, display: "Acts 16:25-26" }],
          explanation: "An earthquake shakes the Philippian prison's foundations, freeing Paul and Silas from their chains.",
        },
        {
          canonical: "Raising Eutychus",
          aliases: ["eutychus raised"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 9, verseEnd: 12, display: "Acts 20:9-12" }],
          explanation: "Paul restores the young man Eutychus to life after he falls from a window during a late-night sermon.",
        },
        {
          canonical: "Healing by Peter's Shadow",
          aliases: ["peter's shadow"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 5, verseStart: 15, display: "Acts 5:15" }],
          explanation: "People lay the sick in the streets hoping Peter's passing shadow might fall on and heal them.",
        },
        {
          canonical: "Handkerchiefs from Paul",
          aliases: ["paul's handkerchiefs", "aprons from paul"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 19, verseStart: 11, verseEnd: 12, display: "Acts 19:11-12" }],
          explanation: "Handkerchiefs and aprons that had touched Paul heal the sick and drive out evil spirits when carried to them.",
        },
        {
          canonical: "Paul Surviving the Viper Bite",
          aliases: ["snakebite on malta", "viper bite paul"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 28, verseStart: 3, verseEnd: 6, display: "Acts 28:3-6" }],
          explanation: "A viper bites Paul's hand on Malta, but he suffers no harm, astonishing the islanders.",
        },
        {
          canonical: "Philip's Miraculous Transport",
          aliases: ["philip caught away", "philip taken away by the spirit"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 8, verseStart: 39, verseEnd: 40, display: "Acts 8:39-40" }],
          explanation: "After baptizing the Ethiopian eunuch, Philip is suddenly caught away by the Spirit and found at Azotus.",
        },
      ],
    },
  ],
};
