import type { SeedDay } from "./types";

export const DAY_39: SeedDay = {
  dayNumber: 39,
  date: "2026-10-26",
  scriptureBonus: {
    displayText: "Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.",
    book: "2 Corinthians",
    chapter: 5,
    verseStart: 17,
    referenceDisplay: "2 Corinthians 5:17",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "Paul describes the transformation that comes from being united with Christ.",
    acceptedBookAliases: ["2 cor", "2nd corinthians", "second corinthians"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a title or name given to the coming Messiah in Old Testament prophecy.",
      instructions: "You get one guess.",
      whatCounts: "Any title or name Old Testament prophecy explicitly applies to the promised Messiah.",
      answers: [
        {
          canonical: "Immanuel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Isaiah", chapterStart: 7, verseStart: 14, display: "Isaiah 7:14" }],
          explanation: "Isaiah prophesies a virgin will bear a son and call him Immanuel, 'God with us.'",
        },
        {
          canonical: "Wonderful Counselor",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Isaiah", chapterStart: 9, verseStart: 6, display: "Isaiah 9:6" }],
          explanation: "Isaiah names the coming child Wonderful Counselor among his royal titles.",
        },
        {
          canonical: "Prince of Peace",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Isaiah", chapterStart: 9, verseStart: 6, display: "Isaiah 9:6" }],
          explanation: "Isaiah's list of titles for the coming ruler ends with Prince of Peace.",
        },
        {
          canonical: "The Branch",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Jeremiah", chapterStart: 23, verseStart: 5, display: "Jeremiah 23:5" }],
          explanation: "Jeremiah foretells a righteous Branch raised up from David's line.",
        },
        {
          canonical: "Root of Jesse",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Isaiah", chapterStart: 11, verseStart: 10, display: "Isaiah 11:10" }],
          explanation: "Isaiah foretells a root of Jesse standing as a banner for the peoples.",
        },
        {
          canonical: "Shiloh",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 49, verseStart: 10, display: "Genesis 49:10" }],
          explanation: "Jacob's blessing on Judah foretells the scepter remaining until Shiloh comes.",
        },
        {
          canonical: "A Star Out of Jacob",
          aliases: ["star out of jacob"],
          score: 60,
          tier: "veil",
          references: [{ book: "Numbers", chapterStart: 24, verseStart: 17, display: "Numbers 24:17" }],
          explanation: "Balaam's oracle foresees a star coming out of Jacob and a scepter rising out of Israel.",
        },
        {
          canonical: "The Anointed One",
          aliases: ["messiah"],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 9, verseStart: 25, display: "Daniel 9:25" }],
          explanation: "Daniel's prophecy of seventy weeks foretells the coming of an Anointed One, a prince.",
        },
        {
          canonical: "The Servant of the LORD",
          aliases: ["the lord's servant"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Isaiah", chapterStart: 42, verseStart: 1, display: "Isaiah 42:1" }],
          explanation: "Isaiah introduces God's chosen servant, in whom his soul delights.",
        },
        {
          canonical: "Son of Man",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Daniel", chapterStart: 7, verseStart: 13, display: "Daniel 7:13" }],
          explanation: "Daniel's vision shows one like a son of man coming with the clouds of heaven, given everlasting dominion.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person in Jesus' genealogy in Luke 3 who does not also appear in Matthew 1.",
      instructions: "You get one guess.",
      whatCounts: "Any name from Luke's genealogy of Jesus (Luke 3:23-38) not also found in Matthew's genealogy (Matthew 1:1-16).",
      answers: [
        {
          canonical: "Adam",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 38, display: "Luke 3:38" }],
          explanation: "Luke traces Jesus' line all the way back to Adam, \"the son of God.\"",
        },
        {
          canonical: "Noah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 36, display: "Luke 3:36" }],
          explanation: "Noah appears in Luke's genealogy, which Matthew's does not include at all.",
        },
        {
          canonical: "Seth",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 38, display: "Luke 3:38" }],
          explanation: "Seth, Adam's son, appears near the very end of Luke's list.",
        },
        {
          canonical: "Enoch",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 37, display: "Luke 3:37" }],
          explanation: "Enoch, who \"walked with God\" and did not see death, appears in Luke's genealogy.",
        },
        {
          canonical: "Methuselah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 37, display: "Luke 3:37" }],
          explanation: "Methuselah, the longest-lived person in Genesis, appears in Luke's line.",
        },
        {
          canonical: "Shem",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 36, display: "Luke 3:36" }],
          explanation: "Shem, Noah's son, appears in Luke's genealogy, absent from Matthew's.",
        },
        {
          canonical: "Terah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 34, display: "Luke 3:34" }],
          explanation: "Terah, Abraham's father, appears in Luke but is skipped in Matthew's, which starts at Abraham.",
        },
        {
          canonical: "Nathan",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 31, display: "Luke 3:31" }],
          explanation: "Luke traces Jesus through David's son Nathan, not through Solomon as Matthew does.",
        },
        {
          canonical: "Heli",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 23, display: "Luke 3:23" }],
          explanation: "Luke names Heli as the father in Joseph's line, where Matthew names Jacob.",
        },
        {
          canonical: "Rhesa",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Luke", chapterStart: 3, verseStart: 27, display: "Luke 3:27" }],
          explanation: "Rhesa is listed as Zerubbabel's son in Luke's otherwise distinct post-exilic names.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a prison, dungeon, or place of confinement described in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any place the biblical text explicitly describes someone being confined, imprisoned, or held captive.",
      answers: [
        {
          canonical: "Joseph's Prison in Egypt",
          aliases: ["josephs prison", "the prison"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 39, verseStart: 20, display: "Genesis 39:20" }],
          explanation: "Potiphar has Joseph thrown into the prison where the king's prisoners are kept.",
        },
        {
          canonical: "Peter's Prison in Jerusalem",
          aliases: ["peters prison"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 4, display: "Acts 12:4" }],
          explanation: "Herod keeps Peter guarded by four squads of soldiers before an angel frees him.",
        },
        {
          canonical: "The Inner Prison at Philippi",
          aliases: ["philippi prison", "inner prison"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 24, display: "Acts 16:24" }],
          explanation: "Paul and Silas are put in stocks in the innermost cell after being beaten.",
        },
        {
          canonical: "Joseph's Pit",
          aliases: ["the pit", "josephs pit", "empty cistern"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 37, verseStart: 24, display: "Genesis 37:24" }],
          explanation: "Joseph's brothers throw him into an empty, waterless cistern before selling him.",
        },
        {
          canonical: "Samson's Prison in Gaza",
          aliases: ["samsons prison", "the mill"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 16, verseStart: 21, display: "Judges 16:21" }],
          explanation: "The blinded Samson is bound and set to grinding grain in a Philistine prison.",
        },
        {
          canonical: "The Cistern of Malchijah",
          aliases: ["jeremiahs cistern", "dungeon of malchijah"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jeremiah", chapterStart: 38, verseStart: 6, display: "Jeremiah 38:6" }],
          explanation: "Jeremiah is lowered into a muddy cistern belonging to Malchijah, the king's son.",
        },
        {
          canonical: "The Court of the Guard",
          aliases: ["jeremiahs courtyard"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Jeremiah", chapterStart: 32, verseStart: 2, display: "Jeremiah 32:2" }],
          explanation: "Zedekiah confines Jeremiah in the court of the guard for prophesying Jerusalem's fall.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a name or title given to Jerusalem in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any name or title the biblical text explicitly applies to Jerusalem.",
      answers: [
        {
          canonical: "Zion",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 7, display: "2 Samuel 5:7" }],
          explanation: "David captures the stronghold of Zion, which becomes another name for Jerusalem.",
        },
        {
          canonical: "City of David",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "2 Samuel", chapterStart: 5, verseStart: 7, display: "2 Samuel 5:7" }],
          explanation: "Jerusalem is renamed the City of David after he captures it from the Jebusites.",
        },
        {
          canonical: "The Holy City",
          aliases: ["holy city"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Nehemiah", chapterStart: 11, verseStart: 1, display: "Nehemiah 11:1" }],
          explanation: "Nehemiah calls Jerusalem 'the holy city' as leaders and people settle it after the exile.",
        },
        {
          canonical: "Salem",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 14, verseStart: 18, display: "Genesis 14:18" }],
          explanation: "Melchizedek, king of Salem, is traditionally identified with the site later called Jerusalem.",
        },
        {
          canonical: "Jebus",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 19, verseStart: 10, display: "Judges 19:10" }],
          explanation: "Jerusalem is called Jebus, the city of the Jebusites, before David's conquest.",
        },
        {
          canonical: "The City of the Great King",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Psalms", chapterStart: 48, verseStart: 2, display: "Psalm 48:2" }],
          explanation: "The psalmist calls Jerusalem, on Mount Zion, the city of the great King.",
        },
        {
          canonical: "Ariel",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Isaiah", chapterStart: 29, verseStart: 1, display: "Isaiah 29:1" }],
          explanation: "Isaiah addresses Jerusalem by the poetic name Ariel, 'the city where David encamped.'",
        },
        {
          canonical: "The Faithful City",
          aliases: ["city of righteousness"],
          score: 60,
          tier: "veil",
          references: [{ book: "Isaiah", chapterStart: 1, verseStart: 26, display: "Isaiah 1:26" }],
          explanation: "Isaiah foresees Jerusalem restored and called the City of Righteousness, the Faithful City.",
        },
        {
          canonical: "Jerusalem Above",
          aliases: ["the jerusalem above"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Galatians", chapterStart: 4, verseStart: 26, display: "Galatians 4:26" }],
          explanation: "Paul contrasts the earthly Jerusalem with 'the Jerusalem that is above,' which is free.",
        },
        {
          canonical: "The New Jerusalem",
          aliases: ["new jerusalem"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Revelation", chapterStart: 21, verseStart: 2, display: "Revelation 21:2" }],
          explanation: "John sees the New Jerusalem coming down out of heaven, prepared as a bride for her husband.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name an ancestor of King David named in the book of Ruth.",
      instructions: "You get one guess.",
      whatCounts: "Any person the book of Ruth's closing genealogy (Ruth 4:18-22) names as an ancestor of David.",
      answers: [
        {
          canonical: "Boaz",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 21, display: "Ruth 4:21" }],
          explanation: "Boaz marries Ruth and becomes the father of Obed.",
        },
        {
          canonical: "Jesse",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 22, display: "Ruth 4:22" }],
          explanation: "Jesse, Obed's son, is named as the father of David.",
        },
        {
          canonical: "Obed",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 21, display: "Ruth 4:21" }],
          explanation: "Obed, son of Boaz and Ruth, is David's grandfather.",
        },
        {
          canonical: "Salmon",
          aliases: ["salma"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 20, display: "Ruth 4:20-21" }],
          explanation: "Salmon is named as Boaz's father in the closing genealogy.",
        },
        {
          canonical: "Nahshon",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 20, display: "Ruth 4:20" }],
          explanation: "Nahshon, a leader of Judah in the wilderness, is named as Salmon's father.",
        },
        {
          canonical: "Perez",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 18, display: "Ruth 4:18" }],
          explanation: "Perez, son of Tamar and Judah, opens the closing genealogy of Ruth.",
        },
        {
          canonical: "Amminadab",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 19, display: "Ruth 4:19-20" }],
          explanation: "Amminadab is named as Nahshon's father in the genealogy leading to David.",
        },
        {
          canonical: "Hezron",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 18, display: "Ruth 4:18-19" }],
          explanation: "Hezron, Perez's son, continues the line toward David.",
        },
        {
          canonical: "Ram",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Ruth", chapterStart: 4, verseStart: 19, display: "Ruth 4:19" }],
          explanation: "Ram, Hezron's son, is one of the least-remembered links in David's ancestry.",
        },
      ],
    },
  ],
};
