import type { SeedDay } from "./types";

export const DAY_33: SeedDay = {
  dayNumber: 33,
  date: "2026-10-20",
  scriptureBonus: {
    displayText: "Yahweh is my strength and shield. My heart has trusted in him, and I am helped.",
    book: "Psalms",
    chapter: 28,
    verseStart: 7,
    referenceDisplay: "Psalm 28:7",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "David expresses confidence in God's protection and help after a prayer for deliverance.",
    acceptedBookAliases: ["psalm", "psalms"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a specific net, snare, or trap mentioned in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific net, snare, or trap the biblical text explicitly describes.",
      answers: [
        {
          canonical: "The Fowler's Snare",
          aliases: ["snare of the fowler"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Psalms", chapterStart: 91, verseStart: 3, display: "Psalm 91:3" }],
          explanation: "The psalmist says God will deliver him from the snare of the fowler.",
        },
        {
          canonical: "The Disciples' Fishing Nets",
          aliases: ["fishing net"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 4, verseStart: 18, display: "Matthew 4:18" }],
          explanation: "Jesus finds Peter and Andrew casting a net into the sea, for they were fishermen.",
        },
        {
          canonical: "The Dragnet in Jesus' Parable",
          aliases: ["dragnet parable"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 13, verseStart: 47, display: "Matthew 13:47" }],
          explanation: "Jesus compares the Kingdom of Heaven to a dragnet cast into the sea, gathering fish of every kind.",
        },
        {
          canonical: "Haman's Gallows",
          aliases: ["gallows haman built for mordecai"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Esther", chapterStart: 5, verseStart: 14, display: "Esther 5:14" }],
          explanation: "Haman builds gallows intending to hang Mordecai, but is hanged on them himself.",
        },
        {
          canonical: "Delilah's Bowstring Snare for Samson",
          aliases: ["delilah's fresh bowstrings"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Judges", chapterStart: 16, verseStart: 7, display: "Judges 16:7" }],
          explanation: "Delilah binds Samson with fresh bowstrings at the Philistines' request, testing his strength.",
        },
        {
          canonical: "Absalom Caught in the Oak",
          aliases: ["absalom's hair caught in a tree"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 18, verseStart: 9, display: "2 Samuel 18:9" }],
          explanation: "Absalom's head catches fast in the branches of a great oak as he flees on his mule.",
        },
        {
          canonical: "The Pit Dug as a Trap",
          aliases: ["whoever digs a pit"],
          score: 60,
          tier: "veil",
          references: [{ book: "Proverbs", chapterStart: 26, verseStart: 27, display: "Proverbs 26:27" }],
          explanation: "Proverbs warns that whoever digs a pit to trap others will fall into it himself.",
        },
        {
          canonical: "The Net Spread for the Psalmist",
          aliases: ["net hidden for me"],
          score: 60,
          tier: "veil",
          references: [{ book: "Psalms", chapterStart: 35, verseStart: 7, display: "Psalm 35:7" }],
          explanation: "David complains that his enemies hid a net for him in a pit without cause.",
        },
        {
          canonical: "The Chaldeans' Fishing Net",
          aliases: ["habakkuk's fishing net image"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Habakkuk", chapterStart: 1, verseStart: 15, display: "Habakkuk 1:15" }],
          explanation: "Habakkuk pictures the Chaldeans hauling up nations with a hook, net, and dragnet.",
        },
        {
          canonical: "Job's Snare of the Wicked",
          aliases: ["net hidden in the ground for him"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Job", chapterStart: 18, verseStart: 8, display: "Job 18:8" }],
          explanation: "Bildad describes the wicked as walking into a net, his own feet leading him into its mesh.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a supernatural sign in the sky or heavens in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific supernatural sign, wonder, or event in the sky or heavens the biblical text describes.",
      answers: [
        {
          canonical: "The Star of Bethlehem",
          aliases: ["star of bethlehem", "the star the wise men followed"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 2, verseStart: 9, verseEnd: 10, display: "Matthew 2:9-10" }],
          explanation: "A star guides the wise men from the east to the place where the child Jesus is.",
        },
        {
          canonical: "Darkness at the Crucifixion",
          aliases: ["darkness over the land"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 27, verseStart: 45, display: "Matthew 27:45" }],
          explanation: "Darkness covers the land from the sixth to the ninth hour while Jesus hangs on the cross.",
        },
        {
          canonical: "The Pillar of Cloud and Fire",
          aliases: ["pillar of cloud", "pillar of fire"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 13, verseStart: 21, verseEnd: 22, display: "Exodus 13:21-22" }],
          explanation: "The LORD leads Israel through the wilderness in a pillar of cloud by day and a pillar of fire by night.",
        },
        {
          canonical: "The Sun Standing Still for Joshua",
          aliases: ["sun stood still", "joshua's long day"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 10, verseStart: 12, verseEnd: 13, display: "Joshua 10:12-13" }],
          explanation: "At Joshua's command, the sun stands still over Gibeon so Israel can finish routing its enemies.",
        },
        {
          canonical: "Tongues of Fire at Pentecost",
          aliases: ["pentecost fire", "tongues of fire"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 2, verseStart: 3, display: "Acts 2:3" }],
          explanation: "Divided tongues like fire rest on each of the disciples gathered at Pentecost.",
        },
        {
          canonical: "Elijah Taken Up in a Whirlwind",
          aliases: ["chariot of fire", "elijah taken to heaven"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 2, verseStart: 11, display: "2 Kings 2:11" }],
          explanation: "A chariot of fire and horses of fire appear, and Elijah goes up to heaven in a whirlwind.",
        },
        {
          canonical: "The Sundial Going Backward for Hezekiah",
          aliases: ["hezekiah's sign", "shadow moving backward"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 20, verseStart: 9, verseEnd: 11, display: "2 Kings 20:9-11" }],
          explanation: "As a sign of healing to Hezekiah, the shadow on the stairway of Ahaz moves back ten steps.",
        },
        {
          canonical: "Fire from Heaven Consuming Elijah's Two Captains",
          aliases: ["fire consumes the captains of fifty"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 1, verseStart: 10, verseEnd: 12, display: "2 Kings 1:10-12" }],
          explanation: "Fire comes down from heaven and consumes two companies of fifty soldiers sent to arrest Elijah.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a person miraculously rescued from prison or danger in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text describes being supernaturally delivered from imprisonment or mortal danger.",
      answers: [
        {
          canonical: "Peter",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 6, verseEnd: 11, display: "Acts 12:6-11" }],
          explanation: "An angel frees Peter from prison, loosing his chains and leading him past the guards unnoticed.",
        },
        {
          canonical: "Daniel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 6, verseStart: 16, verseEnd: 23, display: "Daniel 6:16-23" }],
          explanation: "Daniel is thrown into the lions' den for praying to God but is found unharmed the next morning.",
        },
        {
          canonical: "Shadrach, Meshach, and Abednego",
          aliases: ["shadrach meshach and abednego", "the fiery furnace"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 3, verseStart: 19, verseEnd: 27, display: "Daniel 3:19-27" }],
          explanation: "Shadrach, Meshach, and Abednego walk unharmed out of a blazing furnace after refusing to worship the golden image.",
        },
        {
          canonical: "Paul and Silas",
          aliases: ["paul and silas prison"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 25, verseEnd: 26, display: "Acts 16:25-26" }],
          explanation: "An earthquake shakes the prison at Philippi, freeing Paul and Silas from their chains.",
        },
        {
          canonical: "Lot",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 15, verseEnd: 16, display: "Genesis 19:15-16" }],
          explanation: "Angels seize Lot's hand and lead him and his family out of Sodom before its destruction.",
        },
        {
          canonical: "Jeremiah",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Jeremiah", chapterStart: 38, verseStart: 6, verseEnd: 13, display: "Jeremiah 38:6-13" }],
          explanation: "Jeremiah is lowered into a muddy cistern to die but is pulled out with ropes by Ebed-Melech before he starves.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 14, display: "Genesis 41:14" }],
          explanation: "Joseph is released from an Egyptian prison to interpret Pharaoh's dreams, rising to power.",
        },
        {
          canonical: "David Escaping Through a Window",
          aliases: ["david let down through a window", "michal helps david escape"],
          score: 60,
          tier: "veil",
          references: [{ book: "1 Samuel", chapterStart: 19, verseStart: 12, display: "1 Samuel 19:12" }],
          explanation: "David's wife Michal lets him down through a window at night, helping him escape Saul's men.",
        },
        {
          canonical: "Paul Lowered from the Wall in a Basket",
          aliases: ["paul in a basket", "escape from damascus"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 25, display: "Acts 9:25" }],
          explanation: "Paul's disciples lower him in a basket through an opening in the Damascus city wall by night.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a healing Jesus performed by touch.",
      instructions: "You get one guess.",
      whatCounts: "Any healing the Gospels explicitly describe Jesus performing through touch (his touching someone, or someone touching him).",
      answers: [
        {
          canonical: "Cleansing a Leper",
          aliases: ["touching the leper"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 8, verseStart: 3, display: "Matthew 8:3" }],
          explanation: "Jesus reaches out and touches a leper, saying \"Be clean,\" and the leprosy immediately leaves him.",
        },
        {
          canonical: "The Woman with the Flow of Blood",
          aliases: ["woman touching his cloak", "issue of blood"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Mark", chapterStart: 5, verseStart: 27, verseEnd: 29, display: "Mark 5:27-29" }],
          explanation: "A woman is healed of twelve years of bleeding the moment she touches the fringe of Jesus' cloak.",
        },
        {
          canonical: "Peter's Mother-in-Law",
          aliases: ["peter's mother in law"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Mark", chapterStart: 1, verseStart: 31, display: "Mark 1:31" }],
          explanation: "Jesus takes Peter's mother-in-law by the hand and lifts her up, and her fever leaves her.",
        },
        {
          canonical: "Two Blind Men",
          aliases: ["blind men touched their eyes"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 9, verseStart: 29, display: "Matthew 9:29" }],
          explanation: "Jesus touches the eyes of two blind men, and their sight is restored.",
        },
        {
          canonical: "Malchus's Ear",
          aliases: ["healing the severed ear"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Luke", chapterStart: 22, verseStart: 51, display: "Luke 22:51" }],
          explanation: "Jesus touches the ear of the high priest's servant, severed by Peter, and heals it.",
        },
        {
          canonical: "A Deaf Man with a Speech Impediment",
          aliases: ["deaf mute touched"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 7, verseStart: 33, display: "Mark 7:33" }],
          explanation: "Jesus puts his fingers in the man's ears and touches his tongue, and he can hear and speak plainly.",
        },
        {
          canonical: "A Blind Man at Bethsaida",
          aliases: ["blind man at bethsaida"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 8, verseStart: 23, display: "Mark 8:23" }],
          explanation: "Jesus leads a blind man out of the village, spits on his eyes, and lays hands on him, healing him in two stages.",
        },
        {
          canonical: "The Multitudes at Gennesaret",
          aliases: ["touched the fringe of his garment", "gennesaret healings"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 36, display: "Matthew 14:36" }],
          explanation: "The sick throughout Gennesaret beg to touch just the fringe of Jesus' garment, and all who touch it are healed.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name an instance where God miraculously provided food in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific instance the biblical text describes God or his prophets miraculously providing food.",
      answers: [
        {
          canonical: "Manna in the Wilderness",
          aliases: ["manna", "bread from heaven"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 16, verseStart: 14, verseEnd: 15, display: "Exodus 16:14-15" }],
          explanation: "God provides bread from heaven called manna for Israel to gather each morning in the wilderness.",
        },
        {
          canonical: "Feeding the Five Thousand",
          aliases: ["feeding the 5000", "loaves and fishes"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 13, verseEnd: 21, display: "Matthew 14:13-21" }],
          explanation: "Jesus multiplies five loaves and two fish to feed five thousand people.",
        },
        {
          canonical: "Quail in the Wilderness",
          aliases: ["quail"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 16, verseStart: 13, display: "Exodus 16:13" }],
          explanation: "Quail cover the Israelite camp in the evening, providing meat alongside the manna.",
        },
        {
          canonical: "Elijah Fed by Ravens",
          aliases: ["ravens feeding elijah"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 6, display: "1 Kings 17:6" }],
          explanation: "Ravens bring Elijah bread and meat morning and evening while he hides by the brook Cherith.",
        },
        {
          canonical: "The Widow of Zarephath's Flour and Oil",
          aliases: ["zarephath's flour and oil", "jar of flour never emptied"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 14, verseEnd: 16, display: "1 Kings 17:14-16" }],
          explanation: "At Elijah's word, the widow of Zarephath's jar of flour and jug of oil never run out during the famine.",
        },
        {
          canonical: "Elisha Multiplying the Widow's Oil",
          aliases: ["widow's oil multiplied", "elisha's oil miracle"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 4, verseStart: 1, verseEnd: 7, display: "2 Kings 4:1-7" }],
          explanation: "Elisha instructs a debt-ridden widow to pour her small jar of oil into borrowed vessels, and it keeps flowing until they're all full.",
        },
        {
          canonical: "Elisha Feeding a Hundred Men",
          aliases: ["feeding a hundred men", "twenty loaves of barley bread"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 4, verseStart: 42, verseEnd: 44, display: "2 Kings 4:42-44" }],
          explanation: "Elisha feeds a hundred men with twenty loaves of barley bread, with food left over.",
        },
      ],
    },
  ],
};
