import type { SeedDay } from "./types";

export const DAY_35: SeedDay = {
  dayNumber: 35,
  date: "2026-10-22",
  scriptureBonus: {
    displayText: "Oh taste and see that Yahweh is good. Blessed is the man who takes refuge in him.",
    book: "Psalms",
    chapter: 34,
    verseStart: 8,
    referenceDisplay: "Psalm 34:8",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "David invites others to personally experience the LORD's goodness after his own deliverance.",
    acceptedBookAliases: ["ps", "psalm"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name an instance where God communicated through an unusual or unexpected means.",
      instructions: "You get one guess.",
      whatCounts: "Any specific instance the biblical text describes God or a divine message coming through an unusual, non-human, or unexpected means.",
      answers: [
        {
          canonical: "Balaam's Donkey Speaking",
          aliases: ["balaam's donkey", "talking donkey"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Numbers", chapterStart: 22, verseStart: 28, display: "Numbers 22:28" }],
          explanation: "The LORD opens the mouth of Balaam's donkey, and it speaks to rebuke him for striking it.",
        },
        {
          canonical: "The Burning Bush",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 3, verseStart: 4, display: "Exodus 3:4" }],
          explanation: "God calls to Moses from within a bush that burns without being consumed.",
        },
        {
          canonical: "The Handwriting on the Wall",
          aliases: ["writing on the wall", "mene mene tekel upharsin"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 5, verseStart: 5, display: "Daniel 5:5" }],
          explanation: "A disembodied hand writes words of judgment on the wall of Belshazzar's banquet hall.",
        },
        {
          canonical: "The Voice from Heaven at Jesus' Baptism",
          aliases: ["voice at jesus baptism", "this is my beloved son"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Matthew", chapterStart: 3, verseStart: 17, display: "Matthew 3:17" }],
          explanation: "A voice from heaven declares Jesus his beloved Son at his baptism.",
        },
        {
          canonical: "Casting Lots to Choose Matthias",
          aliases: ["casting lots for matthias", "lots chose matthias"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 1, verseStart: 26, display: "Acts 1:26" }],
          explanation: "The apostles cast lots to choose Matthias as Judas's replacement, trusting God to guide the outcome.",
        },
        {
          canonical: "The Urim and Thummim",
          aliases: ["urim and thummim"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 28, verseStart: 30, display: "Exodus 28:30" }],
          explanation: "The high priest carries the Urim and Thummim in his breastpiece to discern God's will in judgment.",
        },
        {
          canonical: "The Still Small Voice to Elijah",
          aliases: ["still small voice", "gentle whisper"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Kings", chapterStart: 19, verseStart: 12, display: "1 Kings 19:12" }],
          explanation: "After wind, earthquake, and fire, God speaks to Elijah at Horeb in a still, small voice.",
        },
        {
          canonical: "Jesus' Statement that Stones Would Cry Out",
          aliases: ["stones would cry out"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 19, verseStart: 40, display: "Luke 19:40" }],
          explanation: "Jesus tells the Pharisees that if his disciples were silent, the very stones would cry out.",
        },
        {
          canonical: "The Rooster Crowing to Peter",
          aliases: ["rooster crow", "cock crowing"],
          score: 60,
          tier: "veil",
          references: [{ book: "Matthew", chapterStart: 26, verseStart: 74, verseEnd: 75, display: "Matthew 26:74-75" }],
          explanation: "A rooster's crow fulfills Jesus' prediction the moment Peter denies him the third time.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name an instance of miraculous multiplication in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific instance the biblical text describes something being supernaturally multiplied or increased beyond natural means.",
      answers: [
        {
          canonical: "Feeding the Five Thousand",
          aliases: ["feeding the 5000"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 17, verseEnd: 21, display: "Matthew 14:17-21" }],
          explanation: "Five loaves and two fish multiply in Jesus' hands to feed five thousand people with baskets left over.",
        },
        {
          canonical: "Feeding the Four Thousand",
          aliases: ["feeding the 4000"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 15, verseStart: 34, verseEnd: 38, display: "Matthew 15:34-38" }],
          explanation: "Seven loaves and a few small fish multiply to feed four thousand people.",
        },
        {
          canonical: "The Miraculous Catch of Fish",
          aliases: ["net full of fish", "miraculous catch"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Luke", chapterStart: 5, verseStart: 6, display: "Luke 5:6" }],
          explanation: "Simon Peter's nets catch so many fish at Jesus' word that they begin to break.",
        },
        {
          canonical: "The Widow of Zarephath's Flour and Oil",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Kings", chapterStart: 17, verseStart: 16, display: "1 Kings 17:16" }],
          explanation: "The widow of Zarephath's jar of flour and jug of oil never run out for the duration of the famine.",
        },
        {
          canonical: "Elisha Multiplying the Widow's Oil",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 4, verseStart: 6, display: "2 Kings 4:6" }],
          explanation: "A widow's small jar of oil keeps flowing into borrowed vessels until every one of them is full.",
        },
        {
          canonical: "Israel's Population Growth in Egypt",
          aliases: ["israel multiplying in egypt"],
          score: 60,
          tier: "veil",
          references: [{ book: "Exodus", chapterStart: 1, verseStart: 7, display: "Exodus 1:7" }],
          explanation: "The Israelites multiply so greatly in Egypt that the land is filled with them, alarming Pharaoh.",
        },
        {
          canonical: "Job's Restored Possessions",
          aliases: ["job's fortune doubled"],
          score: 60,
          tier: "veil",
          references: [{ book: "Job", chapterStart: 42, verseStart: 10, display: "Job 42:10" }],
          explanation: "The LORD gives Job twice as much as he had before after his time of testing ends.",
        },
        {
          canonical: "Isaac's Hundredfold Harvest",
          aliases: ["isaac's crop"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 26, verseStart: 12, display: "Genesis 26:12" }],
          explanation: "Isaac sows in the land during a famine and reaps a hundredfold in the same year, as the LORD blesses him.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name an instance of someone's physical appearance being miraculously changed in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text describes undergoing a supernatural change in physical appearance.",
      answers: [
        {
          canonical: "Jesus' Transfiguration",
          aliases: ["transfiguration"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 17, verseStart: 2, display: "Matthew 17:2" }],
          explanation: "Jesus' face shines like the sun and his clothes become as white as light before Peter, James, and John.",
        },
        {
          canonical: "Moses' Shining Face",
          aliases: ["moses' radiant face", "moses' veil"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Exodus", chapterStart: 34, verseStart: 29, verseEnd: 30, display: "Exodus 34:29-30" }],
          explanation: "Moses' face shines so brightly after speaking with God on Sinai that he must wear a veil before the people.",
        },
        {
          canonical: "Naaman's Skin Restored",
          aliases: ["naaman healed of leprosy"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 14, display: "2 Kings 5:14" }],
          explanation: "Naaman's skin becomes like that of a young boy after he washes seven times in the Jordan at Elisha's word.",
        },
        {
          canonical: "Miriam's Skin Turning Leprous",
          aliases: ["miriam's leprosy"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Numbers", chapterStart: 12, verseStart: 10, display: "Numbers 12:10" }],
          explanation: "Miriam's skin becomes leprous, white as snow, when she speaks against Moses.",
        },
        {
          canonical: "Gehazi's Skin Turning Leprous",
          aliases: ["gehazi's leprosy"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Kings", chapterStart: 5, verseStart: 27, display: "2 Kings 5:27" }],
          explanation: "Gehazi's skin becomes leprous, white as snow, as punishment for his deceit toward Naaman.",
        },
        {
          canonical: "Nebuchadnezzar's Transformation",
          aliases: ["nebuchadnezzar's beast-like state", "hair like eagle's feathers"],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 4, verseStart: 33, display: "Daniel 4:33" }],
          explanation: "Nebuchadnezzar's hair grows like eagles' feathers and his nails like birds' claws as he lives like a beast for a time.",
        },
        {
          canonical: "Stephen's Face Like an Angel",
          aliases: ["stephen's face", "face of an angel"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 6, verseStart: 15, display: "Acts 6:15" }],
          explanation: "Everyone in the council sees that Stephen's face looks like the face of an angel as he stands trial.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name someone who wrestled with or confronted a supernatural being in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text describes physically wrestling with, or directly confronting face-to-face, an angel or other supernatural being.",
      answers: [
        {
          canonical: "Jacob",
          aliases: ["jacob wrestling with the angel", "jacob at peniel"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 32, verseStart: 24, verseEnd: 30, display: "Genesis 32:24-30" }],
          explanation: "Jacob wrestles all night with a man at Peniel and is renamed Israel, saying he has seen God face to face.",
        },
        {
          canonical: "Joshua",
          aliases: ["joshua and the commander of the lord's army"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Joshua", chapterStart: 5, verseStart: 13, verseEnd: 15, display: "Joshua 5:13-15" }],
          explanation: "Joshua encounters the commander of the LORD's army near Jericho and falls facedown in worship.",
        },
        {
          canonical: "Balaam",
          aliases: ["balaam and the angel with a sword"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Numbers", chapterStart: 22, verseStart: 31, display: "Numbers 22:31" }],
          explanation: "The angel of the LORD stands in Balaam's way with a drawn sword, visible only after God opens his eyes.",
        },
        {
          canonical: "Daniel",
          aliases: ["daniel and the angel gabriel"],
          score: 60,
          tier: "veil",
          references: [{ book: "Daniel", chapterStart: 10, verseStart: 10, verseEnd: 12, display: "Daniel 10:10-12" }],
          explanation: "A glorious being touches and speaks with Daniel, who trembles and falls into a deep sleep from the encounter.",
        },
        {
          canonical: "Gideon",
          aliases: ["gideon and the angel of the lord"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 12, display: "Judges 6:12" }],
          explanation: "The angel of the LORD appears to Gideon at the winepress and commissions him to save Israel.",
        },
        {
          canonical: "Michael the Archangel",
          aliases: ["michael contending with the devil"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Jude", chapterStart: 1, verseStart: 9, display: "Jude 1:9" }],
          explanation: "Michael the archangel contends with the devil over the body of Moses, disputing without pronouncing a reviling judgment.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name an instance where someone requested and received a miraculous sign in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person the biblical text describes explicitly asking God for a confirming sign, who is then given one.",
      answers: [
        {
          canonical: "Gideon's Fleece",
          aliases: ["gideon's fleece test"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 36, verseEnd: 40, display: "Judges 6:36-40" }],
          explanation: "Gideon asks for and receives two confirming signs with a wool fleece, dew, and dry ground.",
        },
        {
          canonical: "Hezekiah's Sign of the Shadow",
          aliases: ["hezekiah's sign"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "2 Kings", chapterStart: 20, verseStart: 8, verseEnd: 11, display: "2 Kings 20:8-11" }],
          explanation: "Hezekiah asks for a sign of his healing, and the shadow on the stairway moves back ten steps.",
        },
        {
          canonical: "Thomas Asking to Touch Jesus' Wounds",
          aliases: ["doubting thomas"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 20, verseStart: 25, verseEnd: 27, display: "John 20:25-27" }],
          explanation: "Thomas says he will not believe without touching Jesus' wounds, and the risen Jesus offers them to him.",
        },
        {
          canonical: "Moses Asking How Israel Will Believe Him",
          aliases: ["moses' staff turning into a snake", "moses' hand turning leprous"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 4, verseStart: 1, verseEnd: 7, display: "Exodus 4:1-7" }],
          explanation: "God gives Moses signs — his staff becoming a snake and his hand turning leprous then restored — to convince Israel.",
        },
        {
          canonical: "Ahaz Given the Immanuel Sign",
          aliases: ["immanuel sign", "sign of the virgin birth to ahaz"],
          score: 60,
          tier: "veil",
          references: [{ book: "Isaiah", chapterStart: 7, verseStart: 11, verseEnd: 14, display: "Isaiah 7:11-14" }],
          explanation: "Though Ahaz refuses to ask, the LORD gives him a sign anyway: a virgin shall conceive and bear a son called Immanuel.",
        },
        {
          canonical: "Zechariah Asking for a Sign",
          aliases: ["zechariah struck mute"],
          score: 60,
          tier: "veil",
          references: [{ book: "Luke", chapterStart: 1, verseStart: 18, verseEnd: 20, display: "Luke 1:18-20" }],
          explanation: "Zechariah asks Gabriel for proof he will have a son, and is struck mute as both a sign and a rebuke until the birth.",
        },
        {
          canonical: "The Sign of Jonah",
          aliases: ["sign of jonah"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Matthew", chapterStart: 12, verseStart: 39, verseEnd: 40, display: "Matthew 12:39-40" }],
          explanation: "Jesus tells a sign-seeking generation that the only sign given them will be the sign of the prophet Jonah.",
        },
      ],
    },
  ],
};
