import type { SeedDay } from "./types";

export const DAY_32: SeedDay = {
  dayNumber: 32,
  date: "2026-10-19",
  scriptureBonus: {
    displayText: "Trust in Yahweh, and do good. Dwell in the land, and enjoy safe pasture.",
    book: "Psalms",
    chapter: 37,
    verseStart: 3,
    referenceDisplay: "Psalm 37:3",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "A psalm of David encouraging trust in God rather than envy of the wicked.",
    acceptedBookAliases: ["psalm", "psalms"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a biblical name whose meaning the text itself explains.",
      instructions: "You get one guess.",
      whatCounts: "Any name the biblical text explicitly explains or interprets the meaning of.",
      answers: [
        {
          canonical: "Jesus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 21, display: "Matthew 1:21" }],
          explanation: "The angel tells Joseph to name him Jesus, 'for he will save his people from their sins.'",
        },
        {
          canonical: "Immanuel",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Matthew", chapterStart: 1, verseStart: 23, display: "Matthew 1:23" }],
          explanation: "Matthew explains that Immanuel, being interpreted, means 'God with us.'",
        },
        {
          canonical: "Peter (Cephas)",
          aliases: ["peter", "cephas"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "John", chapterStart: 1, verseStart: 42, display: "John 1:42" }],
          explanation: "Jesus renames Simon 'Cephas,' which John explains is translated 'Peter,' meaning rock.",
        },
        {
          canonical: "Barnabas",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 4, verseStart: 36, display: "Acts 4:36" }],
          explanation: "Luke explains that Barnabas, given by the apostles, is translated 'son of encouragement.'",
        },
        {
          canonical: "Jacob",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 27, verseStart: 36, display: "Genesis 27:36" }],
          explanation: "Esau protests that Jacob is rightly named 'supplanter,' for he has taken his birthright and blessing.",
        },
        {
          canonical: "Ichabod",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Samuel", chapterStart: 4, verseStart: 21, display: "1 Samuel 4:21" }],
          explanation: "Phinehas's wife names her son Ichabod, explaining, 'the glory has departed from Israel.'",
        },
        {
          canonical: "Babel",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 11, verseStart: 9, display: "Genesis 11:9" }],
          explanation: "The text explains the city was called Babel because there the LORD confused the language of the whole earth.",
        },
        {
          canonical: "Boanerges",
          aliases: ["sons of thunder"],
          score: 60,
          tier: "veil",
          references: [{ book: "Mark", chapterStart: 3, verseStart: 17, display: "Mark 3:17" }],
          explanation: "Jesus names James and John 'Boanerges,' which Mark explains means 'sons of thunder.'",
        },
        {
          canonical: "Akeldama",
          aliases: ["field of blood"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 1, verseStart: 19, display: "Acts 1:19" }],
          explanation: "Luke explains that the field bought with Judas's money is called Akeldama, 'the field of blood.'",
        },
        {
          canonical: "Jabez",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "1 Chronicles", chapterStart: 4, verseStart: 9, display: "1 Chronicles 4:9" }],
          explanation: "Jabez's mother names him so, explaining, 'because I bore him with sorrow.'",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a person the Bible explicitly describes weeping or crying.",
      instructions: "You get one guess.",
      whatCounts: "Any named person, or the group they're part of, the biblical text explicitly describes weeping or crying.",
      answers: [
        {
          canonical: "Jesus",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "John", chapterStart: 11, verseStart: 35, display: "John 11:35" }],
          explanation: "Jesus weeps at the tomb of his friend Lazarus.",
        },
        {
          canonical: "Peter",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Luke", chapterStart: 22, verseStart: 62, display: "Luke 22:62" }],
          explanation: "Peter goes out and weeps bitterly after denying Jesus three times.",
        },
        {
          canonical: "Hannah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "1 Samuel", chapterStart: 1, verseStart: 10, display: "1 Samuel 1:10" }],
          explanation: "Hannah, deeply distressed over her childlessness, prays and weeps bitterly at Shiloh.",
        },
        {
          canonical: "Esau",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 27, verseStart: 38, display: "Genesis 27:38" }],
          explanation: "Esau lifts up his voice and weeps after learning Jacob stole his blessing.",
        },
        {
          canonical: "David",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "2 Samuel", chapterStart: 18, verseStart: 33, display: "2 Samuel 18:33" }],
          explanation: "David weeps and cries out, 'O Absalom, my son, my son,' on learning of his death.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 45, verseStart: 2, display: "Genesis 45:2" }],
          explanation: "Joseph weeps aloud when he finally reveals himself to his brothers in Egypt.",
        },
        {
          canonical: "Hezekiah",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 20, verseStart: 3, display: "2 Kings 20:3" }],
          explanation: "King Hezekiah turns his face to the wall and weeps bitterly upon hearing he will die.",
        },
        {
          canonical: "Paul",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 19, display: "Acts 20:19" }],
          explanation: "Paul recalls serving the Lord among the Ephesians with humility and many tears.",
        },
        {
          canonical: "Job's Friends",
          aliases: ["eliphaz bildad and zophar weeping"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Job", chapterStart: 2, verseStart: 12, display: "Job 2:12" }],
          explanation: "Job's three friends lift up their voices and weep when they see his suffering.",
        },
        {
          canonical: "Jeremiah",
          aliases: ["the weeping prophet"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Jeremiah", chapterStart: 9, verseStart: 1, display: "Jeremiah 9:1" }],
          explanation: "Jeremiah wishes his head were a spring of water and his eyes a fountain of tears for his people.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name an instance of God testing someone's faith in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific episode the biblical text describes as, or clearly presents as, God testing an individual's faith or obedience.",
      answers: [
        {
          canonical: "The Sacrifice of Isaac",
          aliases: ["abraham and isaac", "binding of isaac", "akedah"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 22, verseStart: 1, verseEnd: 2, display: "Genesis 22:1-2" }],
          explanation: "God tests Abraham by commanding him to sacrifice his son Isaac, staying his hand at the last moment.",
        },
        {
          canonical: "Job's Trials",
          aliases: ["job's suffering", "testing of job"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Job", chapterStart: 1, verseStart: 12, display: "Job 1:12" }],
          explanation: "God permits Satan to test Job by stripping away his possessions, children, and health.",
        },
        {
          canonical: "Gideon's Fleece",
          aliases: ["fleece test", "gideon's wool"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Judges", chapterStart: 6, verseStart: 36, verseEnd: 40, display: "Judges 6:36-40" }],
          explanation: "Gideon asks God to confirm his call through the sign of dew on and off a wool fleece.",
        },
        {
          canonical: "The Israelites and Manna",
          aliases: ["manna test", "gathering manna"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Exodus", chapterStart: 16, verseStart: 4, display: "Exodus 16:4" }],
          explanation: "God tests Israel by instructing them to gather only enough manna for each day, except before the Sabbath.",
        },
        {
          canonical: "Peter Walking on Water",
          aliases: ["peter's faith on the water", "peter sinking"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Matthew", chapterStart: 14, verseStart: 28, verseEnd: 31, display: "Matthew 14:28-31" }],
          explanation: "Peter steps out onto the water at Jesus' word but begins to sink when he doubts, testing his faith.",
        },
        {
          canonical: "The Israelites at the Red Sea",
          aliases: ["red sea faith test"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Exodus", chapterStart: 14, verseStart: 13, verseEnd: 14, display: "Exodus 14:13-14" }],
          explanation: "Trapped between Pharaoh's army and the sea, Israel is told to stand still and see the LORD's salvation.",
        },
        {
          canonical: "Abraham's Journey to an Unknown Land",
          aliases: ["abraham's call", "leave your country"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 12, verseStart: 1, display: "Genesis 12:1" }],
          explanation: "God tests Abraham's obedience by calling him to leave his country and family for a land not yet shown to him.",
        },
        {
          canonical: "The Wilderness Wandering",
          aliases: ["forty years in the wilderness", "testing in the wilderness"],
          score: 60,
          tier: "veil",
          references: [{ book: "Deuteronomy", chapterStart: 8, verseStart: 2, display: "Deuteronomy 8:2" }],
          explanation: "Moses tells Israel that God led them forty years in the wilderness to humble and test them.",
        },
        {
          canonical: "Hezekiah and the Babylonian Envoys",
          aliases: ["hezekiah's pride test"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Chronicles", chapterStart: 32, verseStart: 31, display: "2 Chronicles 32:31" }],
          explanation: "God leaves Hezekiah to himself when Babylonian envoys visit, to test what is in his heart.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a person struck blind in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any named person, or clearly identified group, the biblical text explicitly describes being struck blind.",
      answers: [
        {
          canonical: "Saul of Tarsus",
          aliases: ["paul struck blind", "saul blinded"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 9, verseStart: 8, verseEnd: 9, display: "Acts 9:8-9" }],
          explanation: "Saul is struck blind by a bright light on the road to Damascus and regains his sight three days later.",
        },
        {
          canonical: "Elymas",
          aliases: ["bar-jesus"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 11, display: "Acts 13:11" }],
          explanation: "The sorcerer Elymas is struck blind by Paul for opposing his preaching before the proconsul.",
        },
        {
          canonical: "The Men of Sodom",
          aliases: ["sodom's men blinded", "men at lot's door"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 19, verseStart: 11, display: "Genesis 19:11" }],
          explanation: "The angels visiting Lot strike the men surrounding his house with blindness so they cannot find the door.",
        },
        {
          canonical: "The Aramean Army",
          aliases: ["syrian army blinded", "elisha blinds the army"],
          score: 60,
          tier: "veil",
          references: [{ book: "2 Kings", chapterStart: 6, verseStart: 18, display: "2 Kings 6:18" }],
          explanation: "Elisha prays and the LORD strikes the Aramean army sent to capture him with blindness.",
        },
        {
          canonical: "Zedekiah",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "2 Kings", chapterStart: 25, verseStart: 7, display: "2 Kings 25:7" }],
          explanation: "King Zedekiah's eyes are put out by the Babylonians after watching his sons killed before him.",
        },
        {
          canonical: "Samson",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 16, verseStart: 21, display: "Judges 16:21" }],
          explanation: "The Philistines gouge out Samson's eyes after Delilah betrays the secret of his strength.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a dream that someone interpreted for another person in the Bible.",
      instructions: "You get one guess.",
      whatCounts: "Any specific dream the biblical text describes one person interpreting for someone else.",
      answers: [
        {
          canonical: "Pharaoh's Dreams",
          aliases: ["pharaoh's dream", "seven fat and lean cows"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 41, verseStart: 15, verseEnd: 32, display: "Genesis 41:15-32" }],
          explanation: "Joseph interprets Pharaoh's dreams of seven fat and seven lean cows as seven years of plenty then famine.",
        },
        {
          canonical: "Nebuchadnezzar's Statue Dream",
          aliases: ["nebuchadnezzar's dream", "statue of gold silver bronze iron"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Daniel", chapterStart: 2, verseStart: 31, verseEnd: 45, display: "Daniel 2:31-45" }],
          explanation: "Daniel both recalls and interprets Nebuchadnezzar's forgotten dream of a great statue representing future kingdoms.",
        },
        {
          canonical: "Joseph's Dreams of Sheaves and Stars",
          aliases: ["joseph's dreams", "sheaves bowing", "sun moon and stars"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 37, verseStart: 5, verseEnd: 11, display: "Genesis 37:5-11" }],
          explanation: "Joseph's brothers and father interpret his dreams of sheaves and stars bowing to him as claims of future rule.",
        },
        {
          canonical: "The Cupbearer and Baker's Dreams",
          aliases: ["cupbearer's dream", "baker's dream", "butler's dream"],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 40, verseStart: 5, verseEnd: 19, display: "Genesis 40:5-19" }],
          explanation: "Joseph interprets the dreams of Pharaoh's imprisoned cupbearer and baker, correctly foretelling their fates.",
        },
        {
          canonical: "Nebuchadnezzar's Tree Dream",
          aliases: ["nebuchadnezzar's second dream", "great tree dream"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Daniel", chapterStart: 4, verseStart: 4, verseEnd: 27, display: "Daniel 4:4-27" }],
          explanation: "Daniel interprets Nebuchadnezzar's dream of a great tree cut down as a warning of his coming madness.",
        },
        {
          canonical: "The Midianite Soldier's Dream",
          aliases: ["barley loaf dream", "gideon overhears a dream"],
          score: 60,
          tier: "veil",
          references: [{ book: "Judges", chapterStart: 7, verseStart: 13, verseEnd: 15, display: "Judges 7:13-15" }],
          explanation: "Gideon overhears a Midianite soldier's dream of a barley loaf toppling a tent, interpreted by his companion as Gideon's coming victory.",
        },
      ],
    },
  ],
};
