import type { SeedDay } from "./types";

export const DAY_40: SeedDay = {
  dayNumber: 40,
  date: "2026-10-27",
  scriptureBonus: {
    displayText: "Now faith is assurance of things hoped for, proof of things not seen.",
    book: "Hebrews",
    chapter: 11,
    verseStart: 1,
    referenceDisplay: "Hebrews 11:1",
    translation: "World English Bible (public domain)",
    licensingMetadata: "Public domain",
    contextNote: "The opening line of Hebrews' famous roll call of Old Testament faith.",
    acceptedBookAliases: ["heb"],
  },
  questions: [
    {
      slot: 1,
      prompt: "Name a person who sailed with Paul on a voyage recorded in Acts.",
      instructions: "You get one guess.",
      whatCounts: "Any named companion Acts describes traveling by sea with Paul on any of his journeys.",
      answers: [
        {
          canonical: "Luke",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 10, display: "Acts 16:10" }],
          explanation: "Acts shifts to \"we\" language here, implying Luke himself joins Paul's sea travel.",
        },
        {
          canonical: "Barnabas",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Acts", chapterStart: 13, verseStart: 4, display: "Acts 13:4" }],
          explanation: "Barnabas sails with Paul from Seleucia to Cyprus on the first missionary journey.",
        },
        {
          canonical: "Timothy",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 4, display: "Acts 20:4" }],
          explanation: "Timothy is listed among those accompanying Paul as he sails toward Jerusalem.",
        },
        {
          canonical: "Aristarchus",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Acts", chapterStart: 27, verseStart: 2, display: "Acts 27:2" }],
          explanation: "Aristarchus of Thessalonica sails with Paul on the shipwreck voyage to Rome.",
        },
        {
          canonical: "Silas",
          aliases: ["silvanus"],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 11, display: "Acts 16:11" }],
          explanation: "Silas travels with Paul from Troas across to Samothrace and Neapolis.",
        },
        {
          canonical: "Trophimus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 4, display: "Acts 20:4" }],
          explanation: "Trophimus of Asia is named among Paul's traveling companions in Acts 20.",
        },
        {
          canonical: "Tychicus",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 4, display: "Acts 20:4" }],
          explanation: "Tychicus of Asia is named alongside Trophimus among Paul's travel companions.",
        },
        {
          canonical: "Sopater",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 4, display: "Acts 20:4" }],
          explanation: "Sopater of Berea is the first name listed among Paul's companions in Acts 20:4.",
        },
        {
          canonical: "Gaius",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 4, display: "Acts 20:4" }],
          explanation: "Gaius of Derbe is named among the group traveling with Paul into Asia.",
        },
        {
          canonical: "Secundus",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Acts", chapterStart: 20, verseStart: 4, display: "Acts 20:4" }],
          explanation: "Secundus of Thessalonica is named only once, in the same traveling party.",
        },
      ],
    },
    {
      slot: 2,
      prompt: "Name a city Paul addressed a New Testament letter to (by the letter's title).",
      instructions: "You get one guess.",
      whatCounts: "Any city or region named in the title of a Pauline epistle (Romans, Corinthians, Galatians, Ephesians, Philippians, Colossians, Thessalonians).",
      answers: [
        {
          canonical: "Rome",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Romans", chapterStart: 1, verseStart: 7, display: "Romans 1:7" }],
          explanation: "Romans is addressed to the believers at Rome.",
        },
        {
          canonical: "Corinth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 1, verseStart: 2, display: "1 Corinthians 1:2" }],
          explanation: "Both letters to the Corinthians are addressed to the church at Corinth.",
        },
        {
          canonical: "Ephesus",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Ephesians", chapterStart: 1, verseStart: 1, display: "Ephesians 1:1" }],
          explanation: "Ephesians is addressed to the saints at Ephesus.",
        },
        {
          canonical: "Philippi",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Philippians", chapterStart: 1, verseStart: 1, display: "Philippians 1:1" }],
          explanation: "Philippians is addressed to the saints at Philippi.",
        },
        {
          canonical: "Thessalonica",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "1 Thessalonians", chapterStart: 1, verseStart: 1, display: "1 Thessalonians 1:1" }],
          explanation: "Both letters to the Thessalonians address the church at Thessalonica.",
        },
        {
          canonical: "Colossae",
          aliases: ["colosse"],
          score: 60,
          tier: "veil",
          references: [{ book: "Colossians", chapterStart: 1, verseStart: 2, display: "Colossians 1:2" }],
          explanation: "Colossians is addressed to the saints at Colossae.",
        },
        {
          canonical: "Galatia",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Galatians", chapterStart: 1, verseStart: 2, display: "Galatians 1:2" }],
          explanation: "Galatians addresses a region, not a single city — its churches across Galatia.",
        },
      ],
    },
    {
      slot: 3,
      prompt: "Name a person who hosted a house church, named in the New Testament.",
      instructions: "You get one guess.",
      whatCounts: "Any named person a New Testament letter or Acts explicitly connects to a church meeting in their home.",
      answers: [
        {
          canonical: "Priscilla",
          aliases: ["prisca"],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 5, display: "Romans 16:5" }],
          explanation: "Priscilla and Aquila host \"the assembly that is in their house.\"",
        },
        {
          canonical: "Aquila",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "1 Corinthians", chapterStart: 16, verseStart: 19, display: "1 Corinthians 16:19" }],
          explanation: "Aquila and Priscilla host a church in their home at both Rome and Ephesus.",
        },
        {
          canonical: "Philemon",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Philemon", chapterStart: 1, verseStart: 2, display: "Philemon 1:2" }],
          explanation: "Paul writes \"to the assembly in your house,\" addressing Philemon.",
        },
        {
          canonical: "Mary the Mother of John Mark",
          aliases: ["mary mother of mark"],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 12, verseStart: 12, display: "Acts 12:12" }],
          explanation: "Many gather to pray in the house of Mary, mother of John Mark, when Peter is imprisoned.",
        },
        {
          canonical: "Lydia",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Acts", chapterStart: 16, verseStart: 40, display: "Acts 16:40" }],
          explanation: "Paul and Silas gather with believers at Lydia's house after leaving prison.",
        },
        {
          canonical: "Gaius",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Romans", chapterStart: 16, verseStart: 23, display: "Romans 16:23" }],
          explanation: "Paul calls Gaius \"my host, and host of the whole assembly.\"",
        },
        {
          canonical: "Nympha",
          aliases: ["nymphas"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Colossians", chapterStart: 4, verseStart: 15, display: "Colossians 4:15" }],
          explanation: "Paul greets Nympha and \"the assembly that is in her house\" in Colossians' closing.",
        },
      ],
    },
    {
      slot: 4,
      prompt: "Name a person listed in the genealogy from Adam to Noah in Genesis 5.",
      instructions: "You get one guess.",
      whatCounts: "Any of the ten generations named in the Genesis 5 genealogy from Adam to Noah.",
      answers: [
        {
          canonical: "Adam",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 1, display: "Genesis 5:1" }],
          explanation: "Genesis 5 opens \"the book of the generations of Adam.\"",
        },
        {
          canonical: "Noah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 29, display: "Genesis 5:29" }],
          explanation: "Noah is the tenth generation from Adam, closing out the chapter's genealogy.",
        },
        {
          canonical: "Seth",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 3, display: "Genesis 5:3" }],
          explanation: "Seth is born to Adam \"in his own likeness, after his image.\"",
        },
        {
          canonical: "Enoch",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 24, display: "Genesis 5:24" }],
          explanation: "Enoch \"walked with God, and he was not, for God took him.\"",
        },
        {
          canonical: "Methuselah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 27, display: "Genesis 5:27" }],
          explanation: "Methuselah lives 969 years, the longest lifespan recorded in the Bible.",
        },
        {
          canonical: "Lamech",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 28, verseEnd: 29, display: "Genesis 5:28-29" }],
          explanation: "Lamech, Noah's father, names his son hoping for comfort from their toil.",
        },
        {
          canonical: "Enosh",
          aliases: ["enos"],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 6, display: "Genesis 5:6" }],
          explanation: "Enosh, Seth's son, marks the generation when \"men began to call on Yahweh's name.\"",
        },
        {
          canonical: "Jared",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 18, display: "Genesis 5:18" }],
          explanation: "Jared, Enoch's father, lives 962 years.",
        },
        {
          canonical: "Kenan",
          aliases: ["cainan"],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 9, display: "Genesis 5:9" }],
          explanation: "Kenan, Enosh's son, is one of the briefest entries in the chapter.",
        },
        {
          canonical: "Mahalalel",
          aliases: ["mahalaleel"],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Genesis", chapterStart: 5, verseStart: 12, display: "Genesis 5:12" }],
          explanation: "Mahalalel, Kenan's son, is among the least-remembered names in the whole genealogy.",
        },
      ],
    },
    {
      slot: 5,
      prompt: "Name a person from the Old Testament honored by name in Hebrews 11.",
      instructions: "You get one guess.",
      whatCounts: "Any Old Testament figure Hebrews chapter 11 (the \"hall of faith\") names explicitly.",
      answers: [
        {
          canonical: "Abraham",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 8, display: "Hebrews 11:8" }],
          explanation: "Abraham is praised for obeying God's call to an unknown land.",
        },
        {
          canonical: "Noah",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 7, display: "Hebrews 11:7" }],
          explanation: "Noah is commended for building the ark in reverent fear.",
        },
        {
          canonical: "Moses",
          aliases: [],
          score: 10,
          tier: "outer-court",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 24, display: "Hebrews 11:24" }],
          explanation: "Moses is praised for refusing to be called the son of Pharaoh's daughter.",
        },
        {
          canonical: "Sarah",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 11, display: "Hebrews 11:11" }],
          explanation: "Sarah receives strength to conceive in her old age because she judged God faithful.",
        },
        {
          canonical: "Isaac",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 20, display: "Hebrews 11:20" }],
          explanation: "Isaac blesses Jacob and Esau concerning things to come.",
        },
        {
          canonical: "Jacob",
          aliases: [],
          score: 20,
          tier: "bronze-altar",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 21, display: "Hebrews 11:21" }],
          explanation: "Jacob blesses each of Joseph's sons while leaning on his staff.",
        },
        {
          canonical: "Abel",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 4, display: "Hebrews 11:4" }],
          explanation: "Abel offers a better sacrifice than Cain, still speaking through his faith.",
        },
        {
          canonical: "Joseph",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 22, display: "Hebrews 11:22" }],
          explanation: "Joseph, near death, gives instructions about his bones leaving Egypt.",
        },
        {
          canonical: "Rahab",
          aliases: [],
          score: 30,
          tier: "holy-place",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 31, display: "Hebrews 11:31" }],
          explanation: "Rahab the prostitute is commended for welcoming the Israelite spies in peace.",
        },
        {
          canonical: "David",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 32, display: "Hebrews 11:32" }],
          explanation: "David is named among the figures whose stories are too many to tell in detail.",
        },
        {
          canonical: "Samuel",
          aliases: [],
          score: 60,
          tier: "veil",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 32, display: "Hebrews 11:32" }],
          explanation: "Samuel is named in the same closing list of the faithful.",
        },
        {
          canonical: "Gideon",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 32, display: "Hebrews 11:32" }],
          explanation: "Gideon is named among the judges praised for faith in the closing summary.",
        },
        {
          canonical: "Barak",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 32, display: "Hebrews 11:32" }],
          explanation: "Barak, who fought alongside Deborah, is named among the judges of faith.",
        },
        {
          canonical: "Samson",
          aliases: [],
          score: 85,
          tier: "holy-of-holies",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 32, display: "Hebrews 11:32" }],
          explanation: "Samson is named in the same brief roll call of judges.",
        },
        {
          canonical: "Jephthah",
          aliases: [],
          score: 100,
          tier: "third-heaven",
          references: [{ book: "Hebrews", chapterStart: 11, verseStart: 32, display: "Hebrews 11:32" }],
          explanation: "Jephthah is the least-remembered of the four judges named together in Hebrews 11:32.",
        },
      ],
    },
  ],
};
